### ISSUE TITLE
Добавить опцию "Снять выделение текста"

### ISSUE THREAD

**Issue by Fesko** [BladeMight/Mahou#10]
Было бы удобно, если после "Convert Selection" снималось выделение текста и можно было сразу продолжать писать.

**Comment by BladeMight** [comment]
> Было бы удобно, если после "Convert Selection" снималось выделение текста и можно было сразу продолжать писать.

Вот [Mahou-v1.0.9.2](https://github.com/BladeMight/Mahou/releases/tag/v1.0.9.2) в нем добавлена опция переключения выделения текста после "Convert Selection",  проверьте.
