### ISSUE TITLE
Прокрутка вкладок настройки колёсиком мыши и поиск настроек

### ISSUE THREAD

**Issue by grengray** [BladeMight/Mahou#100]
Не знаю на сколько это будет сложно или просто, но удобно прокручивать множество вкладок с настройками колёсиком мыши. Возможно имеет смысл сделать поиск по настройкам, но мне кажется это по лишнее, но в будущем уверен, что пригодится.

**Comment by grengray** [comment]
@BladeMight здесь есть личка?

**Comment by BladeMight** [comment]
Ура 100-я issue!

> настройками колёсиком мыши

Да, думаю уже над этим.

> здесь есть личка?

Есть если нужно могу включить сбоку **Lock conversation**.

**Comment by grengray** [comment]
>Есть если нужно могу включить сбоку Lock conversation.
Что это такое?

**Comment by BladeMight** [comment]
@grengray Перевод - закрытое обсуждение, то есть не позволять никому еще влезать в дискуссию.

**Comment by grengray** [comment]
Это я понял, а это будет видно всем?

**Comment by BladeMight** [comment]
@grengray Не знаю сейчас попробую.

**Comment by BladeMight** [comment]
@grengray Не, все равно всем видна.

**Comment by grengray** [comment]
Давайте протестируем :) Это дело хорошее :)

**Comment by BladeMight** [comment]
Сейчас удалю лишние комментарии.

**Comment by grengray** [comment]
???

**Comment by BladeMight** [comment]
@grengray тихо.

**Comment by grengray** [comment]
@BladeMight у Вас всё нормально?

**Comment by BladeMight** [comment]
@grengray Да, только очень занят на этих днях.

**Comment by grengray** [comment]
Фух... спасибо, что отписались :)

**Comment by BladeMight** [comment]
@grengray Появилась свободная минутка, вот с прокруткой вкладок колесиком([изменения в коде](https://github.com/BladeMight/Mahou/commit/df748c238a30e821b92974a35e5db469da766fd8)): 
[Mahou.exe.gz](https://github.com/BladeMight/Mahou/files/1100623/Mahou.exe.gz)
