### ISSUE TITLE
Престали работать исключения.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#101]
Не знаю с каких пор, но добавления в "программы исключения" больше не работает.
Проверял на notepad.exe
Можете проверить - это только у меня?
Также - что делать если процесс вида programname.exe *32? Сейчас пробелом разделяются программы в списке...

**Comment by BladeMight** [comment]
> Можете проверить - это только у меня?

Нет, у меня тоже, буду исправлять.

>  *32

Не считается.

А вот для программ с именем имеющим пробелы добавлю правило кавычек(или скобок).

**Comment by BladeMight** [comment]
Вот исправил проверь: [Mahou.zip](https://github.com/BladeMight/Mahou/files/1190336/Mahou.zip)

**Comment by Trost123** [comment]
Да, работает. Теперь бы релиз в котором одновременно фикс alt+tab и это, и вообще отилчно было бы.

**Comment by BladeMight** [comment]
Сейчас закончу с #104 и #107 и сделаю релиз.

**Comment by BladeMight** [comment]
@Trost123 Релиз: [Mahou-v2.3.4.4](https://github.com/BladeMight/Mahou/releases/tag/v2.3.4.4).

**Comment by Trost123** [comment]
Проверил, всё норм. Возможно стоит указать в тултипе что case sensitive.
Еще странно эта настройка в вкладке "тайминги" лежит.
P.S. Вкладок наплодилось сколько, что без прокрутки не влазят уже (а еще у меня колесиком по 3 вкладки прокручивает, но это уже косяки драйвера моей мышки). Может пора разширить окно или вкладки в 2 ряда пустит?

**Comment by BladeMight** [comment]
>вкладки в 2 ряда пустить?
