### ISSUE TITLE
При конверте последнего слова добавляет текст из предыдущего окна.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#102]
Пишем в нотпаде слово. Дабл шифт (конверт последнего слова).
Кликаем на текстовое поле в firefox. Пишем слово там. Конвертим. Слово из нотпада появляется перед словом что мы написали в ff.
![mahou_extra_text](https://user-images.githubusercontent.com/21346282/28110998-b09cff52-66fc-11e7-825b-a335493c4e35.gif)

**Comment by BladeMight** [comment]
> Кликаем

Если после этого не очищается слово, значить hook мыши *умер*, попробуйте включить функцию __перезапуск hook'ов__.

**Comment by Trost123** [comment]
Я понял почему случается этот баг.
Захожу в настройки, ничего не меняю, жму "применить" - курсор "фризит" на месте где-то на 1.5 сек, после этого баг будет присутствовать до перезапуска программы.
Если использовать "перезапуск хуков" - всё норм.

В чём вообще смысл делать такие функции отключаемыми? Звучит как завуалированая настройка "работать корректно". Я изначально думал что перезапуск хуков будет дополнительные циклы ЦПУ жрать, вот и отключил.

**Comment by Trost123** [comment]
Судя по всему при сохранении настроек какая-то скрытая ошибка происходит из-за чего фриз и отваливается хук.

**Comment by BladeMight** [comment]
> Судя по всему при сохранении настроек какая-то скрытая ошибка происходит 

Включите логгинг, и пришлите лог, если так.

**Comment by Trost123** [comment]
У меня 100% повторяемость бага.
Включил mahou - сделал как на гифке в первом посте - баг не случился.
Открыл окно, нажал применить\ок - зависание курсора, баг активирован.
Лог:

[2017.07.31.txt](https://github.com/BladeMight/Mahou/files/1188410/2017.07.31.txt)

**Comment by BladeMight** [comment]
Хм, в логе нет информации о очистке запомненных введенных слов Mahou, видимо hook мыши и впрямь умирает при *применить/ОК*(ОК делает и применить), хотя у меня не получается его воспроизвести(~30 раз - все ОК)...

> зависание курсора

Как раз так hook'и(мыши/клавиатуры) обычно *умирают*, и потом сделать что-либо не можно, даже проверить умер ли он тоже... поэтому я  и придумал фикс перезапуска Hook'ов.
Понять бы от чего он *умирает*... И почему именно мыши? Может у тебя есть еще какие-то программы использующие hook'и мыши? Попробуй убрать все лишние программы командой в cmd: `taskkill /f /fi "USERNAME eq %username%"`(**Сразу убивает все процессы пользователя, осторожно.**) , а дальше Ctrl+Shift+Esc и Файл -> новая задача -> explorer.exe, а потом найди и запусти Mahou, notepad, FF и попробуй.

**Comment by Trost123** [comment]
1) taskkill /f /fi "USERNAME eq %username%"
2) Запустил ff, notepad, mahou
3) Хук мышки жив
4) Применил настройки, подвис
5) Баг есть.
6) Решил повторить баг не касаясь мышки (через alt-tab) - баг есть.
7) Включил "перезапускать хуки", перезапустил Mahou - теперь баг ПРИ КЛИКЕ НЕ повторяется, даже после применения настроек но при alt-tab повторяется.
Дичь какая-то.
Выводы:
- Alt-tab всегда забывает сбросить буфер слова.
- Хук мышки умирает при применении настроек, если не использовать функцию "перезапуск хука".
- Приложения роли не играют: пробывал firefox, notepad, notepad++ в любом порядке\комбинации.

Вот мои настройки
[Mahou.zip](https://github.com/BladeMight/Mahou/files/1188561/Mahou.zip)

Если есть время\желание могу сейчас или завтра по TeamViewer продемонстрировать. Может наглядно под твоим командованием получится быстрее выяснить корень проблемы.

**Comment by Trost123** [comment]
Еще наблюдение: ctrl-таб очищает буфер всегда!

**Comment by Trost123** [comment]
У тебя подвисание курсора не происходит при применении насроек?
Хотелось бы знать является ли это индикатором проблемы, чтобы быстрее тестить.

**Comment by Trost123** [comment]
И еще один тест кейс: переименовал Mahou.ini (тем самым сбросил настройки).
Через alt-tab баг есть, через мышку баг есть, если снять галочку хуков и применить настройки.
При этом если (не поставив обратно галочку) перезапустить mahou - хук мышки опять будет жив и работает без проблем.

Выводы:
Alt-tab не резетит кеш на дефолт настройках.
Ctrl+tab\ctrl+e резетит кеш.
Сохранение настроек почему-то убивает хук мышки.

**Comment by Trost123** [comment]
Есть подозрения что Thread.Sleep(10); является причиной фризов:
https://stackoverflow.com/questions/27356165/why-does-thread-sleep-freeze-the-form

**Comment by Trost123** [comment]
Начал перебирать версии постарее: 2.0.0.0 всё еще подвисает и теряет хук при сохранении настроек.
Потом сразу перескочил на v1.4.3.0 - хук при сохранении настроек не слетает. Т.е. где-то в редизайне интерфейса этот баг пришел. Скорее всего как раз с мультитредингом что-то накосячено.

А при переключении окон через alt-tab баг повторяется даже на v1.4.3.0. Alt-tab не сбрасывает слово. ctrl, прото так нажатый сам по себе - сбрасывает слово. Wtf.

**Comment by BladeMight** [comment]
> Есть подозрения что Thread.Sleep(10);

Да, фризит, но на 10 мс, врятли заметно.


> v1.4.3.0. Alt-tab не сбрасывает слово

**Comment by Trost123** [comment]
> Странно эта функция не используется в месте сохранения настроек, поэтому и не должна влиять на это... Она используется только в одном месте - при нажатии на горяч. клавишу → после действия гор. клавиши.

У меня в логе всегда при октрытии окна и применении настроек срабатывает рестарт хуков.
<details>
  <summary>Лог под спойлером</summary>

```
10:37:23.171 [Info]
                    Mahou Main window visibility changed to [True].
10:37:23.222 [Info]
                    Global hooks stopped.
10:37:23.237 [Info]
                    Global hooks started.
10:37:23.365 [Info]
                    Modifiers [15] sent up.
10:37:23.381 [Info]
                    Hwnd 1770490, layout: 67699721, Mahou layout: 68748313
10:37:25.822 [Info]
                    Last word & words cleared [with mouse click].
10:37:25.936 [Info]
                    Mahou Main window visibility changed to [False].
10:37:25.956 [Info]
                    Global hooks stopped.
10:37:25.973 [Info]
                    Global hooks started.
10:37:26.100 [Info]
                    Modifiers [15] sent up.
10:37:26.114 [Info]
                    Hwnd 132386, layout: 68748313, Mahou layout: 68748313
10:37:26.924 [Info]
                    Saved from temps.
10:37:26.977 [Info]
                    All configurations saved.
10:37:26.984 [Info]
                    Language changed.
10:37:26.991 [Info]
                    Locales for ALL comboboxes refreshed.
10:37:27.004 [Info]
                    Hotkeys initialized.
10:37:27.010 [Info]
                    Changed flag to ru lcid 1049
10:37:27.018 [Info]
                    All configurations loaded.
```

</details>


P.S. Пожалуйста не привыкайте через правку комментария добавлять 50% новой информации.
Я не получаю уведомления о том что было дописано и итого либо не замечу, либо буду параноидально проверять обновлять страницу 😄

**Comment by BladeMight** [comment]
> при октрытии окна и применении настроек срабатывает рестарт хуков.

Это потому что включено логирование.

> Пожалуйста не привыкайте через правку комментария добавлять 50% новой информации.

ОК.

По поводу очистки слов кликами мыши, там должна появляться строчка: `Last word & words cleared [with mouse click].`, если ее нет то hook'а мыши нет.

**Comment by Trost123** [comment]
Ну значит умирает хук когда применяешь настройки без галочки.
Впринципе баг не кричиный - просто после настройки Mahou буду перезапускать. Я настройки не часто меняю.
Если всё еще интересно пофиксить - гифка и лог во время записи:
![mahou_dead_mouse_hook](https://user-images.githubusercontent.com/21346282/28823213-1d74d4ce-76c5-11e7-9499-4b2007f2bfe2.gif)
[2017.08.01.txt](https://github.com/BladeMight/Mahou/files/1190412/2017.08.01.txt)

Т.е. "перезапускать хуки" срабатывает когда я делаю конверт. И даже после включения этой опции первый конверт будет с лишним текстом ("привПривет" на гифке).
Почему хуки умирают, когда жму применить\ок - без пониятия.
Подвисание курсора с багом напрямую похоже не связано. Баг случается у меня всегда, а подвисает курсор (при нажатии ок\применить) не всегда. Вообще странно что подвисает курсор, а не окно программы. Т.е. если ткнуть "ок" - окно закрывается анимацией моментально, а курсор невозможно двигать еще долю секунды.

**Comment by Trost123** [comment]
UPD: вру, курсор виснет именно от "смерти" хука. Т.к. если повторно применять настройки когда хук уже умер - подвисания нет. Если перезапустить хуки (перезапуском программы или соотв. галочкой) - при применении опций снова подвиснет.
В общем что-то не так происходит во время сохранения настроек.

**Comment by BladeMight** [comment]
Попробуй здесь: [Mahou.zip](https://github.com/BladeMight/Mahou/files/1190516/Mahou.zip), сделал обязательным перезапуск Hook'ов после сохранения настроек.

**Comment by Trost123** [comment]
Подвисание не пропало. Хуки теперь работают после сохранения настроек, но появилась куча других багов:
- капс лок не переключает раскладку (видимо теперь висит 2 хука на клавиатуре?)
- "ghbdtn" конвертится в "ппррииввеетт"
- Конверт последнего слова захватывает лишние слова.
"ghbdtn ghbdtn ghbdtn" конвертит в "ghbdtn gппррииввеетт"

Да и сам факт подвисания говорит что что-то идёт не так при сохранении настроек. А реально сделать билд, который выкидывал бы в лог (или в всплывающее окошко ошибки) когда они случаются? Ибо методом тыка пытаться выяснить уже надоело.

**Comment by BladeMight** [comment]
> который выкидывал бы в лог (или в всплывающее окошко ошибки) когда они случаются?

У global hook'ов они не случаются...

**Comment by BladeMight** [comment]
@Trost123 Обновил релиз, проверь [Mahou-v2.3.4.4](https://github.com/BladeMight/Mahou/releases/tag/v2.3.4.4).

**Comment by BladeMight** [comment]
>  факт подвисания говорит что что-то идёт не так при сохранении настроек.

Сколько времени подвисает? Если 0.5~1 сек то это нормальное сохранение настроек, а если мышь начинает слабо реагировать на движения(тормозить) то это hook умер, и длиться примерно 4~8+ сек.

**Comment by Trost123** [comment]
в 2.3.4.4 теперь курсор подвисает при каждом сохранении (что логично ведь по-сути мы вылечили симптом а не проблему)
Мышка теперь ведёт себя как положено всегда, а alt-tab fix почему-то опять пропал. Даже если не применять настройки.

**Comment by BladeMight** [comment]
> alt-tab fix почему-то опять пропал

глянем.

**Comment by BladeMight** [comment]
@Trost123 Восстановил фикс, обновил релиз [Mahou-v2.3.4.4](https://github.com/BladeMight/Mahou/releases/tag/v2.3.4.4).

> мы вылечили симптом а не проблему

Ну понять причину проблемы не получается т.к. это global hook'и... так что это единственное быстрое решение.

**Comment by BladeMight** [comment]
> Ну понять причину проблемы не получается т.к. это global hook'и...

Может это и сам Windows их *отключает*, может что-то еще...

**Comment by Trost123** [comment]
Ну по-сути проблемы больше нет, спасибо!
Большинство разработчиков вообще забили бы на такого рода мелкий баг или фиксили бы его с месяц.

А насчет фриза курсора - первый раз вижу чтобы программа такое делала. Даже когда программы виснут от нагрузки (игры, excel, blender), никогда курсор не фризят.
Не критично, но любопытно почему оно так.
Понять причину проблемы думаю можно, выкомментировав все действия что происходят при сохранении настроек и возвращая по одному. Вприцнипе у меня VS2017 стоит на ПК, может когда-то скачаю исходник побалуюсь с этим.

**Comment by BladeMight** [comment]
> Понять причину проблемы думаю можно, выкомментировав все действия что происходят при сохранении настроек и возвращая по одному

Да, вот только у меня не встречается проблема...

> Не критично, но любопытно почему оно так.

Простой ответ:  *Mahou сохраняет и загружает и обновляет и т.д. __очень много__ настроек и свойств.*

> Большинство разработчиков вообще забили бы на такого рода мелкий баг или фиксили бы его с месяц.

Да ладно, серьезно?

> Ну по-сути проблемы больше нет, спасибо!

Круто.

> VS2017

Может она тоже и не заметит проблемы, просто тестил раньше 2015 community и никаких багов о hook'ах там не отображалось...

**Comment by BladeMight** [comment]
@Trost123 А еще по поводу #101 все ок?

**Comment by Trost123** [comment]
> Простой ответ: Mahou сохраняет и загружает и обновляет и т.д. очень много настроек и свойств.
Экзель сохраняет таблицу 15000х30 с кучей информации, но не фризит мне курсор. 😉

**Comment by BladeMight** [comment]
> 15000х30 с кучей информации

Ну то всего лишь запись на диск, а у Mahou кроме этого и в памяти и графически и логически все чекбоксы и т.д. меняет загружает и сохраняет.

**Comment by Trost123** [comment]
Всё-равно не пойму что там такое сложное. Считать все чекбоксы\поля в окне и записать в 173 строки 9kb .ini файл?
Или оно их сразу после записи в файл считыает оттуда и обратно? Тогда возникает вопрос - зачем?

И вообще по-моему это не связано с самим сохранением. Смотрю в диспетчере задач - во время фриза курсора ЦП на процессе Mahou больше 2% не поднимается.
Тем более уже установил закономерность что фриз случается именно тогда, когда умирает хук. Когда хук уже умер (до фикса с рестартом) - применение настроек не вызывало фриза.

_P.S. Не принимай как критику на свой счёт. Мне всего лишь любопытно как коллеге разработчику разгадать очередной баг, потрещать про компульсивную оптимизацию + сделать эту программу еще лучше._

**Comment by BladeMight** [comment]
@Trost123 Тогда вопрос в том *почему хук умирает*, у меня нормально, наверно нужно как-то тебе потестить...

>  Не принимай как критику на свой счёт. Мне всего лишь любопытно как коллеге разработчику разгадать очередной баг, потрещать про компульсивную оптимизацию + сделать эту программу еще лучше.

Да мне так же, спасибо.
