### ISSUE TITLE
неверное определение раскладки в консольном приложении 

### ISSUE THREAD

**Issue by dlukyanov** [BladeMight/Mahou#105]
## Problem/Request description
неверное определение раскладки в консольном приложении 
т.е. показания mahou расходятся с реальной раскладкой 

## Expected behavior (Only if reporting bug)

показывать правильную раскладку (флажок)

## System information

- Windows version: [Windows version 10]
- Windows architecture: [x64]
- .Net version: [Your .Net version (4.0/4.5/4.6)]
- Mahou version: [2.3.4.0]

**Comment by dlukyanov** [comment]
![err-console](https://user-images.githubusercontent.com/7533327/28456667-c443a6d0-6e0b-11e7-954e-7d354b313344.png)

**Comment by dlukyanov** [comment]
думаю как результат  исправление раскладки в консольном приложении не работает (например в Far Manager)

**Comment by BladeMight** [comment]
@dlukyanov Есть легкий способ - воспользоваться дополнением - getconkbl.dll, ТОЛЬКО x86 версии обоих(Mahou и getconkbl.dll) поддерживаются. (вы можете взять dll [отсюда](https://github.com/Elfy/getconkbl/releases), поставьте в папку с Mahou.exe и все будет работать нормально.

По поводу того почему не работает:

1. В консоли(cmd.exe, far.exe) - нет раскладки, а есть(храниться) она только в хосте консольных приложений (conhost.exe), эта __dll__ находит какой процесс conhost.exe ассоциирован с активным консольным приложением.
2. Почему только x86 - потому что .Net x64 не *хочет* принимать значения из x64 dll, но это никак не влияет на работу Mahou, он работает в любых приложениях(x86/x64) не зависимо от своей разрядности.

**Comment by BladeMight** [comment]
@dlukyanov В последнем релизе исправил поддержку getconkbl.dll (даже не знаю в какой момент перестало работать 0_0), [вот здесь](https://github.com/BladeMight/Mahou/releases/tag/v2.3.5.2) есть pack Mahou и getconkbl.dll.

**Comment by BladeMight** [comment]
> вот здесь есть pack Mahou и getconkbl.dll.

Теперь в каждом следующем релизе я добавляю архив с x86 версией и getconkbl.dll.

**Comment by TaciturnShadow** [comment]
Всё равно не работает. Берём Mahou-v2.3.5.6_x86.getconkbl.dll.zip, распаковываем, запускаем, переключаем раскладку в cmd.exe - встроенный переключатель показывает правильно, Mahou - нет. Проверял в 32-битной XP и 64-битной W7.
Как-то даже не заметил как сломалось, ведь когда поддержка getconkbl.dll только появилась точно всё работало.

**Comment by BladeMight** [comment]
@TaciturnShadow Да верно, случайно сборку Mahou Any CPU поставил в архивы последних двух релизов. Перезалил, проверьте.

**Comment by TaciturnShadow** [comment]
Не помогло. На всякий случай скачал из AppVeyor - тоже самое, не работает.

**Comment by BladeMight** [comment]
@TaciturnShadow Странно, у меня работает, включите логинг и пришлите лог когда переключаете раскладку в cmd.exe

**Comment by TaciturnShadow** [comment]
Пожалуйста.
[2017.08.11.log.txt](https://github.com/BladeMight/Mahou/files/1218536/2017.08.11.log.txt)
[debug.txt](https://github.com/BladeMight/Mahou/files/1218537/debug.txt)

**Comment by BladeMight** [comment]
Вот эти строчки: 
>                     INIT: True
                       Tried to get console layout id, return [0], pid [212].

говорят о том Mahou успешно подключился к getconkbl.dll, значит проблема в чем-то другом, у меня очень редко бывает что чтобы заработало опять нужно перезапустить комп. т.к. это единственный способ перезапустить csrss.exe который (по моему мнению) хранит *нечто* благодаря чему getconkbl.dll получает раскладку из консольных приложений. 
В общем перезагрузитесь и попробуйте опять.

**Comment by TaciturnShadow** [comment]
Заработало. Интересно, почему у встроенного переключателя такой проблемы не возникает?

**Comment by BladeMight** [comment]
> почему у встроенного переключателя такой проблемы не возникает?

Видимо он использует другой способ получить раскладку консольного приложения.

**Comment by BladeMight** [comment]
@TaciturnShadow Новости по поводу неверного определения в консольных приложениях, новая функция "Получать раскладку с JKL", посмотри #168

**Comment by BladeMight** [comment]
> Версия с JKL не определяет раскладку в cmd

Уверен? Скачай [отсюда](https://github.com/BladeMight/Mahou/releases/download/latest-commit/Release_x86_x64.zip) и попробуй еще раз и не забудь включить функцию, и лог не помешал бы.

Вот одна из причин:

> очень редко бывает что чтобы заработало опять нужно перезапустить комп

> и зачем что-то менять.

Я не менял, я только добавил.

> Честно говоря так и не смог понять что плохого

Просто захотел придумать свой способ получения раскладки.

**Comment by TaciturnShadow** [comment]
Уверен, я сразу именно этот файл скачал. Но пожалуйста, вот лог.
[2018.04.06.zip](https://github.com/BladeMight/Mahou/files/1883454/2018.04.06.zip)

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>


- Mahou 2.5.9.3-dev
- OS = [Microsoft Windows NT 6.1.7601 Service Pack 1]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Русская(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=False
[Functions]
UseJKL=True
GetLayoutFromTaskbar=false
TrayIconVisible=True
ConvertSelectionLayoutSwitching=True
ReSelect=True
RePress=True
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=False
Logging=True
CapsLockTimer=False
TrayFlags=True
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=True
RestartHooksOnHotkeyActionEnd=True
AutoStartAsAdmin=False
GuessKeyCodeFix=False
AppDataConfigs=False
RemapCapslockAsF18=True
AddOneEnterToLastWord=False
SilentUpdate=False
[Layouts]
SwitchBetweenLayouts=True
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=США(67699721)
MainLayout2=Русская(68748313)
SpecificKey1=1
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Переключать между раскладками
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
OneLayout=False
QWERTZfix=False
SpecificKeysType=0
SpecificKeySets=set0
[Appearence]
DisplayLangTooltipForMouse=True
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
Language=Русский
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Microsoft Sans Serif, 8.25pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Microsoft Sans Serif, 8.25pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Microsoft Sans Serif, 8.25pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Microsoft Sans Serif, 8.25pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
Layout1LTText=
Layout2LTText=
MouseLTUseFlags=True
CaretLTUseFlags=False
MouseLTAlways=False
MouseLTUpperArrow=False
CaretLTUpperArrow=False
WindowsMessages=True
[Timings]
DelayAfterBackspaces=100
UseDelayAfterBackspaces=False
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=50
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
ChangeLayoutInExcluded=True
LangTooltipForMouseSkipMessages=5
[Snippets]
SnippetsEnabled=False
SpaceAfter=False
SwitchToGuessLayout=False
SnippetExpandKey=Space
[Hotkeys]
ToggleMainWindow_Enabled=False
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=False
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=False
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=
ConvertSelectedText_Key=145
ConvertLastLine_Enabled=False
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=False
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=16
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Shift
SelectedTextToRandomCase_Key=17
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win + 
SelectedTextToSwapCase_Key=19
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win + 
SelectedTextTransliteration_Key=191
ExitMahou_Enabled=False
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=False
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
ToggleLangPanel_Enabled=True
ToggleLangPanel_Double=False
ToggleLangPanel_Modifiers=Shift
ToggleLangPanel_Key=120
```
</details>
</details>
</details>

**Comment by BladeMight** [comment]
@TaciturnShadow Просто я недавно перезалил, и поэтому хотел чтобы ты сказал заново. 
В логе не было сообщений связанного с функцией интеграции с JKL, то есть что-то не так.
И так в итоге у тебя после распаковки должно быть Mahou.exe, jkl.exe, jkl.dll, jklx86.dll, jklx86.dll. А в диспетчере задач должны появлятся jkl.exe и jklx86.exe при запуске Mahou с включенной функцией или при ее включении и нажатии на применить.

**Comment by klewerus** [comment]
скачал только что, jkl.exe и jklx86.exe в списке процессов не появляются

**Comment by TaciturnShadow** [comment]
![2018-04-06_124953](https://user-images.githubusercontent.com/23205580/38415100-1930f77a-3999-11e8-9582-91e682bf1fdd.png)
Запускаться всё запускается. Причём настолько, что после закрытия Mahou.exe я не могу удалить jkl.dll и jklx86.dll.

**Comment by klewerus** [comment]
руками jkl.exe и jklx86.exe запускаются, при вЫключении функции JKL и нажатии на применить - пропадают из списка процессов

**Comment by BladeMight** [comment]
> я не могу удалить jkl.dll и jklx86.dll.

Ну это из-за хука мониторинга который(или к которому, не только у меня хуки) подключается к разным приложениям.

**Comment by BladeMight** [comment]
P.S. Как по разному она у всех работает...

**Comment by BladeMight** [comment]
Лично у меня работает нормально и в консольных окнах и в нормальных. После запуска с функцией JKL появляются процессы JKL и все ОК.

Помогли бы логи с ваших систем или TeamViewer (telegram: rBladeMight).

**Comment by BladeMight** [comment]
> Причём настолько, что после закрытия Mahou.exe я не могу удалить jkl.dll и jklx86.dll.

В последней версии добавил удаление, и если не получается то перемещение(с случайным названием) в папку **trash** рядом с Mahou.exe. Далее Mahou будет пытаться ее удалять каждый раз когда запускается.

Как проверить сейчас: Обновиться до latest-commit, удалить строчку "LatestCommit=" в Mahou.ini или удалить сам Mahou.ini, запустить Mahou, обновиться еще раз на latest-commit.

**Comment by BladeMight** [comment]
@dlukyanov Релиз [Mahou-v2.6.2.0](https://github.com/BladeMight/Mahou/releases/tag/v2.6.2.0).
