### ISSUE TITLE
Problem with German Layout

### ISSUE THREAD

**Issue by SvenKarsten** [BladeMight/Mahou#107]
Hi, 

big thanks for great app! I have only one problem with it: 

I use two layouts - Russian and German. If i try to convert selected text from German to Russian the app makes it not correct. Problematic buttons are: Z <-> Y and Ö <-> Ü

Examples: 

If I writes "Нина Овчинникова" in wrong layout, I get "Zbzf Jdxbzzbrjdf". If I try to convert it with hotkey, I get "Яияа Овчияяикова".

If I writes "Хорошо" in wrong layout, I get "Üjhjij". If I try to convert it with hotkey, I get "Жорошо".

If I writes "Zoopark" in wrong layout, I get "Нщщзфкл". If I try to convert it with hotkey, I get "Yoopark".

If I writes "Übung" in wrong layout, I get "Хигтп". If I try to convert it with hotkey, I get "?bung".

If I writes "Ödipus" in wrong layout, I get "Жвшзгы". If I try to convert it with hotkey, I get "Üdipus".

If I writes "Weiß" in wrong layout, I get "Цуш-". If I try to convert it with hotkey Pause, I get "Wei-". If I try to select it first and then convert it with hotkey Scroll Lock, I get "Wie-". 

Thank you

## Expected behavior (Only if reporting bug)

Write here what did you expected to happen?

## System information

- Windows version: 7 Pro German
- Windows architecture: x32
- .Net version: 4.6.1
- Mahou version: 2.3.4.0

**Comment by BladeMight** [comment]
@SvenKarsten OK, I'll make fix for AZERTY keyboard layout.

**Comment by BladeMight** [comment]
@SvenKarsten Done, here take a look:
[Mahou.zip](https://github.com/BladeMight/Mahou/files/1190522/Mahou.zip)
Checkbox in Layouts tab: _QWERTZ fix..._

**Comment by BladeMight** [comment]
@SvenKarsten Release: [Mahou-v2.3.4.4](https://github.com/BladeMight/Mahou/releases/tag/v2.3.4.4).

**Comment by SvenKarsten** [comment]
Thank you, but it not work

If I type "Аннаванна наш отряд хочет видеть поросят" in wrong layout (windows-1252) then select and convert it with hotkey Scroll Lock (to windows-1251) I get "Аяяаваяяа яаш отрнд жочет видеть пороснт"

I think that scancodes of German keyboard are different in compare with English keyboard...

**Comment by SvenKarsten** [comment]
Thank you, it works fine!

**Comment by BladeMight** [comment]
@SvenKarsten Glad you like it, but note: `it not works with Layout switching in Convert Selection(or +).`
