### ISSUE TITLE
Амнезия у чекбоксов.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#108]
![mahou_checkbox_amnesia](https://user-images.githubusercontent.com/21346282/28827137-46aa120e-76d5-11e7-99ab-dcac74da4c57.gif)
Текстфилды при этот норм запоминают всё.

**Comment by BladeMight** [comment]
> Амнезия у чекбоксов

Все потому что я забыл поставить событие обновление временных переменных при клике(изменению состояния) чекбокса, вот исправленная версия:
[Mahou.zip](https://github.com/BladeMight/Mahou/files/1190900/Mahou.zip)

P.S. Скоро сделаю релиз с:
1. Подсказками о пробелах в названиях процессов.
2. Уберу *case sensetive*.
3. 2 ряда вкладок(?).

**Comment by Trost123** [comment]
По-моему проще (потянее для юзера?) сделать разделителем названий не пробел: сброс строки или запятую.
Впрочем, на твоё усмотрение.

**Comment by BladeMight** [comment]
>  сделать разделителем названий не пробел: сброс строки или запятую.

А если все вместе?

**Comment by Trost123** [comment]
Имхо лучше когда постоянство какое-то есть.
Сейчас есть 3 места с таким моментом: "постоянная раскладка", "сниппеты", "программы исключения"
Если везде по-разному будет разделитель - юзеров запутает.
Оборачивать название процесса в кавычки из-за пробела - понятно программисту, но обычному юзеру это еще один "хак" который нужно запоминать.

**Comment by BladeMight** [comment]
> Если везде по-разному будет разделитель - юзеров запутает.

Только в сниппетах особый синтаксис, а в *постоянная раскладка* и *программы исключения* одно и тоже правило.

Кстати по поводу запятых и точек - они же могут быть в именах файлов. Может поставить что-то из того что не может быть в именах? Что-то из этого: `/ \*^<>: ?`

**Comment by Trost123** [comment]
По этому я и предложил line break.
Тем более что так много где делают: robots.txt, скрипты всякие и т.д.

**Comment by BladeMight** [comment]
> line break.

Кстати он уже существовал в *постоянная раскладка*.

**Comment by BladeMight** [comment]
> line break.

Из-за него не можно будет видеть много т.к. высота текстбокса в *программы исключения* маленькая, поэтому я и сделал пробел разделителем.

**Comment by Trost123** [comment]
scrollbar?

**Comment by BladeMight** [comment]
> scrollbar?

Ну он там есть... Хотя не используется...

Сейчас сделаю разделителем line break или пробел.

**Comment by Trost123** [comment]
Просто если можно устранить нужну в
> Подсказки о пробелах в названиях процессов.
То почему бы и нет? Типитчному юзеру меньше думать - тебе респект.

**Comment by BladeMight** [comment]
@Trost123 Готово вот релиз [Mahou-v2.3.4.9](https://github.com/BladeMight/Mahou/releases/tag/v2.3.4.9).

**Comment by Trost123** [comment]
Что-то накосячил: У меня после апдейта вылезла ошибка, и вместо нового exe
оно скачало папку "Mahou-2.3.4.9" с исходниками.

**Comment by Trost123** [comment]
А, дык [тут](https://github.com/BladeMight/Mahou/releases/tag/v2.3.4.9) ссылки на архив с прогой нет.

**Comment by BladeMight** [comment]
@Trost123 Опаньки, релиз не загрузился, перезалил.

**Comment by Trost123** [comment]
Подумай о функции "бета-канал обновлений", а то часто в релиз что-то с косяком выходит, а потом вслед за ним хотфикс =)

**Comment by Trost123** [comment]
Тултип в поле "программы исключения" не вылазит, кстати.

**Comment by Trost123** [comment]
Тултип в поле "программы исключения" не вылазит, кстати.

**Comment by BladeMight** [comment]
> бета-канал обновлений

Уже есть идейка: Создать парсер на [AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou) который будет брать сборку по последнему коммиту.

> Тултип в поле 

Не в поле а на тексте.

**Comment by BladeMight** [comment]
>Не в поле а на тексте.

Выше поля.

**Comment by Trost123** [comment]
Ага, увидел.
Ну тоже как-то непостоянство: в "постоянная раскладка для программ" оно из поля вылезает.
Впрочем, мне и так норм.

**Comment by BladeMight** [comment]
@Trost123 Добавил и при наведение на поле. [коммит](https://github.com/BladeMight/Mahou/commit/85a04b85062ab5b6d6981f7040cc6c8606cb2aa8) [AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou)
