### ISSUE TITLE
[Feature fequest] Исключения на определенные правила.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#109]
Прошлый месяц пока сидел на EveryLang - привык к одной фиче у них:
Мне обычно в играх мешает конверт строки по double shift (который в чат программах очень удобен), а вот переключение раскладки через CapsLock вполне актуально и в играх.
Так вот там исключения [выглядят так](http://prntscr.com/g31h4z).

TLDR: **Сложно ли** сделать чтобы double-shift в определенных программах не срабатывал, а caps lock менял язык везде?
Не критично, но если это быстро делается - было бы круто. 🐈

**Comment by BladeMight** [comment]
> Сложно ли 

Легко, вот: 
[Mahou.zip](https://github.com/BladeMight/Mahou/files/1191202/Mahou.zip)

**Comment by Trost123** [comment]
Прелесть. Только как это будет стачиться с будущими апдейтами? Или теперь это в основной ветке будет?

**Comment by BladeMight** [comment]
@Trost123 Наверное сделаю чекбокс **Менять раскладки одной клавишей даже в исключенных программах**.

**Comment by BladeMight** [comment]
@Trost123 Готово вот [Mahou-v2.3.5.0](https://github.com/BladeMight/Mahou/releases/tag/v2.3.5.0), во вкладке *Тайминги*.
