### ISSUE TITLE
Буфер обмена и convert selection

### ISSUE THREAD

**Issue by Fesko** [BladeMight/Mahou#11]
При convert selection выделенный текст заносится в буфер обмена, заменяя уже там имеющийся. Может можно сохранять ранее находившийся в буфере текст и возвращать после конвертации?

**Comment by BladeMight** [comment]
> Может можно сохранять ранее находившийся в буфере текст и возвращать после конвертации?
Я уже [пробовал](https://github.com/BladeMight/Mahou/blob/master/Mahou/Classes/NativeClipboard.cs#L42) пока что не получалось, а еще так много видов данных что [восстановить некоторые будет не возможно...](http://stackoverflow.com/questions/2578900/how-do-i-backup-and-restore-the-system-clipboard-in-c)
НО, Я попробую...

**Comment by qfeuer** [comment]
Приветствую,
как вариант можно сделать следующее: так как в буфере при такой работе зачастую бывает текст, пусть и с форматированиями, можно сохранять в резервный буфер 255 символов plain text, и после конвертации их вставлять с потерей форматирования. это немного костыль, но внутри письма, работы в ворде, печатания или IDE - этот вариант приемлем. описание можно добавить в tool tip, чтобы возникало меньше вопросов. основная аудитория продукта - гики, как ни крути =)

**Comment by Fesko** [comment]
Поддерживаю вариант @qfeuer

**Comment by BladeMight** [comment]
Вот [Mahou-v1.1.0.0](https://github.com/BladeMight/Mahou/releases/tag/v1.1.0.0) в нем добавлена автоматическое восстановление(только текста).

> 255 символов plain text

А как насчет 65535?(

**Comment by TrueXakeP** [comment]
> Я так понял, что проблема решена...

Нет, текст не восстанавливается. После перевода буфер пуст.
Mahou-v1.5.0.0 с админ правами
Win 8.1 x64
.NET 4.6.01532

От проги нашел только эти 2 файа:
[Mahou.ini](https://github.com/BladeMight/Mahou/files/765551/Mahou.txt)
[Mahou.exe.log](https://github.com/BladeMight/Mahou/files/765553/Mahou.exe.log.txt) (C:\Users\root\AppData\Local\Microsoft\CLR_v4.0\UsageLogs\Mahou.exe.log)

**Comment by BladeMight** [comment]
@TrueXakeP ОК, сейчас гляну...

**Comment by BladeMight** [comment]
Да и впрямь, ошибка в [59 линии](https://github.com/BladeMight/Mahou/blob/master/Mahou/Classes/NativeClipboard.cs#L59) NativeClipboard.cs не правильно созданный массив... Сейчас будет релиз...

**Comment by TrueXakeP** [comment]
Спасибо :)

**Comment by BladeMight** [comment]
@TrueXakeP Готово, [вот](https://github.com/BladeMight/Mahou/releases/tag/v1.5.0.3).

**Comment by TrueXakeP** [comment]
Да, заработало. Спасибо :)

**Comment by BladeMight** [comment]
#305
