### ISSUE TITLE
В текстовом поле сниппетов не работает ctrl+a

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#110]
Не выделяет текст, проверил на двух машинах.

**Comment by BladeMight** [comment]
@Makishima ОК, [исправил](https://github.com/BladeMight/Mahou/commit/61538164d151efdf7d266da9da777b3e1cd51d05), это из-за того что в [.Net в Multiline Textbox ctrl - не поддерживается](https://msdn.microsoft.com/en-us/library/system.windows.forms.textboxbase.shortcutsenabled(v=vs.100).aspx#alert_note)(хотя я так и не понял почему?), сборка на [AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou).

**Comment by BladeMight** [comment]
@Makishima Релиз [Mahou-v2.3.5.4](https://github.com/BladeMight/Mahou/releases/tag/v2.3.5.4).
