### ISSUE TITLE
Настройка 3-х раскладок

### ISSUE THREAD

**Issue by timurmelnikov** [BladeMight/Mahou#111]
Как настроить программу, если у меня 3 раскладки - Русский, Украинский и Английский?

**Comment by BladeMight** [comment]
@timurmelnikov Если хотите что-бы переключало и конвертировало по всем раскладкам то снимите галочку "Переключать между раскладками" во вкладке "Раскладки". Есть еще вариант как использовать 3-ю раскладку, поставить переключение раскладки 1 клавишей на украинскую раскладку клавишей <kbd>R-Alt</kbd>, а <kbd>Caps-Lock</kbd> на переключение между раскладками, и включить "Переключать между раскладками", в итоге получим переключение между раскладками по <kbd>Caps-Lock</kbd> и если нужно переключиться на украинский то нажимаем <kbd>R-Alt</kbd>. 
Если есть конкретное желание как чтобы программа работала - пишите. (например: конвертация выделенного в специфическую(3-ю) раскладку)

**Comment by timurmelnikov** [comment]
Спасибо! Получилось!
