### ISSUE TITLE
Проблемы конвертации в некоторых кейсах (выделением)

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#112]
Оригинал | Конвертация | Коммент
------------ | ------------- | -------------
да да | lflf | В одно слово
Проблемы конвертации |Ghj,ktvs rjydthnfwbbd ytrjnjhs[rrtqcf[ (dsltktybtv) | Мультилайн в одну строку, без пробелов на месте переноса 
в некоторых кейсах | |
(выделением) |  |

**Comment by BladeMight** [comment]
> в некоторых кейсах

т.е. **в некоторых случаях/местах**? Можно по-подробнее? 
Если в выделении нет новой линии(**\r**,**\n**,**\r\n**) то и после конвертации ее не будет.

**Comment by Makishima** [comment]
> т.е. в некоторых случаях/местах? 
нет, под кейсами имел в виду табличку

"да да" в любом приложении превращается в lflf
несколько строк сливаются в одну в некоторых ---  skype, firefox (vk), sublime text, а вот в notepad все ок (строку я и копировал, и писал с нуля)

**Comment by BladeMight** [comment]
@Makishima Это все функция считать раскладку для всего слова, пользуйтесь пока сменой раскладки в КВ(или +).

**Comment by BladeMight** [comment]
ОК, [исправил](https://github.com/BladeMight/Mahou/commit/2b8a407277943e387bb2fde96ddfa78ac6cc74ce) вот проверь:
[Mahou.zip](https://github.com/BladeMight/Mahou/files/1215268/Mahou.zip)

**Comment by BladeMight** [comment]
@Makishima ОК, [исправил](https://github.com/BladeMight/Mahou/commit/2b8a407277943e387bb2fde96ddfa78ac6cc74ce) вот проверь:
[Mahou.zip](https://github.com/BladeMight/Mahou/files/1215268/Mahou.zip)

**Comment by Makishima** [comment]
с https://github.com/BladeMight/Mahou/commit/2b8a407277943e387bb2fde96ddfa78ac6cc74ce работает довольно странно :) в sublime text он влияет на положение курсора и нажатие левой клавиши (notepad так же)

![mahou](https://user-images.githubusercontent.com/5548003/29176799-8a316726-7df5-11e7-8346-c9fd5ba348be.gif)

**Comment by BladeMight** [comment]
@Makishima У тебя что-то не так, я ничего связанного с этим не менял как видно из https://github.com/BladeMight/Mahou/commit/2b8a407277943e387bb2fde96ddfa78ac6cc74ce

**Comment by Makishima** [comment]
@BladeMight проверил на домашнем компе - поведение похожее, только сворачивает окна, но чаще моник выключает 
Вот лог, я даже не знаю как доказать :) [2017.08.10.txt](https://github.com/BladeMight/Mahou/files/1216079/2017.08.10.txt)

**Comment by Makishima** [comment]
Вот лог от той версии, что у меня стояла, все ок с ней[2017.08.10 OLD.txt](https://github.com/BladeMight/Mahou/files/1216082/2017.08.10.OLD.txt)

**Comment by BladeMight** [comment]
> но чаще моник выключает

ДА НУ! С чего бы!???? Вот список изменений которые я сделал:
1. Добавил замену различный line break'ов на \n, благодаря чему начало правильно работать в:
> несколько строк сливаются в одну в некоторых - skype, firefox (vk), sublime text, а вот в notepad все ок

2. Добавил проверку по индексу последнего слова в конвертации выделения с "Считать раскладку для всего слова" включенной, что исправило:
>"да да" в любом приложении превращается в lflf

3. Упростил проверку каждого символа добавив проверку на line break, т.е. его не нужно конвертировать он во всех раскладках один и тот же.

4.  В **KInputs.cs** в функции ** MakeInput** добавил 1 к первому аргументу функции WinAPI - **SendInput**, т.е. увеличил кэш ввода.

Думаешь что-то из-этого влияет на **это**:
>  sublime text он влияет на положение курсора и нажатие левой клавиши (notepad так же) - нажал на пуск ПКМ и залочил комп :)


>только сворачивает окна, но чаще моник выключает]

🤔  ?

**Comment by BladeMight** [comment]
Есть идея почему:

> нажал на пуск ПКМ и залочил комп :)

В #81 посмотри мой последний коммент.

**Comment by Makishima** [comment]
Ставлю на 4 пункт :)
Можно поотлаживаться по teamviewer здесь 824 841 559 pass mahou
Проверил вызывается контекстное меню и сворачиваются окна. Воспроизвести легко - выделяешь текст в файлике и жмешь ScrLk несколько раз

**Comment by Makishima** [comment]
bq. В #81 посмотри мой последний коммент.
непонятно как он убирает фокус из текстового редактора, кроме того, меню, которое на гифке открывается через win+x (при этом в нижней части экрана) или кликом ПКМ на значок пуск (тогда сверху, как на гифке) (у меня тулбар с левой стороны, а не снизу)

**Comment by BladeMight** [comment]
> Ставлю на 4 пункт :)

@Makishima Да, ты прав, только что проверил в teamviewer, видимо в Windows 10 эта единица много значит :) , сборку оставил там.

**Comment by Makishima** [comment]
Вижу, без нее все стабильно работает :)

**Comment by BladeMight** [comment]
@Makishima Я сейчас работаю над **удалением** HOOK'ов, и использованием вместо них *WM_INPUT* ([тестовый прототип](https://github.com/BladeMight/rids)) который будет работать стабильнее и #82 больше не встретится.

**Comment by Makishima** [comment]
Ждем, а пока можно релиз без +1, вроде бы все работает на ура.

**Comment by BladeMight** [comment]
@Makishima Релиз без +1 [Mahou-v2.3.5.6](https://github.com/BladeMight/Mahou/releases/tag/v2.3.5.6).

**Comment by BladeMight** [comment]
Вот почти что готовая версия: [Mahou-no-hooks.zip](https://github.com/BladeMight/Mahou/files/1218694/Mahou-no-hooks.zip) (нужно потестить как работает)

**Comment by BladeMight** [comment]
Вот версия [Mahou+RawInputs.zip](https://github.com/BladeMight/Mahou/files/1218818/Mahou.RawInputs.zip) в которой #114 работает, исправлен баг на вкладке гор. клавиши, улучшена система логгинга, теперь логгинг происходит в другом потоке(т.е. не загружает основной поток) и много других мелких улучшений.

**Comment by BladeMight** [comment]
Лучше все же последнюю с [AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou) возьми если будешь тестить.

**Comment by Makishima** [comment]
@BladeMight взял эту [сборку](https://ci.appveyor.com/project/BladeMight/mahou/build/job/y31nqaolldfh6b5g/artifacts), при попытке снять "нажимать снова модификаторы горячих клавиш" - вылет. Потом вылетело просто когда убрал фокус с окна.
[2017.08.12.txt](https://github.com/BladeMight/Mahou/files/1219549/2017.08.12.txt)
Из интересного в логах
> The process cannot access the file 'G:\Downloads\Mahou\Logs\2017.08.12.txt' because it is being used by another process.
Как будто конкурируют старая и новая система логирования

**Comment by BladeMight** [comment]
@Makishima Ну это проблема в самом логгинге, попробуй поработать без него, а я пока исправлю.

**Comment by BladeMight** [comment]
@Makishima Ну я просто забыл поставить lock, исправил: https://github.com/BladeMight/Mahou/commit/95033b9443bc704888c66e365b027a25a9b50435

**Comment by BladeMight** [comment]
Сделал авто-обновляющийся релиз на GitHub, по последнему коммиту из AppVeyor, [вот](https://github.com/BladeMight/Mahou/releases/tag/latest-commit), теперь буду делать канал обновлений на него.

**Comment by Makishima** [comment]
Вот это удобно будет

**Comment by BladeMight** [comment]
> Вот это удобно будет

@Makishima Готово(сборка там же), как работает обновление:
- При обновлении на последний коммит, Mahou сохраняет hash коммита в Mahou.ini, и по нему проверяет потом есть ли новая версия, а вот если обновиться с *версии последнего коммита* назад на Stable, то эта настройка становиться `Downgraded to Stable` т.е. не равняется ни одному коммиту, другими словами снова позволяет обновиться на *версию последнего коммита*. 
Можешь пока попробовать, я сейчас еще коммит сделаю.

P.S. Как со стабильностью RawInputDevices слушателей (альтернатива low-level HOOK'ов), стоит уже делать новый релиз?

**Comment by Makishima** [comment]
@BladeMight обновился, пока проблем не наблюдаю

**Comment by BladeMight** [comment]
@Makishima Давай потестим пару деньков и тогда уже сделаем релиз.

**Comment by Makishima** [comment]
На работе полет нормальный с #4f004e

**Comment by BladeMight** [comment]
@Makishima Да, у меня тоже всё ОК, сейчас сделаю релиз.

**Comment by BladeMight** [comment]
Релиз [Mahou-v2.4.0.0](https://github.com/BladeMight/Mahou/releases/tag/v2.4.0.0).
