### ISSUE TITLE
Писать лги с расширением *.txt

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#113]
.log не прикрепляется к постам гитхаба

> We don’t support that file type. Try again  with a  PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by BladeMight** [comment]
@Makishima ОК, со следующего релиза.

**Comment by BladeMight** [comment]
Релиз [Mahou-v2.4.0.0](https://github.com/BladeMight/Mahou/releases/tag/v2.4.0.0).
