### ISSUE TITLE
Конвертация не работает на вкладке сниппетов 

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#114]
Стал редактировать список из интерфейса, и понял, что Mahou не может работать сам в себе :)

**Comment by BladeMight** [comment]
@Makishima Ну я думал что будут проблемы например на вкладке горячих клавиш, поэтому выключил вообще при активном Mahou, думаю можно добавить пару исключений :)

**Comment by BladeMight** [comment]
Релиз [Mahou-v2.4.0.0](https://github.com/BladeMight/Mahou/releases/tag/v2.4.0.0).
