### ISSUE TITLE
Добавлять пробел после конвертации по сниппетам

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#116]
Не очень удобно набирать слово, потом пробел и еще раз пробел.
Возможно, не работает со сниппетами настройка "Добавлять 1 пробел в текущее слово"

**Comment by BladeMight** [comment]
> Возможно, не работает со сниппетами настройка "Добавлять 1 пробел в текущее слово"

Не то вообще другая функция, почитай [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9). 
А вот насчет:

> Добавлять пробел после конвертации по сниппетам

Сейчас сделаю.

**Comment by Makishima** [comment]
Не очень понятно из вики, в какой момент срабатывает опция? Вот я ввел слово и нажал Break? Не сработало. Ввел слово, выделил и ScrLck, опять не сработало :)

**Comment by BladeMight** [comment]
@Makishima Она срабатывает так: после ввода если нажать пробел а потом Pause(конверт последнего слова) то произойдет конвертация, а если без нее то нет.

**Comment by BladeMight** [comment]
Релиз [Mahou-v2.4.0.0](https://github.com/BladeMight/Mahou/releases/tag/v2.4.0.0).
