### ISSUE TITLE
Вспыхивает лампочка CapsLock при переключении

### ISSUE THREAD

**Issue by TaciturnShadow** [BladeMight/Mahou#118]
## Проблема/описание запроса

В Mahou 2.4.0.0 при переключении по CaspLock на короткое время загорается лампочка CaspLock, в предыдущих версяих (например 2.3.5.6) такого не было. Так и задумано?

## Ожидаемое поведение (только при сообщении об ошибках)

Хотелось бы переключение без лишней иллюминации.

**Comment by BladeMight** [comment]
@TaciturnShadow Я работаю над исправлением, пока что(в latest-commit версии) на миг загорается лампочка.

**Comment by BladeMight** [comment]
@TaciturnShadow К сожалению лампочка будет *вспыхивать* теперь, т.к. я недавно заменил low-level HOOK'и WM_INPUT'ом, который выполняется чуть медленнее. Возвращаться к HOOK'ам - **не буду** т.к. *вспыхивание лампочки* не так важно как #82 и #77 .

**Comment by BladeMight** [comment]
> К сожалению лампочка будет вспыхивать теперь, 

@TaciturnShadow А теперь **не будет**,подробнее в #143.

**Comment by TaciturnShadow** [comment]
Да, всё стало снова хорошо, огромное спасибо!

Можно «Wont-Fix» менять на «Fixed».

**Comment by BladeMight** [comment]
@TaciturnShadow ОК, так и сделал.
