### ISSUE TITLE
Mahou changelog nOTPa4eHO

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#119]
Не в обиду, но уже давно заметил что чейнчлоги в Mahou местами выглядят так, будто их гугл транслейтом переводили. Для меня уже мини игрой стало "угадай что там было задумано".
Судя по отзывам на GitHub - у приложения большая часть пользователей русскоязычные. Может не морочить голову и оставлять чейнжлог на рус.? И разработчику меньше мороки, и пользователю понятней. А англоязычный юзер всегда сможет в гуглтранслейт вбить сам при необходимости.

**Comment by BladeMight** [comment]
> оставлять чейнжлог на рус.

оставлять? т.е. ставить в releases на релизы на русском? или ты про readme? Я оставляю только англ. а рус. перевожу на месте в Readme.

Когда-то очень давно был [один релиз на русском](https://github.com/BladeMight/Mahou/releases/tag/v1.1.2.0).

>но уже давно заметил что чейнчлоги в Mahou местами выглядят так, будто их гугл транслейтом переводили

Ну значит мой перевод похож на моего учителя английского(Google Translate) :)

P.S. А какой язык похоже на Google Translate, англ.(взято из [commit'ов](https://github.com/BladeMight/Mahou/commits/master)) или рус.(перевод на месте с того английского)?

**Comment by Trost123** [comment]
Я говорю про англ. тексты, которые появляются в окне "что нового", в windows, когда есть апдейт Mahou.

Скорее всего они берутся [отсюда](https://github.com/BladeMight/Mahou/releases).
Это не критично. Просто предложение не делать лишней работы. (Или оставлять оба варианта?)

**Comment by BladeMight** [comment]
> Просто предложение не делать лишней работы

Нет ты как раз предложил *делать* лишнюю работу, т.е. переводить на русский, т.к. оригинал и есть на английском.

**Comment by Trost123** [comment]
А, понял. Тогда отбой, сорри.
