### ISSUE TITLE
Сохранение пользовательских горячих клавиш при обновлениях Mahou

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#12]
Здравствуйте, я задал собственные (поскольку те, что в Mahou по умолчанию, заняты у меня в другой программе) сочетания: <kbd>F10</kbd> для смены раскладки в строке и <kbd>Shift+F10</kbd> для смены раскладки на последнем слове. Можно ли сделать, чтобы после обновлений Mahou не происходил сброс моих хоткеев на дефолтные?

Спасибо.

**Comment by BladeMight** [comment]
> чтобы после обновлений Mahou не происходил сброс моих хоткеев на дефолтные?

У меня не происходит...
Приложите здесь ваш `Mahou.ini`.
Попробуйте удалить его и загрузить версию 1.0.9.7(https://github.com/BladeMight/Mahou/releases/tag/v1.0.9.7) и настроить все, а потом обновиться.

**Comment by Kristinita** [comment]
Обновлялся на 1.1.0.0. А на 1.1.0.1 обновиться совсем не получается. 

![Обновление Mahou](http://i.imgur.com/tg2STXh.gif)

Спасибо.

**Comment by BladeMight** [comment]
> Обновлялся на 1.1.0.0. А на 1.1.0.1 обновиться совсем не получается. 

Я лично КАЖДЫЙ раз сам обновляюсь, чтобы проверить работает ли, так что у вас были проблемы с интернетом во время скачивания...

**Comment by Kristinita** [comment]
Вроде теперь корректно работает. Спасибо!

**Comment by BladeMight** [comment]
> у вас были проблемы с интернетом

На случай проблем с интернетом добавил таймаут, в [версии 1.1.0.4](https://github.com/BladeMight/Mahou/releases/tag/v1.1.0.4).
