### ISSUE TITLE
Donate using Visa\Mastercard?

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#120]
Есть ли возможность скинуть денег на  🍕/☕️  разработчику без регистрации в WM\YM?
Ради меня одного заморачиваться не стоит, но я думаю донейты чаще капали бы, если был бы доступен удобный способ для людей, живущих за пределами России.

**Comment by BladeMight** [comment]
Полезная идея, но у меня пока нет Vis'ы/Mastercard'а думаю скоро сделаю, а есть ли еще какие-то варианты? И да еще вот недавно на YM прислали с карточки, т.е. без регистрации.

P.S. Тортики и кофе люблю :)

**Comment by Trost123** [comment]
Попробую на днях на YM с карточки, не знал что так можно.

**Comment by Trost123** [comment]
Мда, у нас Яндекс заблочен же в стране. А через бесплатный прокси\ВПН стрёмно вводить свои данные карточки.

**Comment by BladeMight** [comment]
@Trost123 Ну тогда не стоит.

**Comment by BladeMight** [comment]
@Trost123 Добавил MasterCard.
