### ISSUE TITLE
После обновления до 2.4.0.0. сломалось переключение раскладок по левому и правому shift

### ISSUE THREAD

**Issue by coctic** [BladeMight/Mahou#121]
## Проблема

У меня установлено включение нужной раскладки по левому и правому shift (левый - русская, правый - США). Т.е. в настройках на вкладке "раскладки" стоит галка "переключать раскладки по клавишам", ниже выбрано
"Left Shift -> Русская(68748313)"
"Right Shift -> США(67699721)"

При нажатии на shift раскладка не переключается. 

## Ожидаемое поведение

Чтобы включалась нужнася раскладка. До обновления на 2.4.0.0 все работало. При этом конвертация выделения по-прежнему работает.

## Системная информация

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>

- Mahou 2.4.0.0
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Русская(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=False
[Functions]
TrayIconVisible=True
ConvertSelectionLayoutSwitching=True
ReSelect=False
RePress=True
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=True
ScrollTip=False
StartupUpdatesCheck=True
Logging=False
CapsLockTimer=False
TrayFlags=False
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=True
RestartHooksOnHotkeyActionEnd=True
[Layouts]
SwitchBetweenLayouts=False
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Ctrl+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=США(67699721)
MainLayout2=Русская(68748313)
SpecificKey1=4
SpecificKey2=5
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Русская(68748313)
SpecificLayout2=США(67699721)
SpecificLayout3=
SpecificLayout4=
OneLayout=False
QWERTZfix=False
[Appearence]
DisplayLangTooltipForMouse=False
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
Language=Русский
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Georgia; 8pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Georgia; 8pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Georgia; 8pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Georgia; 8pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
Layout1LTText=
Layout2LTText=
MouseLTAlways=False
MouseLTUseFlags=False
CaretLTUseFlags=False
MouseLTUpperArrow=False
CaretLTUpperArrow=False
[Timings]
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
ChangeLayoutInExcluded=True
[Snippets]
SnippetsEnabled=False
SpaceAfter=False
[Hotkeys]
ToggleMainWindow_Enabled=False
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=False
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=True
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=Shift
ConvertSelectedText_Key=19
ConvertLastLine_Enabled=False
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=False
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=16
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Shift
SelectedTextToRandomCase_Key=17
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win + 
SelectedTextToSwapCase_Key=19
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win + 
SelectedTextTransliteration_Key=191
ExitMahou_Enabled=False
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=False
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
ToggleLangPanel_Enabled=True
ToggleLangPanel_Double=False
ToggleLangPanel_Modifiers=Shift
ToggleLangPanel_Key=120
```
</details>
</details>
</details>

## Приложите логи

Приложил лог.
[2017.08.15.txt](https://github.com/BladeMight/Mahou/files/1225416/2017.08.15.txt)

**Comment by BladeMight** [comment]
@coctic Да, все из-за того что в новом способе ловить клавиши (WM_INPUT) модификаторы(Ctrl,Alt,Shift) не разделялись на левые/правые по умолчанию, сейчас добавил свой *разделитель*, можешь обновиться по каналу latest-commit и проверь.

**Comment by coctic** [comment]
Да теперь работает. Но вернулся другой глюк, который был и до обновления. У меня конвертация выделения в дргую раскладку стоит в Shift+Pause. Соответственно, после конвертации после отпускания Shift раскладка переключается в зависимости от того, с каким Shift была нажата Pause. То есть фактически он сначала конвертирует, а потом при отпускании Shift переключает раскладку в зависимости от того, какой это Shift (левый или правый). А очень хочется, чтобы раскладка оставалась той, в которую проищошла конвертация. Если поставить на ковертацию сочетание клавиш без Shift, то все так и работает, но вот привык я к Shift+Pause еще со времен Punto. Нельзя ли сделать так, чтобы и с Shift+Pause все работало вне зависимости от того, какой Shift я зажимаю?

**Comment by BladeMight** [comment]
Сейчас что-то придумаю.

**Comment by BladeMight** [comment]
@coctic ОК, готово попробуй.(сборка там же)

**Comment by coctic** [comment]
Скачал, попробовал, не работает.

Открываю Notepad, пишу там русский текст, выдлеяю его, жму левый Shift + Pause. Все конвертируется, до отпускания Shift язык английский, как только отпустил Shift - включается русский.

**Comment by BladeMight** [comment]
@coctic Может включена функция менять раскладку в конверт выделения или может быть ты слишком быстро обновился(сборка появляется через минуту)
. У меня все нормально, вот смотри:

![mahou works](https://user-images.githubusercontent.com/11931888/29359622-0bb47a5e-8288-11e7-9e77-b70b3a47307b.gif)

**Comment by coctic** [comment]
Да, "Менять раскладку в конверт выделения" была включена, но дело не в ней. Оказалось, надо было снять "Нажимать снова модификаторы горячих клавиш".

Теперь все работает, огромное спасибо.

Остался еще один вопрос - когда снова можно переключаться на канал обновления Stable? А то я попробовал переключиться, так мне после проверки обновлений предложили откатиться к 2.4.0.0. А у меня включена "автоматическая проверка обновлений", так он почему-то не только их проверяет, но и автоматом ставит (по крайней мере раньше так делал), поэтому сразу канал переключить нельзя, а то после переезагрузки оно откатится на 2.4.0.0

**Comment by BladeMight** [comment]
> Нажимать снова модификаторы горячих клавиш

Ох как мне не нравится эта функция, нужно вообще ее убрать из-за нее вот что бывает еще: #81

> когда снова можно переключаться на канал обновления Stable

Когда я сделаю следующий релиз, думаю сейчас сделаю. Сидите пока на latest-commit.

> автоматом ставит 

**Только** если нажать на OK при выходе сообщения окна обновления при запуске.

> после проверки обновлений предложили откатиться к 2.4.0.0

Ну это я сделал на случай если пользователь захочет переключится туда-сюда из Stable на latest-commit и наоборот.

**Comment by BladeMight** [comment]
Думаю добавлю правило в котором если версия Stable (на github) больше чем dev (та что у пользователя) только тогда предлагать обновиться из latest-commit при запуске.

**Comment by BladeMight** [comment]
> Думаю добавлю правило в котором если версия Stable (на github) больше чем dev (та что у пользователя) только тогда предлагать обновиться из latest-commit при запуске.

Только что посмотрел, а там оно уже есть. :)

**Comment by coctic** [comment]
Переключил канал на Stable, посмотрим после перезагрузки.

Спасибо.

**Comment by BladeMight** [comment]
@coctic Релиз [Mahou-v2.4.0.5](https://github.com/BladeMight/Mahou/releases/tag/v2.4.0.5).

**Comment by BladeMight** [comment]
> Ох как мне не нравится эта функция

Пока что оставил, и исправил:

>Оказалось, надо было снять "Нажимать снова модификаторы горячих клавиш".

**Comment by coctic** [comment]
А на #81 я тоже наступал, и тоже с Alt, просто не дошли руки разобраться, кто же его дает (какая программа). Отключил эту функцию, судя по описанию в  Wiki, она мне и не нужна, даже не помню, зачем включал.

**Comment by BladeMight** [comment]
>  даже не помню, зачем включал.

А может и не ты, раньше(еще в версиях ниже 1.5) она стояла по умолчанию(до того как я нашел баг).
