### ISSUE TITLE
Конвертация последнего или выделенного слова одной комбинацией клавиш (клавишей)

### ISSUE THREAD

**Issue by suturn123** [BladeMight/Mahou#122]
Приветствую! перешел на Mahou после того как punto стал стабильно вешать chrome и многие другие приложения (и это при отключенной автозамене).. собственно автозаменной никогда не пользовался. 
Мне очень удобно переключать раскладку и конвертировать введенное слово клавишей PAUSE . иногда возникает конвертировать выбранные выделением слова -
-!! Оч удобно (до автоматизма) делать конвертацию и выделенных слов той же клавишей PAUSE (она всегда навострена на раскладку или конвертацию) . 

Ситуация:
Сейчас в приложении Mahou есть возможность назначить в горячих клавишах PAUSE как на конвертацию последнего слова так и выделенного текста. Но при этом приложение реагирует только для последнего слова на выделенном тексте ничего не происходит.

Возможно ли как то поправить ? Mahou мне показался оптимальным и безглючным (на текущий момент) приложением. Пока не ясность с назначением  одинаковой клавиши для разных операций (в пунто кстати такой вариант с назначением проканывал).

**Comment by BladeMight** [comment]
@suturn123 Вы уверены? Какая у Вас версия Mahou? У меня работает, вот действия:
1. Назначил обе клавиши на Pause.
2. Попробовал написать слово -> Pause -> Конвертировалось.
3. Выделил какой-то текст -> Pause -> Конвертировалось.

**Comment by BladeMight** [comment]
@suturn123 Если у Вас старая версия обновитесь к последней, [вот здесь](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9E%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B5%D0%BB%D0%BA%D1%83-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0-%D0%B2%D0%B2%D0%BE%D0%B4-%D0%B2%D0%B5%D1%80%D1%85%D0%BD%D0%B5%D0%B3%D0%BE-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0).

**Comment by BladeMight** [comment]
@suturn123 Раннее уже спрашивали такое #104

**Comment by BladeMight** [comment]
> Назначил обе клавиши на Pause.

Заметил баг в текущей последней релиз версии, что если включен какой-то из таймеров (Scroll-Lock или Caps-Lock) то настроит 2 горячие клавиши на Pause крайне сложно, исправил в https://github.com/BladeMight/Mahou/commit/752d3671951741003c7af117f3bfc8cf60f4f111 сборка есть [здесь](https://github.com/BladeMight/Mahou/releases/tag/latest-commit) или обновитесь из Mahou по каналу latest-commit.

**Comment by suturn123** [comment]
ЗАРАБОТАЛО, шикарно! С обновлением 752d367 build #327.

Кстати ,предыдущий релиз стоял у меня 2.3.4.0. Видимо забыл обратно включить пункт, чтобы проверял обновление автоматом. Хотя таймер caps lock отключал, подсвечивание для Scroll lock не включал) , но факт в том что в новых версиях всё работает.

Спасибо за мега оперативный ответ!

**Comment by BladeMight** [comment]
@suturn123 Рад был помочь, обращайтесь еще если что.
