### ISSUE TITLE
Переключение раскладки по Shift+Pause или ScrollLock

### ISSUE THREAD

**Issue by pi100n** [BladeMight/Mahou#124]
Возможность переключать раскладки по Shift+Pause или ScrollLock.

**Comment by BladeMight** [comment]
Ну можно добавить, но вы уверены что это удобнее чем просто одной клавишей (Caps-Lock/Правый альт)

**Comment by pi100n** [comment]
Привет!
Когда конвертируешь последнее введенное слово через Pause, то еще и переключается раскладка, но когда то же самое делаешь для выделенного текста, то раскладка остается старая, может есть опция или можно ли добавить, чтобы раскладка переключалась и при конвертации выделенного фрагмента?
Я обычно печатаю фразы не смотря на экран, поэтому часто приходится выделять текст и конвертировать, потом продолжаю печатать дальше, снова не смотря на экран и в Пунто Свитчере привык. что раскладка меняется =) Теперь же приходится постоянно выделять и конвертировать куски текста.

**Comment by BladeMight** [comment]
@pi100n Ну так уже понятнее, функция называется **менять раскладку в конвертациях выделения**, почитайте [wiki](https://github.com/BladeMight/Mahou/wiki).

**Comment by pi100n** [comment]
да, спасибо, все работает! просто шикарно =)

**Comment by BladeMight** [comment]
Обращайтесь еще если что.
