### ISSUE TITLE
Постоянная раскладка потребляет слишком много ЦП.

### ISSUE THREAD

**Issue by saroff** [BladeMight/Mahou#128]
Отключил все функции (все горячие клавиши и т.д. кроме "постоянной раскладки" для ряда приложений. Обычно потребление ЦП низкое, но иногда вырастает до 20%, причем держится такое значение минут по 10. Отладочная инфо:
`<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>

- Mahou 2.4.0.8
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

US(67699721)
Russian(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=False
[Functions]
AutoStartAsAdmin=False
TrayIconVisible=True
ConvertSelectionLayoutSwitching=False
ReSelect=False
RePress=False
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=False
Logging=False
CapsLockTimer=False
TrayFlags=False
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=False
[Layouts]
SwitchBetweenLayouts=False
OneLayout=False
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=False
MainLayout1=US(67699721)
MainLayout2=Russian(68748313)
SpecificKey1=1
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Переключать между раскладками
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
QWERTZfix=False
[PersistentLayout]
ActivateForLayout1=True
ActivateForLayout2=False
Layout1CheckInterval=50
Layout2CheckInterval=50
Layout1Processes=webstorm64.exe ConEmu.exe ConEmuC64.exe idea64.exe
Layout2Processes=notepad++.exe winword.exe
[Appearence]
DisplayLangTooltipForMouse=False
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
MouseLTAlways=False
Language=Русский
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Microsoft Sans Serif, 8.25pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Microsoft Sans Serif, 8.25pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Microsoft Sans Serif, 8.25pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Microsoft Sans Serif, 8.25pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
MouseLTUseFlags=False
CaretLTUseFlags=False
Layout1LTText=
Layout2LTText=
MouseLTUpperArrow=False
CaretLTUpperArrow=False
[Timings]
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
ChangeLayoutInExcluded=True
[Snippets]
SnippetsEnabled=False
SpaceAfter=False
SwitchToGuessLayout=False
[Hotkeys]
ToggleMainWindow_Enabled=False
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=False
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=False
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=
ConvertSelectedText_Key=145
ConvertLastLine_Enabled=False
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=False
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=False
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=0
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=False
SelectedTextToRandomCase_Modifiers=Shift
SelectedTextToRandomCase_Key=0
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win +  
SelectedTextToSwapCase_Key=190
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win +  
SelectedTextTransliteration_Key=191
ExitMahou_Enabled=False
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=False
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
ToggleLangPanel_Enabled=False
ToggleLangPanel_Double=False
ToggleLangPanel_Modifiers=Shift
ToggleLangPanel_Key=120
[LangPanel]
Display=False
Transparency=90
RefreshRate=25
Position=X0 Y0
ForeColor=#000000
BackColor=#FFFFFF
Font=Microsoft Sans Serif, 25pt
BorderColor=#8B5FFF
BorderAeroColor=True
UpperArrow=True
[Updates]
Channel=Stable
LatestCommit=
```
</details>
</details>
</details>`

**Comment by BladeMight** [comment]
@saroff Чем ниже интервал проверки тем выше потребление ЦП, попробуйте увеличить интервал проверки до 150:
![default](https://user-images.githubusercontent.com/11931888/30065908-0ba3dc08-925f-11e7-9888-0c44c14b8cc1.PNG)

P.S. У меня выше 5% не поднималось даже с интервалом в 1мс. ЦП: 4x2.3 ГГц

**Comment by saroff** [comment]
Включена только одна раскладка (Раскладка 1) для 3 разных процессов. Интервал обновления стоял дефолтный, 50. 

Поигрался с интервалами обновления: 
Если поставить совсем маленький (1мс)  сразу поднимается до 30-35% и держится стабильно.
С увеличением постепенно падает. При 150мс 15-20%. При 500мс 5-7% нагрузки, все это держится стабильно.

Закрыл указанные процессы - не нашел чтобы это влияло.

**Comment by BladeMight** [comment]
> Закрыл указанные процессы - не нашел чтобы это влияло

Полезная информация, есть идея в чем может быть дело.

> После перезагрузки компьютера даже с 1мс интервалом ЦП почти не потребляет

Странно...

> перезапускать сам Mahou еще не пробовал. 

Ну если так то есть горячая клавиша для перезапуска, по умолчанию<kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>Page Up</kbd>.

> Кажется со временем что-то утекает.

Тоже нужно будет проверить.

**Comment by BladeMight** [comment]
Кстати неплохо бы обновиться а то у Вас 2.4.0.8, а уже 2.4.5.0.

**Comment by BladeMight** [comment]
>>    Закрыл указанные процессы - не нашел чтобы это влияло

>Полезная информация, есть идея в чем может быть дело.
>Кажется со временем что-то утекает.

Сейчас поставил проверку на постоянную раскладку в 8 процессах, интервал в 1мс, запустил все и оставил в фоне, посмотрим что будет со временем...

**Comment by BladeMight** [comment]
@saroff Целый день тестил, проблемы не заметил, думаю попробую улучшить что-то с таймерами, в следующем релизе.

**Comment by BladeMight** [comment]
@saroff Возможно вам пригодиться новая функция из #145 которая потребляет меньше ЦП.

**Comment by BladeMight** [comment]
@saroff После исправления https://github.com/BladeMight/Mahou/commit/25871950955f4a51a83f2512343a4f24626320ae должно меньше потреблять.

**Comment by BladeMight** [comment]
@saroff После https://github.com/BladeMight/Mahou/commit/dfc88c84a22372afe9e37c7c8f6487c2b80e1914 в котором сильно отпимизирована функция постоянной раскладки, Mahou стал еще меньше потреблять ЦП <1%, пока только в latest-commit версии.

**Comment by BladeMight** [comment]
@saroff Релиз [Mahou-v2.6.2.0](https://github.com/BladeMight/Mahou/releases/tag/v2.6.2.0).
