### ISSUE TITLE
Игнорирование небуквенных символов

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#13]
Допустим, мне понадобилось изменить раскладку набранного текста. Вместе с текстом меняются запятые, скобки, кавычки и т. д. Они часто у меня бывают написаны в правильной раскладке, а вот буквы в неправильной. Могли бы Вы сделать дополнительные шорткаты, при нажатии на которые менялась бы раскладка только у буквенных символов — `[А-Яа-яЕё]` и `[A-Za-z]`? Спасибо.

**Comment by BladeMight** [comment]
Включите CS-Switch

**Comment by Kristinita** [comment]
У меня стоит галочка, но раскладка у небуквенных символов изменяется:

![CS-Switch](http://i.imgur.com/ur2rpVS.gif)

Да, если б написали документацию к новым функциям Mahou на русском, было бы неплохо :smile: . Кажется, не всё там понимаю...

Спасибо.

**Comment by BladeMight** [comment]
Ну я про Convert Selection, а насчет Руссификации и документации я уже собираюсь сделать.

**Comment by qfeuer** [comment]
Добрый день, на мой взгляд этого функционала не должно быть, так как нужна именно конвертация раскладки, а значить всего набранного в этом количестве символом. 99% случаев это - ghbdtncnde., yt [jnbnе kb vzurb[ ahfywepcrb[ ,ekjr, xnj bcgtrkb ctujlyz

**Comment by BladeMight** [comment]
в 

> ghbdtncnde., yt [jnbnе kb vzurb[ ahfywepcrb[ ,ekjr, xnj bcgtrkb ctujlyz

запятая не в той раскладке :laughing:

**Comment by qfeuer** [comment]
вот и я, примерно о том же =)

**Comment by Kristinita** [comment]
> Добрый день, на мой взгляд этого функционала не должно быть, так как нужна именно конвертация раскладки, а значить всего набранного в этом количестве символом. 99% случаев это - ghbdtncnde., yt [jnbnе kb vzurb[ ahfywepcrb[ ,ekjr, xnj bcgtrkb ctujlyz

1. «Не должно быть» — в принципе, плохой подход для программиста. Даже если игнорирование небуквенных символов необходимо лишь в одном проценте случаев, если опция будет введена, хуже от этого не станет, а кому-то она пригодится.

2. По моему вероятностному суждению процент не 1, а где-то 20. Проблемы с раскладкой у меня часто начинаются после введения знаков препинания.

Спасибо.

**Comment by BladeMight** [comment]
Я в принципе могу добавить возможность разпознования по текущей локали, но будет работать только для EN(1033)/RU(1049).

**Comment by Kristinita** [comment]
> Как у вас вообще получается вводить не те символы в ТОЙ раскладке?

мне приходится писать тексты, где много скобок, кавычек и прочих спецсимволов. Угловые, фигурные и квадратные скобки есть только в английской раскладке.

![Клавиатура справа](http://i.imgur.com/j0JxrhW.png)

Проблемы с раскладкой возникают, когда я ввожу первую скобку в английской раскладке, а потом не переключаюсь на русскую, когда после скобок надо писать русские символы. Вот и хочется, чтобы была возможность оставить скобки как есть, но изменить раскладку только букв.

Спасибо.

**Comment by BladeMight** [comment]
> Вот и хочется, чтобы была возможность оставить скобки как есть, но изменить раскладку только букв.

Тогда придется забыть про `х`,`Х`,`ъ` и `Ъ`.

**Comment by BladeMight** [comment]
Можно добавить хоткей переключающий конвертиртацию с символами и без.

**Comment by Kristinita** [comment]
> Можно добавить хоткей переключающий конвертиртацию с символами и без.

Было бы неплохо :smile: .

**Comment by BladeMight** [comment]
> Было бы неплохо :smile: .

Проверь версию 1.1.3.0, горячая клавиша `Ctrl+Alt+Shift+F11`.([Подробнее](https://github.com/BladeMight/Mahou/releases/tag/v1.1.3.0))

**Comment by Kristinita** [comment]
1. Добавьте, пожалуйста, возможность пользователям самим выбрать горячие клавиши . 4 кнопки для функции, которая, возможно, будет использоваться часто, многовато.

2. Не всё остаётся на месте. Также можно добавить отмену конвертации символов, которые на одних клавишах с цифрами и буквой ё: `'@#$^&`.

![1](http://i.imgur.com/8BVqjCD.gif)

Спасибо.

**Comment by BladeMight** [comment]
> Также можно добавить отмену конвертации символов, которые на одних клавишах с цифрами и буквой ё: '@#$^&.

А вот и нет! Если их добавить то про русские символы придется забыть как и про буквы...

> 4 кнопки для функции, которая

В смысле, для одной функции 4 гор. клавиши???

> Не всё остаётся на месте

`>` и правда остается

**Comment by BladeMight** [comment]
> > и правда меняется

Исправлено в [Mahou-v1.1.3.2](https://github.com/BladeMight/Mahou/releases/tag/v1.1.3.2).

**Comment by Kristinita** [comment]
> В смысле, для одной функции 4 гор. клавиши???

`Ctrl+F11` нажимать легче, чем `Ctrl+Alt+Shift+F11`.

**Comment by BladeMight** [comment]
> Ctrl+F11 нажимать легче, чем Ctrl+Alt+Shift+F11.

Ну я выбирал так чтобы **конфликтов** с другими программами **точно** не было.
Ну а вообще добавлю по-позже.

**Comment by Kristinita** [comment]
> Ну а вообще добавлю по-позже.

Ждём. И чтобы по умолчанию можно было бы этот режим установить.

**Comment by BladeMight** [comment]
> Ждём. И чтобы по умолчанию можно было бы этот режим установить.

Все готово в [Mahou-v1.1.3.5](https://github.com/BladeMight/Mahou/releases/tag/v1.1.3.5).
Почитайте всплывающую подсказку над "Игнор. символов" в "Дополнительных настройках"(раньше "Расширенная настройка Ctrl'ов").

**Comment by BladeMight** [comment]
@Kristinita ну так что?

**Comment by BladeMight** [comment]
Видимо, ответа - нет, но действительно работает...
