### ISSUE TITLE
Проблема с местом хранения файла настроек

### ISSUE THREAD

**Issue by stolpov** [BladeMight/Mahou#130]
Большое спасибо за последнее обновление v2.4.5.0, в котором добавлена возможность запускать одновременно под несколькими аккаунтами. Теперь Mahou работает на серверных ОС одновременно у нескольких пользователей. 

Но есть проблема, когда политикой компании блокируются все приложения не из системных папок. В таком случае нет возможности запускать Mahou из папки пользователя. А если запускать из Program Files, то тогда получается только один файл с настройками для всех, при этом без прав на запись. Это не удобно, так как сложно подобрать файл настроек, который бы удовлетворял всех пользователей.

Можно ли добавить возможность выбирать место хранения файла настроек для пользователя?
Вот просто пример того, как это сделано во FreeCommander: если рядом с программой положить файл fcStart.ini со строкой `freeCommanderIniDir=%appdata%\FreeCommander XE\`, то программа уже берёт личные настройки пользователя из профиля. Ну или добавить галочку в интерфейс, которая реализует что-то подобное.

**Comment by BladeMight** [comment]
@stolpov ОК, добавлю галочку для сохранения настроек в профиле текущего пользователя, проблема только в этом: как сохранить настройку "сохранять в AppData" в Mahou.ini если нет прав на запись?

**Comment by stolpov** [comment]
У администратора есть права на запись. Поэтому можно так: администратор запускает Mahou и ставит галочку, которая применяется для всех пользователей. Если после этого обычный пользователь запускает программу, то при наличии этой галочки используются/создаются настройки в AppData. 

А в идеале можно сделать так, чтобы при первом запуске под обычным пользователем файл Mahou.ini копировался из папки программы, а не создавался с нуля. В таком случае администратор сможет при желании немного повлиять на первоначальные настройки обычного пользователя.

**Comment by BladeMight** [comment]
@stolpov Так и сделаю.

**Comment by BladeMight** [comment]
@stolpov Пришел вот домой, сделал (https://github.com/BladeMight/Mahou/commit/c601d0aefa020ba01704f5f355455e83652a05c0) можете обновиться по каналу latest-commit и проверить. (Галочка во вкладке Функции)

**Comment by BladeMight** [comment]
P.S. Может логи тоже туда сохранять? А то ведь прав на запись в Program Files - нет.

**Comment by stolpov** [comment]
Основной функционал работает. Но кажется при первом запуске от обычного пользователя не полностью копируется текущая конфигурация. То есть новый файл в AppData с разными параметрами. А если после этого открыть приложение из трея и закрыть, то при новом открытии некоторые галочки уже стоят в других местах. Такое впечатление, что постоянно обращается к разным файлам настроек.

P.S. Можно сохранять логи тоже в AppData. Но тогда туда же хорошо бы сохранять и snippets.txt и AS_dict.txt

**Comment by BladeMight** [comment]
> Но кажется при первом запуске от обычного пользователя не полностью копируется текущая конфигурация.

Ага вижу, исправил добавив условие что если настройки уже существуют в AppData то тогда просто загрузить, иначе создать новые и импортировать с основного Mahou.ini.

> P.S. Можно сохранять логи тоже в AppData. Но тогда туда же хорошо бы сохранять и snippets.txt и AS_dict.txt

Все, сделал.

P.S. Прям круто как-то иметь глобальную и пользовательскую настройку и переключаться между ними, мне идея очень понравилась 👍 :)

**Comment by BladeMight** [comment]
@stolpov В последней бете все работает как надо, закрываю.

**Comment by BladeMight** [comment]
А, нет лучше после нового релиза.

**Comment by BladeMight** [comment]
@stolpov Закрываю с релизом [Mahou-v2.5.0.0](https://github.com/BladeMight/Mahou/releases/tag/v2.5.0.0).
