### ISSUE TITLE
Не обновляет сниппеты если количество не изменилось.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#131]
Имхо это мини-даунгрейд. Редактируешь сниппет и нужно перезапускать Mahou, раньше такого не было.
У меня всего 3 сниппета, но содержимое одного из них время от времени меняю.
Я понимаю что это имеет смысл в "автозамене", где вы тысячи слов вбиваете, но в сниппетах странно это видеть.

_P.S. Надеюсь что Mahou со временем не раздуется до уберкомбайна из-за постоянных feature-request-ов и фиксов для супер-специфических багов._ 💭

**Comment by BladeMight** [comment]
>Имхо это мини-даунгрейд. 

Согласен, но я внедрял это правило только из-за того что раньше Mahou слишком долго инициализировал большой словарь автозамены, а после того как в https://github.com/BladeMight/Mahou/commit/737eb80898d83d589167c6cdaf2e603a1a4cc3ea я написал собственный парсер(который **намного** быстрее), можно было уже и убрать... просто поленился тогда... Сейчас в latest-commit версии убрал правило.(коммит: https://github.com/BladeMight/Mahou/commit/a6fe72750d14fc620b32ab640fde10f4896ec58d)

> P.S. Надеюсь что Mahou со временем не раздуется до уберкомбайна из-за постоянных feature-request-ов и фиксов для супер-специфических багов. 💭

Стараюсь делать все как можно минималистичнее и быстрее.
