### ISSUE TITLE
Mahou Updates Delay Information

### ISSUE THREAD

**Issue by BladeMight** [BladeMight/Mahou#132]
Через неделю я иду в армию, где-то на 1.5 года, Mahou за это время обновляться не будет. Вы и дальше можете создавать issue, чтобы потом когда я приду смог сразу знать что исправлять.

P.S. Правда есть вероятность что я и в армии смогу обновлять Mahou, но это очень малая вероятность.

**Comment by Trost123** [comment]
Good luck! :godmode:

**Comment by MishGa** [comment]
Удачи. Спасибо за работу.

**Comment by BladeMight** [comment]
> Через неделю я иду в армию

Тогда было не точно, но точно: завтра 23.11.17 я иду в армию.

**Comment by avently** [comment]
@BladeMight надеюсь, тебе там понравится! Там может быть классно. Удачи

**Comment by Trost123** [comment]
Ну ноги жалко что угробили из-за такой глупости. А по поводу язвы - выходит же еще до армии была? Тогда хорошо что сейчас заметил, а не позже...

**Comment by BladeMight** [comment]
Да походу была, но в областной комиссии даже не проверяли, а здесь в госпитале сразу начали проверять все о чем я говорил, в общем в хороший госпиталь попал. Мне тут нравиться, соседи отличные и кормят хорошо. 
Ноги уже лучше, по-тихоньку спадает опухоль. В общем пока все хорошо.

**Comment by BladeMight** [comment]
Все, я вернулся домой, комиссовали по язве. Я снова с Вами. :)

**Comment by avently** [comment]
@BladeMight как всегда быстро закрываешь issues

**Comment by BladeMight** [comment]
эт точно )
