### ISSUE TITLE
Падает MS Office (Word, Excel)

### ISSUE THREAD

**Issue by AndreWin** [BladeMight/Mahou#133]
Добрый день.

После того, как вышел chrome 60, он перестал падать из-за mahou. И последующие обновления тоже перестали. Но стал падать word и excel.

Прежде всего, mahou мешает их запуску. Запускаю word - он запускается и сразу зависает. Если выключу mahou и запущу ms word, то работает нормально.

С недавнего времени word стал зависать ещё в процессе работы. Грешил на отображение флажка у курсора. Оказалось, зависает ещё и переключении раскладки.

Пока есть только [Отладочная информация](https://github.com/BladeMight/Mahou/files/1304305/default.zip). 

Удалось записать лог - упал Excel: [2017.09.14.txt.zip](https://github.com/BladeMight/Mahou/files/1304320/2017.09.14.txt.zip)

С уважением, Андрей.

**Comment by BladeMight** [comment]
В #98 тоже самое(но только на англ.).

> Прежде всего, mahou мешает их запуску.

Это функция отображения языка возле каретки, которая подключает потоки активного процесса с потоком Mahou... Можно попробовать увеличить интервал проверки для каретки во вкладке тайминги.

> Грешил на отображение флажка у курсора.

Тоже что и выше.

> Оказалось, зависает ещё и переключении раскладки.

Это сообщение windows: `WM_INPUT_LANGCHANGE_REQUEST`, которое меняет раскладку в программах, можно пока включить эмуляцию переключения раз у вас только 2 раскладки.

**Comment by BladeMight** [comment]
@AndreWin Попробуй latest-commit версию, там я походу сделал получше.

**Comment by BladeMight** [comment]
@AndreWin А только что в последнем коммите(`latest-commit`) сделал возможность включать `Эмулировать переключение раскладки` и `Переключать между раскладками` вместе что сделает так чтобы программы вроде MSOffice2016 не зависали. Включаете их вместе и проверяете.

P.S. Также недавно исправил https://github.com/BladeMight/Mahou/commit/dc40c9a287440c9558c670c16e816460fd5a34af:

> Грешил на отображение флажка у курсора

**Comment by BladeMight** [comment]
@AndreWin Добавил информацию по исправлению Mahou с MSOffice2016 на [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B2-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%3F#microsoft-office-2016skype-%D0%B8-%D0%BF%D0%BE%D1%85%D0%BE%D0%B6%D0%B8%D0%B5), релиз [Mahou-v2.5.1.0](https://github.com/BladeMight/Mahou/releases/tag/v2.5.1.0).
С исправлением что я написал на wiki MSOffice2016 и похожие не зависнут больше никогда, закрываю.
