### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by AlexCzar** [BladeMight/Mahou#134]
## Problem/Request description

Cannot run the application.

## Expected behavior (Only if reporting bug)

Application launch

## System information

- Windows version: Win 10
- Windows architecture: x64
- .Net version: 4.7
- Mahou version: HAHA, never seen the window in my life, but the archive has `2.5.1.0` in its name

## Steps to reproduce
1. download 2.5.1.0 version with dll
2. double click it (nothing happens, the cursor briefly changes to "thinking" animation)
3. run cmd, cd to mahou directory, try to run from command prompt -> same result, nothing happens, cursor changes to "thinking" animation for a moment.

**Comment by BladeMight** [comment]
@AlexCzar Try moving/deleting `Mahou.ini`, `snippets.txt`, `AS_dict.txt` and maybe `getconkbl.dll` and make sure they're both x86(32-bit).

**Comment by AlexCzar** [comment]
@BladeMight there's nothing like that, it's the first time I'm trying the app, I haven't configured anything, this is literally: 'download, try to run - nothing happens' situation.

**Comment by BladeMight** [comment]
Then paste this file as `Mahou.ini` in Mahou.exe directory:
[Mahou.ini.txt](https://github.com/BladeMight/Mahou/files/1320845/Mahou.ini.txt)

**Comment by BladeMight** [comment]
And after it start Mahou, and then check if there are folder called Logs in directory where Mahou.exe

**Comment by BladeMight** [comment]
@AlexCzar Maybe i could help you through TeamViewer?(if you wish)

**Comment by AlexCzar** [comment]
I figured it out. It wouldn't run from C:\Program Files, probably because it was trying to create some files and it didn't have permissions due to UAC. I just hate this little Windows problems which have to be guessed instead of diagnosed. I'm not Windows native, use it exclusively for gaming.
Sorry to bother you with this.

**Comment by BladeMight** [comment]
@AlexCzar But in that case you can use the AppData to store settings, just create the Mahou.ini with folowing content:
```
[Functions]
AppDataConfigs=True
```
or download this: [Mahou.ini.txt](https://github.com/BladeMight/Mahou/files/1322744/Mahou.ini.txt) and rename to Mahou.ini and put it where Mahou.exe is. After this settings will be stored in %AppData%\Mahou.

**Comment by AlexCzar** [comment]
Yup, as I said, I've figured it out. But it would've been beneficial if that setting was default. Instead the application just refuses to run without any output at all. Not user friendly at all.

**Comment by BladeMight** [comment]
@AlexCzar Well, I added that feature not so long ago, and didn't thinked that it could be better(user friendly) than just store where Mahou.exe is, to make it default.

**Comment by AlexCzar** [comment]
It's just a suggestion mind you, but if potentially breaking feature is default it's good to at least explain to the user why failure occurs.

**Comment by BladeMight** [comment]
> it's good to at least explain to the user why failure occurs.

Completely missed this, OK, i will make Mahou show startup errors if something prevents its launch.

**Comment by BladeMight** [comment]
@AlexCzar OK done, try the latest-commit version.

**Comment by AlexCzar** [comment]
It's not released yet, I'm reluctant to set-up .NET development environment just for that :)
I'm sure other users who might encounter the same problem will appreciate the fix though :)

**Comment by BladeMight** [comment]
@AlexCzar Release [Mahou-v2.5.1.4](https://github.com/BladeMight/Mahou/releases/tag/v2.5.1.4), i added an message-box with prompt user to switch to AppData configs if Mahou can't create/read default configs on start, check it out.(see #138)
