### ISSUE TITLE
Как поставить свои иконки флагов?

### ISSUE THREAD

**Issue by VVinRar** [BladeMight/Mahou#135]
Добрый день, спасибо за отличную программу.
Как можно сделать, чтобы иконка флага у мышки и каретки была только в русской раскладке и как можно поставить свои иконки этих флагов, не нашел каких-то отдельных файлов с иконками, только эксешник и ини.
Благодарю.

**Comment by BladeMight** [comment]
>как можно поставить свои иконки этих флагов

@VVinRar Сейчас можно почитайте [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9E%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%82%D1%8C-%D1%84%D0%BB%D0%B0%D0%B3%D0%B8-%D1%81%D1%82%D1%80%D0%B0%D0%BD-%D0%B2-%D1%82%D1%80%D0%B5%D0%B5).

> Как можно сделать, чтобы иконка флага у мышки и каретки была только в русской раскладке

Поставить прозрачный флаг из способа выше. Но намного лучше будет если включить функцию `использовать разный вид для раскладок` и в раскладка 1(или 2 смотря как у вас стоит во вкладке раскладки) включить прозрачный фон и в текст подсказки вписать символ *пустоты* (alt+255) или вот между ковычками " " скопируйте и вставьте в текст подсказки.

**Comment by BladeMight** [comment]
> или вот между ковычками " " скопируйте и вставьте в текст подсказки.

@VVinRar Нет, символ *пустоты* на GitHub заменяется на пробел так что нужно писать вручную, удерживаете Alt и набираете на NumPad 2, 5, 5 и отпускаете Alt.

**Comment by VVinRar** [comment]
Спасибо вам

**Comment by BladeMight** [comment]
Пожалуйста, если что обращайтесь. :)

**Comment by VVinRar** [comment]
Ксати, еще вопрос, а то, что у меня флаг-возле-каретки как-то странно "прыгает" в зависимости от положения каретки, это "баг" или "фича"?

**Comment by BladeMight** [comment]
@VVinRar Увидеть бы, а то так я не очень понял о чем вы... В большинстве случаев *прыгает*(перемещается) тогда когда двигается каретка.

**Comment by BladeMight** [comment]
@VVinRar Сейчас вот в latest-commit версии добавил возможность при включении функции `использовать разный вид для раскладок` и `отображать флаги` возле мыши/каретки, и вписать в текст подсказки *символ пустоты* то флаг перестанет отображаться для конкретной раскладки. Т.е. теперь не нужно пустого png.

**Comment by VVinRar** [comment]
Благодарю, попробую новую версию и отпишусь по поводу положения каретки.
