### ISSUE TITLE
Определять сниппеты при конверте последнего слова?

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#136]
Не уверен что это будет полезно всем, но я часто пишу какой-то сниппет, например "`myip" только чтобы понять что я забыл поставить англ. раскладку и написал "ёьншз".
Пока что обошел это тем, что просто продублировал все сниппеты в версии из другой раскладки, но может стоит добавить опциональную проверку при _конверте последнего слова_, и в случае если результат = сниппет, делать замену?

**Comment by BladeMight** [comment]
@Trost123 А может просто сделать чтобы после конверта последнего слова сниппет пере-набирался через Mahou? А потом при нажатии на пробел делал замену. Ну в принципе я уже так сделал в https://github.com/BladeMight/Mahou/commit/5a2925e4167db5235afe4547cf9f43c5d2f32548 проверь по latest-commit.

**Comment by Trost123** [comment]
Хм. А каким методом он раньше перенабирался?
Ну, если это новых багов не наплодит - отличное решение.

_P.S. возможность скачать Latest-commit через интерфейс Mahou довольно удобная штука. 😃_

**Comment by BladeMight** [comment]
> Хм. А каким методом он раньше перенабирался?

Только пользователем.

> Ну, если это новых багов не наплодит - отличное решение.

Потестируем, и потом закроем если все ОК будет.

> скачать Latest-commit через интерфейс Mahou довольно удобная штука

Да, мне самому нравится.
