### ISSUE TITLE
Не работает без прав администратора

### ISSUE THREAD

**Issue by UnityUser** [BladeMight/Mahou#138]
## Проблема:

Не работает с правами ПОЛЬЗОВАТЕЛЯ.

## Описание проблемы:

0. Как я понял, у данной утилиты нет установщика, поэтому переходим на шаг 1.
1. Копируем файл Mahou.exe в папку на системном диске:
_C:\Program files\Mahou\_
2. Запускаем файл под учетной записью БЕЗ прав администратора.
3. Получаем сообщение об ошибке "Mahou has stopped working"
В журнале детальная информация следующая:

> Faulting application name: Mahou.exe, version: 2.5.1.0, time stamp: 0x59bc043f
> Faulting module name: KERNELBASE.dll, version: 10.0.14393.1715, time stamp: 0x59b0d93a
> Exception code: 0xe0434352
> Fault offset: 0x000da9f2
> Faulting process id: 0x3350
> Faulting application start time: 0x01d33b8db53da03c
> Faulting application path: C:\Program Files (x86)\Mahou\Mahou.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: fee541fa-e5cf-4364-b7f9-6d104c1ce43c
> Faulting package full name: 
> Faulting package-relative application ID: 

## Желаемое поведение:

Утилита ДОЛЖНА создавать файл настроек не в папке с экзешником, а в профиле пользователя (AppData)

## Системная информация 

- Windows version: Windows 10
- Windows architecture: x64
- .Net version: 4.6
- Mahou version: v2.5.1.0

## Дополнительно:

Как я уже писал выше, у программы нехватает прав на запись данных в папку, для этого не предназначенную. Все настройки должны записываться или в реестр или в файл настроек, который должен хранится в профиле пользователя.

**Comment by BladeMight** [comment]
@UnityUser Попробуйте версию latest-commit.

**Comment by BladeMight** [comment]
> Утилита ДОЛЖНА создавать файл настроек не в папке с экзешником

@UnityUser Вообще-то это называется portable, т.е. ничего нигде в системе не остается.

Если Вы можете:

> Копируем файл Mahou.exe в папку на системном диске: _C:\Program files\Mahou_

То значить вы можете создать там же файл `Mahou.ini` в котором можете указать Mahou что нужно хранить настройки в AppData, вот с таким содержанием:
```ini
[Functions]
AppDataConfigs=True
```
И после этого Mahou будет читать/сохранять настройки в `%AppData%\Mahou`, до момента как отключите функцию.
![default](https://user-images.githubusercontent.com/11931888/31132257-04aa7a62-a865-11e7-9224-34471e4494d1.PNG)

**Comment by UnityUser** [comment]
А она автоматом не пишет настройки в папку ТЕКУЩЕГО пользователя?
Так я же написал, что установщик я не нашел. Качал отсюда:
https://github.com/BladeMight/Mahou/releases

**Comment by BladeMight** [comment]
> А она автоматом не пишет настройки в папку ТЕКУЩЕГО пользователя?

Нет.

> Так я же написал, что установщик я не нашел.

Так я же писал:

> Вообще-то это называется portable

**Comment by BladeMight** [comment]
@UnityUser 
> а то что есть нет указания на версию PORTABLE

Так ведь Mahou всегда был portable, даже с момента появления функции сохранения настроек в AppData(по умолчанию)... 

По поводу самой папки `Mahou` в `Program Files` можно получить доступ для текущего пользователя командой `takeown /f . /r && icacls . /inheritance:e /grant %USERNAME%:F /t` в командной строке в папке `%systemdrive%\Program Files\Mahou` или вот полностью одной строкой через Win+R:
```bash
cmd /c pushd "%systemdrive%\Program Files\Mahou"  && takeown /f . /r && icacls . /inheritance:e /grant %USERNAME%:F /t && pause
```

**Comment by BladeMight** [comment]
> Экзешник НЕ должен хранится в папках пользователя.

Да ладно, у меня все программы так и живут, portable... а вот папки `Program Files` и `Program Files x86` пустуют...

**Comment by UnityUser** [comment]
> Да ладно, у меня все программы так и живут
Да я про корпоративные политики безопасности, а также рекомендации от MS ;)
Ладно. Если это portable, то вопрос можно/нужно закрыть. А вот если это не portable, то по идее она должна проверять права, и, если их нет, то не выбрасывать исключения, а перехватывать и молча писать настройки либо в дефолтовую папку, либо использовать временные дефолтовые настройки. Но это просто пожелания ;)

**Comment by BladeMight** [comment]
@UnityUser А ну ладно :), я вот в [latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit) версии добавил уведомление о том что файл настроек не может быть создан и предлагать пользователю переключиться на настройки в %AppData%, проверь как работает.

**Comment by BladeMight** [comment]
@UnityUser Релиз [Mahou-v2.5.1.4](https://github.com/BladeMight/Mahou/releases/tag/v2.5.1.4).

**Comment by UnityUser** [comment]
Спасибо.
