### ISSUE TITLE
Конвертирование последнего слова, если после него стоят пробелы или знаки препинания

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#14]
Со следующей проблемой нередко сталкиваюсь. Написал слово → что раскладка неправильная, замечаю только тогда, когда уже поставил после слова пробел или знак препинания. А поменять раскладку только этому последнему слову уже не получается (менять всю строку обычно не вариант, в ней могут содержаться как русские, так и английские слова). Хотелось бы возможности, заявленной в заголовке. Спасибо.

**Comment by BladeMight** [comment]
Включите "" " ←" для пробела.

**Comment by BladeMight** [comment]
А в знаках препинания нет смысла так как после них нажимаем <kbd>Space</kbd>...
