### ISSUE TITLE
Гибче настройки

### ISSUE THREAD

**Issue by TupiNUMBooR** [BladeMight/Mahou#141]
Как насчет возможности настройки клавиши снипеттов? Чтобы не пробелом единым переключать, а табом например как в пунтосвичере(привычка прост уже)

И еще одно. Может стоит добавить переключение игнора символов в обычные настройки, чтобы без горячих клавиш можно было в меню переключить, и статус переключения всегда видеть?

**Comment by BladeMight** [comment]
> Как насчет возможности настройки клавиши снипеттов?

Думаю можно добавить, а с автозаменой как? тоже менять клавишу на Tab? или там все таки лучше оставить Space, т,к, без него это уже не будет выглядеть **авто**заменой. Какой способ лучше подойдет для выбора клавиши:
 1. создать список с клавишами(Tab, Space) и выбирать из них или:
 2. создать что-то вроде настройки горячей клавиши?

> и статус переключения всегда видеть?

Если включена иконка в трее, то при включении "режима игнора символов" иконка становиться красной.

> Может стоит добавить переключение игнора символов в обычные настройки

А может сделать как с отображением языковой панели? Т,е, и горячая клавиша и галочка  в настройках.

> Гибче настройки

Обычно говорят что у меня и так слишком сложные настройки, но если можно сделать еще сложнее я только за :)

**Comment by BladeMight** [comment]
@TupiNUMBooR По поводу Tab'а - готово, вот [Mahou-v2.5.2.4](https://github.com/BladeMight/Mahou/releases/tag/v2.5.2.4).

**Comment by TupiNUMBooR** [comment]
> Какой способ лучше подойдет для выбора клавиши
Мне кажется лучше бы подошел с горячей клавишей, кастомизации так больше

> Если включена иконка в трее
не заметил сразу
и кстати флаг исчезает из трея тогда
а может стоит добавить вариант, где объединены иконки mahou и флаг? Чтобы и язык видно сразу было, и на глаза попадалось(один флаг легко теряется из виду, особенно когда он часто меняется).

> А может сделать как с отображением языковой панели? Т,е, и горячая клавиша и галочка в настройках.
идеально)

> По поводу Tab'а - готово
Пасибки))

P.S.
не в тему, просто число клевое) http://joxi.ru/DrlR3Y3i46G4X2
не в тему 2 - попытка обновы беты выдает ошибку. Если надо новое обсуждение сделаю.
