### ISSUE TITLE
Набор символов "->" для снипетов не удобен

### ISSUE THREAD

**Issue by alexvoz** [BladeMight/Mahou#142]
del

**Comment by BladeMight** [comment]
> Набор символов "->" для снипетов не удобен

Можно назначить другой сниппет на ->, например:

```
->--
====>-><====
```
Хоть в Mahou будет отображаться что есть ошибка, работать будет нормально, **если поставить его в конец**.

P.S. Удалять не нужно было, я все равно узнаю, и к тому же удалить issue на GitHub нельзя.

**Comment by BladeMight** [comment]
> в Mahou будет отображаться что есть ошибка(сейчас посмотрю)

Все исправил, теперь между `====>` и `<====` игнорируются `->`. (В latest-commit версии)

**Comment by alexvoz** [comment]
Оперативно. 
Я удалил тему т.к. понял, что переоценил проблему и можно решить просто изменив немного настройки. Но теперь больше вариантов решения есть )
Спасибо.
