### ISSUE TITLE
Просьба добавить опцию: Добавлять 1 Enter в текущее слово

### ISSUE THREAD

**Issue by klewerus** [BladeMight/Mahou#144]
## Request description

Очень нравится работа программы.
Хотелось бы еще немного приблизить к идеалу, а именно добавить новую опцию.

Добавлять 1 Enter в текущее слово.
(аналогично пробелу)

Если включено, то к последнему введенному слову будет добавляться ОДИН перевод строки, благодаря чему конвертация последнего слова будет работать если вы случайно нажали Enter после слова.

**Comment by BladeMight** [comment]
@klewerus Готово, проверьте на канале latest-commit.

**Comment by klewerus** [comment]
Спасибо!
Для последнего слова - работает.
Для последней строки - работает странно - удаляет все переводы строк введенные ранее.

Mahou.exe из Release_x86_x64.zip - диспетчер задач в 8.1 показывает (32 бита) - так и должно быть?

**Comment by BladeMight** [comment]
> Для последней строки - работает странно - удаляет все переводы строк введенные ранее.

А не должно было работать вообще, т.к. это функция только для последнего слова. В общем это баг, сейчас исправлю.

**Comment by BladeMight** [comment]
@klewerus 
> показывает (32 бита) - так и должно быть?

Это не так уж и важно, но может быть что-то в скрипте авто-сборщика AppVeyor не так, сейчас посмотрю.

> работает странно 

Переделал, проверь latest-commit.

**Comment by BladeMight** [comment]
> сейчас посмотрю.

Все исправил, это все из-за того что при сборке через скрипт он не очищает прошлые объекты сборки, а первой сборкой была release x86 поэтому все последующие использовали её объекты и в итоге все были release x86, а теперь все ОК.

**Comment by BladeMight** [comment]
Исправил только что серьезный баг в latest-commit, из-за которого каждая следующая конвертация становилась медленнее. ([обновиться из Mahou](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%92%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-%D0%9E%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F) или [скачать здесь](https://github.com/BladeMight/Mahou/releases/latest-commit)

**Comment by BladeMight** [comment]
@klewerus Сейчас функция "Считать 1 Enter частью последнего слова" с функцией конвертации линии работает следующим образом:
Очистки последней линии не происходить по нажатию Enter, происходить при повторном нажатии на Enter, т.е. очистка происходить после 2 нажатий на Enter, мне кажется это немного странно, вам так и хотелось или как? _С этой функцией функция конвертации последней линии становиться функции конвертации последнего параграфа_ :)

**Comment by klewerus** [comment]
Функция конвертации последней линии - мне нужна не особо. Просто написал, что странновато работает.
Сейчас работает не так странно :)
Как по мне - можно так оставлять.
То что было нужно - работает. Спасибо.

**Comment by BladeMight** [comment]
>  Просто написал, что странновато работает.

Было очень полезно.

> Как по мне - можно так оставлять.

Так и сделаю, а если кому надо как-то по другому, то тогда и сделаю.

> Спасибо.

Пожалуйста. Рад был помочь. Сейчас сделаю релиз.

**Comment by BladeMight** [comment]
> Сейчас сделаю релиз.

Готово, вот [Mahou-v2.5.5.4](https://github.com/BladeMight/Mahou/releases/tag/v2.5.5.4).

**Comment by klewerus** [comment]
Отлично! А я уже новый запрос наваял :)
