### ISSUE TITLE
Просьба добавить опцию: Постоянная раскладка - устанавливать в новом окне только один раз

### ISSUE THREAD

**Issue by klewerus** [BladeMight/Mahou#145]
## Request description

Продолжаем совершенствование :)

Если в постоянной раскладке будет опция "Переключать в новом окне только один раз" - это добавит удобства. А, возможно, уберет у кого-то проблемы с производительностью :).

Между считываниями названия процесса текущего окна можно запоминать, например, ID процесса и если он не меняется - раскладку больше не устанавливать.

**Comment by BladeMight** [comment]
@klewerus Добавлю, наверно уже завтра.

**Comment by BladeMight** [comment]
> опция "Переключать в новом окне только один раз" 

Но тогда функция больше не будет *постоянной раскладкой*, а будет немного похоже на функцию "Единая раскладка для всех" которая работает не через таймеры, а через сообщения Windows(при смене окна и т.п.), в итоге будет что-то вроде "Менять раскладку 1 раз для каждого из выбранных процессов." - не думаю что это будет так уж полезно...

**Comment by klewerus** [comment]
Мне бы пригодилось - чтобы в нужных окнах сначала ставилась нужная раскладка, а далее бы работало как обычно, а не переключало бы постоянно на эту раскладку.

**Comment by BladeMight** [comment]
@klewerus ОК, понял.

**Comment by BladeMight** [comment]
@klewerus Я тут подумал и решил что лучшим вариантом будет сделать чтобы раскладка менялась только при смене окон **без запоминания** уже окон в которых раскладка уже менялась, т.к. выглядит как-то странно раскладка меняется 1 раз для окна и всё больше не меняется... Так что я решил сделать это тоже отдельной функцией, в итоге может быть:
1. Менять раскладку при активации любого окна из выбранных процессов.
2. Менять раскладку 1 раз при активации любого окна из выбранных процессов.
Обновись по latest-commit и проверь.

**Comment by klewerus** [comment]
Проверил, сейчас работает по варианту 2, вроде-бы, так?
Но мне кажется удобнее (и логичнее) будет вариант 1.

**Comment by BladeMight** [comment]
> Но мне кажется удобнее (и логичнее) будет вариант 1.

Ну так и я о том же:

>т.к. выглядит как-то странно раскладка меняется 1 раз для окна и всё больше не меняется... 

Пояснение(как включить):

Вариант 1 - когда включена только галочка "Менять только тогда когда меняются окна."
Вариант 2 - когда включена галочка "Менять только тогда когда меняются окна." и "Менять 1 раз для окна."

**Comment by klewerus** [comment]
Проверил. Все ок. Мне нужен был вариант 1 :)

**Comment by BladeMight** [comment]
@klewerus Значит я догадался.

**Comment by klewerus** [comment]
Если окно - консольное и не используется dll определения раскладки, но используется эмуляция переключения - может можно допереключать по циклу до нужной раскладки?

**Comment by BladeMight** [comment]
> может можно допереключать по циклу до нужной раскладки

Нет, т.к. не узнать текущей раскладки консольного окна без dll чтобы сравнить с нужной.

**Comment by klewerus** [comment]
Ну, предполагая :) что раскладка единая для всех окон (например у меня в 8.1 так)

**Comment by BladeMight** [comment]
Надо же откуда-то взять раскладку если не с консольного окна, можно попробовать брать с проводника(панели задач, меню пуск) например.

**Comment by klewerus** [comment]
Вообще - и так прекрасный продукт, с чем тебя поздравляю. :)

**Comment by BladeMight** [comment]
@klewerus Спасибо :) 👍

**Comment by klewerus** [comment]
Этот запрос завершаю. А с консолью - думай сам, нужны ли такие сложности логики программы.

**Comment by BladeMight** [comment]
> думай сам

Подумаю...

**Comment by BladeMight** [comment]
@klewerus Star Mahou:
![star](https://cloud.githubusercontent.com/assets/11931888/24076818/581623f4-0c43-11e7-83ef-4bba1b3d5445.jpg)
