### ISSUE TITLE
cmd.exe - по Pause съедает один символ слева

### ISSUE THREAD

**Issue by klewerus** [BladeMight/Mahou#146]
## Request description

В консольных приложениях, если в горячих клавишах участвует Pause, то при конвертации удаляется один символ, слева от конвертируемого текста.
Это объяснимо, но, может, получится как-то побороть?
Действительно очень нужно.

**Comment by BladeMight** [comment]
@klewerus Во первых при работе с консольными приложениями(те что работают через conhost.exe) используйте эмуляцию переключения раскладки и/или пользуйтесь версией Mahou_x86+getconkbl.dll, подробнее на [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B2-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%3F#cmdexe).

> но, может, получится как-то побороть?

Можно добавить правило при котором если горячая клавиша имеет Pause и если текущее окно консольное, то конвертации будут использовать на 1 меньше удалений, но будет лучше понять почему это происходить и сделать исправление получше.

**Comment by BladeMight** [comment]
@klewerus Вспомнил из-за чего:
В Windows 10 нажатие Pause останавливает консоль до следующей любой клавиши, поэтому я сделал исправление добавив 1 произвольный BackSpace. В версиях Windows ниже Pause  так не действует, поэтому я поставил правило - использовать этот фикс только для Windows 10.
Уже исправил в latest-commit.

**Comment by klewerus** [comment]
Работает, спасибо!
