### ISSUE TITLE
Silent update

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#147]
Не помешала бы возможность "автоматически обновлять втихую". Т.е. программа скачивает и устанавливает апдейт и при этом юзера не отвлекает. Максимум - из трея вылазит tooltip, где пишет что "Mahou обновлен до версии Х"

**Comment by BladeMight** [comment]
@Trost123 Думаю можно, но нужно будет добавить интервал проверки или оставить только при запуск?

**Comment by Trost123** [comment]
Меня лично только при запуске вполне устраивает т.к. на ночь ПК выключаю.

**Comment by BladeMight** [comment]
@Trost123 ОК, значит пока сделаю только при запуске.

**Comment by BladeMight** [comment]
@Trost123 Готово вот с этой версии обновись по latest-commit и увидишь как работает: [Mahou+SilentUpdate.zip](https://github.com/BladeMight/Mahou/files/1485741/Mahou.SilentUpdate.zip)
Не забудь включить "Обновление при запуске" и "Тихо обновлять", а потом перезапусти(Shift+Win+Alt+PageUp).

**Comment by BladeMight** [comment]
> Не забудь 

и поменять канал обновлений на latest-commit

**Comment by Trost123** [comment]
> 💎 Added silent update feature. > 🐛 Fixed infinite silent update.

Из-за таких вещей я за фичами в бетку обычно не спешу 😈 
Спасибо, как в Stable перекочует, буду пользоваться. Теперь меня Mahou на 100% устраивает (после наверное десятка оперативно выполненых feature-request-ов). 🙌

**Comment by BladeMight** [comment]
> Из-за таких вещей я за фичами в бетку обычно не спешу

Ну так надо же как-то тестить.

> как в Stable перекочует, буду пользоваться

Скоро, сейчас еще есть один противный баг с авто-заменой, его исправлю и сделаю новый релиз.

> Теперь меня Mahou на 100% устраивает 

Я очень рад.

**Comment by BladeMight** [comment]
@Trost123 Релиз [Mahou-v2.5.6.0](https://github.com/BladeMight/Mahou/releases/tag/v2.5.6.0).

**Comment by BladeMight** [comment]
@Trost123 ОК, теперь можно(**нужно** т.к. важные исправления в 2.5.6.2) проверить обновившись с [2.5.6.0 ](https://github.com/BladeMight/Mahou/releases/tag/v2.5.6.0) на [2.5.6.2](https://github.com/BladeMight/Mahou/releases/tag/v2.5.6.2).

**Comment by Trost123** [comment]
Всё ок.
![It works](https://image.prntscr.com/image/-QwuXuqhSsqqNaGFUGM7xw.png)

**Comment by BladeMight** [comment]
@Trost123 Отлично, спасибо за изображение, думаю добавлю его на Wiki.
