### ISSUE TITLE
Улучшить окно с историей версии 

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#148]
Некоторые чейнджлоги занимают почти весь fullhd монитор по высоте.

Мое предложение сделать текст в двух text-area с прокруткой (две - по одной на язык).
Само же окно не должно занимать более 70% от текущей высоты экрана.

![image](https://user-images.githubusercontent.com/5548003/33144335-c40e478c-cfcd-11e7-8ab2-7d484cad3587.png)

**Comment by BladeMight** [comment]
@Makishima Ну я использовал обычный системный MessageBox, поэтому переделать его не можно, а сделать свой - много времени может занять, может просто обрезать количество линий? До 6 на пример, а если есть продолжение то 7 строчка - три точки.

**Comment by Makishima** [comment]
7 строкой можно вставлять ссылку вида https://github.com/BladeMight/Mahou/releases/tag/v2.5.6.7

**Comment by BladeMight** [comment]
Только что изменил в https://github.com/BladeMight/Mahou/commit/64b084807e7cb3165ca10a5dd975fa7bd441911e максимальный размер окна обновления до 640 символов + строка с ссылкой на zip архив. Проверить можно если обновится на latest-commit, включить проверку обновлений, поменять канал на Stable, нажать применить и перезапустить Mahou.
