### ISSUE TITLE
Конвертирование определённого количества последних слов

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#15]
Допустим, я написал строку из 10 слов. Первые 6 в правильной раскладке, последующие 4 в неправильной. И вот ввожу я, например, сочетание <kbd>Ctrl+Alt+Shift+F10</kbd> затем нажимаю клавишу <kbd>4</kbd> → изменяется раскладка именно у четырёх последних слов и символов между ними. А если бы <kbd>Ctrl+Alt+Shift+F10</kbd>, а потом <kbd>8</kbd>, изменилась бы раскладка у 8 последних слов и символов между ними.

Не сердитесь сильно, я предлагаю функции, которые, на мой взгляд, мне сократили бы время работы. Спасибо.

**Comment by BladeMight** [comment]
Не легко будет... Но возможно.

**Comment by BladeMight** [comment]
В [v1.4.3.0](https://github.com/BladeMight/Mahou/releases/tag/v1.4.3.0) уже есть.

**Comment by BladeMight** [comment]
@Kristinita В [v1.4.3.0](https://github.com/BladeMight/Mahou/releases/tag/v1.4.3.0) уже есть.

**Comment by BladeMight** [comment]
Закрыто, по причине:
Функция и впрямь есть, с версии 1.4.3.0 и работает как было запрошено.
