### ISSUE TITLE
После блокировки компьютера Caps Lock переключатся вместе с раскладкой

### ISSUE THREAD

**Issue by TaciturnShadow** [BladeMight/Mahou#150]
## Проблема/описание запроса

В некоторых случаях после блокировки компьютера, по Win+L, при переключении раскладки по Caps Lock раскладка меняется, но состояние Caps Lock тоже. Я смог записать в лог оба варианта.
Сначала запустил Mahou, ввёл test «Enter»«Caps Lock» тест «Enter» «Win+L» «разблокировал» «Caps Lock» test «Enter»«Caps Lock» тест «Enter» «Win+L» «разблокировал» «Caps Lock» test «Enter»«Caps Lock» тест
Получил:
test
тест
test
тест
TEST
тест
Т.е. после второй блокировки возникла проблема.

## Ожидаемое поведение (только при сообщении об ошибках)

Переключение раскладки без переключения Caps Lock.

## Информация окружения/Отладочная информация

<details>
[2017.11.23.txt](https://github.com/BladeMight/Mahou/files/1498708/2017.11.23.txt)
<summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>

- Mahou 2.5.6.3
- OS = [Microsoft Windows NT 6.1.7601 Service Pack 1]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Русская(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=False
[Functions]
TrayIconVisible=True
ConvertSelectionLayoutSwitching=True
ReSelect=True
RePress=False
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=False
Logging=False
CapsLockTimer=False
TrayFlags=True
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=True
RestartHooksOnHotkeyActionEnd=True
AutoStartAsAdmin=False
GuessKeyCodeFix=False
AppDataConfigs=False
RemapCapslockAsF18=True
AddOneEnterToLastWord=False
SilentUpdate=False
[Layouts]
SwitchBetweenLayouts=True
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=США(67699721)
MainLayout2=Русская(68748313)
SpecificKey1=1
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Переключать между раскладками
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
OneLayout=False
QWERTZfix=False
SpecificKeysType=0
SpecificKeySets=set0
[Appearence]
DisplayLangTooltipForMouse=True
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
Language=Русский
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Microsoft Sans Serif; 8.25pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Microsoft Sans Serif; 8.25pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Microsoft Sans Serif; 8.25pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Microsoft Sans Serif; 8.25pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
Layout1LTText=
Layout2LTText=
MouseLTUseFlags=True
CaretLTUseFlags=False
MouseLTAlways=False
MouseLTUpperArrow=False
CaretLTUpperArrow=False
WindowsMessages=True
[Timings]
LangTooltipForMouseRefreshRate=100
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=50
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
ChangeLayoutInExcluded=True
LangTooltipForMouseSkipMessages=5
[Snippets]
SnippetsEnabled=False
SpaceAfter=False
SwitchToGuessLayout=False
SnippetExpandKey=Space
[Hotkeys]
ToggleMainWindow_Enabled=False
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=False
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=False
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=
ConvertSelectedText_Key=145
ConvertLastLine_Enabled=False
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=False
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=16
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Shift
SelectedTextToRandomCase_Key=17
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win + 
SelectedTextToSwapCase_Key=19
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win + 
SelectedTextTransliteration_Key=191
ExitMahou_Enabled=False
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=False
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
ToggleLangPanel_Enabled=True
ToggleLangPanel_Double=False
ToggleLangPanel_Modifiers=Shift
ToggleLangPanel_Key=120
```
</details>
</details>
</details>

## Приложите журналы (logs) (если логирование было включено)
[2017.11.23.zip](https://github.com/BladeMight/Mahou/files/1498710/2017.11.23.zip)

**Comment by BladeMight** [comment]
@TaciturnShadow По поводу:

> «разблокировал» «Caps Lock»

То есть после разблокировки сразу нажал на CapsLock? Если да то все понятно, это не ошибка Mahou, т.к. Mahou не работает на Экране блокировки, а после разблокировки есть некоторое время в которое все еще считатется что система в режиме "Экрана блокировки" если нажать в этот момент CapsLock то он будет работать как обычно в системе, т.е. на переключение *лампочки* CapsLock и изменение регистра ввода. 

> Переключение раскладки без переключения Caps Lock.

Надеюсь я понятно объяснил почему так произошло.

**Comment by TaciturnShadow** [comment]
Проблема не единичная, такое поведения оставалось до перезапуска Mahou. Если перезапуск решает проблему, то может со стороны Mahou можно ловить разблокировку и перерегистрировать клавишу?
Но попробую ещё проверить на самой новой версии, дня через два.

**Comment by BladeMight** [comment]
> Проблема не единичная, такое поведения оставалось до перезапуска Mahou

Попробуй нажать Alt или Shift + Caps Lock для выключения, еще посмотри #159 и попробуй отключить функцию [Переопределить Caps-Lock как F18](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9F%D0%B5%D1%80%D0%B5%D0%BE%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C-caps-lock-%D0%BA%D0%B0%D0%BA-f18)

> Mahou можно ловить разблокировку 

Слишком сложно, да и врят ли в .Net такое возможно.

**Comment by TaciturnShadow** [comment]
Сегодня пытался повторить на 2.5.8.8 - не воспроизводится, ничего не залипает. Возможно проблема была в каком-то из багов исправленных после 2.5.6.3.

**Comment by BladeMight** [comment]
@TaciturnShadow Вот как? Ну может быть...

**Comment by TaciturnShadow** [comment]
Прошло много времени, сотни блокировок/разблокировок - на 2.5.8.8/2.5.9.0 проблема ни разу не повторялась. Ради эксперимента снова запустил 2.5.6.3 - проблема повторилась сразу же. Так что это был всё же баг Mahou, но он явно исправлен.
