### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by TrueXakeP** [BladeMight/Mahou#153]
## Problem/Request description
После указания хранить настройки в %appdata% и перезапуске - они были сброшены.
После этого они были выставлены [так](https://github.com/BladeMight/Mahou/files/1509924/Mahou.ini.txt) и применены.
Среди них было указание обновляться скрыто, а в интерфейсе было сообщение об одном доступном обновлении включающем замену виджета donate (наличие обновления было только проверено, оно установлено из интерфейса не было).
Последующая попытка перезапуска, как и все последующие запуски, оканчиваются этим сообщением:

![error](https://user-images.githubusercontent.com/5345528/33320692-c19e5a78-d44b-11e7-9598-8cb7d23baa03.png)

Самого файла MahouMahou.exe в %appdata%, как и в %appdata%\Mahou\ естественно нет, как и любых других *.exe.

## Expected behavior (Only if reporting bug)

Normal start and work.

## System information
[mahou_debug_info.txt](https://github.com/BladeMight/Mahou/files/1510022/mahou_debug_info.txt) (-- от предыдущего отчета, текущие настройки в приложенном Mahou.ini)

Версия файла 2.5.6.7
Дата изменения: 22.11.2017 4:27

В %appdata%\Mahou\ присутствуют файлы: [Mahou.ini](https://github.com/BladeMight/Mahou/files/1509924/Mahou.ini.txt), [UpdateMahou.cmd](https://github.com/BladeMight/Mahou/files/1509994/UpdateMahou.cmd.txt) и [Release_x86_x64.zip](https://github.com/BladeMight/Mahou/files/1509996/Release_x86_x64.zip)

## Attach logs (if logging were enabled)
До закрытия Mahou лог был выключен. После этого его включение в Mahou.ini результата не дает -- лог не создается.

**Comment by BladeMight** [comment]
Все, исправил в latest-commit версии. Вот версия из которой можно проверить:
[Mahou-UpdateTestToLatestCommit.zip](https://github.com/BladeMight/Mahou/files/1638640/Mahou-UpdateTestToLatestCommit.zip)
Сразу с настройками(тихое обновление и т.д.) которые будут копированы в AppData(если там еще нет настроек).

**Comment by BladeMight** [comment]
@TrueXakeP В последнем релизе все исправлено, и еще кстати обновился GitHub из-за чего обновление из старых версий теперь не работает...

**Comment by BladeMight** [comment]
@TrueXakeP О том что обновился GitHub я уже [написал в Readme](https://github.com/BladeMight/Mahou#%D0%92%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D0%B8) и в последнем релизе [Mahou-v2.5.8.8](https://github.com/BladeMight/Mahou/releases/tag/v2.5.8.8). Если обновляться с 2.5.7.6 или 2.5.8.0 то никаких проблем не будет. В последних 3 релиз версиях уже все ОК.

**Comment by TrueXakeP** [comment]
Это был узкий случай и переустановка решила его тогда.
