### ISSUE TITLE
Переключение на определенную расскладку по модификаторам

### ISSUE THREAD

**Issue by iamkarlson** [BladeMight/Mahou#16]
Например по левому CTRL на английскую, по правому на русский.

**Comment by BladeMight** [comment]
Можно добавить, неужели так удобно?

**Comment by iamkarlson** [comment]
невероятно, я даж капслоком не очень пользуюсь когда есть правый/левый CTRL

**Comment by BladeMight** [comment]
Ладно, добавим. :)

**Comment by BladeMight** [comment]
Вот проверь новую [версию 1.1.1.0](https://github.com/BladeMight/Mahou/releases/tag/v1.1.1.0).

**Comment by BladeMight** [comment]
А еще лучше [последнюю версию](https://github.com/BladeMight/Mahou/releases/latest).

**Comment by iamkarlson** [comment]
Работает нормально, только та же проблема что и в дотсвитчере что я недоделал, когда CTRL вместе с какой либо клавишей нажимается, то все равно свитчется, хотя по идее не должно, ну не самая удобная особенность. Но жить можно и так. Спасибо

**Comment by BladeMight** [comment]
> хотя по идее не должно

Можно сделать так:
Если пользователь нажал клавишу до того как отпустил CTRL то не переключать, иначе переключать.

**Comment by iamkarlson** [comment]
Да, будет круто

**Comment by BladeMight** [comment]
Вот проверь [версию 1.1.2.1](https://github.com/BladeMight/Mahou/releases/tag/v1.1.2.1).

**Comment by iamkarlson** [comment]
Очень похоже что все работает

**Comment by BladeMight** [comment]
Рад что все получилось. :smile_cat:
