### ISSUE TITLE
Флажок у курсора постоянно ошибается.

### ISSUE THREAD

**Issue by sindzicat** [BladeMight/Mahou#160]
Добрый день.

Версия Mahou 2.5.6.7.

Эта и более ранние версии постоянно ошибались, отрисовывали рядом с курсором флаг не той страны. Раскладка на русском, рядом с курсором английский флаг. Пока набирал этот текст, обратил внимание, что после n-ного переключения раскладки по ALT+SHIFT программа сбилась. Приходится идти в настройки, жать OK, и только после этого флажок снова соответствует раскладке.

С уважением,
Андрей.

**Comment by BladeMight** [comment]
@sindzicat Только исправил в latest-commit версии, сейчас сделаю релиз.

**Comment by BladeMight** [comment]
@sindzicat Готово вот и релиз [Mahou-v2.5.8.0](https://github.com/BladeMight/Mahou/releases/tag/v2.5.8.0).

**Comment by BladeMight** [comment]
@sindzicat Если все еще ошибается то тогда лучше выключить функцию "Использовать сообщения Windows вместо таймеров" во вкладке Вид. 

Это все происходит из-за того что при смене раскладки по Alt+Shift Mahou не может поймать раскладку на которую переключается, т.к. есть некий интервал(в Windows 10 кстати он поменьше) после которого раскладка переключается, поэтому я добавил интервал в 200мс в Mahou при переключении раскладки по Alt+Shift и т.п. 

Однако если выключить "Использовать сообщения Windows вместо таймеров" то тогда раскладка будет проверятся каждые n мс как задано в настройках, хоть и берет больше ЦП, но зато точнее.

**Comment by BladeMight** [comment]
@sindzicat В последней latest-commit добавил более лучшее исправление.

**Comment by sindzicat** [comment]
@BladeMight, спасибо огромное! Скачал обновление, ща затестим :)

**Comment by BladeMight** [comment]
@sindzicat Лучше если будешь проверять на latest-commit, т.к. это последняя версия Mahou и она включает последние исправления.

**Comment by sindzicat** [comment]
У меня на вкладке &laquo;Обновления&raquo; стоит &laquo;LatestCommit(Beta)&raquo;.
Я, правда, чёт никак не найду, где это &laquo;Использовать сообщения Windows вместо таймеров&raquo;...

**Comment by BladeMight** [comment]
@sindzicat Во вкладке Вид, а вообще если не знаешь где функция, открывай страницу на [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9), Ctrl+F в браузере для поиска и начинай писать название функции, когда найдешь, прокрути вверх чтобы узнать по скриншоту в какой она вкладке.

**Comment by sindzicat** [comment]
Ага, увидел. Про wiki буду иметь ввиду.

**Comment by BladeMight** [comment]
@sindzicat Правда сейчас уже я придумал фикс получше, и выключать "Использовать сообщения Windows вместо таймеров" уже не надо.

**Comment by BladeMight** [comment]
Ну что ж, вот релиз [Mahou-v2.5.8.8](https://github.com/BladeMight/Mahou/releases/tag/v2.5.8.8).

**Comment by sindzicat** [comment]
Предварительно вроде работает. Пока закрою.

**Comment by BladeMight** [comment]
@sindzicat Ну если вдруг что, всегда можно открыть заново.
