### ISSUE TITLE
Mahou.exe куда-то пропадает.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#162]
Что-то странное. Последнее время при загрузке компа время от времени вылазит ошибка что Mahou.exe не найден и собственно говоря он реально куда-то пропадает. Антивирус проверял, он не при делах.
Подозрения на феил апдейтера.

**Comment by Makishima** [comment]
С текстом "Не найден c:\ProgramData\chocolatey\lib\Mahou\tools\Mahou.exe"?
Если да, то  [вот](https://github.com/BladeMight/Mahou/issues/155#issuecomment-358242077), нужно поставить новую версию отсюда, а не через механизм обновления.

**Comment by BladeMight** [comment]
@Trost123 @Makishima Как я писал уже здесь: https://github.com/BladeMight/Mahou/issues/153#issuecomment-361411144 это все из-за поломанной функции обновления в более старых версиях(старее 2.5.7.6).
