### ISSUE TITLE
Для консольных окон - при отсутствии getconkbl.dll определять текущую раскладку по другим окнам

### ISSUE THREAD

**Issue by klewerus** [BladeMight/Mahou#168]
Хотелось бы добавить в фиксированную раскладку: для консольных окон - при отсутствии getconkbl.dll определять текущую раскладку по другим окнам.
Можно попробовать брать с проводника(панели задач, меню пуск) например - такая была твоя идея :)

**Comment by BladeMight** [comment]
@klewerus Функция уже создана, нужно проверить как работает в Win 8.1+, в Win 7 работает как и следовало ожидать... т.к. тут то не используется общая раскладка системой, в итоге Mahou будет думать что раскладка постоянна та которая в панели задач/меню пуск.

**Comment by klewerus** [comment]
При включенной функции "Get layout from Taskbar" функция Постоянная раскладка стала работать неправильно - раскладка переключается по кругу несколько раз до той же, что была перед активацией окна (например cmd.exe). При этом системный индикатор раскладки мерцает всеми раскладками сразу около 0.5 сек.

**Comment by klewerus** [comment]
Также предлагаю сузить действие функции - только для консольных окон (в которых раскладка не определяется без getconkbl.dll).

**Comment by BladeMight** [comment]
@klewerus Спасибо за информацию и предложение, как освобожусь попробую что-то придумать.

**Comment by BladeMight** [comment]
@klewerus Оказывается все не так просто, новая функция таки не получает верную раскладку, т.к. Windows не меняет раскладку всех окон(и панели задач включительно)... Из-за чего мне кажется теперь что маловероятно сделать функцию которая будет получать раскладку с других окон - невозможно т.к. раскладка в них не меняется... И в итоге мне пока кажется что самый лучший вариант в Mahou (C#/.Net) - это использование getconkbl.dll, я вот думаю создать Mahou на C, там то можно будет всякого такого избежать создав хуки WH_SHELL и благодаря им следить за изменениями раскладки в **абсолютно любом окне**, но на перепись всего что на C# в C потребуется много времени(хотя у меня есть небольшой [прототип](https://github.com/BladeMight/NMahou)). Так что пока только с getconkbl.dll, а новая функция - **опасная** оказалась.... 

Да и кстати это таки проблема API консоли Windows...(https://github.com/Microsoft/console/issues/83)

**Comment by BladeMight** [comment]
@klewerus Внедрил свой небольшой проект JKL(мониторит реальное изменение раскладки) в Mahou, можешь проверить как работает в latest-commit версии.

**Comment by klewerus** [comment]
Работает также как и раньше, неправильно.
При включенных функциях "Get layout from JKL" и Постоянная раскладка (например для окна cmd.exe), при активации окна cmd.exe раскладка переключается по кругу несколько раз до той же, что была перед активацией окна.
При этом системный индикатор раскладки мерцает всеми раскладками сразу, около 0.5 сек.

**Comment by BladeMight** [comment]
> Постоянная раскладка

С JKL все доложно быть нормально т.к. при активации можно получить раскладку 1 раз, а далее уже JKL будет мониторить когда меняется раскладка, а потом Mahou поменяет на постоянную если нужно.

**Comment by BladeMight** [comment]
> При этом системный индикатор раскладки мерцает всеми раскладками сразу, около 0.5 сек.

Наверно ты используешь Переключение между раскладками и Эмуляцию переключения раскладки, сейчас заметил что они странно ведут себя в консоли без getconkbl.dll, что-то придумаю...

**Comment by klewerus** [comment]
Проверил, похоже что работает.

**Comment by BladeMight** [comment]
@klewerus Я вот уже 3 день тестирую вроде все ОК и с самим JKL и с обновлениями, думаю скоро сделать релиз.

**Comment by BladeMight** [comment]
@klewerus Релиз [Mahou-v2.6.2.0](https://github.com/BladeMight/Mahou/releases/tag/v2.6.2.0).
