### ISSUE TITLE
Tab в снипеттах не работает

### ISSUE THREAD

**Issue by TupiNUMBooR** [BladeMight/Mahou#169]
Если выбрать ![space в клавишах развертывания](http://dl4.joxi.net/drive/2018/03/13/0021/1326/1422638/38/b559ab0ff3.png) всё работает норм.

Еслы выбрать ![tab в клавишах развертывания](http://dl3.joxi.net/drive/2018/03/13/0021/1326/1422638/38/67f164911b.png) не работает ни на таб, ни на пробел(на всякий тоже проверил).

Применить нажимал, таб как горячая клавиша не назначен.

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>

- Mahou 2.5.9.0
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Русская(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
```
</details>
<details><summary>Snippets</summary>

```
->Tu
====>TupiNUMBooR<====
```
</details>
</details>

**Comment by BladeMight** [comment]
Исправил в latest-commit.

**Comment by TupiNUMBooR** [comment]
1. При замене на таб(только на таб) оставляет первую букву сниппета

```
->2222
====>1111<====
```
`2222 Tab` -> `21111`

2. при применении конфигурации не сразу включается механизм сниппетов (но это может быть особенностью работы, так что это я просто на всякий)

**Comment by BladeMight** [comment]
> При замене на таб(только на таб) оставляет первую букву сниппета

Дело в том что в некоторых приложениях Tab печатается как символ, а в некоторых может имеет другое или несколько действий, вот там где я тестировал Notepad++, там Tab вводится как символ или выбирает из авто-дополнения, сейчас что-то придумаю...

> при применении конфигурации не сразу включается механизм сниппетов

Немного времени тратиться на инициализацию сниппетов, около 1 с.

**Comment by BladeMight** [comment]
> сейчас что-то придумаю...

Можно попробовать сделать так чтобы Tab не печатал, а работал как отдельная клавиша предназначенная только для развертывания сниппетов, ну как подойтет?

**Comment by BladeMight** [comment]
> Можно попробовать сделать так чтобы Tab не печатал, а работал как отдельная клавиша предназначенная только для развертывания сниппетов

Собственно вот тестовая сборка: [Mahou.zip](https://github.com/BladeMight/Mahou/files/1845607/Mahou.zip)

**Comment by TupiNUMBooR** [comment]
Если `таб` не будет печатать неудобно...

Может можно как то сделать, чтобы `таб` при снипетте перехватывался и ничего другого не делал? И стирать его не надо тогда, да и как команда он мало ли чего может лишнего сделать невовремя. Да и `пробел` можтет мне кажется, в некоторых приложениях или сайтах.

Если не получится, может тогда и правда `пробел` лучше оставить?

**Comment by BladeMight** [comment]
> при снипетте

Ну тут довольно двойной вопрос... Сниппет может есть или нет проверяется при нажатии клавиши развертывания(в нашем случае Tab), а потом уже происходят другие манипуляции. 
Можно сделать так: при нажатии Tab если были введенные буквы сниппета то будет перехватываться и развертываться а если пусто то обычное действие клавиши Tab.

> Да и пробел

Может быть, если добиться *правильного перехвата*...

**Comment by BladeMight** [comment]
@TupiNUMBooR Сделал как писал раннее, то есть Tab будет печататься только если перед этим не было введено букв/цифр(т.е. всего того что может быть частью сниппета), т.е. если сниппет пуст.

**Comment by BladeMight** [comment]
@TupiNUMBooR Релиз [Mahou-v2.6.2.0](https://github.com/BladeMight/Mahou/releases/tag/v2.6.2.0).
