### ISSUE TITLE
Функционирование Mahou в терминале Windows

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#17]
Сейчас Mahou не работает в программе `Cmd.exe`. А хотелось бы. Много времени провожу в командной строке. Спасибо.

**Comment by BladeMight** [comment]
Включите Циклич. режим.

**Comment by Kristinita** [comment]
Спасибо! Работает в CMD и Powershell.

Ждём подробной документации на русском!

**Comment by BladeMight** [comment]
Знаете всплывающие подсказки довольно подробно описывают каждую функцию, а  с версии 1.1.2.0 они еще и на русском, почитайте.

> Ждём подробной документации на русском!

Ну да, она все же будет.

**Comment by Kristinita** [comment]
@BladeMight, в командной строке от имени администратора Mahou не работает. В «обычном» интерпретаторе командной строки, Git Bash и Powershell всё в порядке. Спасибо.

**Comment by BladeMight** [comment]
> в командной строке от имени администратора Mahou не работает

Ну запустите Mahou  тоже от Администратора! [Подробнее...](https://github.com/BladeMight/Mahou/wiki/Mahou-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85-%D0%B7%D0%B0%D0%BF%D1%83%D1%89%D0%B5%D0%BD%D0%BD%D1%8B%D1%85-%D0%BE%D1%82-%D0%90%D0%B4%D0%BC%D0%B8%D0%BD%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0.)

**Comment by Kristinita** [comment]
Есть и [другое](http://superuser.com/a/1039156/572069), более простое решение. 

мне оно помогло, когда я столкнулся с [проблемой](http://superuser.com/q/1098398/572069) в моём клипбоард-менеджере. Запуск той программы от имени администратора, настроенный в Task Scheduler, мне не принёс успеха.

Спасибо.

**Comment by BladeMight** [comment]
> Есть и другое, более простое решение на VBScript. 

Добавлю наверно на Wiki.

> Убрали бы метку invalid

invalid = недействительно => Функционирование Mahou в терминале Windows = недействительно(то есть функционирует)
Ну а вообще ну их все эти метки =)

**Comment by Kristinita** [comment]
Всё же здесь проблема имела место быть, лучше было бы использовать метку, отличную от `invalid`.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Все же может и Вам нужно - недавно восстановил поддержку getconkbl, благодаря которой теперь можно переключать язык одной клавишей и без эмуляции, и еще отображает правильный язык в иконке в трее и в панели языка, и производит конвертацию(если гор. клавиша не назначена на Pause) подробнее в #105. Скачать Mahou с getconkbl можно [здесь](https://github.com/BladeMight/Mahou/releases/tag/v2.3.5.2).

**Comment by Kristinita** [comment]
@BladeMight , я не пользуюсь Mahou в последние месяцы, поскольку **#81** и **#82** слишком часто мешают. Но хорошо, посмотрю, может сейчас изменилось что-то.

Спасибо.

**Comment by BladeMight** [comment]
> может сейчас изменилось что-то.

@Kristinita Я очень старался придумать исправления для #81 и #82 , если у Вас все еще воспроизводится, то очень хотелось бы их решить, но у меня они не воспроизводяться... 😢
