### ISSUE TITLE
Не работает обновление

### ISSUE THREAD

**Issue by TupiNUMBooR** [BladeMight/Mahou#170]
При проверке обновления выдает

>Соединение с github.com не может быть установлено, проверьте подключение к интернету или ваши настройки прокси...

Прокси нет, канал обновлений любой

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>

- Mahou 2.5.9.0
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Русская(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
```
</details>
<details><summary>Snippets</summary>

```
->Tu
====>TupiNUMBooR<====
```
</details>
</details>

**Comment by BladeMight** [comment]
Извиняюсь за поздний ответ, были проблемы с интернетом в моей местности.

> При проверке обновления выдает

Да, заметил похоже GitHub поменял сертификат доступа на более защищенный чем используется по умолчанию в .Net, исправил поменяв его. Теперь нормально работает в latest-commit версии.

**Comment by BladeMight** [comment]
@TupiNUMBooR Релиз [Mahou-v2.6.2.0](https://github.com/BladeMight/Mahou/releases/tag/v2.6.2.0).
