### ISSUE TITLE
При обновлении версии, сработал антивирус

### ISSUE THREAD

**Issue by SaintDI** [BladeMight/Mahou#172]
## Problem/Request description

Во время обновления (до v2.6.2.0) "Защитник Windows" удалил файл программы.
Это было первое обновление программы с момента начала использования, поэтому не могу сказать проблема в этой версии или вообще при любом обновлении.

Настройки системы и антивируса дефолтные:

- [x] Защита в режиме реального времени
- [x] Облачная защита
- [x] Автоматическая отправка образцов

Оставшиеся файлы:
```
AS_dict.txt
jkl.dll
Mahou.ini
snippets.txt
```

Разумеется, помещено в карантин это было практически незаметно — только сообщение об устранённой угрозе в уведомлениях. Так что я даже не сразу понял что произошло.

## Expected behavior (Only if reporting bug)

Успешное обновление программы.

## System information

- Windows version: 10, 1709, 16299.309
- Windows architecture: x64
- .Net version: 4.7.02556
- Mahou version: v2.5.9.3

## Attach logs (if logging were enabled)

![image-20180411-0958](https://user-images.githubusercontent.com/18102192/38595157-48454a28-3d74-11e8-9b11-36d232903487.png)

**Comment by BladeMight** [comment]
@SaintDI Да уж, эти антивирусы... Попробую что-то придумать.

>поэтому не могу сказать проблема в этой версии или вообще при любом обновлении

Проблема появилась после появления новых файлов JKL в папке Mahou с релиза 2.6.2.0.

**Comment by BladeMight** [comment]
@SaintDI Добавил в бинарники информацию о версии, создателе, продукте и т.д. проверь latest-commit версию(Вкладка обновления, поставь канал обновлений на LatestCommit(Beta), нажми проверить обновления, потом скачать обновление.)

**Comment by SaintDI** [comment]
Успешно обновился до 2.6.2.0-dev <bd29f36>

Когда, после обновления, опять решил «обновиться» на Stable (блин, не знал, что так можно) — винда снова словила «троян».

Другими словами, кажется, пофикшено.

**Comment by BladeMight** [comment]
> (блин, не знал, что так можно) 

Ну так удобно ведь, если вдруг Stable работает нормально а в LatestCommit глючит.

**Comment by SaintDI** [comment]
> Ну так удобно ведь, если вдруг Stable работает нормально а в LatestCommit глючит.

Конечно удобно. Ещё бы в кучу других программ такую возможность...

**Comment by BladeMight** [comment]
@SaintDI Релиз [Mahou-v2.6.2.5](https://github.com/BladeMight/Mahou/releases/tag/v2.6.2.5), думаю можно закрывать issue.
