### ISSUE TITLE
Сниппет даты и времени (Date/Time snippet)

### ISSUE THREAD

**Issue by SaintDI** [BladeMight/Mahou#176]
# Сниппет для даты и времени

Есть предложение добавить сниппет на быстрое добавление даты и времени, которая будет автоматически браться у системы (если такое возможно)

## Пример:

**По-умолчанию (системный формат)**

```
->date
====>=date()<====
```

> 17.05.2018

**Свой формат**

```
->date
====>=date(YYYY-MM-DD)<====
```

> 2018-05-17

**Свой формат со временем**

```
->TD
====>=time(), =date(DD.MM.YY)<====
```

> 12:50, 17.05.18

Как-то так.

**Comment by BladeMight** [comment]
@SaintDI Полезно, попробую что-то придумать.

**Comment by BladeMight** [comment]
В b3e838336174e4a4dc518fac3c81340a7fc88911 добавил различные функции в сниппеты, а именно:

1. `__date([format])` / `__time([format])` (по сути то же самое, просто alias) [подробнее о формате](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings).
2. `__version()` - Версия Mahou.
3. `__title()` - Заголовок окна Mahou.
4. `__system()` - Система на которой запущен Mahou.

P.S. Для ввода **именно**(escape) строки названия функции есть escape правило - просто поставь `\` перед названием функции, например: `\__date(HH:mm:ss)`.

Так же обновил стандартные сниппеты на:

```
->mahou
====>Mahou (魔法) - Magical layout switcher.<====
->eml
====>BladeMight@gmail.com<====
->nowtime====>__date(HH:mm:ss)<====
->nowdate====>__date(dd/MM/yyyy)<====
->datepretty====>__date(dd, ddd MMM)<====
->mahouver====>__version()<====
->mahoutitle====>__title()<====
->env_system====>__system()<====
->date_esc====>\__date(HH:mm:ss)<====
->ses====>__system(<====
```

Проверь в [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit).

**Comment by BladeMight** [comment]
@SaintDI Ну как?

**Comment by BladeMight** [comment]
Так же заметил что `'`/`"` в формате тоже нужно escape'ить => `\'`/`\"`.

**Comment by SaintDI** [comment]
Да, работает.
Тестил на Mahou 2.6.7.7-dev <4b95fa3>.

[Форматы](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings) ещё поизучаю, но вроде конструкции типа "Время: 22:28, Дата: 21.05.2018" `__date(Время: HH:mm, Дата: dd/MM/yyyy)` работают.

P.S. сначала подумал, что

> ->nowtime====>__date(HH:mm:ss)<====
> ->nowdate====>__date(dd/MM/yyyy)<====
> <...>

— это новый формат однострочных сниппетов, удивился, что не работает. Потом дошло, что просто при форматировании не было переноса строки.

**Comment by BladeMight** [comment]
ОК, говори если заметишь что-то странное.

**Comment by AlexTransit** [comment]
про форматы. 
очень удобно их в экселе "обкатывать" :) 
пишешь в ячейке значение. а потом "format cells / number / custom" пишешь тип и сразу видешь как оно отображается.
