### ISSUE TITLE
транслятор (перевод выделенного текста)

### ISSUE THREAD

**Issue by AlexTransit** [BladeMight/Mahou#178]
зачастую приходиться переводить выделенный текст. ( думаю не только у меня такое)
и приходится копировать нужное в буфер, запускать гуглевый транслятор, и смотреть перевод.
при работе с китайскими сайтами лучше транслировать биндом.

а тут программа работает с клавиатурой и буфером.
было бы удобно выделить нужный текст, и дабл кликом ctrl или alt, получить окошко в котором покажет перевод.

**Comment by BladeMight** [comment]
@AlexTransit Понимаю, тоже думал об этом уже как-то, думаю попробую что-то придумать(после того как разберусь с Google Translate API...).

**Comment by mssign** [comment]
Не надо комбайн.. https://quest-app.appspot.com/ - QTranslate  прекрасно работает.

**Comment by BladeMight** [comment]
@mssign Я уже почти закончил, скоро будет тестовая сборка в latest-commit.

**Comment by BladeMight** [comment]
@mssign @AlexTransit  Готово, можно проверять в [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit). 
Что и как:
1. Включите переводчик во вкладке `Переводчик`.
2. По желанию настройте вид, языки для перевода, показ по двойному клику(мыши).
3. По желанию включите гор. клавишу "Показать перевод выделенного текста" во вкладке `Горячие клавиши`(по умолчанию стоит два раза по <kbd>Alt</kbd>).

**Comment by AlexTransit** [comment]
спасибо. почему то, ничего не шевельнулось поискать стороннюю софтинку. :)

проверил переводчик. работает. :) 
сначала смутило поведение по дабл клику мыши. 
просто часто использую трипл клик, а тут откаботал дабл. отключил в настройках и все прекрасно работает. 

покопал немного. попробовал. очень понравился QTranslate. из за возможности выбора переводчика. (просто китайский гугл не очень хорошо переводит)
еще нарыл еще один переключатор. правда он "тяжелый" и полный функционал за деньги. https://everylang.net/
но там неплохо реализованы некоторые идеи.
например работа со Snippets. выводит подсказку если соответствие.

и спасибо за реализацию.

**Comment by BladeMight** [comment]
@AlexTransit Всегда интересно сделать что-то новое, получается что сейчас только(ну парочку `user.js` скриптов переводчиков можно найти на greasyfork, но там не более 3 языков) в Mahou есть перевод на `n`-нное количество языков.
