### ISSUE TITLE
Отмена конвертации

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#19]
Положим, я пишу длинную строку, где присутствуют русские, английские буквы, и много кода со скобками, кавычками, запятыми и прочими знаками препинания. Запускаю команду конвертации строки → в строке теперь только русские или только английские символы. Откатить изменения не получается → `Ctrl+Z` конвертации не изменяет.

![Ctrl+Z](http://i.imgur.com/YB3ncj7.gif)

В итоге приходится переписывать эту длинную строку заново. А хотелось бы возможности отмены конвертации.

Спасибо.

**Comment by BladeMight** [comment]
> А хотелось бы возможности отмены конвертации.

Она есть, но только в формах поддерживающих ее.(Блокнот например)

**Comment by Kristinita** [comment]
> Она есть, но только в формах поддерживающих ее.(Блокнот например)

Там, где я обычно ввожу тексты: Sublime Text, Search Bar Firefox, QTranslate, поле ввода на GitHub, куда ввожу данное сообщение, не говоря уже о cmd.exe, отмена не работает.

Спасибо.

**Comment by BladeMight** [comment]
> Sublime Text

Ну не с одного раза по<kbd> Ctrl</kbd>+<kbd>Z</kbd>(сколько слов столько и раз).

**Comment by Kristinita** [comment]
У меня не работает ни в одной из программ.

Возможно, я неверно выразился. Нужна **отмена конвертации**, а не удаление неправильно сконвертированных слов. Т. е. я написал `Sasha Ьшкфсду` → запустил команду конвертации линии, получилось `Ыфырф Ьшкфсду`. <kbd>Ctrl+Z</kbd> удаляет слова, а необходимо, чтобы можно было вернуться к варианту `Sasha Ьшкфсду`.

Пример надуманный, но в длинных строках важно иметь возможность возврата после неверной конвертации, иначе подчас приходится переписывать всю строку.

Спасибо.

**Comment by BladeMight** [comment]
Нет ну вы дочитали?
Нажимайте <kbd>Ctrl</kbd>+<kbd>Z</kbd>  пока не вернетесь.

**Comment by Kristinita** [comment]
> Нет ну вы дочитали?
Нажимайте Ctrl+Z пока не вернетесь.

Понял, спасибо. Но если строка большая, придётся жать долго-долго, а можно ли сделать так, чтобы отмена осуществлялась в один клик?

> cmd.exe
> > Для каждой буквы -> Ctrl+Z.

Разве [будет работать](http://superuser.com/a/147927/572069)?

Спасибо.

**Comment by BladeMight** [comment]
> Разве будет работать?

У меня работает...

> можно ли сделать так, чтобы отмена осуществлялась в один клик?

Если сделать ввод не каждого символа а всех сразу (через буфер обмена например) то не будет работать в `cmd.exe` и где-то еще.

**Comment by Kristinita** [comment]
> P.S. Попробуйте напечатать слово в cmd.exe, стереть его и нажать пару раз на Ctrl+Z, как увидите отмена такая же как и в Mahou.

В `CMD.exe` при нажатии `Сtrl+Z` всегда добавляется `^Z`:

![1](http://i.imgur.com/8FIPlKP.gif)

Спасибо.

**Comment by BladeMight** [comment]
Ну есть 2 варианта:

1. Правой кнопкой на панели назнания(то за которую тянут чтобы перетащить окно) → значения по умолчанию → настройки(вкладка) → включите "разрешить комбинации Сtrl клавиш"(галочка).
2. `Alt+BackSpace`
