### ISSUE TITLE
Преобразование выделенного текста к нижнему и к верхнему регистру

### ISSUE THREAD

**Issue by maca1shivom** [BladeMight/Mahou#199]
## Problem/Request description

Добавьте, пожалуйста, такие возможности в Mahou.

**Comment by GlebMorgan** [comment]
Поддерживаю. Единственное, чего не хватает, чтоб окончательно перейти на Mahou!

**Comment by BladeMight** [comment]
@maca1shivom Добавил в latest-commit.

**Comment by BladeMight** [comment]
@maca1shivom @GlebMorgan @f242 Только что добавил в latest-commit.
