### ISSUE TITLE
не переключает в Telegram Desktop на Win 10 x64

### ISSUE THREAD

**Issue by f242** [BladeMight/Mahou#2]
при попытке переключить выделенный текст получаю строку содержащую одну букву ппппппппппппп

**Comment by BladeMight** [comment]
Завтра скачаю и проверю, а потом исправлю.

**Comment by BladeMight** [comment]
Проверь [новую версию(1.0.0.4](https://github.com/BladeMight/Mahou/releases).
У меня все нормально работает.

**Comment by f242** [comment]
да в телеге теперь норм, но в других не всегда сразу или с первого раза, в waterfox тут в форме ответа надо медленно нажимать чтобы выделенное сконвертило и то не факт, в outlook 2016 x64 не работает вообще, кажется она не подходит у кого большой выбор софта :(

**Comment by BladeMight** [comment]
Исправленная [версия(1.0.0.5)](https://github.com/BladeMight/Mahou/releases), в этой версии переключается всегда(то есть с первого раза) и быстрее с выделением.
В Outlook должно работать если запустить Mahou от Администратора.

**Comment by BladeMight** [comment]
Исправленная [версия(1.0.0.5)](https://github.com/BladeMight/Mahou/releases), в этой версии переключается всегда(то есть с первого раза) и быстрее с выделением.
В Outlook должно работать если запустить Mahou от Администратора.

**Comment by f242** [comment]
всё равно не с первого раза в основном, что-то не в той написал быстро ctrl+a и конвертация по ctrl+` и не конвертит, а вот ещё раз нажать и тогда срабатывает, в аутлуке всё равно не конвертит, даже от администратора

**Comment by BladeMight** [comment]
Проверь какой метод ввода(язык) стоит когда нажимаешь, и скажи на что у тебя назначены ctrl+a и ctrl+`, и каким способом не конвертит(выделением/последнее слово)

**Comment by BladeMight** [comment]
Только что проверил, у меня все отлично работает.
По поводу клавиш Shift, Alt, и Ctrl их надо нажимать каждый раз заново, чтобы сработала горячая клавиша. То есть если назначено Ctrl + A то надо нажать Ctrl а потом A, но для следующего раза нужно сначала отпустить Ctrl, а потом нажать Ctrl а потом A. 
Знаю немного не удобно, но пока так.
Это я исправлю завтра.

**Comment by BladeMight** [comment]
И правда, проблемы были, но теперь уже точно всегда с первого раза будет.
Добавил ограничитель скорости переключения по выделению,добавил несколько попыток на конвертацию. С ними проблем не будет.[Версия 1.0.0.6](https://github.com/BladeMight/Mahou/releases/tag/v1.0.0.6)

**Comment by f242** [comment]
не, вообще перестала конвертить выделенный текст, курсор мыши чуток подвисает после комбинации ctrl+`, у меня контрол+тильда забиндены на сие действие

**Comment by BladeMight** [comment]
Попробуй [последнюю версию](https://github.com/BladeMight/Mahou/releases) в нескольких приложениях(Блокнот, Браузер, Проводник, еще что-то...) и напиши как себя ведет программа.
Подвисания - это значит что произошла ошибка,и он пытается ее исправить, если не получится, то пропускает, тогда она просто заново начнет.
P.S. У меня все в Блокноте, Хроме, Проводнике нормально работает... :( даже с той же горячей клавишей(CTRL+`)... В WordPad'e плохо работает, сейчас буду исправлять :)

**Comment by BladeMight** [comment]
Знаешь, а в WordPad'e даже знаменитый Punto Switcher глючит :)

**Comment by BladeMight** [comment]
Вух, вот [последняя версия](https://github.com/BladeMight/Mahou/releases), в ней точно все работает!
P.S. Удали конфигурацию страрых версий.(Файл: "Mahou.settings").

**Comment by f242** [comment]
1. вместо **прежнему** конвертит в **пре;нему**, а **волшебно** конвертится как **волше,но**, **юпитер** выходит **.питер**, но с **х**омяками, под**ъ**ездом и **э**демом всё норм
2. если захватить пробел кажется не конвертит
3. в аутлук по прежнему не клнвертит, что с администратором что без, причём не конвертит при написании текста письма, в поле "тема" всё работает

**Comment by BladeMight** [comment]
На счет 1. поменяй языки местами (Language 1 на русский, Language 2 на Английский)
На счет 2. не понял? настроить гор. клавишу на пробел? или конвертация пробела, если она то она работает.
На счет 3. У меня нету Аутлука чтобы проверить.... но если у тебя есть Visual Studio то проверить можешь ты... и сказать мне..

**Comment by f242** [comment]
поменял, теперь вместо **прежнему** конвертит в **преЖнему**
имелось в виду выделяя захватить пробел между словами, но видимо показалось, вроде конвертирует, но тут в форме глючит, то переключает то нет, а в конце вообще вывалилось
![default](https://cloud.githubusercontent.com/assets/10371194/16397222/bf8ff728-3ccb-11e6-8d8a-1d8b8894e6de.PNG)
как я понимаю она работает через буфер в результате чего его содержимое теряется

**Comment by BladeMight** [comment]
> как я понимаю она работает через буфер в результате чего его содержимое теряется
Да, это пожалуй единственный известный мне способ получить выделенный текст.
`Надо будет поисправлять все...`
Ты пиши тут если еще что-то заметишь.

**Comment by BladeMight** [comment]
Попробуй [последнюю версию](https://github.com/BladeMight/Mahou/releases) и скажи как там.

**Comment by BladeMight** [comment]
Ну проблема с Telegram Desktop на Win 10 x64 - решена? Значит проблема **закрыта**.
