### ISSUE TITLE
Конвертация выделенного куска в MS Outlook 2013

### ISSUE THREAD

**Issue by vicodin77** [BladeMight/Mahou#20]
Доброго дня!
Не работает конвертация выделенного куска в MS Outlook 2013. Строку и последнее слово конвертирует!

**Comment by BladeMight** [comment]
> Не работает конвертация выделенного куска в MS Outlook 2013

Outlook блокирует для Mahou доступ к буферу обмена.
Работает ли [SimpleSwitcher](https://github.com/alexazz19/SimpleSwitcher/releases)?

**Comment by vicodin77** [comment]
SimpleSwitcher - не могу ни где найти...

**Comment by BladeMight** [comment]
Видимо удалил репозиторий, [вот](https://vk.com/away.php?to=https%3A%2F%2Fyadi.sk%2Fd%2FhpJUylukuVQKh).

**Comment by vicodin77** [comment]
Проверил, SimpleSwitcher работает!

**Comment by BladeMight** [comment]
Ясно, разберусь с этим позже.

**Comment by vicodin77** [comment]
Спасибо!

**Comment by BladeMight** [comment]
Проверьте с этими настройками в Mahou:

1. Включите `Циклч. режим`.
2. Включите `Эму`.
3. Тип эмуляции на `Win+Space`
4. Включите `КВ-Ключ`
5. Проверьте...

**Comment by vicodin77** [comment]
Нет, не работает...

**Comment by BladeMight** [comment]
Что пишет при конвертации в консоли в Mahou-BETA:
[Mahou-BETA.zip](https://github.com/BladeMight/Mahou/files/451419/Mahou-BETA.zip)

**Comment by vicodin77** [comment]
Пишет четыре раза выделенный текст и работает!!!

**Comment by BladeMight** [comment]
Ясно, сейчас за-релизю.

**Comment by vicodin77** [comment]
Так же может убивать пробелы или до выделенного слова, или после него!

**Comment by BladeMight** [comment]
> Так же может убивать пробелы или до выделенного слова, или после него!

Не понял, как это?

**Comment by vicodin77** [comment]
Консолька может выводить не только четыре раза выделенное слово, но два раза, и три раза! Так же перед ними выводится две или три пустых строки!
Может это будет полезно!

**Comment by BladeMight** [comment]
> Может это будет полезно!

Да ! Очень!

**Comment by BladeMight** [comment]
Еще проверьте как работает в [Mahou-BETA-2.zip](https://github.com/BladeMight/Mahou/files/451475/Mahou-BETA-2.zip)

**Comment by vicodin77** [comment]
Вот так убивается пробел - 
![02 09](https://cloud.githubusercontent.com/assets/16464189/18197559/6f6b7042-7100-11e6-8392-180219c910e0.jpg)

**Comment by vicodin77** [comment]
А вот в бете два конвертация выделенного не работает и в консоль ни чего не выдается...

**Comment by vicodin77** [comment]
Но не работает только в оутлуке!

**Comment by BladeMight** [comment]
Вот проверь [Mahou-v1.1.2.6](https://github.com/BladeMight/Mahou/releases/tag/v1.1.2.6)

**Comment by BladeMight** [comment]
Вот проверь [Mahou-v1.1.2.6](https://github.com/BladeMight/Mahou/releases/tag/v1.1.2.6) или обновись из Mahou.

**Comment by vicodin77** [comment]
Не работает!

**Comment by vicodin77** [comment]
И пробелы в бете1 убивались только в оутлуке!

**Comment by BladeMight** [comment]
> И пробелы в бете1 убивались только в оутлуке!

Ну у меня не Outlook так что досконально проверить не могу...

> Не работает!

Вообще что ли?

**Comment by vicodin77** [comment]
Не, в оутлуке не переключает выделенное! Все остальное работает!

**Comment by BladeMight** [comment]
Ладно вот последняя бета, 
[Mahou-BETA-LAST.zip](https://github.com/BladeMight/Mahou/files/451607/Mahou-BETA-LAST.zip)
как работает здесь?

**Comment by BladeMight** [comment]
Ладно вот последняя бета, 
[Mahou-BETA-LAST.zip](https://github.com/BladeMight/Mahou/files/451607/Mahou-BETA-LAST.zip)
как работает здесь?

**Comment by vicodin77** [comment]
Дубль?
Да, последняя бетка работает норм! Пробельчики бывает что режуться, но это не так критично и отловить не всегда получается! В релиз!))

**Comment by BladeMight** [comment]
> Дубль?

В смысле?

> В релиз!))

Окей.

Ну так что закрываем проблему?

**Comment by vicodin77** [comment]
Да!
