### ISSUE TITLE
Convert last word не работает после пробела

### ISSUE THREAD

**Issue by persty** [BladeMight/Mahou#207]
## Problem/Request description

После набора слова и пробела за ним, горячая клавиша Convert last word не срабатывает

## Expected behavior (Only if reporting bug)

Хотелось бы идентифицировать пробел, как связанную часть последнего слова (с точки зрения конвертации раскладки). Привычка осталась после другого переключателя раскладки...

## System information

- Windows version: 10
- Windows architecture: x64
- .Net version: 4.0
- Mahou version: 2.7.5.0

**Comment by ArmanHigh** [comment]
В окне Функции поставьте галочку `Считать Пробел частью последнего слова`

**Comment by persty** [comment]
Идеально)
