### ISSUE TITLE
[Баг] Необходимость двойного нажатия при конвертации

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#21]
## Описание проблемы

В новой версии для перехода из одной раскладки в другую мне через раз приходится дважды нажимать заданный мной хоткей для команды «Конверт линии».

## Шаги воспроизведения

Набираю текст → нажимаю моё сочетание → иногда достаточно нажать хоткей 1 раз, но иногда приходится дважды.

![Двойное нажатие](http://i.imgur.com/VC1IDqU.gif)

##  Прочие мои действия по исправлению проблемы

Тестировал в Sublime Text, Firefox и QTranslate → поведение то же. Отключал все программы кроме той, в которой тестирую.

## Дополнительная информация

Проблемы начались сегодня, с версией 1.1.2.7. Раньше подобного не было.

## Программно-аппаратное окружение

Windows 10
Mahou 1.1.2.7

----

Спасибо.

**Comment by BladeMight** [comment]
Какие раскладки установлены в системе?

**Comment by Kristinita** [comment]
Проблема возникает при включенной галочке «Циклч. режим». Без неё всё переключается с первого раза.

> Какие раскладки установлены в системе?

Русская и английская. Установлена [раскладка](https://tabun.everypony.ru/blog/computers/105151.html) c функционирующим правым Alt.

> Попробуйте с другой горячей клавишей.

Ставил также `F8` и `Insert`, результат тот же.

> Прямо сейчас проверьте с ранней версией.

Пробовал сейчас с ранними версиями. По крайней мере на 1.1.2.0 баг остался.

(Можно в README.MD ссылку оставить на историю релизов, не все найдут ещё.)

Спасибо.

**Comment by BladeMight** [comment]
> Проблема возникает при включенной галочке «Циклч. режим».

А `Эму` включен?

> Русская и английская.

Английская US? Просто на Windows есть баг(вечный) который автоматически добавляет English US даже если ее нет, просто у меня Японский IME и я частенько с этим сталкивался.
Попробуйте пере-добавить их по очереди(если не US).

> Можно в README.MD ссылку оставить на историю релизов, не все найдут ещё
ОК.

**Comment by Kristinita** [comment]
> Попробуйте пере-добавить их по очереди(если не US).

Передобавлял, проблема осталась.

> А Эму включен?

Теперь функция заработала. Спасибо! (Только [эта проблема](http://superuser.com/q/1098398/572069) после всех манипуляций опять появилась, когда я первое сообщение в эту тему писал, её точно не было.)

Есть ли минусы использования «Эму»?

**Comment by BladeMight** [comment]
> Есть ли минусы использования «Эму»?
Эму - прямая эмуляция нажатия `Alt+Shift`/`Ctrl+Shift`/`Win+Space` которую лучше всего работает в Metro приложениях.
Всего один минус = ~10-20 мс на эмуляцию нажатия, если за это время успеть нажать что-то то эмуляция возможно не заработает, хотя все еще зависит от быстродействия формы в которой вводите.

**Comment by Kristinita** [comment]
Из-за чего эта проблема могла возникнуть? В чём причина? Помимо Ditto, мне один плагин для Sublime Text пришлось удалять, [багрепорт](https://github.com/Skullmonkey/IPS-BBCode/issues/2). Спасибо.

**Comment by BladeMight** [comment]
> мне один плагин для Sublime Text пришлось удалять

Там просто настроена `Ctrl+Shift+p` настроена на Insert Snippet в Windows, вот строчки:
```json
  { "keys": ["ctrl+shift+p","ctrl+shift+u","ctrl+shift+r","ctrl+shift+p","ctrl+shift+l","ctrl+shift+e"], "command": "insert_snippet", "args": {"name": "Packages/IPS BBCode/Snippets/purple.sublime-snippet"} },
```
и
```json
  { "keys": ["ctrl+shift+p","ctrl+shift+h","ctrl+shift+p"], "command": "insert_snippet", "args": {"name": "Packages/IPS BBCode/Snippets/php.sublime-snippet"} },
````
Вот исправленная версия [IPS BBCode.zip](https://github.com/BladeMight/Mahou/files/453373/IPS.BBCode.zip)

> Ditto

Ну не знаю, у меня все нормально вставляет(самостоятельно по Win+F2 последний клип), может опишите по подробнее что и как у вас настроено?

**Comment by BladeMight** [comment]
А по поводу остальных клавиш,`Ctrl+Shift+b` и тд., они назначены уже в Sublime Text, `Ctrl+Shift+b` - `Build With` а установка этого плагина переписывает их... так что вам придется вручную определить все горячие клавиши в плагине(можно открыть архиватором) в файле `Default (Windows).sublime-keymap`.
Удачи.

**Comment by Kristinita** [comment]
> опишите по подробнее что и как у вас настроено?

Из всех функций клипбоард-менеджеров мне нужна только такая: когда нажимаешь на определённое сочетание горячих клавиш, вставляется какой-то текст. Таких кусков текста, которые мне приходится постоянно вставлять, достаточно много.

Пример, как настраиваю сочетание клавиш: 2ЛКМ по иконке Ditto в трее → что-нибудь пишу в открывшемся поле → `Ctrl+Shift+S` → вписываю вот так:

![1](http://i.imgur.com/WA2cZGc.png)

Итого при нажатии `Win+.` вставляется ` &nbsp;`, при нажатии `Win+Scroll Lock` → `cd /D E:/SashaSublime` и т. д.

![2](http://i.imgur.com/2vCA3GL.png)

В настройках галочка напротив «Отправить вставку» стоит:

![3](http://i.imgur.com/c57Yg1d.png)

Ditto запущена от имен администратора.

>  (и заодно узнаю почему Вы используете его, я например пользуюсь ClipDiary)

Не знаю других программ, где можно было бы делать так, как я описал выше. В ClipDiary также не нашёл, как назначать вставке определённого текста сочетания клавиш.

Спасибо.

**Comment by Kristinita** [comment]
И в QTranslate [баг](http://forum.ru-board.com/topic.cgi?forum=5&topic=35038&start=2520#15): не копируется текст из поля перевода в буфер обмена.

Может, Вы знаете какие-то программы, уменьшающие количество проблем с буфером обмена Windows? 

Спасибо.

**Comment by BladeMight** [comment]
>  когда нажимаешь на определённое сочетание горячих клавиш, вставляется какой-то текст

Тогда вам нужна всего лишь [QuickTextPaste](http://rsload.net/soft/desktop/11743-quicktextpaste.html)(59кб)

Странно, но у меня все всегда с первого раза...
И `Win+.` и `Win+Scroll Lock` вставляют `&nbsp;` и `cd /D E:/SashaSublime` с первого раза.

> И в QTranslate баг

Который у меня тоже нормально работает на гор. клав. `Ctrl+Win+t`...

**Comment by BladeMight** [comment]
Вот [теперь](https://github.com/BladeMight/Mahou/releases/tag/v1.3.0.0) появилась такая функция(Double hotkey для двойного shift и т.д.).

**Comment by BladeMight** [comment]
А как в последней версии? >1.3.0.0, там переделан способ управления хоткеями.

**Comment by BladeMight** [comment]
А в последних версиях, все гораздо лучше работает...
И двойного нажатия не нужно(только если не включена функция двойных гор. клавиш), так что проблема решена.

**Comment by Kristinita** [comment]
@BladeMight, (оффтоп). Как специалист по клавиатурным раскладкам, не могли бы посмотреть [**вопрос**](http://superuser.com/q/1169680/572069)? У меня эта проблема давно и в разных операционных системах. Причём, ничего не получается нагуглить по ней.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Гляну чуть позже, сейчас занят.
