### ISSUE TITLE
Внедрить горячую клавишу—временная пауза mahou

### ISSUE THREAD

**Issue by reifwp** [BladeMight/Mahou#210]
1) На ноутбуке, не удобно pause, для конвертации, переназначил на insert . Но иногда insert нужен в других прогах .Добавьте горячую клавишу—временное отключение(пауза) программы
2) Сниппет бы добавить текущее время и дата

**Comment by BladeMight** [comment]
> Добавьте горячую клавишу—временное отключение(пауза) программы

Хорошо добавлю.

> Сниппет бы добавить текущее время и дата

Есть с использованием [функций в сниппетах](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BD%D0%B8%D0%BF%D0%BF%D0%B5%D1%82%D1%8B%3F-%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%3F#Функции-в-сниппетахС-версии-mahou-2700), функция `__date(здесь формат времени)`, пример сниппета с ее использованием:
```
->времмя
====>__date(ddd[dddd], MMM[MMMM], dd-MM-yyyy, HH:mm:ss.fff)<====
```
Результат:
```
Чт[четверг], окт[октября], 18-10-2018, 19:11:19.620
```
Подробнее о формате [есть здесь](https://metanit.com/sharp/tutorial/19.2.php).

**Comment by reifwp** [comment]
спасибо

**Comment by reifwp** [comment]
прога великолепная(без преувеличения).. Маленькая,быстрая,стабильная..Пользуюсь скоро полгода,вообще сбоев не было,как часы работает швейцарские.
Лучше сделать невозможно по моему. Всех Вам благ!

**Comment by BladeMight** [comment]
@reifwp 
1. Звуки создал я сам, в репозиторие есть еще звуки из которых можно выбрать [/master/snd/](https://github.com/BladeMight/Mahou/tree/master/snd), а у твоих звуков может быть копирайт.
2. У меня норм:
![mahou everything](https://user-images.githubusercontent.com/11931888/47256296-50235880-d486-11e8-9654-984f9a0b0392.gif)

**Comment by reifwp** [comment]
1) Понятно
2) Странно,а у меня не пашет . Лады .

**Comment by BladeMight** [comment]
@reifwp В 32b1324 в latest-commit версии добавил:

> горячую клавишу—временная пауза mahou

Проверяй, обновляйся из Mahou по каналу обновлений LatestCommit(Beta) или вот ссылка на архивы [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit)(Release_x86_x64.zip).

**Comment by ArmanHigh** [comment]
А можно добавить функцию включения/выключения паузы из меню правого клика по иконке программы в трее? Там сейчас только Показать/скрыть и Выход.

**Comment by BladeMight** [comment]
@ArmanHigh Да, можно.

**Comment by reifwp** [comment]
гран мерси ! 👍👍👍

**Comment by BladeMight** [comment]
> @ArmanHigh Да, можно.

@ArmanHigh Таки добавил...
