### ISSUE TITLE
Хранение паролей в виде сниппетов

### ISSUE THREAD

**Issue by ArmanHigh** [BladeMight/Mahou#211]
Всегда хранил свои длинные, незапоминаемые пароли в KeePass, но его нужно открывать, вводить пароль к базе, находить нужное поле... В общем долго и лень. Хранить пароли в самом Chrome не позволяет внутренний пароноик.
С недавнего времени использую сниппеты для ввода паролей к не особо важным сайтам.
На примере Фейсбук:
->[fbl]====>mylogin<====
->[fbp]====>mypassword<====

**Вопрос:** где хранится эта информация? Легко ли её будет умыкнуть злоумышленнику? Имеет ли смысл использовать Mahou в таком ключе, или это опасно.

**Comment by BladeMight** [comment]
> где хранится эта информация?

В `snippets.txt` рядом с Mahou.exe. Если доступ к файлу имеешь только ты то не опасно, но даже если доступ имеется, как злоумышленнику понять что:
```
->[fbl]====>mylogin<====
```
Это логин от Фейсбука?
Можно ведь вообще записать подобным образом:
```
->ffq1====>Buig$qNaNl%+1<====
```
Ну и никто кроме тебя не будет знать что такое `ffq1` и откуда `Buig$qNaNl%+1`(просто у меня пароли все такого формата :)). 

А еще можно сделать возможность вставлять в сниппет зашифрованный пароль каким-то способом, и используя функцию `__execute` вызвать команду которая ее расшифрует и запустить это все в `cmd` и можно добавить в конце `| clip` чтобы скопировать в буфер обмена(вот тут я подумал может добавить функцию которая вставляет результаты функции `__execute`?), хотя в него копировать может быть небезопасно, в зависимости от того какие программы запущены, которые могут перехватывать и сохранять эти данные, хотя в большинстве случаев такими программами являются установленные пользователем менеджеры буфера обмена, вроде ClipDiary, которые используются пользователем(т.е. тобой) так что думаю и в данном случае тоже довольно безопасно. Другое дело если есть какая-то вредоносная программа которая следит за буфером, но даже если у нее и будут эти данные догадаться что с ними делать она не сможет, хотя если она их куда-то отравляет то там уже могут и догадаться, но вероятность почти 0%. Пример сниппета с `__execute`:
```
->eqt====>__execute(cmd.exe| /c echo QnVpZyRxTmFObCUrMQ== | base64.exe -d | clip)<====
```
Показывает окно cmd(чтобы скрыть окно можно использовать [h](https://github.com/BladeMight/h), потом может добавлю функцию `__hiddenexecute`), расшифрофует `QnVpZyRxTmFObCUrMQ==` => `Buig$qNaNl%+1` используя утилиту `base64.exe` в моей системе, и копирует в буфер с `clip`.

В итоге безопасно если: 
1. *Доступ и знание о том что и для чего в **snippets.txt** есть только у тебя.*
2. *Программы имеющие доступ к буферу пользовательские(т.е. ты сам ими пользуешься)*

**Comment by ArmanHigh** [comment]
У меня пароли тоже такого формата, только длиннее, это я к примеру писал. Поэтому сниппеты и к месту. 
Нашёл snippets.txt в папке `C:\Users\Пользователь\AppData\Roaming\Mahou` , а не в папке с программой. На данный момент, когда Mahou не используется пользователями для целей хранения паролей, то думаю слишком заморачиваться не стоит. Но на будущее, если программа приобретёт большую известность, не будет ли этот файл в известном положении первым, который будет представлять ценность для программы злоумышленника. Вставка чего-то такого `Buig$qNaNl%+1` явно намекает на то, что это пароль, а найти к чему он не особо сложно. Нельзя ли snippets.txt как-то обезопасить, зашифровать?
Твой следующий параграф интересен. Правда приведённый пример у меня не завёлся. Окно открывается, но расшифровка и копирование в буфер скорее всего не произошло, не вставляется. Поискал на диске `bse64.exe`, не нашёл.

**Comment by BladeMight** [comment]
> Нельзя ли snippets.txt как-то обезопасить, зашифровать?

Можно но проект OpenSource, судя по этому метод шифровки будет всем известен.

> Поискал на диске bse64.exe, не нашёл

Да, это дополнительная утилита(GNU CoreUtils), у меня стоит через `MSYS2`.

**Comment by ArmanHigh** [comment]
> Можно, но проект OpenSource, судя по этому метод шифровки будет всем известен.

Печаль-беда.
