### ISSUE TITLE
Скрипт обновления

### ISSUE THREAD

**Issue by Fesko** [BladeMight/Mahou#22]
При обновлении Mahou выполняется PowerShell скрипт, разархивирующий скачанный файл. Ему для работы нужен .NET Framework 4.5 (для ZipFile), если его нет, то просто удаляются все файлы Mahou без каких либо сообщений и ошибок.
Я набросал батник, создающий и выполняющий VBScript для той же задачи
```
@echo off
TASKKILL /PID 2272 /F
del "D:\Mahou.exe"

echo UnZip WScript.Arguments(0), WScript.Arguments(1) > unzip.vbs
echo Function UnZip(source, destination) >> unzip.vbs
echo   With CreateObject("Shell.Application") >> unzip.vbs
echo        .NameSpace(destination).Copyhere .NameSpace(source).Items >> unzip.vbs
echo   End With >> unzip.vbs
echo End Function >> unzip.vbs

cscript unzip.vbs "D:\Mahou-v1.1.3.2.zip" "D:\"
start "" "D:\Mahou.exe" _!_updated_!_

del "D:\Mahou-v1.1.3.2.zip"
del unzip.vbs
```
По идее, ему для выполнения не нужны никакие дополнительные библиотеки

**Comment by BladeMight** [comment]
> Ему для работы нужен .NET Framework 4.5

Ну по идее для Mahou тоже 4.5 нужен...
> Я набросал батник, создающий и выполняющий VBScript для той же задачи

Я уже думал над другими вариантами распаковки(т.к. PowerShell немного медленный), спасибо за подсказку, проверю позже сейчас у меня есть дела.

**Comment by Fesko** [comment]
> Ну по идее для Mahou тоже 4.5 нужен...

У меня 4.0, все работает)

**Comment by BladeMight** [comment]
> У меня 4.0, все работает)

Странно... Я пишу Mahou на 4.5, а работает на 4.0? Чудеса?

**Comment by Fesko** [comment]
> Странно... Я пишу Mahou на 4.5, а работает на 4.0? Чудеса?

Magic Switcher же :)
Как-то странно, сейчас покопался в своей системе, 4.5.1 похоже действительно стоит, но PowerShell его не видит и ругается на ZipFile

**Comment by BladeMight** [comment]
Вобщем закончил с делами, сейчас возмусь за освоение основ VBScript(чтобы понять что к чему) как закончу напишу.

**Comment by BladeMight** [comment]
Разобрался я как работает VBScript, и все готово, в [версии 1.1.4.0](https://github.com/BladeMight/Mahou/releases/tag/v1.1.4.0).
Вот [*специальная* тестовая версия 0.0.0.0](https://github.com/BladeMight/Mahou/files/456851/Mahou-ZERO.zip)(на самом деле 1.1.4.0) для проверки работы, обновитесь из 0.0.0.0 и скажите как все прошло...

**Comment by qfeuer** [comment]
проверил новый скрипт обновления, работает у меня без нареканий и ошибок, оба тестирования были на 4.6.1 фреймворке

**Comment by Fesko** [comment]
> Разобрался я как работает VBScript, и все готово, в версии 1.1.4.0.
> Вот специальная тестовая версия 0.0.0.0(на самом деле 1.1.4.0) для проверки работы, обновитесь из 0.0.0.0 и скажите как все прошло...

Все сработало, спасибо

**Comment by BladeMight** [comment]
Пожалуйста!
