### ISSUE TITLE
Синхронизация сниппетов между устройствами

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#222]
У меня завелся второй ПК, на котором тоже пользуюсь Mahou, хотелось бы чтобы сниппеты синхронизировались между компами.
Пока что вижу только вариант - закинуть Mahou в Dropbox (или аналоги), но сейчас я такими не пользуюсь.
Может у вас есть варианты получше\полегче?

**Comment by BladeMight** [comment]
@Trost123 Можно попробовать использовать анонимные GitHub Gist, в которые сохранять и загружать сниппеты.

**Comment by BladeMight** [comment]
В общем нужен какой-то сервер на который каждый(по логину наверно) мог бы сохранять/загружать свои сниппеты...

**Comment by Trost123** [comment]
Или https://pastebin.com/api.php
Ну это не срочно и не горит. Но было бы прикольно, чтобы без стороннего софта Mahou делал это.
И setting.ini можно было бы в pastebin тоже бекапить если научишься с их апи работать.
Короче это чисто если тебе интересно будет, после праздников уже.
С наступающим, кстати.

**Comment by BladeMight** [comment]
@Trost123 Хорошо посмотрю потом, и тебя с наступающим!

**Comment by BladeMight** [comment]
@Trost123 Сделал синхронизацию с использованием [hastebin](https://hastebin.com/about.md), новая вкладка "Синхронизация" в latest-commit.

P.S. pastebin разрешает только 500 КБ.

**Comment by Trost123** [comment]
Проверил, работает. Отдельное спс за находку hastebin.
Вообще я представлял это немного иначе.
Сохранение: в облаке где либо висит конфиг + сниппеты. Доступны они по статик ссылке. В этот облачный файл при сохранении настроек Mahou автоматом пишет настройки, сниппеты.
Загрузка: при запуске Mahou проверяет файл (или его хеш\дату для скорости) и автоматом подтягивает настройки если они новее локальных.
В таком случае юзер один раз активирует фичу и у него всегда синхрон между устройствами между надобности руками запускать синхронизацию или прокидывать ссылку с ПК на ноутбук.

**Comment by BladeMight** [comment]
> Сохранение: в облаке где либо висит конфиг + сниппеты. Доступны они по статик ссылке

Можно будет сделать если вместо hastebin использовать GitHub Gists(уже думал над реализацией...), но там нужно будет вводит логин/пароль.

> Загрузка: при запуске Mahou проверяет файл (или его хеш\дату для скорости) и автоматом подтягивает настройки если они новее локальных

Интересная идея.

> мне нет смысла включать JKL?
JKL в основном нужен только для консольных/других проблемных приложений в которых функция WinAPI: `GetKeyboardLayout` не даёт правильный результат.

**Comment by Trost123** [comment]
rip. Как я понимаю умер hastebin и фичу потому выпилили?

**Comment by Trost123** [comment]
Прошу прощения, перепутал. В 2.9.0.1 вкладка есть, но "The remote server returned an error: (503) Server Unavailable."

**Comment by BladeMight** [comment]
💐⎧ᴿᴵᴾ⎫💐
Да... Уже ничего не поделаешь с hastebin, нужно либо искать что-то другое...

**Comment by Trost123** [comment]
Я проверил и это сервер hastebin выделывается просто...

**Comment by BladeMight** [comment]
Правда было один раз что заработало через пару дней...

**Comment by Trost123** [comment]
Ладно, фиг с ним. Жалко конечно что код писал а сервис упал через год. 😕

**Comment by BladeMight** [comment]
Ну что, бывает...

**Comment by Trost123** [comment]
4 года спустя вернулся на Windows, снова поставил Mahou и пошёл гуглить как завести Hastebin синхронизацию. Нашёл свой же тред тут, ахах. ❤️ 

Благо Mahou опенсорсный, я смог по коду глянуть что значит галочка 0x0.st в настройках, понял что это альтернативный сервер и рабочий.

Ещё раз спасибо за проделанный труд!
Сейчас смотрю назад на те горы фидбека и feature request-ов (в том числе и от меня, в том числе очень нишевых) и поражаюсь как у автора хватило на это всё терпения. 😮 

Закрываю этот тред т.к. считаю что проблема решена - сейчас протестировал, синхронизация через https://0x0.st/ работает!

(Note to future self: Единственное, что нужно не забывать ставить галочку напротив 0x0.st в секции создания бекапа и во время восстановления копии.)
