### ISSUE TITLE
new releace 2.9.0.0 (small problem)

### ISSUE THREAD

**Issue by AlexTransit** [BladeMight/Mahou#223]
небольшая проблема при установке 2,9

1. из приложения в "stable" не видит обнову. видно только в "beta"
2. после обновления у меня прога упала. как оказалось виной было содерщимое Mahou.ini. (руками в нем ничего не менял) 
удаление своего инишника решило проблему. (расширение .log добавил что бы гит его принял.)
[Mahou.ini.log](https://github.com/BladeMight/Mahou/files/2722738/Mahou.ini.log)

PS сначала проапгрейдился из проги, когда она сама "выгрузилась", установил из архива. даже из архива не помогло, тогда выяснил что виной был файл настроек. (в принципе можно ничего не делать. настроек не много. главное знать как все апустить после апгрейда. :) )

Вы сами примите решение, закрывать эту ишу сразу, или "похоронить" время и разобраться почему упало. 

дополнение. 
падает из за чего то в [Functions] (взял свой ini, заменил все кроме [Functions] и все заработало. 
сейчас вычислю на чем упало.

дополнение. 
причина была в UseJKL=False

**Comment by BladeMight** [comment]
Как не видно, у меня видно:
![2019 01 03 - 07 39 14_rect](https://user-images.githubusercontent.com/11931888/50624646-f0880580-0f2a-11e9-8b8b-fb18f5a35156.jpg)

Может с 2.8.0.0 обновление не отображается, но в 2.9.0.0 я это исправил, а с 2 ошибкой тоже исправил уже в b94b9ed.

**Comment by AlexTransit** [comment]
хорошо. меня то это не парит. :) я установил и вычислил почему не работало.
но не все могут подобное. вот и написал. 
PS проверил обнорвления. - показывает нормально. до этого была версия вроде 2.8.2 и в ней не показывало.
спасибо.

**Comment by BladeMight** [comment]
> но не все могут подобное. вот и написал

Да, за это очень благодарю. Существенно облегчаешь мне поиск причины :) :+1:
