### ISSUE TITLE
Проверка орфографических и грамматических ошибок

### ISSUE THREAD

**Issue by EvolutionPixG** [BladeMight/Mahou#227]
Интересен такой вопрос есть ли планы на добавления сервиса проверки орфографических и грамматических ошибок в Mahou?
Данный функционал был бы полезен всем кому нужно быстро проверить текст на ошибки в нем(и для повседневного пользования тоже было бы очень даже нужно).
Данный функционал можно реализовать подобным образом как переводчик в Mahou.

**Comment by BladeMight** [comment]
Ну с переводчиком пока есть проблемы(_я уже давно думаю как сделать чтобы постоянно работал, но пока работает не постоянно, после 10-20 раз использования не работает_), а вот с проверкой - она должна работать в **ДРУГИХ ПРИЛОЖЕНИЯХ**, да? 

Если так что будет оч. не просто, нужно будет придумывать что будет отображать `неправильное` написание, т.е. `извилистое подчеркивание` под словом, его можно реализовать используя функционал "подсказка языка для каретки", а в памяти Mahou хранить последнее введенное слово, и по нажатию на пробел проверять его и выводить `извилистую линию`(т.е. `подсказка неправильного слова`) если неправильная орфогр., но такой способ будет работать только с последним словом, да и сама `извилистая линия` будет `как подсказка языка`, и ее расположение может быть не там где нужно(нужно будет делать правила её позиции для разных приложений/Windows/Тем). А можно вообще просто сделать проверку орфогр. только последнего слова, т.е. ввел слово -> пробел -> если неправ. орфогр. показать подсказку неправ. орфогр..

Насчет того чтобы проверять орфографию глобально, т.е. всего текста, можно сделать окошко которое можно будет вызвать гор. клавишей или из трея, а в него ставить текст, и там еще будет кнопка проверить и галочка "авто-проверять при вставке", потом сама проверка и "извилистые линии" на словах с неправильной орфогр.. Или даже гор. клавишу проверки орфогр. выделенного текста, а результат выводить в этом "окно орфографии" или добавить к каждому слову с неправ. орфограф. пользовательский символ вроде `*`, пример:

> Этат текст выдилите и проверьте на орфаграфийу.

После проверки:

> *Этат текст *выдилите и проверьте на *орфаграфийу.

и в окне Mahou:


> ~~Этат~~ текст ~~выдилите~~ и проверьте на ~~орфаграфийу~~.

А вот со словарём проверки, нужно будет составить все слова с правильной орфографией... Или написать правила для проверки правильности.... Но _я думаю что словарь будет получше_, т.к. меньше ошибок, ведь слова уже правильные, хотя и будут брать намного больше чем правила.


В общем всё можно сделать, но как всегда **нужно время**....

**Comment by EvolutionPixels** [comment]
> она должна работать в ДРУГИХ ПРИЛОЖЕНИЯХ, да?
И да и нет. Можно реализовать проверку для поля ввода текста в любой программе(кроме поля ввода в играх). А можно просто как вы уже написали в отдельном окне. И тот и другой вариант хороший.

Буду ждать реализации проверки орфографии от вас в Mahou(по сложности реализации проверку орфографии будет сделать не сложнее чем у вас реализован переводчик).

**Comment by EvolutionPixels** [comment]
> изменить текстовую форму другой программы - не получиться(так просто), а нарисовать подсказку поверх(как подсказка языка у каретки) - это не требует модификации формы другой программы

В таком случае лучшим вариантом будет вывод в отдельном окне. Там уже можно обработать весь тот текст что был выделен.

Повторюсь:
> можно просто как вы уже написали в отдельном окне(выделил текст в любом поле ввода, нажал определенную комбинацию клавиш(например Ctrl+Shift+O) и текст проверяется на орфографию в отдельном окне)

**Comment by BladeMight** [comment]
Ну да, думаю в отдельном окне будет лучше всего.

**Comment by veb86** [comment]
Я думаю создание отдельного окна с проверкой орфографии, а еще и с правилами, аналог ворда. Так же с возможностью правой кнопкой выбрать правильную замену слова. Это было бы просто супер!!!
Только надо что бы была возможность добавить в окно целые абзацы (используя выделение и горячую клавишу), что бы проверку можно было выполнить на большом участке. Кнопку скопировать все, что бы быстро вставить текст на замену. 

Так же было бы здорово если при вводе программа так же позволяла определить правильность написания последнего слова. Я думаю что отлавливать места ввода, и подчеркивания текста было бы очень здорово, но я это вижу очень сложным. В качестве простого решения предлагаю использовать всплывающие сообщение над часами, с ошибкой слова и вариантами правильного его написания, такой вариант гораздо проще реализовать и позволит быстрее получать удовольствие от использования.

**Comment by EvolutionPixG** [comment]
Есть какие-то успехи в создании функционала проверки орфографии и грамматических ошибок(анализ текста при вводе или по комбинации клавиш)?

**Comment by BladeMight** [comment]
Я делал пару тестовых сборок с стандартным .Net'овской проверкой орфографии и доп. словарями, но работало ужасно медленно... Так что я пока забросил. Нужно найти какой-то другой способ проверки/отрисовки, или *делать самому*...
может SciNet? Проверил, отлично работает, но вот теперь проблема в словарях..............
[SciNet.zip](https://github.com/BladeMight/Mahou/files/4016159/SciNet.zip)

**Comment by EvolutionPixG** [comment]
> 
> 
> Я делал пару тестовых сборок с стандартным .Net'овской проверкой орфографии и доп. словарями, но работало ужасно медленно... Так что я пока забросил. Нужно найти какой-то другой способ проверки/отрисовки, или _делать самому_...
> может SciNet? Проверил, отлично работает, но вот теперь проблема в словарях..............
> [SciNet.zip](https://github.com/BladeMight/Mahou/files/4016159/SciNet.zip)

Ясно. Я уж думал вы забыли про данный issue(много времени прошло в тишине).
Хорошо что не забросили реализацию. Буду ждать дальнейшего продвижения реализации проверки.
