### ISSUE TITLE
Не ловить нажатие Ctrl и подобных, если нажата другая клавиша

### ISSUE THREAD

**Issue by Mercury13** [BladeMight/Mahou#228]
## Problem/Request description

У меня три раскладки, нормальная полноразмерная клава и миниклавиатура Rii i8 (имеет один Shift, один Ctrl и два Alt). Как ни крути, одну из раскладок на Rii придётся включать системной кнопкой. И эта самая кнопка не действует, если пересекается с горячими клавишами Mahou. 

1. Поставить две раскладки, например, на Ctrl и AltGr.
2. Нажать и удерживать AltGr.
3. Нажать Ctrl.
4. Отпустить AltGr.

## Expected behavior (Only if reporting bug)

ДОЛЖНО: ничего не делается.
ПРОИСХОДИТ: одно переключение при отпускании Ctrl, и второе при отпускании AltGr.

## System information

- Windows version: 7
- Windows architecture: x64
- .Net version: 4.7
- Mahou version: 2.9.0.0

**Comment by BladeMight** [comment]
@Mercury13 Добавил исправление в 922296f, можешь проверять в [latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit).

**Comment by Mercury13** [comment]
Частично работает: реализовано только для AltGr, но не для других (например, Ctrl). Для Shift → Ctrl работает, а для Ctrl → Shift — нет.

**Comment by BladeMight** [comment]
@Mercury13 Я делал правило для всех клавиш, так чтобы если перед нажатием клавиши была нажата другая - ничего не делать.
У меня Ctrl → Shift — да.

**Comment by Mercury13** [comment]
Скорее всего, Ctrl → Shift — это уже другая моя ошибка: в программу не передаётся нажатие Ctrl и подобных. Так что считаем, что решено.
