### ISSUE TITLE
Перестали работать горячие клавиши с Ctrl/AltGr

### ISSUE THREAD

**Issue by Mercury13** [BladeMight/Mahou#229]
![mahou bug](https://user-images.githubusercontent.com/10164882/53942240-ea490d80-40c2-11e9-8cb9-4b8380413c34.png)

Если с Ctrl — хотелка, то эта ошибка — уже серьёзно и бросает тень на юзабельность Mahou,

## Problem/Request description

1. Включить галку «Переключать раскладки по клавишам».
2. Переключиться в браузер, нажать Ctrl+T.
3. Переключиться в любую программу, работающую с текстом, нажать любую клавишу с AltGr.

## Expected behavior (Only if reporting bug)

РЕАЛЬНО: компьютер ведёт себя, как будто я нажал T и клавишу без AltGr.
ТРЕБУЕТСЯ: браузер открывает новую вкладку, клавиша с AltGr печатается.

## System information

- Windows version: 7
- Windows architecture: x64
- .Net version: 4.7
- Mahou version: 2.9.0.0

**Comment by BladeMight** [comment]
> ТРЕБУЕТСЯ: браузер открывает новую вкладку, клавиша с AltGr печатается

Хм. у меня так и работает, попробуй в [latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit).

**Comment by BladeMight** [comment]
в Mahou стоит Ctrl на "переключение между раскладками" и Ctrl+T в Сhrome работает:

![mahou ctrl t](https://user-images.githubusercontent.com/11931888/53945256-e371c900-40c9-11e9-800f-3ab121136e98.gif)

**Comment by Mercury13** [comment]
Повторяется и в последнем коммите.

**Comment by Mercury13** [comment]
> P.S. Не стоят ли в типе "назначить гор. клавишу" эти клавиши?

Что значит «в типе», уточни как постороннему…

**Comment by BladeMight** [comment]
Тут поменяй: 
![53942240-ea490d80-40c2-11e9-8cb9-4b8380413c34](https://user-images.githubusercontent.com/11931888/53958168-f8aa2000-40e8-11e9-8ed3-8d2b384db54e.png)
И внизу появится "новый метод" назначения для типа "назначить гор. клавишу".

**Comment by Mercury13** [comment]
Ура, решено!

**Comment by BladeMight** [comment]
@Mercury13 Серьезно? Поделись как для тех кому может быть будет интересно в будущем.

**Comment by Mercury13** [comment]
В «Назначить горячую клавишу» действительно стояло Ctrl+Ctrl.
