### ISSUE TITLE
[BUG?] Подвисание при convert selection

### ISSUE THREAD

**Issue by qfeuer** [BladeMight/Mahou#23]
Доброго дня.

С начала 1.1.3 и далее есть серьёзный глюк, воспроизводимый мной на обоих моих ПК, при нажатии pause - которая привязана на convert & convert selection - если ничего не выделено то весь windows висит, на экран поступает только половина от fps герцовки монитора, то есть 30кадров на 60 гц мониторе и 72 фпс на 144 гц мониторе. это не связано с xbox dvr application, так как у меня нет 1607 обновления, и самим приложением я не пользуюсь.

зависание происходит на 7-8 секунд, затем всё восстанавливается, но слово не конвертируется, а если в это время находиться в браузере то начинается вызов хоткеев по открытию новых вкладок и что-то ещё, точно не могу сказать, так как всё происходит быстро, да и перехватчика у меня нет (если у Вас есть на примете, можете порекомендовать ? для более содержательных отчётов)

Если во время 7-8 секунд зависания нажимать клавиши - то они так же не работают

опытным путём удалось выяснить, что если назначить convert selection на другую комбинацию - то глюк происходит именно при вызове convert selection, без выделенного текста. если текст выделить - то конвертация происходит в нормальном режиме.

пробовал включать\отключать CS-switch, Emu type, перезагрузку (0_0), и прочие важные и не очень попытки фикса.

Общее описание глюка: при вызове convert selection, в случае отсутствия выделенного текста, происходит полу-фриз системы.

текущее решение - отвязать convert от convert selection.

**Comment by BladeMight** [comment]
У меня тоже так, Я уже знаю в чем причина, сейчас исправлю...

**Comment by BladeMight** [comment]
[Вот](https://github.com/BladeMight/Mahou/releases/tag/v1.1.4.1) проверь.

**Comment by qfeuer** [comment]
работает спасибо., но лаг всё равно есть. теперь ~0.5 секунды. и внутренние симптомы остались внутри этого промежутка времени. но теперь это практически незаметно.

**Comment by BladeMight** [comment]
> работает спасибо., но лаг всё равно есть. теперь ~0.5 секунды.

Он(несколько попыток взять текст) нужен для [Outlook](https://github.com/BladeMight/Mahou/issues/20).

**Comment by BladeMight** [comment]
Думаю я добавлю функцию включения/выключения попыток, и установки их количества для `Конверт выделения`.

**Comment by BladeMight** [comment]
> Думаю я добавлю функцию включения/выключения попыток, и установки их количества для Конверт выделения.

Добавил в [Mahou-v1.1.5.0](https://github.com/BladeMight/Mahou/releases/tag/v1.1.5.0) если ее выключить то задержка должна стать минимальной.

**Comment by qfeuer** [comment]
Спасибо большое, теперь всё работает, в outlook 2016 тоже работает с отключенными попытками конвертации. Magic is real

**Comment by BladeMight** [comment]
Рад стараться!
