### ISSUE TITLE
Вылет при хитрых условиях

### ISSUE THREAD

**Issue by Mercury13** [BladeMight/Mahou#230]
## Problem/Request description

Если включить такое опции…
![mahou2](https://user-images.githubusercontent.com/10164882/53958569-0f04ab80-40ea-11e9-8f3f-ed1ebf201b44.png)

и нажать в окне настроек Ctrl, будет такой вылет…
![mahou3](https://user-images.githubusercontent.com/10164882/53958589-1cba3100-40ea-11e9-9aff-32add604225e.png)

## System information

- Windows version: 7
- Windows architecture: x64
- .Net version: 4.6
- Mahou version: 2.9.0.0 dev <922296f>

**Comment by BladeMight** [comment]
Ну тут понятно, Mahou - не может получать раскладку с окна "Mahou" поэтому и говорит что culture не может быть 0, сейчас сделаю исправление чтобы Mahou - не старался изменит раскладку в этой вкладке.

P.S. Оба типа клавиш работают **ВМЕСТЕ**, так что смотри где и что стоит.

**Comment by BladeMight** [comment]
Сделал в 366c15f.

**Comment by BladeMight** [comment]
@Mercury13 Еще как альтернатива можно включить "Эмулировать переключение раскладки" и эта ошибка не будет выводится. ->[wiki](https://github.com/BladeMight/Mahou/wiki)

**Comment by Mercury13** [comment]
Работает!
