### ISSUE TITLE
Ошибка компоновки в русской версии

### ISSUE THREAD

**Issue by Mercury13** [BladeMight/Mahou#231]
![mahou4](https://user-images.githubusercontent.com/10164882/54037349-9e7f8c80-41c6-11e9-9b29-d22dbcd41e89.png)

- Windows version: 10
- Windows architecture: x64
- .Net version: 4.7
- Mahou version: видно на картинке

**Comment by BladeMight** [comment]
@Mercury13 Было похожее: #181, видимо в W10 строки вкладок повыше...

**Comment by Mercury13** [comment]
Да, в 7 OK.

**Comment by BladeMight** [comment]
@Mercury13 В 5a71885, добавил исправление проверь: [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit)

**Comment by Mercury13** [comment]
В понедельник, 10-ка на работе. А то на двух компах из трёх уже заменил Punto на Mahou, остался только выездной ноут.
Интереса ради в понедельник ещё HiDPI проверю, посмотрим, что выйдет. А то у меня нормальное зрение и нет нигде мелких пикселей.

**Comment by Mercury13** [comment]
![mahou5](https://user-images.githubusercontent.com/10164882/54132379-ce27d200-441c-11e9-8993-45298767fc75.png)
Получилось!
