### ISSUE TITLE
Не работает клавиша AltGr под Windows 10 v19H1

### ISSUE THREAD

**Issue by Mercury13** [BladeMight/Mahou#235]
## Problem/Request description

Перебрался 7 → 10.
Все используемые раскладки (Бирман и украинская расширенная) используют RAlt как AltGr. 
Мини-клавиатура Rii i8 имеет один Shift, один Ctrl и два Alt. Так что хотелось бы использовать для переключения в том числе и AltGr.

![mahou1](https://user-images.githubusercontent.com/10164882/57809821-04603580-776f-11e9-9a83-a6d59f73f0ef.png)

Не работает!

## Expected behavior (Only if reporting bug)

Под 7-кой работало.

## System information

- Windows version: 10
- Windows architecture: x64
- .Net version: 4.8.03752
- Mahou version: 2.9.0.0-dev <366c15f>

**Comment by BladeMight** [comment]
Ну вообще `AltGr === CTRL + ALT`, как говорят [здесь](https://stackoverflow.com/questions/17857404/why-does-alt-gr-have-the-same-keycode-as-ctrl), так что можешь попробовать сам настроить его через "Тип клавиш": "Назначить клавишу":
![2019 05 16 - 01'54'10_rect](https://user-images.githubusercontent.com/11931888/57814877-c8809c80-777d-11e9-9e93-1bf2e8adeba3.jpg)
потом появиться "другой" способ выбора клавиш для смены раскладки:
![2019 05 16 - 01'55'42_rect](https://user-images.githubusercontent.com/11931888/57814916-f1a12d00-777d-11e9-9771-504641670a5f.jpg)
Там можно настроить любую клавишу/комбинацию, потом применить и пробуй. И не забывай ЧТО ОБА МЕТОДА РАБОТАЮТ ВМЕСТЕ, так что смотри не вводи одинаковые клавиши для обоих методов, иначе получишь бесконечную смену раскладки.

**Comment by Mercury13** [comment]
Этот метод я пробовал. Клавиша AltGr перестаёт работать по прямому назначению — ввод спецсимволов.

**Comment by Mercury13** [comment]
Системе кажется, что прижат только Ctrl, без Alt.

**Comment by Mercury13** [comment]
И штука номер два. Реагирует не на отпускание клавиши, а на нажатие. Это значит, даже если всё заработает, раскладка будет переключена раньше, чем удастся ввести спецсимвол.

**Comment by BladeMight** [comment]
> Этот метод я пробовал

Что выводиться в месте горячей клавиши?

> Системе кажется, что прижат только Ctrl, без Alt.

А если настроишь на CTRL? Работает ли потом при нажатии/отпускании на AltGr?
И еще работает ли если настроить просто на RAlt? 

> И штука номер два. Реагирует не на отпускание клавиши, а на нажатие

Ну это проблематично... Ведь Mahou как раз обрабатывает все действия связанные с переключением раскладки на отпускании клавиш, именно потому что ты написал.

Можешь еще попробовать переназначить свою клавишу AltGr на другую, [здесь](https://stackoverflow.com/questions/229633/how-to-globally-map-altgr-key-to-alt-key).

**Comment by Mercury13** [comment]
> Что выводиться в месте горячей клавиши?

Ctrl+Alt+Alt
 
> А если настроишь на CTRL? Работает ли потом при нажатии/отпускании на AltGr?

Не работает.

> И еще работает ли если настроить просто на RAlt?

На рабочем работает. На домашнем вроде бы нет :(  Перепроверю.

> Ну это проблематично... Ведь Mahou как раз обрабатывает все действия связанные с переключением раскладки на отпускании клавиш, именно потому что ты написал.

«Выбирать клавиши» — на отпускание.
«Назначить горячую клавишу» — на нажатие.

> Можешь еще попробовать переназначить свою клавишу AltGr на другую, [здесь](https://stackoverflow.com/questions/229633/how-to-globally-map-altgr-key-to-alt-key).

Исчезает прямое назначение AltGr, ввод спецсимволов.

**Comment by Mercury13** [comment]
Но на работе версия 5A71885. Перекину домой, посмотрим.

**Comment by Mercury13** [comment]
А как вообще скачать свежую сборку?

**Comment by Mercury13** [comment]
Перенёс домой 5A71885. То же самое: на работе действует, а дома — нет.

**Comment by Mercury13** [comment]
Ещё разница в версиях: на работе 1809, дома 1901.

**Comment by Mercury13** [comment]
А эти самые Ctrl+Alt в список, обведённый красной рамкой, внести можно? Это должно решить вопрос.

**Comment by BladeMight** [comment]
Добавил пару правил для "AltGr" в списке, попробуй, должно заработать(т.к. у меня нет такой клавиши, проверить не могу) [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit)

**Comment by BladeMight** [comment]
Сделал небольшую программу для тестирования того как работает "нажатие" клавиши AltGr:
[klog.zip](https://github.com/BladeMight/Mahou/files/3192393/klog.zip)
Запускай klog.exe, нажми пару раз AltGr, и закрой. Программа сама сделает log.txt, отправь его мне и я посмотрю.

**Comment by Mercury13** [comment]
Рабочий комп.
```
Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[162], char=[] and name=[Ctrl] is pressed(SYS).
Code=[165], char=[] and name=[Alt] is pressed(SYS).
Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[165], char=[] and name=[Alt] is Pressed(NRM).
Code=[162], char=[] and name=[Ctrl] is pressed(SYS).
Code=[165], char=[] and name=[Alt] is pressed(SYS).
Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[165], char=[] and name=[Alt] is Pressed(NRM).
Code=[162], char=[] and name=[Ctrl] is pressed(SYS).
Code=[165], char=[] and name=[Alt] is pressed(SYS).
Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[165], char=[] and name=[Alt] is Pressed(NRM).
```

**Comment by Mercury13** [comment]
Ночью приду на домашний комп, посмотрим. В данном случае между Си и Си-диез нет принципиальной разницы, вы считаете? — я не в курсе, насколько напрямую вы обрабатываете кнопки.

**Comment by Mercury13** [comment]
На рабочем пока никаких изменений.

**Comment by Mercury13** [comment]
UPD. На рабочем компе обнаружилось одно изменение. Дело в том, что на рабочем компе работало только RAlt, но не AltGr. Сейчас оба. Дома не работало ни то, ни другое — так что, надеюсь, всё заработает.

**Comment by BladeMight** [comment]
> Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[165], char=[] and name=[Alt] is Pressed(NRM).
Code=[162], char=[] and name=[Ctrl] is pressed(SYS).
Code=[165], char=[] and name=[Alt] is pressed(SYS).

Странно она их нажимает двумя способами одновременно, используя и `WM_SYSKEYDOWN` и обычный `WM_KEYDOWN`, может быть в этом проблема, т.к. насколько я помню в Mahou я в основном для этой функции использовал только `WM_KEYDOWN`/`WM_KEYUP`, а `SYS` - используется только для спец-клавиш.

> Си и Си-диез нет принципиальной разницы, вы считаете? 

Ну вообщем разница есть, но в данном случае именно эти функции работают одинаково и там и там, но имеют странности со стабильностью в C#, т.е. сами просто перестают работать. Сама система Windows на C, а C# уже придумали позже, и функции(особенно те что связаны со сменой раскладки и слежением за вводом мыши/клавиатурой) всей системы лучше всего работают именно в C/C++. На C# нельзя сделать `WH_CALLWNDPROC`, хук который будет ловить все сообщения Windows, т.е. можно будет узнать когда изменилась раскладка, окно, активный элемент окна и т.п. В C# можно сделать только хуки для ловли мыши и клавиатуры, поэтому я и сделал дополнение к Mahou - JKL, программу которая следит за изменением раскладки и говорит об этом Mahou, через HWND сервер. Всё больше начинаю думать: "Может стоило сразу делать на C/C++?"

> я не в курсе, насколько напрямую вы обрабатываете кнопки.

`LowLevelHook` в C, `RawInputListener`/`LowLevelHook` в C#.

**Comment by Mercury13** [comment]
Домашний комп.
```
Code=[162], char=[] and name=[Ctrl] is pressed(SYS).
Code=[165], char=[] and name=[Alt] is pressed(SYS).
Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[165], char=[] and name=[Alt] is Pressed(NRM).
Code=[162], char=[] and name=[Ctrl] is pressed(SYS).
Code=[165], char=[] and name=[Alt] is pressed(SYS).
Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[165], char=[] and name=[Alt] is Pressed(NRM).
Code=[162], char=[] and name=[Ctrl] is pressed(SYS).
Code=[165], char=[] and name=[Alt] is pressed(SYS).
Code=[162], char=[] and name=[Ctrl] is Pressed(NRM).
Code=[165], char=[] and name=[Alt] is Pressed(NRM).
```

**Comment by Mercury13** [comment]
На домашнем всё ещё не работает, версия 93d3969.

**Comment by Mercury13** [comment]
Пока выяснилось, что причина — именно сборка Windows. Пока нет официальной майской версии, пусть будет так, но грядёт обнова, правильно?

**Comment by Mercury13** [comment]
Всё, 1903 вышла официально! Проверим.

**Comment by Mercury13** [comment]
Ну разумеется. Установилась сборка 1903, AltGr пропал.

**Comment by Mercury13** [comment]
Проще всего проверить на AltGr, установив раскладку клавиатуры «Украинская (расширенная)».
Думаю, есть ещё всякие там немецкие, французские и чешские, но не проверял.

**Comment by Mercury13** [comment]
Ах да. Если вы хотите разведать причины ошибки — до вашего хотфикса 93d3969 под Windows 10 v1809 работал только RAlt. С хотфиксом работают и RAlt, и AltGr.
В Windows 19H1 не работает ни то, ни другое, ни до хотфикса, ни после.

**Comment by Mercury13** [comment]
Я не стал проверять клавиатуру США (в своё время никак не мог от неё избавиться, появлялась и появлялась), но и в простой русской, и в простой украинской именно что AltGr и он не работает! Установил белорусскую — там RAlt, реакция на него нормальная,  разве что меню мигает. Не знаю, баг это или фича.

**Comment by Mercury13** [comment]
Автор, вы живы? Вопросу месяц, последнему комменту две недели, и я сумел уточнить, что виной всему новый выпуск W10.

**Comment by BladeMight** [comment]
@Mercury13 Жив я, жив. у меня есть предположение что в новой W10 начинают убирать функции которые Mahou использует для того чтобы например получить список раскладок, мне вот недавно присылали сообщение о том что Mahou постоянно пишет уведомление о "You have too less layouts" в трее, что говорит о том что у пользователя слишком раскладок(меньше 2), но в итоге оказывается что раскладок у него таки больше 1-ой... Выходит мне придется опять ставить в VM 10-ку и придумывать как с этим бороться, но если всё же они поубирали нужные функции, придется смириться с этим. Эх, не нравиться мне 10-ка, такая непредсказуемая... 
**OFFTOP:**
Вот Вам что собственно дал "новый выпуск W10"? - Можете не отвечать, вероятнее что-то что сидит в "процессах" и берет память, и пользователь этим так никогда и не пользуется...(только в первый раз, чтобы понять "а что это?")

**Comment by BladeMight** [comment]
Но всё же у меня появилась идея, сделал hotfix.

**Comment by Mercury13** [comment]
RAlt начало работать! Например, в стандартной английской раскладке — узнал, что она появляется с запуском Dota 2, видимо, дело в античите. А AltGr, который в английской Бирмана, стандартной русской и стандартной украинской — нет.

**Comment by Mercury13** [comment]
Выбор «AltGr» перестал реагировать на RAlt. Правда, и на AltGr реагировать не начал.

**Comment by BladeMight** [comment]
> Выбор «AltGr» перестал реагировать на RAlt. Хорошо это или плохо, ХЕЗ, но факт

ОК, понял, а если так, новый хотфикс.

**Comment by Mercury13** [comment]
Частично заработало.
Теперь RAlt реагирует на правый Alt и не на AltGr, а AltGr — на AltGr и не на правый Alt. Логично.
Но нажатия других клавиш не срывают переключение раскладок. Это несколько неудобно (хотим ввести спецсимвол, а получаем и спецсимвол и переключение), и напрочь уничтожает одну из фишек типографской раскладки Бирмана (и, вероятно, некоторых европейских раскладок) — ввод умляутов.
Чтобы ввести u с умляутом, надо на английской раскладке Бирмана нажать **AltGr+Shift+:**, после чего, **не нажимая ни на что другое и не переключая раскладку**, нажать **U**. Разумеется, это не выйдет, если переключается раскладка, даже с английского на английский.
Причём для обоих Ctrl и RShift всё в порядке — Mahou отличает одиночное нажатие от комбинации.

**Comment by Mercury13** [comment]
Поскольку AltGr — это Ctrl+Alt, попробовал выяснить, как Mahou ведёт себя на других парных комбинациях. Shift+Ctrl запустить никак не удалось. Shift+Caps Lock, Shift+Alt — вполне себе допускает посторонние кнопки

**Comment by BladeMight** [comment]
Вообще раскладка должна меняться только на "отпускании" клавиши, так что можно ввести символ пока держишь.
Для других модификаторов есть правило что если после нажатия модификатора нажмёться и отпуститься другая клавиша то не переключать раскладку. Здесь будет сложнее сделать такое правило т.к. AltGr = Ctrl+Alt = 2 клавиши, т.е. нужно будет ждать другую клавишу после их обоих.

**Comment by Mercury13** [comment]
Я же сказал, что полностью сорвалось и не работает: ввод некоторых монолитных умляутов состоит из нажатия двух клавиш. AltGr+Shift+:, затем U.

**Comment by BladeMight** [comment]
> AltGr+Shift+:, затем отпустить всё и нажать U.

Ооо? Так даже... Ну тут без вариантов...

**Comment by Mercury13** [comment]
Комбинирующий умляут ввести получилось: нажать U, затем AltGr+Shift+(дважды :)

**Comment by BladeMight** [comment]
Попробовал сделать сие правило:

> Для других модификаторов есть правило что если после нажатия модификатора нажмёться и отпуститься другая клавиша то не переключать раскладку

для AltGr, пока не знаю как будет работать... но нужно проверить.

**Comment by Mercury13** [comment]
Чем монолитный умляут лучше комбинирующего? Во-первых, монолитный свёрстан дизайнером и хорошо смотрится — а комбинирующий верстается типографским движком. Видели иногда такие штуки, что у буквы «й» шапочка куда-то поехала? Это кто-то (как я понял, Google Docs) заменяет монолитное «й» на «и» + комбинирующую кратку. Поэтому, если есть монолитный умляут с ударением, я пишу именно его, а не комбинирующий, даже если это семантически не очень верно. Везде, кроме Википедии, где просят именно комбинировать.
Во-вторых, из-за того, что кулхацкеры любят дестабилизировать типографские движки кучами комбинирующих умляутов, в веб-службах (Пикабу, скажем) умляуты иногда запрещают, а монолитные — нет.

**Comment by BladeMight** [comment]
Ага вот здесь их например много: https://stackoverflow.com/a/1732454/5420570
И в японском языке для некоторых символов добавляются кружок и полоски. Тоже как бы комбинируемо. 4412f08

**Comment by BladeMight** [comment]
Сделал небольшой тест на 4412f08, у меня 1 клавиши AltGr нету но я использовал Alt+Ctrl, при нажатии и отпускании раскладка меняется, при нажатии а потом вводе других клавиш раскладка - не меняется вот гифка(ScreenToGif):
![Mahou ALTGR](https://user-images.githubusercontent.com/11931888/59555538-c5ffa580-8fbc-11e9-93d8-50d320acb198.gif)

**Comment by Mercury13** [comment]
Монолитные: Mahou über alles, зáмок, а не замóк.
Комбинирующие: Mahou über alles, за́мок, а не замо́к.
Вроде работает!

**Comment by Mercury13** [comment]
Я посмотрел на свою писульку поближе. Для u с умляутом разницы особой не видно. А вот монолитное ударение больше и правее, и мне так больше нравится.

**Comment by BladeMight** [comment]
Да, есть отличие вида в ударении. Мне вот то что покороче нравится.
