### ISSUE TITLE
Show locale in mouse cursor

### ISSUE THREAD

**Issue by OleksandrKucherenko** [BladeMight/Mahou#24]
Hi,

is it possible to add feature "show current language in mouse cursor" like it done in [Aml mapper](http://amlpages.com/amlmaple.shtml) application.

idea behind the scene:
- hook mouse cursor change API calls, and in case of "caret" mouse pointer show own version of it

Thanks

**Comment by BladeMight** [comment]
I would try doing this in next release.

**Comment by BladeMight** [comment]
So how about [this](https://github.com/BladeMight/Mahou/releases/tag/v1.1.5.6)?

**Comment by OleksandrKucherenko** [comment]
Will test today

**Comment by OleksandrKucherenko** [comment]
Found issues:
- [ ] expected 2-chars for language "EN", "SE", "UA", "RU"
- [ ] bug, cursor displays only two languages (E, R), in system installed four: EN, SE, UA, RU
- [ ] expected half transparent colors selection, no alpha channel in color selection dialog :(
- [ ] will be super to apply simple alpha channel animation for cursor language (if no mouse move, language box disappears, on move - become stronger background color)
- [ ] language character displayed not in vertical center of the background rect...


My settings:
```
DLForeColor=Gray
DLBackColor=#E6E6E6
[TTipUI]
Height=14
Width=10
Font=Roboto Mono for Powerline, 8.25pt
xpos=8
ypos=-16
```

**Comment by OleksandrKucherenko** [comment]
![image](https://cloud.githubusercontent.com/assets/6419758/18563693/f6f76c5e-7b88-11e6-94c9-b04e98e47fd9.png)

**Comment by OleksandrKucherenko** [comment]
Great job! Thanks for updates!

**Comment by BladeMight** [comment]
> expected 2-chars for language "EN", "SE", "UA", "RU"

Increase the width of tooltip.

> bug, cursor displays only two languages (E, R), in system installed four: EN, SE, UA, RU

Will add more later.

> expected half transparent colors selection, no alpha channel in color selection dialog :(

I working on this, still...(yet it is impossible to do so, due to windows native transparency lack for label, or maybe i don't know something...)

> will be super to apply simple alpha channel animation for cursor language (if no mouse move, language box disappears, on move - become stronger background color)

Possible, but need to do first the one above.

>  language character displayed not in vertical center of the background rect...

Try increasing/decreasing height.

**Comment by OleksandrKucherenko** [comment]
With alpha channel, if i correctly remember, exist a workaround:
- layered windows + custom drawing
- https://support.microsoft.com/en-us/kb/318876

**Comment by OleksandrKucherenko** [comment]
For alpha transperency we in past use imagelist and drawing api

**Comment by BladeMight** [comment]
Thanks for info, I already know ho to do it now, wait next release.

**Comment by BladeMight** [comment]
The ClearType font aliasing causes problems:
![what happens](https://cloud.githubusercontent.com/assets/11931888/18606949/e18adefc-7cc6-11e6-8b93-0cf0fee73fd7.jpg)
but without it font looks crappy:
![or this](https://cloud.githubusercontent.com/assets/11931888/18606957/12003a5a-7cc7-11e6-9740-b2c0c80bafd0.jpg)
So should i add that feature to Mahou?

**Comment by BladeMight** [comment]
Maybe adding custom images with text? Then resizing will not be avaible...

> https://support.microsoft.com/en-us/kb/318876

My program doesn't replace cursor, it just draws text tooltip at it position.

**Comment by OleksandrKucherenko** [comment]
in past we solve issue with anti-aliasing and transparency by creating in-memory canvas (Image List). That we draw custom control/elements on it and use Image List for rendering the composed in-memory image on screen.

**Comment by OleksandrKucherenko** [comment]
http://www.codeproject.com/Articles/9142/Adding-and-using-bit-alphablended-images-and-ic

```
private static void Add( Bitmap bm, ImageList il )
{
    IntPtr hBitmap, ppvBits;
    BITMAPINFO bmi = new BITMAPINFO();
    if ( bm.Size != il.ImageSize )
    {
        // resize the image to dimensions of imagelist before adding
        bm = new Bitmap( bm, il.ImageSize.Width, il.ImageSize.Height );
    }
    bmi.biSize = 40;            // Needed for RtlMoveMemory()
    bmi.biBitCount = 32;        // Number of bits
    bmi.biPlanes = 1;           // Number of planes
    bmi.biWidth = bm.Width;     // Width of our new bitmap
    bmi.biHeight = bm.Height;   // Height of our new bitmap
    bm.RotateFlip( RotateFlipType.RotateNoneFlipY );
    // Required due to the way bitmap is copied and read

    hBitmap = CreateDIBSection( new IntPtr(0), bmi, 0, 
              out ppvBits, new IntPtr(0), 0 );
              //create our new bitmap
    BitmapData bitmapData = bm.LockBits( new Rectangle( 0, 0, 
               bm.Width, bm.Height ), ImageLockMode.ReadOnly, 
               PixelFormat.Format32bppArgb );
    RtlMoveMemory( ppvBits, bitmapData.Scan0, 
                   bm.Height * bitmapData.Stride );
                   // copies the bitmap
    bm.UnlockBits( bitmapData );
    ImageList_Add( il.Handle, hBitmap, new IntPtr(0) );
    // adds the new bitmap to the imagelist control
}
```

**Comment by BladeMight** [comment]
But that for images! My application draws text, will that work for text?

**Comment by OleksandrKucherenko** [comment]
You try to use control. Try to use custom drawing approach.

**Comment by BladeMight** [comment]
OK, i'll try it later.

**Comment by OleksandrKucherenko** [comment]
link with a solution - http://stackoverflow.com/questions/2991490/system-drawing-bad-text-rendering-using-drawstring-on-top-of-transparent-pixel

**Comment by BladeMight** [comment]
>link with a solution 

As i said before 

>font looks crappy

But i figured out that not all fonts looks so, for example:
Georgia looks ok:
![georgia](https://cloud.githubusercontent.com/assets/11931888/18961712/9940dc1e-8676-11e6-9d05-898b1c9ced87.png)
or Palatino Linotype:
![palatino](https://cloud.githubusercontent.com/assets/11931888/18961745/b528b0c8-8676-11e6-8221-8d69481a48dc.png)
So its up to font selection. Now i will add that feature to Mahou.

**Comment by BladeMight** [comment]
Here take a look at [Mahou-v1.3.1.0](https://github.com/BladeMight/Mahou/releases/tag/v1.3.1.0).
