### ISSUE TITLE
Включить по умолчанию "Считать пробел частью последнего слова"

### ISSUE THREAD

**Issue by palashman** [BladeMight/Mahou#243]
Здравствуйте!
Хотел бы предложить поставить по умолчанию галочку "Считать пробел частью последнего слова" (по поводу Enter не так остро). 
Я некое время полагал, что приложение просто это не умеет, и почти даже уже снёс его. Но после очередного (непростого, долгого, вдумчивого) изучения всех чекбоксов наконец-то нашёл эту фичу.
Думаю, что это важная опция и прежде чем юзер более менее освоится, хорошо бы ему облегчить жизнь. Что думаете?

**Comment by BladeMight** [comment]
@palashman Да, я уже тоже об этом думал... Очень многие спрашивают, как сделать то что делает эта функция. Начиная с 90e87ba, будет стоять по умолчанию.(<s>пока что только</s> в latest-commit версиях, а релиз версию <s>сделаю позже</s>  [Mahou-hotfix релиз](https://github.com/BladeMight/Mahou/releases/tag/v2.9.0.1))
