### ISSUE TITLE
just nothing happens .. ???

### ISSUE THREAD

**Issue by sharp-dev** [BladeMight/Mahou#245]
## Problem/Request description

subj

## Expected behavior (Only if reporting bug)

intuitively, I expect behavior, at least approximately similar to the "punto-switcher". but just nothing happens. none of the text editing programs or the console

## System information

- Windows version: Windows 10 1903 RU Pro (license, normal updates)
- Windows architecture: x64
- .Net version: 4.8
- Mahou version: Mahou-v2.9.0.1.zip

Or you can Paste here debug info from Mahou (version >1.4.4.1):

No debugging information, no errors. just no reaction to anything at all

## Attach logs (if logging were enabled)

I tried to use as a portable program. Alas, I do not see logs

PS I do not speak English. I apologize for the electronic transfer. perhaps not always successful. thank

**Comment by BladeMight** [comment]
Можно и по-русски.

Странно, как это? Прям вообще ничего, это как? В трее иконка появилась? Нажатие на неё отображает окно? **Запускали от админа?** Антивирус не *съел* Mahou.exe/jkl.exe/jkl_x86.exe/jkl.dll/jkl_x86.dll? Можешь сделать GIF?(ScreenToGif)
Еще попробуй [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit)(Release_x86_x64.zip)

**Comment by sharp-dev** [comment]
Можно тут ответить? Благодарю за отклик! ))

1 – иконка в трее есть. Скрин после запуска - https://i.imgur.com/6AEhJ5E.png

2 – клик по иконке, снчала выкидывает из приложения (сейчас это аутлук), потом открывает окно. Скрин окна (окно может выглядеть непривычно, но у меня масштабирование 125%, старенький уже, сори) - https://i.imgur.com/bEBr6Ns.png

3 – от админа не запускал. Полагаю это не совсем нормально. Кстати, давно слежу за вашим проектом. Но так, лениво )) вот подумал – может уже созрело? Меня смущали ранние отзывы о проблемах в скайпе. А по сути автопереключалка мне нужна именно в скайпе (метрошном), да еще Unigramm (метрошная телега). Они паталогически не помнят раскладку. Поясню – у меня стойкая привычка к режиму – каждому приложению своя раскладка, интерфейс русский, но дефолтная клава – US. Всю жизнь (мне 6й десяток) в ИТ ))) и извините за подробности не относящиеся прямо к сути проблемы )).. был еще проект до вашего.. не помню, я даже там предлагал правки кода (C#), парень из Украины. Позднее он открытым текстом писал, что ваш проект явно сильнее. Еще раз сори за избыточность

4 – антивирус ни чего не ел точно – папка программы, и контент скачанного архива почти совпадают. Скрин из Far, слева рабочая папка, справа архив - https://i.imgur.com/eY9zrY8.png

Я очень готов к тому, что делаю что то не верно. И сильно сомневаюсь, что в моей системе есть особенности (совсем недавно перезаливался, обычное дело для эксперементаторов) – винда, офис 2013 (коробочный, по тому все еще не обновляюсь), студия 2019 Community.. да почти все.. даже ShareX не всегда висит, только по необходимости. Ну разве что OneDrive, но это вроде стандарт для 10ки

Повторюсь – ни в аутлуке, ни в Notepad++, ни в студии, ни в консоли, попытки набрать слово/фразу, на языке противоположной раскладки, ни чего не происходит.

**Comment by sharp-dev** [comment]
OMG!!! я то думал в почту пишу ))

**Comment by sharp-dev** [comment]
OMG!!! я то думал в почту пишу ))

**Comment by BladeMight** [comment]
1. Так это хорошо.
2. ОК.

> Позднее он открытым текстом писал, что ваш проект явно сильнее. Еще раз сори за избыточность

Оо? Даже так? Приятно услышать.

А вот:

> Повторюсь – ни в аутлуке, ни в Notepad++, ни в студии, ни в консоли, попытки набрать слово/фразу, на языке противоположной раскладки, ни чего не происходит.

>автопереключалка

>  Поясню – у меня стойкая привычка к режиму – каждому приложению своя раскладка

> стандарт для 10ки

но ведь в 10ке вроде не стоит для каждого своё. Или ты сам настроил?


Может быть вся проблема в том что не переключает **автоматически**? По умолчанию только в ручную, по Pause(для последнего введенного слова)/Scroll(для выделенного), чтобы включить Автоматику, нужно включить "Автозамену":

1. Во вкладке "Сниппеты" включить сниппеты.(Автозамена использует этот движок для автозамен), применить.
2. В во вкладке "Автозамена" включить автозамену. Применить.
3. Нажать скачать словарь автозамен. дважды 1 - раз для проверки размера фала, второй раз именно скачивание, или можешь скачать с [репозитория](https://github.com/BladeMight/Mahou/blob/master/AS_dict.txt) и поставить рядом с Mahou.exe.

**Comment by BladeMight** [comment]
> OMG!!! я то думал в почту пишу ))

Ага, называется ["Почтовый ответ на GitHub"](https://github.blog/2011-03-10-reply-to-comments-from-email/).

**Comment by sharp-dev** [comment]
я практически готов закрыт инцидент - работает breack
но только на одно слово, при условии нажатия сразу

1 - я ожидал возможности автопереключения, осторожные попытки поиграть с настройками, пока ни чего не дают

2 - хотелось бы фичу "брейка" фразы/строки/абзаца .. по описаниям, мне казалось что это уже выполнено, но ни как не могу разобраться с клавиатурными комбинациями

**Comment by sharp-dev** [comment]
мнда, логин на джите давно, но.. все еще чайник ))

**Comment by sharp-dev** [comment]
> но ведь в 10ке вроде не стоит для каждого своё. Или ты сам настроил?
да, это старый и прочный бзик ))

**Comment by BladeMight** [comment]
> но только на одно слово, 

Есть функция конвертация Линии, по умолчанию на Shift+Pause

>при условии нажатия сразу

Есть функция: ["Считать пробел частью последнего слова"](#243) из-за многочисленных подобных вопросов я включил её по умолчанию.

**Comment by BladeMight** [comment]
> логин на джите

https://ttsmp3.com/created_mp3/a6a2286b25b7f33adc19531b10bc8ba7.mp3

**Comment by sharp-dev** [comment]
положительный побочный эффект - убираем и 10й дефольный индикатор ввода (бесит, когда переключаемся в RDP - весь трей прыгает ((( ), и олдскульную клавиатурную панель - чуток больше места на такбаре, нагляднее и предсказуемее поведение клавы ))
скрин трея - https://i.imgur.com/3sV6wWh.png

**Comment by sharp-dev** [comment]
ок. читаю и перевариваю..

**Comment by sharp-dev** [comment]
> https://ttsmp3.com/created_mp3/a6a2286b25b7f33adc19531b10bc8ba7.mp3

мне стыдно, но я не понял ))

остальное супер

**Comment by BladeMight** [comment]
> https://ttsmp3.com/created_mp3/a6a2286b25b7f33adc19531b10bc8ba7.mp3

Git is not JIT.

**Comment by sharp-dev** [comment]
получилось из серии - "читай инструкцию!" ))
простите за беспокойство! в остальном - супер! ))

эмм.. есть еще вопрос? можно тут?

я не разобрался с этими опциями (скрин) - https://i.imgur.com/BDTabQG.png
 правильно ли я понял, что можно настроить Mahou, на выбор раскладки для приложения?

у меня пока не получается ((
по сути всего 2 приложения, где я хотел бы автоматом иметь RU - скайп и телега (метрошные)

ps - в любой ситуации, при любом удобном случае, буду поддерживать ваше приложение, как альтернативу пунто-свичеру )))

**Comment by sharp-dev** [comment]
спсб )) (про Гит и Джит) ))

**Comment by BladeMight** [comment]
> правильно ли я понял, что можно настроить Mahou, на выбор раскладки для приложения

Да именно, **Постоянной** раскладки для приложения(-ий). Если включить "Менять 1 раз для окна", то раскладка будет меняться только при первой активации каждого окна приложения(-ий).

**Comment by sharp-dev** [comment]
пока не выходит ((
скрин параметров - https://i.imgur.com/7wdbPYU.png

**Comment by BladeMight** [comment]
>  меня пока не получается ((
по сути всего 2 приложения, где я хотел бы автоматом иметь RU - скайп и телега (метрошные)

Исполняемые файлы **точно** так называются? Посмотри в диспетчере/Process Hacker'е?
+ Вижу галочки не включены. Включи "Постоянная раскладка" для той что справа. И настрой "Раскладку №2" во вкладке раскладки.

**Comment by sharp-dev** [comment]
пробую
1 - https://i.imgur.com/iBb7bEW.png
2 - https://i.imgur.com/NzUVc0A.png + https://i.imgur.com/PXF4MBK.png
3 - https://i.imgur.com/KtYL3O5.png + https://i.imgur.com/olFAGpB.png

**Comment by sharp-dev** [comment]
сори, еще скрин https://i.imgur.com/c9QjqSb.png

что тут?

**Comment by BladeMight** [comment]
> что тут?

Полный наоборот:

> да, это старый и прочный бзик ))

Т.е. иметь на 7-ке одну раскладку во всех приложениях. [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#Единая-раскладка-для-всех-программ).

Попробуй на чём-то простом вроде `notepad.exe`, добавь его в правила(1 или 2 раскладки), настрой раскладку(ту куда добавил, если не уже настроил), открой notepad.exe, открой еще что-то. Переключись на блокнот пробуй менять раскладку, переключись на еще что-то, и назад на блокнот.

**Comment by sharp-dev** [comment]
?!!! так ? https://i.imgur.com/k9bDUY0.png

.. не сказал бы что очевидна логика.. но .. пробую, спасибо ))

**Comment by sharp-dev** [comment]
чет пока не очень ((

**Comment by BladeMight** [comment]
> ?!!! так ? https://i.imgur.com/k9bDUY0.png

Ну так как ты писал что тебе не нравится что приложения забывают свою раскладку - я думаю что тебе функцию "Единая раскладка для всех программ"

**Comment by BladeMight** [comment]
> https://i.imgur.com/k9bDUY0.png

Вижу у тебя Раскладки `#1` и `#2` - настроены. Теперь во вкладке "Постоянная раскладка" включи как тут: https://i.imgur.com/iBb7bEW.png и убери "менять 1 раз" и/или "менять когда меняются окна"([эффекты](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515699146)), применить. И проверяй, в этих программах  должна автоматически устанавливаться постоянно раскладка которую ты выбрал.

**Comment by BladeMight** [comment]
Смотри:
![mahou const layout](https://user-images.githubusercontent.com/11931888/61997564-f2bed680-b0ab-11e9-9d04-fdf1873c159d.gif)

**Comment by sharp-dev** [comment]
https://i.imgur.com/eDBMLPk.png или https://i.imgur.com/Gr4u8mP.png без разницы ((

**Comment by sharp-dev** [comment]
фуууххх.. ок. на седня хватит, сори. спасибо за потраченное время! ))
по крайней мере брейк слова/строки - несоизмеримо больше чем ни чего )))

**Comment by BladeMight** [comment]
Ладно, тогда включи "Включить журналирование действий" во вкладке функции(внизу), **применить**, по-переключайся между окнами Skype и Unigram, переключись обратно на Mahou, напротив галочки "Включить журналирование действий" есть "Открыть" нажми правой кнопкой, откроется папка с логами, кинь(прикрепить) лог с текущей датой сюда на GitHub.

**Comment by sharp-dev** [comment]
не не... седня релакс )) может потом

спасибо в любом случае! ))

**Comment by BladeMight** [comment]
Ну как знаешь...

**Comment by sharp-dev** [comment]
Еще раз благодарю за уделенное время!

1 - вроде как уловил идею с логгированием, но руки не дошли

2 - несколько раз пересмотрев анимашку про "постоянную раскладку", вроде как дошло, что именно "постоянная" то и не нужна. я думал можно сделать так сказать "другой дефолт" для избранных приложение. но точно не "постоянную", которую нельзя сменить. боже упаси )) я просто отключил все на вкладке "постоянная раскладка"

3 - заметил сначала на метрошных скайпе/юниграме, отдельно проверил на метрошных "заметках" - в целом Mahou вполне работает. но при первом РУЧНОМ переключении раскладки на русский (вынь-пробелом) он не меняет индикатор. если использовать разок другой переключение брейком (Mahou), индикация приходит в соответствие с раскладкой

4 - при переключении в метрошное приложение ВСЕГДА показывает US (системный дефолт) даже если приложение уже было запущено, и уже была выбрана раскладка RU. для восстановления правильно индикации, опять надо пару раз брейкнуть

в целом это жить не мешает. достаточно помнить об этой особенности. так как метрошных приложений всего три, где мне может потребоваться RU. ну может еще в "погоде" добавить город ))

напомню что у меня w10 1903, и особенность все таки есть - включены отдельные раскладки для разных приложений. возможно что такого побочного эффекта нет, когда раскладка единая для всех приложений.
________________________________
От: BladeMight <notifications@github.com>
Отправлено: 27 июля 2019 г. 21:27
Кому: BladeMight/Mahou <Mahou@noreply.github.com>
Копия: sharp-dev <sharp.dev@outlook.com>; State change <state_change@noreply.github.com>
Тема: Re: [BladeMight/Mahou] just nothing happens .. ??? (#245)


Ну как знаешь...

**Comment by sharp-dev** [comment]
любопытно, что последний ответ не отобразился обсуждении. это связано с закрытием issue?

если все таки вы получаете ответы (предыдущий и этот) могу предложить личный контакт?
скайп fissoft

гарантирую что не буду отвлекать попусту. посмотрю код (дотнет все таки, я с ним дружу с 2000). чему то подучусь, а может даже и возникнут предложения ))

исторически подготовка АСУ (неодоучка), но в итоге приличный кандидат в системные программисты. кем и удалось активно поработать в конце 80х. с середины 90х админ (МС и только МС) )).. и с 2000 возврат к кодингу, хотя в основном в фоне. шарш уж больно хорошо зашел ))
________________________________
От: BladeMight <notifications@github.com>
Отправлено: 27 июля 2019 г. 21:27
Кому: BladeMight/Mahou <Mahou@noreply.github.com>
Копия: sharp-dev <sharp.dev@outlook.com>; State change <state_change@noreply.github.com>
Тема: Re: [BladeMight/Mahou] just nothing happens .. ??? (#245)


Ну как знаешь...

**Comment by sharp-dev** [comment]
1 - проект о котором упоминал - https://github.com/kurumpa/dotSwitcher/releases

[https://avatars2.githubusercontent.com/u/1300401?s=400&v=4]<https://github.com/kurumpa/dotSwitcher/releases>
Releases · kurumpa/dotSwitcher · GitHub<https://github.com/kurumpa/dotSwitcher/releases>
Be notified of new releases. Create your free GitHub account today to subscribe to this repository for new releases and build software alongside 36 million developers.
github.com

2 - испытал шок столкнувшись с поведением капса.. вроде разобрался, но не сразу )) буду изучать настройки. ну и так как обычно капсом не пользуюсь - тоже достаточно запомнить

3 - выше была опечатка что то типа
шарш зашел
естественно означало
C# зашел
________________________________
От: BladeMight <notifications@github.com>
Отправлено: 27 июля 2019 г. 21:27
Кому: BladeMight/Mahou <Mahou@noreply.github.com>
Копия: sharp-dev <sharp.dev@outlook.com>; State change <state_change@noreply.github.com>
Тема: Re: [BladeMight/Mahou] just nothing happens .. ??? (#245)


Ну как знаешь...

**Comment by BladeMight** [comment]
> я думал можно сделать так сказать "другой дефолт" для избранных приложение

Правильно думал, можно. С функцией "Менять когда меняются окна", при активации окон указанных приложений раскладка смениться на ту в которой есть название исполняемого файла приложения.

> проект о котором упоминал

Знаю, если не читал мой пост на [habrhabr](https://habr.com/ru/post/321518/)... и [см1](https://github.com/kurumpa/dotSwitcher/issues/37#issuecomment-337849805) [см2](https://github.com/kurumpa/dotSwitcher/tree/dotSwitcherNew(MahouEngine)) [см3](https://habr.com/ru/post/324592/)

> при переключении в метрошное приложение ВСЕГДА показывает US

возбьму на заметку

**Comment by sharp-dev** [comment]
Правильно думал, можно
спсб! ща пакопаю настройки ))

при переключении в метрошное приложение ВСЕГДА показывает US

возбьму на заметку

напомню:
1 - у меня русский интерфейс, но дефолт US
2 - всегда включаю "каждому приложению своя раскладка"

возможно не так много пользователей это делает, по этому и не было фидбека
________________________________
От: BladeMight <notifications@github.com>
Отправлено: 29 июля 2019 г. 17:37
Кому: BladeMight/Mahou <Mahou@noreply.github.com>
Копия: sharp-dev <sharp.dev@outlook.com>; State change <state_change@noreply.github.com>
Тема: Re: [BladeMight/Mahou] just nothing happens .. ??? (#245)


я думал можно сделать так сказать "другой дефолт" для избранных приложение

Правильно думал, можно. С функцией "Менять когда меняются окна", при активации окон указанных приложений раскладка смениться на ту в которой есть название исполняемого файла приложения.

проект о котором упоминал

Знаю, если не читал мой пост на habrhabr<https://habr.com/ru/post/321518/>... и см1<https://github.com/kurumpa/dotSwitcher/issues/37#issuecomment-337849805> см2<https://github.com/kurumpa/dotSwitcher/tree/dotSwitcherNew(MahouEngine)> см3<https://habr.com/ru/post/324592/>

при переключении в метрошное приложение ВСЕГДА показывает US

возбьму на заметку

**Comment by sharp-dev** [comment]
Правильно думал, можно
так? https://i.imgur.com/gbAmAop.png
[https://i.imgur.com/gbAmAop.png]
увы, не работает. но может заморочка в метрошности приложений? (для которых я хочу RU дефолтом)
________________________________
От: Rybak Konstantin <sharp.dev@outlook.com>
Отправлено: 29 июля 2019 г. 18:09
Кому: BladeMight/Mahou <reply@reply.github.com>
Тема: RE: [BladeMight/Mahou] just nothing happens .. ??? (#245)

Правильно думал, можно
спсб! ща пакопаю настройки ))

при переключении в метрошное приложение ВСЕГДА показывает US

возбьму на заметку

напомню:
1 - у меня русский интерфейс, но дефолт US
2 - всегда включаю "каждому приложению своя раскладка"

возможно не так много пользователей это делает, по этому и не было фидбека
________________________________
От: BladeMight <notifications@github.com>
Отправлено: 29 июля 2019 г. 17:37
Кому: BladeMight/Mahou <Mahou@noreply.github.com>
Копия: sharp-dev <sharp.dev@outlook.com>; State change <state_change@noreply.github.com>
Тема: Re: [BladeMight/Mahou] just nothing happens .. ??? (#245)


я думал можно сделать так сказать "другой дефолт" для избранных приложение

Правильно думал, можно. С функцией "Менять когда меняются окна", при активации окон указанных приложений раскладка смениться на ту в которой есть название исполняемого файла приложения.

проект о котором упоминал

Знаю, если не читал мой пост на habrhabr<https://habr.com/ru/post/321518/>... и см1<https://github.com/kurumpa/dotSwitcher/issues/37#issuecomment-337849805> см2<https://github.com/kurumpa/dotSwitcher/tree/dotSwitcherNew(MahouEngine)> см3<https://habr.com/ru/post/324592/>

при переключении в метрошное приложение ВСЕГДА показывает US

возбьму на заметку

**Comment by BladeMight** [comment]
>так? https://i.imgur.com/gbAmAop.png

Нет, но почти - галочка "Постоянная раскладка"(для желаемой раскладки - должна стоять, ведь эта функция - дополнение изменяющие поведение функции "Постоянная раскладка"...

> при переключении в метрошное приложение ВСЕГДА показывает US

> может заморочка в метрошности приложений?

Может при активации Метро приложений язык неправильно достаётся. Или может сама функция "каждому приложению своя раскладка" не влияет на метро?(увы я не использую windows 10, так что проверить сам не смогу...)

**Comment by BladeMight** [comment]
P.S. Заходи на GitHub(а не через почту...), иначе не заметишь изменений в моих постах... (и рекомендую перечитать всю тему)

**Comment by sharp-dev** [comment]
Там нет возможности добавить сообщение. Вероятно по тому что issue закрыт, но я не спец по git ))
И по моим наблюдениям, в почте полный дубликат. По крайней мере твоих ответов точно.

И еще раз спасибо за потраченное время ))

**Comment by BladeMight** [comment]
> Вероятно по тому что issue закрыт

Может ты просто не зашел(Login)? Вот я зашел на случайный закрытый issue в другом проекте и могу написать:
![2019 07 29 - 19'06'34_rect](https://user-images.githubusercontent.com/11931888/62063848-5bd15600-b234-11e9-8d2f-ef4b2349a5e2.jpg)

> И по моим наблюдениям, в почте полный дубликат 

А вот и нет, вот все сообщения которые я изменял(а после изменения изменения видны только здесь!):

[245#issuecomment-515696282](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515696282)
[245#issuecomment-515696762](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515696762)
[245#issuecomment-515698156](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515698156)
[245#issuecomment-515698370](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515698370)
[245#issuecomment-515699146](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515699146)
[245#issuecomment-515699650](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515699650)
[245#issuecomment-515700212](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515700212)
[245#issuecomment-515994680](https://github.com/BladeMight/Mahou/issues/245#issuecomment-515994680)
[245#issuecomment-516046970](https://github.com/BladeMight/Mahou/issues/245#issuecomment-516046970)

**Comment by sharp-dev** [comment]
Читать в одном месте, писать в другом – не айс..

И если не примешь скайп – затру сообщение )))

**Comment by BladeMight** [comment]
> скайп  

не пользуюсь

**Comment by BladeMight** [comment]
> Читать в одном месте, писать в другом – не айс..

Когда на почту приходит, заходи сюда и пиши и читай здесь.

**Comment by sharp-dev** [comment]
ок
1 - еще одна особенность - использую много профилей браузеров )) и да, у FF в памяти есть, но (собака) автоматически не залогинился ((
2 - вроде все перечитал..
3 - что то еще было.. конкретное.. пшел перечитывать

**Comment by BladeMight** [comment]
> использую много профилей браузеров

Можно просто [cookieprofileswitcher](https://addons.mozilla.org/ru/firefox/addon/cookieprofileswitcher/), если не обращать внимание на то что история будет общей.

**Comment by sharp-dev** [comment]
3 - торможу, сори ))..
единая раскладка не катит. ну сам посуди VS, консоль, (и до одури всего).. и тут телега и скайп.. ну иногда еще аутлук и ворд (но на столько реже, что не жмет/не трет/не чешется)

**Comment by sharp-dev** [comment]
> если не обращать внимание на то что история будет общей

вот это сразу мимо, профили для жесткого разделения )) ... просто давно не логинился в том же профиле, где основная почта по дефолту )).. FF (собака) помнит, но не торопиться прогнуться.. хотя может по нынешним временам это и логично ))

**Comment by BladeMight** [comment]
> вот это сразу мимо, профили для жесткого разделения

ОК, понятно.

**Comment by sharp-dev** [comment]
даже FF по двум причинам - простота многопрофильности с командной строки + ленивые вкладки (не грузит стопятсот вкладок прошлого сеанса при старте)..
.. пробовал вивальди - вроде все тоже самое.. но сыро, сыро, сыро... а сам все ни как не запилю ))) CEF# же под рукой ))

**Comment by sharp-dev** [comment]
могу попробовать подебажить что там с метрошными приладами.. но.. сам понимаешь )).. я в том возрасте, когда между словом и делом, могут пройти годы.. или вовсе остаться слова, сори ))

**Comment by BladeMight** [comment]
> ленивые вкладки

Знаю, в FF это еще с давних времён... Ну я лично пользуюсь CentBrowser, в нём тоже неплохо реализировано.

**Comment by BladeMight** [comment]
> могу попробовать подебажить что там с метрошными приладами

В общем то всё что нужно https://github.com/BladeMight/Mahou/issues/245#issuecomment-515700503

**Comment by sharp-dev** [comment]
ок ))
но я могу и по коду походить ))
я же шарпист, фан ))

**Comment by sharp-dev** [comment]
оппа !! CentBrowser - "ленивые вкладки есть"? ))

в смысле 50 вкладок с прошлого сеанса, при старте грузим только выбранную.. остальные только при переключении

**Comment by sharp-dev** [comment]
сори.. сам покопаю уже ))

**Comment by BladeMight** [comment]
Ну можешь конечно, но наверно ничего не поймешь с моей то логикой и кодом... Ну идея в том чтобы узнать что про то что происходит т.е. какая раскладка, какое название процесса и т.д.

> оппа !! CentBrowser - "ленивые вкладки есть"? ))

Ага:
![2019 07 29 - 19'34'00_rect](https://user-images.githubusercontent.com/11931888/62065668-23337b80-b238-11e9-8b7a-d9fd259e995a.jpg)

**Comment by sharp-dev** [comment]
> Ну можешь конечно, но наверно ничего не поймешь с моей то логикой и кодом...

последние белее менее "проекты":
- перевод с плюсов на шарп, склейку панорамы, с предварительной нарезкой на полосы (в общем ИИ контроля лесовозов - кубатура, на основе OpenCV)
- 8 месяцев работы.. с профессиональным игроком... эмм .. тут публик все таки ))).. в общем бот над супе умной виндовой программой, но не на хендлах.. прога на QT )))... граб со скрина, распознавание -> логика .. ;)

**Comment by BladeMight** [comment]
:) Ну, ИИ с точность OpenCV - сложно настраивать...
А QT тоже имеют свои хуки, как и Win32-шники, так что особой разницы - нет, просто API знать...

**Comment by BladeMight** [comment]
> драйвера клавиатуры под DOS*.*

А на *nix?

**Comment by sharp-dev** [comment]
эмм.. исходный код был закрыт, но возможно я и правда ломился "с топором" ))

**Comment by sharp-dev** [comment]
не. лет 5 пользовательского ознакомления (обучаемость уже не та).. (ну или мотивации нет)

**Comment by BladeMight** [comment]
ясно, интересно просто стало...

**Comment by sharp-dev** [comment]
хотя жизнь в консоли то с молодости - норма ))
компиляция в командной строке...
.. но VS круто подсаживает ))

**Comment by sharp-dev** [comment]
ну.. что еще забавно - экспериментальный поток обучения (всего 1 год программы, потом поменялась) с 1 сентября 1 курса - ASM

**Comment by BladeMight** [comment]
> жизнь в консоли

Понимаю, сам почти постоянно в "терминале"(mintty/conemu).

**Comment by sharp-dev** [comment]
извини, если избыточно ))

**Comment by BladeMight** [comment]
нормально.

**Comment by sharp-dev** [comment]
ща смотрю на нейронки и на крипту ))

надо что то лепить на старость (взрослая жизнь пришлась на смутное время в стране )).. сейчас ни на работу ни кто не берет (хотя стажировался с НЕ нулевым успехом на .Net Core bakcend).. и ни каких перспектив на.. лан, тут не о грустном ))

**Comment by BladeMight** [comment]
Всякое может быть...

**Comment by sharp-dev** [comment]
хм.. centbro, возможно НЕ меньший подарок, чем Mahou! )))
