### ISSUE TITLE
Ошибка обновления за фаерволом

### ISSUE THREAD

**Issue by vicodin77** [BladeMight/Mahou#25]
Доброго дня!
При попытке обновиться, выскакивает такая ошибка.
![image](https://cloud.githubusercontent.com/assets/16464189/18428752/6edb6a4e-78d8-11e6-8a1b-83dfeed8b8ac.png)

Полный текст ошибки:
--------------------------
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Mahou.Update.flVersion(String ver)
   в Mahou.Update.Update_VisibleChanged(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   в System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   в System.Windows.Forms.Form.OnVisibleChanged(EventArgs e)
   в System.Windows.Forms.Control.WmShowWindow(Message& m)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   в System.Windows.Forms.Form.WmShowWindow(Message& m)
   в System.Windows.Forms.Form.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

Mahou

PS: сижу за корпаративным фаерволом, Win7

**Comment by BladeMight** [comment]
Ок, сейчас исправлю.

**Comment by BladeMight** [comment]
А можно по подробнее, как у вас получилось это сделать?

**Comment by vicodin77** [comment]
Просто нажимаю кнопку "Обновить"!)

**Comment by BladeMight** [comment]
В главном окне?

**Comment by BladeMight** [comment]
Случайно закрыл :)

**Comment by vicodin77** [comment]
Да.

**Comment by BladeMight** [comment]
Видимо файрвол блокирует подключение...
Вот попробуй, 
[MahouBETA.zip](https://github.com/BladeMight/Mahou/files/466833/MahouBETA.zip) как здесь работает?

**Comment by vicodin77** [comment]
Тоже самое!

**Comment by BladeMight** [comment]
[Вот версия с консолью](https://github.com/BladeMight/Mahou/files/466879/MahouCONSOLETESING.zip), при нажатии обновить что пишет в консоли?

**Comment by vicodin77** [comment]
![image](https://cloud.githubusercontent.com/assets/16464189/18429748/d5a02c74-78dd-11e6-8d77-9b47ec1e434b.png)

**Comment by BladeMight** [comment]
Ну вот как я говорил, файрвол блокирует подключение к github...

**Comment by vicodin77** [comment]
Может ввести настройки фаервола и юзать их? Или использовать настройки фаервола сисчтемы... Хром то нормально ходит на гитхаб...

**Comment by BladeMight** [comment]
Думаю надо разрешить Mahou в файре, и еще попробуй с отключенным(если можешь).

**Comment by vicodin77** [comment]
Блин, ошибся! Не фаер, а прокся!!!)))

**Comment by vicodin77** [comment]
А фаер отключить не могу - правов не хватает!)))

**Comment by BladeMight** [comment]
[Вот сборка](https://github.com/BladeMight/Mahou/files/466897/Mahou-NO-HANG.zip) в которой вылетать не должно.

**Comment by vicodin77** [comment]
Да, теперь не вылетает, но и не цепляется к гитхабу... Прокся не используется при соединении?

**Comment by BladeMight** [comment]
> Прокся не используется при соединении?

Наверно как раз наоборот, т.к. у меня получилось повторить ошибку с не рабочей проксей, без нее работает...

**Comment by BladeMight** [comment]
Аааа! Понял прокси должен быть HTTPS т.к. GitHub HTTPS! Или выключите использование одного прокси для HTTPS/FTP.

**Comment by BladeMight** [comment]
![proxy edit](https://cloud.githubusercontent.com/assets/11931888/18430468/53eafe58-78e1-11e6-8256-8758919315bf.png)

**Comment by BladeMight** [comment]
![proxy edit](https://cloud.githubusercontent.com/assets/11931888/18430518/8ffa2b76-78e1-11e6-8719-70c2ba7edaf6.jpg)

**Comment by vicodin77** [comment]
Если уберу, то меня вобче ни куда не пустит!))

**Comment by BladeMight** [comment]
Ну тогда прокси должен быть HTTPS.

**Comment by BladeMight** [comment]
Вот например 213.136.65.138 порт 3128  работает.

**Comment by BladeMight** [comment]
Или если нужен анонимный 212.227.159.39 порт 80. Беру их [здесь](http://spys.ru/).

**Comment by vicodin77** [comment]
У меня корпоративный прокси и https поддерживает. И выход в инет тока через него!

**Comment by BladeMight** [comment]
Ну не знаю, значит в ручную придется обновляться...

**Comment by vicodin77** [comment]
Я сейчас так и делаю!) Странно, что хром нормально ходит по https к гитхабу...

**Comment by BladeMight** [comment]
А как насчет других программ?(Менеджер загрузок, онлайн плеер или еще что-то?)

**Comment by vicodin77** [comment]
download master точно работает при указании у него в настройках прокси!

**Comment by BladeMight** [comment]
Ну тогда я тоже попробую добавить опцию настройки прокси.

**Comment by vicodin77** [comment]
Только что глянул! О как:
![image](https://cloud.githubusercontent.com/assets/16464189/18433061/348da30a-78ee-11e6-9d04-19555dda5b49.png)

**Comment by BladeMight** [comment]
Что значит он использует системный прокси. Думаю смогу тоже так сделать.

**Comment by vicodin77** [comment]
Было бы очень здорово! Буду ждать!

**Comment by BladeMight** [comment]
Нука попробуй этот:
[MahouDefaultProxy.zip](https://github.com/BladeMight/Mahou/files/467109/MahouDefaultProxy.zip)

**Comment by BladeMight** [comment]
И еще эту сборку [MahouForceNoProxy.zip](https://github.com/BladeMight/Mahou/files/467113/MahouForceNoProxy.zip)

**Comment by vicodin77** [comment]
Оба, увы, с таким же результатом...

**Comment by BladeMight** [comment]
А используется ли Логин/Пароль у прокси?

**Comment by vicodin77** [comment]
Под виндой используется NTLM-авторизация, а под никсами надо явно указывать доменные имя и пароль!

**Comment by BladeMight** [comment]
Ясно, сейчас приделаю выбор прокси.

**Comment by BladeMight** [comment]
Вот по-быстрому для теста сделал:
[MahouProxyConf.zip](https://github.com/BladeMight/Mahou/files/467141/MahouProxyConf.zip)

**Comment by vicodin77** [comment]
Тоже самое...

**Comment by BladeMight** [comment]
Ну тогда я не знаю как это сделать...

**Comment by BladeMight** [comment]
И вообще я думаю что все-таки не в прокси дело, а в файре.

**Comment by vicodin77** [comment]
Попробуй еще два поля приделать именем и паролем...

**Comment by BladeMight** [comment]
>Попробуй еще два поля приделать именем и паролем...

Ладно попробую.

**Comment by vicodin77** [comment]
Спасибо!

**Comment by vicodin77** [comment]
Проверил логи фаера - чисто!

**Comment by BladeMight** [comment]
>Попробуй еще два поля приделать именем и паролем...

Вот [MahouProxyWithCredentials.zip]
(https://github.com/BladeMight/Mahou/files/467157/MahouProxyWithCredentials.zip)

> Проверил логи фаера - чисто!

Странно, прокси не принимает соединение?

**Comment by vicodin77** [comment]
Не, все-равно не пашет... У нас была похожая проблема, не могли комититься на гитхаб. Решили ее заведением в системные переменные переменной HTTP_PROXY=http://login:pass@proxy:port. После этого комиты пошли. Может попробуешь тоже использовать эту переменную?

**Comment by vicodin77** [comment]
Кстати, сейчас нажал "Обновить" на другой машине с Win10 накоторой все прекрасно обновлялось до этого и получил ошибку "Индекс находился вне границ массива"! Версия 1.1.5.2!

**Comment by BladeMight** [comment]
> Кстати, сейчас нажал "Обновить" на другой машине с Win10 накоторой все прекрасно обновлялось до этого и получил ошибку "Индекс находился вне границ массива"! Версия 1.1.5.2!

Я сейчас выпущу скоро новую версию, там будет все норм.

> Может попробуешь тоже использовать эти переменные?

Сейчас, подожди закончу с 1.1.5.6 и сразу попробую.

**Comment by vicodin77** [comment]
Оки!

**Comment by vicodin77** [comment]
Доброго дня!
Ну как успехи?

PS: кстати, по поводу значка языка возле курсора. Работает не плохо, только мне кажется, он не должен появляться когда курсор находится над текстом не в полях ввода,,,)

**Comment by BladeMight** [comment]
> Доброго дня!

И Вам тоже доброго дня!

> Ну как успехи?

Вот [здесь](https://dl.dropboxusercontent.com/s/f8t3se62f6zn4cq/Mahou-ProxyEnvVar.zip) все готово для проверки.

> только мне кажется, он не должен появляться когда курсор находится над текстом не в полях ввода,,,)


Он появляется ВСЕГДА когда курсор мыши становится I , и проверить вводимая ли форма под курсором - **невозможно**(*или по крайней мере я не знаю как*).

**Comment by vicodin77** [comment]
Мдя... Все-равно не может подключится к гитхабу... Переменные правильно подхватывает. Буду думать...

PS: а можешь прислать кусок кода с использованием прокси?

**Comment by BladeMight** [comment]
```C#
async Task GetUpdateInfo()
        {
            var Info = new List<string>(); // Update info
            try
            {
                // Latest Mahou release url
                const string url = "https://github.com/BladeMight/Mahou/releases/latest";
                var request = (HttpWebRequest)WebRequest.Create(url);
                Console.WriteLine("Proxy = " + Environment.GetEnvironmentVariable(textBox1.Text));
                try
                {
                request.Proxy = new WebProxy(Environment.GetEnvironmentVariable(textBox1.Text));
                }catch{Console.WriteLine("Wrong proxy variable, skipping proxy...");}
                request.ServicePoint.SetTcpKeepAlive(true, 5000, 1000);
                var response = (HttpWebResponse)await Task.Factory
                    .FromAsync<WebResponse>(request.BeginGetResponse,
                    request.EndGetResponse,
                    null);
                //Console.WriteLine(response.StatusCode)
```

Переменная `request` к ее свойствам приставляем прокси если правильный, и тогда получаем ответ(переменная responc),

**Comment by vicodin77** [comment]
Вот что надыбал - https://gist.github.com/bryanbarnard/8102915
Моей проксе надо явно указывать Basic proxy auth...

**Comment by BladeMight** [comment]
> Вот что надыбал

Работает у тебя этот способ?

**Comment by vicodin77** [comment]
К сожалению нет возможности проверить этот пример...((

**Comment by BladeMight** [comment]
Вот небольшой консольный [тест](https://dl.dropboxusercontent.com/s/cioi4etlf2q34l4/BasicAuthTest.zip).

**Comment by BladeMight** [comment]
Вот какой у меня вывод в консоли:
```batch
Enter the url to get(http://...):
https://github.com/
Enter the proxy for url(http://proxyaddress:port):
http://212.227.159.39:80
Enter the proxy name:password get(username:password):

GET: + https://github.com/
With proxy: http://212.227.159.39:80
Response StatusCode: 200

<!DOCTYPE html>
<html lang="en" class="">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>


    ...
```

**Comment by BladeMight** [comment]
А вот код всей программы:
```C#
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using System.Net.Http;
using System.Net;


namespace HTTP_Test
{
    class program
    {
    	static string url = "";
    	static string proxy = "";
    	static string namepass = "";
        static void Main()
        {
            Task t = new Task(HTTP_GET);
            Console.WriteLine("Enter the url to get(http://...):");
            url = Console.ReadLine();
            Console.WriteLine("Enter the proxy for url(http://proxyaddress:port):");
            proxy = Console.ReadLine();
            Console.WriteLine("Enter the proxy name:password get(username:password):");
            namepass = Console.ReadLine();
            t.Start();
            Console.ReadLine();
        }

        static async void HTTP_GET()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                Proxy = new WebProxy(proxy),
                UseProxy = true,
            };

            Console.WriteLine("GET: + " + url +"\nWith proxy: " + proxy);

            // ... Use HttpClient.            
            HttpClient client = new HttpClient(handler);

            var byteArray = Encoding.ASCII.GetBytes(namepass);
            client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));

            HttpResponseMessage response = await client.GetAsync(url);
            HttpContent content = response.Content;

            // ... Check Status Code                                
            Console.WriteLine("Response StatusCode: " + (int)response.StatusCode);

            // ... Read the string.
            string result = await content.ReadAsStringAsync();

            // ... Display the result.
            if (result != null &&
            result.Length >= 250)
            {
                Console.WriteLine(result.Substring(0, 250) + "...");
            }
        }
    }
}
```

**Comment by vicodin77** [comment]
Вот что вернуло у меня:
GET: + https://github.com/
With proxy: bproxy.msk.mts.ru:3131

Необработанное исключение: System.Net.Http.HttpRequestException: Произошла ошибка при отправке запроса. ---> System.Net.WebException: Удаленный сервер возвратил ошибку: (407) Требуется аутентификация посредника.
   в System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   в System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в HTTP_Test.program.<HTTP_GET>d__1.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   в System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch()
   в System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by BladeMight** [comment]
Надо было не `bproxy.msk.mts.ru:3131` а **http://**bproxy.msk.mts.ru:3131 или **https://**bproxy.msk.mts.ru:3131

**Comment by vicodin77** [comment]
Ок, сейчас попробую!

**Comment by vicodin77** [comment]
GET: + http://google.com/
With proxy: http://bproxy.msk.mts.ru:3131
Response StatusCode: 407
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en">

          <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <met...

**Comment by BladeMight** [comment]
Я тут [нашел](http://stackoverflow.com/questions/2581609/the-remote-server-returned-an-error-407-proxy-authentication-required) видимо нужно устанавливать стандартные данные входа прокси в конфигурации.
Попробуй эту:
[BasicAuthe.exe.gz](https://github.com/BladeMight/Mahou/files/471630/BasicAuthe.exe.gz)(надеюсь у тебя есть чем открыть gzip, а то чего-то GitHub ругается на zip'ы?)

**Comment by vicodin77** [comment]
Таже 407я ошибка...

**Comment by vicodin77** [comment]
Ты в VC кодишь?

**Comment by BladeMight** [comment]
> Ты в VC кодишь?

Если ты про IDE, у меня есть VS 2012 Express, но она слишком велика, так что Я пока что SharpDevelop'ом пользуюсь. И да у меня есть VSCode еще.
Если про язык, то C#.

Я тут [еще](http://stackoverflow.com/questions/9603093/proxy-basic-authentication-in-c-http-407-error) кое-что нашел, сейчас попробую приделать.

**Comment by BladeMight** [comment]
[NewCredentialsUsage.exe.gz](https://github.com/BladeMight/Mahou/files/471695/NewCredentialsUsage.exe.gz), а здесь?

**Comment by vicodin77** [comment]
Вот что теперь -
STARTING...(wait a little!)
Staus is : OK
<!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ru"><head><meta content="????? ?????????? ? ?????????: ??? ????????, ????????, ????? ? ?????? ??????." name="description"><meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><tit

**Comment by vicodin77** [comment]
А это, если на http://github.com - 
STARTING...(wait a little!)
Staus is : OK



<!DOCTYPE html>
<html lang="en" class="">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>


    <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-6340907fbb4f7160ce9266a1b9167ab4df8a62790bdea1e26de1b3918da62416.c

**Comment by vicodin77** [comment]
О! У меня на VS2015Comm тоже скомпилилась и стартанула даже!)) Пришли, плиз, крайний код консольной утили?

**Comment by BladeMight** [comment]
```C#
using System;
using System.Linq;
using System.Threading.Tasks;
using System.IO;
using System.Net;


namespace HTTP_Test
{
	class program
	{
		static string url = "";
		static string proxy = "";
		static string name = "";
		static string pass = "";
		static void Main()
		{
			Task t = new Task(HTTP_GET);
			Console.WriteLine("Enter the url to get(http://...):");
			url = Console.ReadLine();
			Console.WriteLine("Enter the proxy for url(http://proxyaddress:port):");
			proxy = Console.ReadLine();
			Console.WriteLine("Enter the proxy username:");
			name = Console.ReadLine();
			Console.WriteLine("Enter the proxy password:");
			pass = Console.ReadLine();
			t.Start();
			Console.ReadLine();
		}

		static async void HTTP_GET()
		{
			HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
			Console.WriteLine("STARTING...(wait a little!)");
			WebProxy myProxy = new WebProxy();
			try{
			Uri newUri = new Uri(proxy);
			myProxy.Address = newUri;
			}catch {Console.WriteLine("Proxy is empty, or not right!");}
			myProxy.Credentials = new NetworkCredential(name, pass);
			request.Proxy = myProxy;
			var response = (HttpWebResponse)await Task.Factory
                    .FromAsync<WebResponse>(request.BeginGetResponse,
                    request.EndGetResponse,
                    null);
			Console.WriteLine("Staus is : " + response.StatusCode);
			var data = new StreamReader(response.GetResponseStream(), true).ReadToEnd();
                    response.Close();
                    
                    Console.WriteLine(data.Substring(0,400));
                    
		}
	}
}
```
Как по-мне так все очень просто

**Comment by vicodin77** [comment]
Ну, вроде не тормозит...) У меня CORE DUO 3.0Ghz и памяти 8Gb

**Comment by vicodin77** [comment]
Я то сам в IDEA на JAVA кодю!))

**Comment by vicodin77** [comment]
Слушай, а какой лучше шарп скачать? Мне просто еще и по VB он понадобиться!)
Заранее спасибо!

**Comment by BladeMight** [comment]
.net 4 или 4.5 для windows 7 лучше всего.

**Comment by vicodin77** [comment]
Не могу найти 4.5... На офф-сайте только 4.3.3 лежит от 2013 года...

**Comment by BladeMight** [comment]
Ты про SharpDevelop? Или .Net? Фреймворк [.Net 4.5.1](https://www.microsoft.com/ru-ru/download/details.aspx?id=42642), среда разработки [SharpDevelop](http://www.icsharpcode.net/OpenSource/SD/Download/)(5.1 только C#, 4.4 С# и VB)

**Comment by vicodin77** [comment]
Спасибо!
НУ, похоже крайний вариант по проксе работает! выпустишь сборку Mahou?

**Comment by BladeMight** [comment]
Нука еще эту проверь, чтоб наверняка:
[NPCUNoDefInConfs.exe.gz](https://github.com/BladeMight/Mahou/files/472014/NPCUNoDefInConfs.exe.gz)

**Comment by vicodin77** [comment]
Вроде все ОК!
```
STARTING...(wait a little!)
Staus is : OK



<!DOCTYPE html>
<html lang="en" class="">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
    <meta charset='utf-8'>


    <link crossorigin="anonymous" href="https://assets-cdn.github.com/assets/frameworks-6340907fbb4f7160ce9266a1b9167ab4df8a62790bdea1e26de1b3918da62416.c
```

**Comment by BladeMight** [comment]
А при вводе прокси ты вводил http:// или https:// ??

**Comment by vicodin77** [comment]
http://

**Comment by BladeMight** [comment]
Ну так что? Проверил Mahou?

**Comment by BladeMight** [comment]
Вот лучше проверь улучшенную версию.
[Mahou-ZERO(1.2.0.0).gz](https://github.com/BladeMight/Mahou/files/472354/Mahou-ZERO.1.2.0.0.gz)
Это специальная 0.0.0.0 версия для проверки возможности обновления. 
В ней уже есть возможность сохранять прокси, имя, пароль, и много другого.
Проверь, я не зарелизю пока не убедюсь в работоспособности.

**Comment by BladeMight** [comment]
Вот исправленная версия, в которой загрузка файла тоже идет через прокси:
[Mahou-DownloadProxyToo-ZERO(1.2.0.0).gz](https://github.com/BladeMight/Mahou/files/473061/Mahou-DownloadProxyToo-ZERO.1.2.0.0.gz)

**Comment by vicodin77** [comment]
А где вводить проксю???

**Comment by BladeMight** [comment]
> и что-то у меня не собирается под шарпом консольный проект... Вроде поставил все компоненты...

Проект > Параметры проекта > Компиляция > Целевая версия Framework > изменить, установите 4.5+

> А где вводить проксю???

В окне обновления, есть маленькая стрелка внизу нажми на нее и появятся формы прокси:
![2016-09-15 01-57-04-window](https://cloud.githubusercontent.com/assets/11931888/18547554/b34c9894-7b4c-11e6-8b41-f104ea98f57f.jpg)

**Comment by vicodin77** [comment]
Спасибо! Проект скомпилился!)

А вот Mahou все так же не может обновится...

**Comment by vicodin77** [comment]
О! Обновился!!!!!!!!!!!!!!! Проксю надо было без http вводить!!!)))

**Comment by BladeMight** [comment]
>без http вводить!!

Да, видно же на скрине!

> О! Обновился

Рад, что получилось 😄

**Comment by vicodin77** [comment]
Да, я понял уже!))) Но не плохо бы это обработать! ;)

**Comment by BladeMight** [comment]
И так, в релиз?

**Comment by vicodin77** [comment]
Еще пара замечаний!)
1. При включенном индикаторе языка, начинаются проблемки с всплывающими подсказками в главном окне Mahou - они появляются и через долю секунды скрываются.
2. При попытке закрыть окно обновления крестиком мышь замирает секунды на три и только потом окно закрывается и мышь отмирает.

**Comment by vicodin77** [comment]
1. Да, на 10й винде такого эффекта нет... Но есть эффект, что когда проводишь курсором над названиями клавиш окно Mahou как бы переключается: активное - не активное...

2. Пинг 1мс

**Comment by BladeMight** [comment]
1. Активной становится маленькая подсказка, но думаю можно исправить.
2. Странно, но у меня есть еще одна идея, сейчас закончу и скину сборку.

**Comment by BladeMight** [comment]
1. С использованием P/Invoke, получилось.
2. Проверь в общем:

[Mahou.TipNoActivate+UpdatedHideUPDWND.gz](https://github.com/BladeMight/Mahou/files/474579/Mahou.TipNoActivate.UpdatedHideUPDWND.gz)

**Comment by vicodin77** [comment]
И можно ли прикрутить вот такие курсорчики, как в этой проге?
Прога:[langcursor.exe.gz](https://github.com/BladeMight/Mahou/files/474578/langcursor.exe.gz)
Курсорчики:
[ibeam7en.cur.gz](https://github.com/BladeMight/Mahou/files/474583/ibeam7en.cur.gz)
[ibeam7ru.cur.gz](https://github.com/BladeMight/Mahou/files/474582/ibeam7ru.cur.gz)

**Comment by vicodin77** [comment]
Да, вот теперча работает норм!

**Comment by BladeMight** [comment]
Как-то мы тут мнооого пишем, лучше создать уже новую issue, а эту(решенную) закрыть.

**Comment by vicodin77** [comment]
Ок!

**Comment by vicodin77** [comment]
По курсорам создал новую issue!

**Comment by BladeMight** [comment]
Ок, все эту закрываем, и скоро будет релиз 1.2.0.0.

**Comment by vicodin77** [comment]
Супер!!!
