### ISSUE TITLE
Не меняется RUS\ENG индикатор если Mahou в панели "скрытые значки"

### ISSUE THREAD

**Issue by lpslp** [BladeMight/Mahou#250]
## Problem/Request description
После перехода на windows 10X64 сборка 1909 появилась не приятная особенность. Если значек Mahou закинуть в  панель "скрытые значки" на task bar то сам индикатор винды не меняет свое состояние RUS\ENG при этом раскладки переключаются. Если вытащить mahou из "скрытые значки" то индикатор начинает работать.

**Comment by BladeMight** [comment]
Честно скажу, не знаю... каким образом мой индикатор может влиять на виндовский???

**Comment by lpslp** [comment]
я не знаю как, но до обновления винды мне очень нравился Mahou (много настроек), после обновления на 1909 все настолько поменялось (не срабатывает переключение даже так как я описал, а иногда срабатыват посередине слова - это и добило), что прилось перейти обратно на https://lrepacks.ru/repaki-programm-dlya-ofisa/41-punto-switcher-repack-amp-portable.html Punto Switcher с которого уходил лет 10-11 назад на что то(не помню), потом еще на что то(не помню), потом Mahou и теперь опять Punto (смешно но с ним все нормально)...
