### ISSUE TITLE
Свои курсоры отображения раскладки

### ISSUE THREAD

**Issue by vicodin77** [BladeMight/Mahou#26]
И можно ли прикрутить вот такие курсорчики, как в этой проге? Или дать возможность использовать свои курсоры?
Прога:[langcursor.exe.gz](https://github.com/BladeMight/Mahou/files/474599/langcursor.exe.gz)
Курсорчики:
[ibeam7en.cur.gz](https://github.com/BladeMight/Mahou/files/474600/ibeam7en.cur.gz)
[ibeam7ru.cur.gz](https://github.com/BladeMight/Mahou/files/474602/ibeam7ru.cur.gz)
Заранее спасибо!

**Comment by BladeMight** [comment]
Ну у меня, программа не меняет курсор, а добавляет к нему подсказку...
Можно добавить способ изменения курсора, но будет сложнее без кода...

**Comment by vicodin77** [comment]
А если просто такую подсказку сделать? Что б не очень мозолила глаза при движении мыши по странице броузера, например?

**Comment by BladeMight** [comment]
> не очень мозолила глаза

Вы про цвета? Так поменяйте в ...

**Comment by vicodin77** [comment]
Я про размер!)

**Comment by BladeMight** [comment]
Ок, сейчас добавлю возможность изменения.

**Comment by BladeMight** [comment]
Такая нормально? [Mahou-smaller-tip.gz](https://github.com/BladeMight/Mahou/files/474653/Mahou-smaller-tip.gz)

**Comment by vicodin77** [comment]
Да, так вобче супер!!!

**Comment by BladeMight** [comment]
Так и оставить тогда? Добавлять настройку размера?

**Comment by vicodin77** [comment]
Наверно лучше добавить... Может кому-то надо наоборот, по больше!

**Comment by BladeMight** [comment]
Ок, тогда...

**Comment by BladeMight** [comment]
Вот, проверь:
[Mahou-tip-Customization.gz](https://github.com/BladeMight/Mahou/files/474768/Mahou-tip-Customization.gz)

**Comment by vicodin77** [comment]
Изменяется размер окошка, а шрифт нет!)

**Comment by BladeMight** [comment]
Ты уверен? У меня  меняется!

**Comment by vicodin77** [comment]
![image](https://cloud.githubusercontent.com/assets/16464189/18552370/d13718f8-7b64-11e6-812d-bf60e9f51707.png)

**Comment by vicodin77** [comment]
Блин! Сорри! Не заметил настройку шрифта!!!)))))))))))))

**Comment by BladeMight** [comment]
Ничего, бывает, ну так что отлично?

**Comment by vicodin77** [comment]
Да, отлично!

**Comment by BladeMight** [comment]
Проблема, решена, делать релиз?

**Comment by vicodin77** [comment]
Да! В релиз!

**Comment by vicodin77** [comment]
PS: Кстати, нельзя ли изменить место вывода этой подсказочки? Сместить ее внизотносительно курсора? Если выставить размеры 10 на 13 и 6й шрифт, то выводится она будет сыерху!

**Comment by BladeMight** [comment]
Добавить X/Y относительно курсора?

**Comment by vicodin77** [comment]
Именно!!!!

**Comment by BladeMight** [comment]
[Вот](https://github.com/BladeMight/Mahou/releases/tag/v1.2.0.6).

**Comment by vicodin77** [comment]
Супер!!! На скорую руку проверил - все работает! Апдейт через проксю тоже! 
Кстати, добавление работы через проксю, не вынесен в описание релиза!)))

**Comment by BladeMight** [comment]
> Кстати, добавление работы через проксю, не вынесен в описание релиза!)))
[Здесь](https://github.com/BladeMight/Mahou/releases/tag/v1.2.0.0) первая строчка.

**Comment by vicodin77** [comment]
Опа на! Это я два релиза пропустил!!!)))))))))))

**Comment by BladeMight** [comment]
Обращайся, если что.

**Comment by vicodin77** [comment]
По Mahou можно уже статейку на хабре запилить!))

**Comment by BladeMight** [comment]
Знаешь, я как-то пробовал, но там какая-то **жесткая** администрация, так что 3 раза не получилось, может ты напишешь?

**Comment by vicodin77** [comment]
Ух... Попробу, хотя ни когда не писал ни чего такого!))

**Comment by BladeMight** [comment]
Буду ждать :)
