### ISSUE TITLE
Как ее устанавливать?

### ISSUE THREAD

**Issue by maxrempel** [BladeMight/Mahou#264]
`...`

**Comment by BladeMight** [comment]
Mahou - не требует установки. Требует только .Net 4.0 и выше.

**Comment by maxrempel** [comment]
Спасибо. Даже если она не требует установки, надо ее как-то перенести на компьютер?
И как-то запустить?
И как ей сказать, чтобы стартовала с виндами?

**Comment by BladeMight** [comment]
[Отсюда](https://github.com/BladeMight/Mahou/releases/latest-commit) скачиваешь `Release_x86_x64.zip`, распаковываешь где тебе удобно(лучше избегать системных папок). О дополнительных функциях можно узнать на [wiki](https://github.com/BladeMight/Mahou/wiki).
И конкретно вот [Запускать вместе с Windows.](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#Запускать-вместе-с-windows).

**Comment by maxrempel** [comment]
Спасибо! Теперь понятно!
