### ISSUE TITLE
[Fix possibility] Convert Selection превращает ,(en) в ?(ru), вместо б

### ISSUE THREAD

**Issue by qfeuer** [BladeMight/Mahou#27]
Приветствую, 

нашёл подобное поведение, если набрать ,kby и нажать конвертацию последнего слова (pause), то конвертация происходит без ошибок, но если выделить слово, то первая буква заменяется на другую, относящующся к другой части символов клавиатуры - цифровому ряду.

примеры

Женева, если выделить и сконвертировать получим ===   :tytdf    === но если выделить снова и сделать convert selection получим ===  ^енева  ===, попадают под эту конвертацию все буквы из х.ъ.ж.э.б.ю..(точка =))

**Comment by BladeMight** [comment]
Включите `КВ-Ключ`, там же написано:
`Нет проблем с символами`.
