### ISSUE TITLE
Наглухо виснет в DxO PhotoLab 3 (стандартный диалог выбора каталога?)

### ISSUE THREAD

**Issue by Mercury13** [BladeMight/Mahou#272]
Виснет как 2.9.0.1, так и 3ea3707.

В самом DxO не виснет, и надо выполнить такую операцию: Export to Disk, кнопка выбора каталога в поле Path, открывается стандартный диалог выбора папки (не путать с диалогом открытия). И вот если в нём вручную переключить язык (например, через Ctrl), DxO наглухо виснет.

Может, подскажете другие программы с таким диалогом? — хотя бы проверю.

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>

- Mahou 2.9.0.1-dev <3ea3707>
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Английская (Типографская раскладка Ильи Бирмана)(4039115785)
Русская (Типографская раскладка Ильи Бирмана)(4039181337)
Украинская (расширенная)(4037542946)

</details><details><summary>Mahou.ini</summary>

```ini
[Hidden]
__setlayout_ONLYWM=false
__setlayout_FORCED=false
onlySnippetsExcluded=
__selection=false
CycleCaseReset=false
CycleCaseOrder=TULSR
LibreCtrlAltShiftV=false
ReSelectCustoms=tTRSULCN
[FirstStart]
First=False
[Functions]
WriteInputHistoryHourly=false
WriteInputHistoryByDate=false
AutoStartAsAdmin=False
TrayIconVisible=True
ConvertSelectionLayoutSwitching=False
ReSelect=True
RePress=False
AddOneSpaceToLastWord=True
AddOneEnterToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=False
SilentUpdate=False
Logging=False
CapsLockTimer=False
TrayFlags=True
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=True
GuessKeyCodeFix=False
AppDataConfigs=False
RemapCapslockAsF18=False
UseJKL=True
ReadOnlyNA=False
WriteInputHistory=False
WriteInputHistoryBackSpaceType=0
TrayText=False
[Layouts]
SwitchBetweenLayouts=False
OneLayout=False
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=Английская (Типографская раскладка Ильи Бирмана)(4039115785)
MainLayout2=Русская (Типографская раскладка Ильи Бирмана)(4039181337)
SpecificKey1=2
SpecificKey2=5
SpecificKey3=3
SpecificKey4=9
SpecificLayout1=Английская (Типографская раскладка Ильи Бирмана)(4039115785)
SpecificLayout2=Украинская (расширенная)(4037542946)
SpecificLayout3=Русская (Типографская раскладка Ильи Бирмана)(4039181337)
SpecificLayout4=Русская (Типографская раскладка Ильи Бирмана)(4039181337)
SpecificKeysType=0
SpecificKeySets=set_0
QWERTZfix=False
[PersistentLayout]
OnlyOnWindowChange=False
ChangeOnlyOnce=False
ActivateForLayout1=False
ActivateForLayout2=False
Layout1CheckInterval=50
Layout2CheckInterval=50
Layout1Processes=devenv.exe wdexpress.exe
Layout2Processes=notepad++.exe winword.exe
[Appearence]
DisplayLangTooltipForMouse=False
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
MouseLTAlways=False
Language=Русский
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Georgia; 8pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Georgia; 8pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTFont=Georgia; 8pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
CaretLTTransparentBackColor=False
CaretLTFont=Georgia; 8pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
MouseLTUseFlags=False
CaretLTUseFlags=False
Layout1LTText=
Layout2LTText=
MouseLTUpperArrow=False
CaretLTUpperArrow=False
WindowsMessages=True
[Timings]
UsePasteInCS=False
ExcludeCaretLD=false
ConvertSWLinExcl=False
DelayAfterBackspaces=100
UseDelayAfterBackspaces=False
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
ChangeLayoutInExcluded=True
LangTooltipForMouseSkipMessages=5
[Snippets]
SnippetsEnabled=False
SpaceAfter=False
SwitchToGuessLayout=False
SnippetExpandKey=Space
[AutoSwitch]
Enabled=False
SpaceAfter=True
SwitchToGuessLayout=True
DownloadInZip=True
[Hotkeys]
SelectedTextToCustomConv_Mods=
SelectedTextToCustomConv_Enabled=False
SelectedTextToCustomConv_Double=False
SelectedTextToCustomConv_Modifiers=
SelectedTextToCustomConv_Key=0
CycleCase_Enabled=False
CycleCase_Double=False
CycleCase_Modifiers=Shift
CycleCase_Key=114
ToggleMainWindow_Enabled=True
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=True
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=True
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=
ConvertSelectedText_Key=145
ConvertLastLine_Enabled=True
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=True
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=True
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=0
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Alt
SelectedTextToRandomCase_Key=0
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win
SelectedTextToSwapCase_Key=190
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win
SelectedTextTransliteration_Key=191
SelectedToUpper_Enabled=False
SelectedToUpper_Double=False
SelectedToUpper_Modifiers=Win
SelectedToUpper_Key=90
SelectedToLower_Enabled=False
SelectedToLower_Double=False
SelectedToLower_Modifiers=Win
SelectedToLower_Key=88
ExitMahou_Enabled=True
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=True
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
ToggleLangPanel_Enabled=True
ToggleLangPanel_Double=False
ToggleLangPanel_Modifiers=Shift
ToggleLangPanel_Key=120
ShowSelectionTranslate_Enabled=False
ShowSelectionTranslate_Double=True
ShowSelectionTranslate_Modifiers=Alt
ShowSelectionTranslate_Key=0
ToggleMahou_Enabled=True
ToggleMahou_Double=False
ToggleMahou_Modifiers=Win Shift
ToggleMahou_Key=112
[LangPanel]
Display=False
Transparency=90
RefreshRate=25
Position=X0 Y0
ForeColor=#000000
BackColor=#FFFFFF
Font=Microsoft Sans Serif; 8,25pt
BorderColor=#8B5FFF
BorderAeroColor=True
UpperArrow=True
[Updates]
Delay=5
Channel=Stable
LatestCommit=3ea3707
[Sounds]
CustomSound2=
UseCustomSound2=False
OnLayoutSwitch2=True
OnConvertLast2=False
OnSnippets2=True
OnAutoSwitch2=False
CustomSound=
UseCustomSound=False
OnLayoutSwitch=False
OnConvertLast=True
OnSnippets=False
OnAutoSwitch=True
Enabled=False
[TranslatePanel]
UseNA=True
UseGS=False
LanguageSets=set_1/auto/ru|set_2/auto/en
BG=#FFFFFF
BorderC=#F1F100
FG=#8B5FFF
Transparency=90
BorderAero=False
OnDoubleClick=False
Enabled=False
TitleFont=Segoe UI; 12pt
TextFont=Microsoft Sans Serif; 8,25pt
[Sync]
BLast=
RLast=
RBools=1|1|1|1|0
BBools=0|1|0|0|0


</details>
</details>
</details>

**Comment by Mercury13** [comment]
UPD. Нашёл похожий диалог в 7-Zip, но там в порядке.

**Comment by BladeMight** [comment]
@Mercury13 Очень похоже на поведение в MS Office/Skype, есть на wiki информация по настройке переключения: [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B2-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%3F)

Т.е. нужно включить эмуляцию, и Mahou будет "эмулировать переключение раскладки до нужной", а не через сообщение WM_INPUTLANGCHANGEREQUEST как без эмуляции. \

Я до сих пор не смог понять каким образом система меняет раскладку, я даже через Spy++ смотрел и там видно что система меняет раскладку через [WM_INPUTLANGCHANGE](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-inputlangchange) но для неё нужно указывать "charset" который нужно как-то получить для каждой раскладки, и только система знает как...

**Comment by BladeMight** [comment]
Вот при "стандартном винодсовском" методе смены раскладки(или эмуляция через Mahou):
![2020 04 19 - 22'11'40_rect](https://user-images.githubusercontent.com/11931888/79697347-f3774880-828a-11ea-85bf-8310710d5063.jpg)
Не виснет.
А вот через Mahou без эмуляции:
![2020 04 19 - 22'10'06_rect](https://user-images.githubusercontent.com/11931888/79697357-fd994700-828a-11ea-85c8-7c0ec6e8bb3a.jpg)
Получил WM_INPUTLANGCHANGEREQUEST и потом завис:
![2020 04 19 - 22'05'07_rect](https://user-images.githubusercontent.com/11931888/79697368-09850900-828b-11ea-93a8-fbe7cd02a55b.jpg)

Нужно как-то понять как получать *charset* для раскладки и использовать **WM_INPUTLANGCHANGE** вместо `WM_INPUTLANGCHANGEREQUEST`.............................................................................................................................................................................................................................................................................................................................................

Ну а пока можно пользоваться эмуляцией, благо я придумал "эмуляцию переключения раскладки до нужной" - так что можно пользоваться.

**Comment by Mercury13** [comment]
Эмуляция работает хреново.

**Comment by BladeMight** [comment]
Вообще не информативно. Как?

Ну другого варианта пока что нет.

**Comment by Mercury13** [comment]
Выставляет не ту раскладку.

**Comment by BladeMight** [comment]
@Mercury13 Лучше всего работает именно "Alt+Shift" метод, "Win+Space" глючный т.к. у него есть огромная задержка, с Alt+Shift при 7 раскладках:
![Mahou-multi-layout-emu](https://user-images.githubusercontent.com/11931888/80259431-3b80db80-868e-11ea-9c28-fb7ad3ad7572.gif)
Работает нормально *если не сильно спешить* переключать.

>Ну другого варианта пока что нет.

Все ещё так же. Либо эмуляция, либо добавить в исключения, либо использовать только 2 раскладки и убрать "переключать между раскладками", либо пользоваться конвертацией выделения + ручное переключение.

Любая другая программа будет давать такой же эффект, т.к. "другого способа программно переключить раскладку", кроме 'WM_INPUTLANGCHANGEREQUEST' - нет, а именно из-за него и виснет. 
**\*Любая другая программа** - Хотя они все "переключают по следующей раскладке", так что там скорее всего просто используется эмуляция, нет там никаких "переключений на конкретную раскладку 1 клавишей".

**Comment by BladeMight** [comment]
@Mercury13 Исходя из https://stackoverflow.com/questions/61310903 и ответа: https://stackoverflow.com/a/61402370/5420570, я пришел к выводу что проблема в самом DxO т.к. там неправильное обращение с сообщениями. Другого варианта сменить раскладку кроме `WM_INPUTLANGCHANGEREQUEST` - нет.
