### ISSUE TITLE
2 приложения с Магазина Windows намертво зависают при переключении раскладки или автозамене

### ISSUE THREAD

**Issue by Juriyx** [BladeMight/Mahou#276]
## Problem/Request description
2 приложения с Магазина Windows намертво зависают при переключении раскладки или автозамене - **Unigram** и **Удалённый рабочий стол**. Приходится только принудительно закрывать и перезапускать. Пожалуйста, исправьте эту проблему. Замечу, что зависание происходит не каждый раз, но часто.

## Expected behavior (Only if reporting bug)
Обычное переключение раскладки без зависания программы.

## System information
- Windows version: [Windows 10 Pro x64 2004]
- Windows architecture: [x64]
- .Net version: [4.8]
- Mahou version: [2.9.0.1 Stable]

**Comment by BladeMight** [comment]
@Juriyx см. [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B2-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%3F)

Используй эмуляцию переключения раскладки, если раскладок менее 3 или не используешь "переключать раскладку 1 клавишей" на конкретную раскладку - тогда можно выключить и "переключать между раскладками".

**Comment by Juriyx** [comment]
> @Juriyx см. [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B2-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%3F)
> 
> Используй эмуляцию переключения раскладки, если раскладок менее 3 или не используешь "переключать раскладку 1 клавишей" на конкретную раскладку - тогда можно выключить и "переключать между раскладками".

В настройке эмуляции имеет ли значение "Тип эмуляции" (сочетание клавиш)? В чём-то проявляется разница?

И ещё такой вопрос. Вроде когда пользовался Mahou в посл. раз, после ввода слова нажимаешь пробел (видишь что раскладка не та была), затем Backspace и сочетание клавиш, заданное на конвертацию раскладки и она переключалась. А сейчас нет. Это в бета-версиях только есть или по другой причине не работает?

**Comment by BladeMight** [comment]
> Вроде когда пользовался Mahou в посл. раз, после ввода слова нажимаешь пробел (видишь что раскладка не та была), затем Backspace и сочетание клавиш

Функция "Считать (1) Пробел частью последнего слова" делает то что ты хочешь.

P.S. Бета версии лучше.
