### ISSUE TITLE
У меня прграмма везде работает кроме гугл хром, как исправить? опера и все другие браузеры все робит

### ISSUE THREAD

**Issue by anytwocards** [BladeMight/Mahou#277]
У меня программа везде работает кроме гугл хром, как исправить? опера и все другие браузеры все робит.

**Comment by BladeMight** [comment]
@anytwocards Возможно Chrome запущен от админа? Попробуй и Mahou запустить от админа.

И "как" не работает, вообще или что-то конкретное?

**Comment by anytwocards** [comment]
все гуд спасибо, дело в админке было, автозамена не работала в гугл доках и в браузере

**Comment by BladeMight** [comment]
@anytwocards ОК.
