### ISSUE TITLE
Crash on internet connection loss.

### ISSUE THREAD

**Issue by Dra9o** [BladeMight/Mahou#279]
Each time a power failure occurs, Mahou throws an unhandled exception (.Net 4.7.03062 exception) and terminates. Please note that simply disconnecting the Ethernet cable does not cause problems. When launched manually (not from task scheduler), Mahou also does not respond to a loss of Ethernet connection. After each reboot, this problem is reproduced in 100% of cases.

Somewhat outdated operating system Windows 7x64 7601 SP1.
The list of .Net libraries is in the picture. Logs are attached.
Mahou 2.9.0.1

![Alt Text](https://downloader.disk.yandex.ru/preview/89c66ca454b9a80b8d2ac7392da3822b26dc3f63df0fa33be0317798c4794c03/5f0a650f/teXZRRpx7xCID6-zdhGDhccmZ1Tn6sCNXEoBICS7XcYOe7fHLxZh2_IenjEt_mlbY0Rlpi1nhJo5IsL2IR3gYw==?uid=0&filename=2020-07-11+22_07_15-%D0%9F%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%B0+Microsoft+.NET+Framework.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=64698832&size=2048x2048)

![Alt Text](https://s178vla.storage.yandex.net/rdisk/306c9f6778cff76fa0ea80331d664e0e3dd6e82d8174b69a2771af08c88a83f8/5f0a6598/GiA7zhxb6Bgs0bf_xsPngM6vZZRu5ccoqAE4J47pdpqn8dX31NOHlmr4OfCYasdVReYp8K-77F8MtMVhS6JB9g==?uid=0&filename=2020-07-11%2022_07_55-Mahou.png&disposition=attachment&hash=Ap/tmY0r6POf4BzXkpWsVUlCXMkkuOxbYov2A5tiQbixRA6CdBFgtZYPeFixeUTPq/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=image%2Fpng&owner_uid=64698832&fsize=8494&hid=8c641a70f7d1a1cbeb370ee073b913ea&media_type=image&tknv=v2&rtoken=W3vwh6lJu3lT&force_default=no&ycrid=na-f97bff0882da20e730ccaed050d0965d-downloader8f&ts=5aa3464b29600&s=db987e75e1cddbf23fcb93d121c3d97c204de5477bb3e666ac6e1465902286e8&pb=U2FsdGVkX1_iTBHWts3v3HfHyR58jfaSEb-Y7rYGtMpG79JmI8ruxTU7hYgzkAgFFB707WanuPT3Mfpzrlr0TpDXFSoDtIDjiJ4iFiNSqf8)

![Alt Text](https://s199vla.storage.yandex.net/rdisk/19ed43933db925a13e5fe780b06abc4638c633a2b6a015a55a58fe2a024b667d/5f0a65ce/GiA7zhxb6Bgs0bf_xsPngB32pmH9T-Ee_7LZJXZh2mcvPCAozxKyBn-CJh9XDcLtxobJqDjZyNCaFFyMLo7ksA==?uid=0&filename=2020-07-11%2022_34_32-C__Users_Yaroslav_AppData_Local_Temp_7zO8D161AAC_DotNetVersions.exe.png&disposition=attachment&hash=%2BbMtRQqdTieffj3tJkXyEargBaKFlFZYYimGatdLj8PZeU3OEsTXD01/Tbbk/sLfq/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=image%2Fpng&owner_uid=64698832&fsize=49105&hid=35632f51834e30dfa7dc0db1c20f2c33&media_type=image&tknv=v2&rtoken=07vmoxb67LtP&force_default=no&ycrid=na-93fb49bb2e506dd0903d533a2e58e401-downloader8f&ts=5aa3467ea8f80&s=e04e66fc908a7bd675754b95f8d124713b5fd7d482b3aef4477f93bfc061b464&pb=U2FsdGVkX18UnSV9a6NHkfhqFT2SFCsI8JiHey_LqzBfP_hfg6rM2g9tw76X7fozfzdp9f5tT1nLIMtHXmEsPtNaSdIJjrcl6OWLZoHvoZQ)

[Log](https://s124sas.storage.yandex.net/rdisk/3f33c5c923841c61029b5adff319ca4a9bd44e1e4392e80622b0c60f3e665e51/5f0a66ab/GiA7zhxb6Bgs0bf_xsPngMHc4C4porB8pSAsIVTWC7pV34rlDPJKyKtGwFoiZdV8f83h_XvjJiYtH3DRr-KuqA==?uid=0&filename=2020.07.11.txt&disposition=attachment&hash=hM7adqAShdXSsW4/0qVes7GaX8R/qSn/E3sNh9AIxTuRQbFEfWZ%2BkuVYIDiYs8U1q/J6bpmRyOJonT3VoXnDag%3D%3D&limit=0&content_type=text%2Fplain&owner_uid=64698832&fsize=1159719&hid=2cb3047bfdcd64a75c270ccb920a174e&media_type=document&tknv=v2&rtoken=fF96ss1gQPIs&force_default=no&ycrid=na-aaca6d6cf7f80fd54861c6f458f7aa65-downloader24f&ts=5aa347516c0c0&s=53e4aa415533f61c18b59a775f52916d6146a7936bd86998b288c18237507c36&pb=U2FsdGVkX19RaF3tXd_dH8sreCSANAkAbn8cDNire_snu3QnF0VpFeJAZqhbLT8QbfQ9Q2lyQk3xTaEhFLwBAqJxI7ND0ad1BaZhPpTX4kI)

**Comment by BladeMight** [comment]
I can suggest to try getting more info from latest-commit debug version: [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit), download the Debug*.zip and try doing the same thing, this time error will be more informative. Also i'm kinda suspect that it is because of ".Net" startup problem after shutdown/reboot, .Net apps tend to have a lot time before they are loaded at each boot, but somehow its so slow that even Mahou window is not yet ready but update is already trying to get done, thats why it happens. You can disable the check for updates at startup, this likely will remove the error, but you won't be able to know if there any updates. 

I'll see what I can do, hopefully to see logs from debug version, they could lead me in right way...

**Comment by BladeMight** [comment]
@Dra9o Here I did some fix in 5dbec83, try in latest-commit:

1.Manually:
Download `Release_x86_x64.zip` from [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit), unpack, run.
2. Using Mahou update:
Change update channel to LatestCommit(Beta) and update as usually(click check for updates, then download).

**Comment by Dra9o** [comment]
Thank. 
Here are the logs of the debug version. ( [5dbec830490c4a46e232b4f1af168533e4c509be](https://github.com/BladeMight/Mahou/commit/5dbec830490c4a46e232b4f1af168533e4c509be) ):
[Debug log](https://yadi.sk/d/CBUTt558QHoodw)

Updating and disabling updates does not solve the problem (but updated version works fine with Windows scaling - in the old one, only part of the window was visible). Perhaps the crash is really not related to Mahou - my system has been installed for several years and errors have inevitably accumulated. Maybe I should somehow manually initialize .Net?
I also noted the fact that a window with a message about the termination of the program appears twice. Maybe the checkbox 'Run with Windows' launches the second copy, besides the one launched from the task scheduler?

**Comment by BladeMight** [comment]
> but updated version works fine with Windows scaling

Yes, this one of features added in latest-commit version. #232 

> Here are the logs of the debug version

Logs doesn't contain anything about crash, did you catch crash while logging enabled?

> Maybe I should somehow manually initialize .Net?

No, you can't, its done automatically, but you can try delaying Mahou startup through task scheduler at startup. So that .Net woud probably be ready at the time Mahou starts, about 30-60s.

Usually this kind of error shouldn't happen, maybe try reinstalling .Net... I could not reproduce this error in neither of versions.(latest-commit/2.9.0.1)

**Comment by Dra9o** [comment]
:) While I can reproduce it with 100% accuracy :D
Debug version does not update log file, that's weird. Anyway:
[New Log](https://yadi.sk/d/Bo7AgMqMQO7NuA)
[Crash dialog text (Cyrillic warning)](https://yadi.sk/d/QBYgyXNAWAmq4g)
[Crash dumps (may be useless)](https://yadi.sk/d/Zu7TIIOXW-Dcog)

Do not spend too much time on this bug - it is not critical for me.

**Comment by BladeMight** [comment]
@Dra9o Thanks, your logs pointed out where exactly it happens in code, added fix in fa2752f try and tell if it works now in latest-commit.

**Comment by Dra9o** [comment]
Mahou was updated to fa2752f .
.Net 3.0 3.5 4.0 4.8 were reinstalled.
Auto start delay was set to 1 minute.
No luck :(

**Comment by Dra9o** [comment]
`System.InvalidOperationException: Невозможно вызвать Invoke или BeginInvoke для элемента управления до завершения создания дескриптора окна.
   в System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   в System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   в Mahou.KMHook.DoSelf(Action self_action)
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Dra9o** [comment]
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

Mahou
    Версия сборки: 2.9.0.1
    Версия Win32: 2.9.0.1
    CodeBase: file:///D:/Users/Yaroslav/!_SYSTEM/S_DATA/SOFTWARE/USER_S/Typing_Fix/Mahou-v2.9.0.1/Mahou.exe

System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

Microsoft.CSharp
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3761.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll

System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

System.Web
    Версия сборки: 4.0.0.0
    Версия Win32: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll

mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll

System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll

**Comment by BladeMight** [comment]
@Dra9o OK, test again in 40350ef, it should be fixed now. It was caused by timers, which were probably started before Mahou main window is initialized. 

So, if it still occurs you might try disabling any "timer" related checkboxes in Mahou, like: `Highlight Scroll-Lock when layout 1 active` or `Activate Caps Lock disabler timer` or enabling the checkbox `Use Window Messages instead of timers` if it was disabled.

**Comment by Dra9o** [comment]
40350ef crashes without any exceptions. With manual start, Mahou does not display the tray icon. (After manual completion of the Mahou.exe process and starting Mahou again, the behavior is normal).

But

I have noticed that another .Net related applications (ThrottleStop) crashes as well (without exceptions, it was hard to notice).
So I believe now that this issue related to my Windows 7 damage (sfc tells me "ok"). Moreover, after a short test, I found that Explorer blocks many files forever. Say I could not update Mahou.exe until I restarted Explorer.exe. This is reproduced with some other files, not necessarily programs.
Perhaps you should close this question as non-Mahou?

**Comment by Dra9o** [comment]
40350ef crashes without any exceptions. With manual start, Mahou does not display the tray icon. (After manual completion of the Mahou.exe process and starting Mahou again, the behavior is normal).

But

I have noticed that another .Net related applications (ThrottleStop) crashes as well (without exceptions, it was hard to notice).
So I believe now that this issue related to my Windows 7 damage (sfc tells me "ok"). Moreover, after a short test, I found that Explorer blocks many files forever. Say I could not update Mahou.exe until I restarted Explorer.exe. This is reproduced with some other files, not necessarily programs.
Perhaps you should close this question as non-Mahou?

**Comment by BladeMight** [comment]
@Dra9o 

> crashes without any exceptions

Hm, that is quite strange, it should at least say anything. Does logs showing any line containing `[E]:`(Error)?

> Perhaps you should close this question as non-Mahou?

Maybe, but i'm kinda curious what is this all about.

**Comment by Dra9o** [comment]
Sorry for delay.

<details><summary>There are lines like this:</summary>
(I think this is ok)
08:43:32.227 [I]: Snippets with length [267], snippets count [7], errors [False], elapsed [0.827] ms.

(possible errors)
07:16:30.005 [W]: Error getting GUI info for thread id: [4248], L-W32Err: [87].
04:28:59.356 [W]: Error getting GUI info for thread id: [0], L-W32Err: [1400].
</details>

Maybe I need to install the debug version, but last time it didn't log at all (explorer.exe lock?). Specify exactly where she writes the logs and how to install it correctly (is it enough to unpack zip with a replacement?).

It is also probably worth checking this issue on another Windows 7. It is very likely, given the file blocking issue by the explorer.exe process, that this is a .Net installation issue (I had a hard time uninstalling and reinstalling the built-in version 3.5. It was imposible without .Net repair tool and 4.8 installation.).

**Comment by BladeMight** [comment]
@Dra9o 

> Error getting GUI info for thread id: [4248], L-W32Err: [87].

This seems related to "Caret display language tooltip", try disabling it in Appearance tab.

> explorer.exe lock?

Its probably about `jkl*` files, if it is - then its ok, its natural behaviour for "Global hook WH_CALLWNDPROC", you can "move" or "rename" them, but you can't delete them unless you restart/sign-out system. Actually Mahou moves them to "trash" folder if they are blocked during update and tries to delete trash folder each start.

Did you try disabling any **timer** related functions?

> this issue on another Windows 7

I did check on Windows 7 right now, however no problems were visible... Everything runs smoothly, no errors.

**Comment by Dra9o** [comment]
Yes, I turned off everything related to timers. explorer.exe blocks many files that were opened by something, say Chrome cannot overwrite its files when updating.

 I deleted the entire folder with the program and updated to the latest version.
There is a clarification - Mahou.exe is not really crashing. The tray icon just disappears. But as before - after the loss of the network there are no error messages and, of course, auto-layout does not work. ThrottleStop breaks similarly. After manually starting the scheduler task, the program is no longer sensitive to network loss. A very strange problem :) At first I thought that your program sends data entered from the keyboard and is so 'smart' that it reports a transfer error to the hacking victim. :) Users of systems in which absolutely all possible software has been installed for several years are always sure that they were hacked.

**Comment by Dra9o** [comment]
The memory consumption of the remaining Mahou process is slowly growing. There are no logs, an empty log folder is created ...

**Comment by BladeMight** [comment]
> At first I thought that your program sends data entered from the keyboard

No way! The project is open-source, and anyone can see that there are no such thing. The only network activities are done through manually actions like: downloading AS_Dict or checking for updates. The only exception is: "Automatically checking for updates" which is executed automatically - once you enable it of course.

>The memory consumption of the remaining Mahou process is slowly growing.

This is interesting, seems like it is in a kinda of "memory loss loop", dunno what more to say about it though... I have never able to reproduce such behaviour...

> A very strange problem :)

Indeed, and a rare one....

> explorer.exe blocks many files that

If its `jkl*` files then its fine, it is expected from it. Because it install a System-Wide global hook that used to "catch whenever you change layout", it is the most efficient way to determine whenever you change layout so far... so I highly suggest you do not disable jkl. Also you can overwrite only `Mahou.exe` itself, the jkl itself is updated very rarely and basically they are the same as of previous version.

**Comment by Dra9o** [comment]
> If its `jkl*` files then its fine, it is expected from it.
explorer.exe blocks many files that were opened by something, say Chrome cannot overwrite it's files when updating.

> No way! The project is open-source
Yes, now it is obvious that the problem is not with sending data.

> This is interesting, seems like it is in a kinda of "memory loss loop", dunno what more to say about it though... I have never able to reproduce such behaviour...
Let's close this issue? Or are there any other ways to get more information (for example to make a debug version to write the logs)?

**Comment by BladeMight** [comment]
@Dra9o 

> Or are there any other ways

I'll make some...

**Comment by BladeMight** [comment]
@Dra9o Here you go, test on this version:
[Special-Debug.zip](https://github.com/BladeMight/Mahou/files/4950182/Special-Debug.zip)

After starting this version it will start to show various message boxes, after clicking on ok Mahou will continue loading, tell me on which **crash** will occur, so we can narrow the area of what causes this.

**Comment by Dra9o** [comment]
When the computer boots up, all dialog boxes are shown and the program continues to run. The fall when the network is disconnected is guaranteed, without messages. When manually starting a scheduler job, the last dialog is "After Language Initialise". Probably due to the remaining Mahou process in memory. The tray icon sometimes (very rarely) appears, but when you click on it, an exception occurs similar to the one that occurs when the network is lost. The next (after manually stopping the process) launch is always normal (dialog - After Forms Initialization).

Perhaps I found the reason (well, or another minor problem). When the "Unified layout for all programs" option is activated, the system does not go into standby mode. You can check this on the screensaver settings screen - when you press the "view" button there, the screensaver appears and stops instantly. This was one of the reasons why I considered my system to be "buggy". I suspect the "Change layout only when changing windows" option may also cause this problem (unconfirmed). My theory is that when a network connection is lost, an invisible window is created in the system (or an event that changes the tray icon). And since Mahou constantly monitors windows and emulates keystrokes (taking the system out of standby mode, for example), then it starts to process this window / event too, but when it is gone.

Also this can be related to "Windows 7 Networking issue - Error: 0x80070426".

**Comment by Dra9o** [comment]
Update: After manually restarting the WAS service, Mahou is guaranteed to throw a "Before Memori Flush" exception when manually started.
[img](https://yadi.sk/i/yUp4sRwMZBa49w)

**Comment by BladeMight** [comment]
>  then it starts to process this window / event too, but when it is gone.

Interesting thought, might be true...

> [img](https://yadi.sk/i/yUp4sRwMZBa49w)

This image indicates that crash occured through "Highlight Scroll-Lock when layout 1 is active." which is actually also using a **timer**, try disabling it. Also before that can you try in 314ac36, I think I added fix just for that.

**Comment by Dra9o** [comment]
The latest update resolved the hibernation issue. Or removing the remnants of the Avast antivirus mentioned in the CBS.log helped. The rest is as it was.

**Comment by BladeMight** [comment]
@Dra9o The **hibernation issue**? You never mentioned such. Does message box mentioned in image appears again? Also have you seen any other "error message boxes"(from debug version in latest-commit releases)? They might be helpful.

**Comment by Dra9o** [comment]
> The **hibernation issue**?

This one:
> Perhaps I found the reason (well, or another minor problem). When the "Unified layout for all programs" option is activated, the system does not go into standby mode. You can check this on the screensaver settings screen - when you press the "view" button there, the screensaver appears and stops instantly.

> Does message box mentioned in [image](https://yadi.sk/i/yUp4sRwMZBa49w) appears again?
I am unable to interact with the dialog. The exception instantly appears again after 'continue' and I don't have time to click OK. The program settings window can be displayed until 'complete' is selected in the exception window.

**Comment by BladeMight** [comment]
> The hibernation issue

I could not reproduce this one also... Screensaver doesn't stop even with "One layout for all programs" enabled.

> The exception instantly appears again 

I meant this one, let me see the exception dialog's screenshot.

**Comment by Dra9o** [comment]
> I could not reproduce this one also... Screensaver doesn't stop even with "One layout for all programs" enabled.
As I said, this problem is no longer exits in the new version. Removing Avast leftovers may have helped.

**Comment by Dra9o** [comment]
[img](https://yadi.sk/i/yUp4sRwMZBa49w)

**Comment by Dra9o** [comment]
Exception text is on yellow.

**Comment by BladeMight** [comment]
@Dra9o OK, this is useful, now try in: d6dfdfc latest-commit (release_x86_x64.zip) enable and give me logs if any error occurs.

**Comment by Dra9o** [comment]
Thank you.

Tray icon still disappears, without any exception, just like ThrottleStop. But Mahou.exe stays in memory. As it was before — relaunched Mahou works fine.

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>


- Mahou 2.9.0.1-dev <8cc617e>
- OS = [Microsoft Windows NT 6.1.7601 Service Pack 1]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

Русская(68748313)
США(67699721)

</details><details><summary>Mahou.ini</summary>

```ini
[Hidden]
DisableMemoryFlush=false
ChangeLayoutOnTrayLMB=false
AS_IngoreLSTimeout=5000
AS_IngoreRules=SWMCLT
AS_IngoreLS=false
AS_IngoreDel=false
AS_IngoreBack=false
__setlayout_ONLYWM=false
__setlayout_FORCED=false
onlySnippetsExcluded=
__selection=false
CycleCaseReset=false
CycleCaseOrder=TULSR
LibreCtrlAltShiftV=false
ReSelectCustoms=tTRSULCN
AutoCopyTranslation=
[FirstStart]
First=False
[Functions]
WriteInputHistoryHourly=false
WriteInputHistoryByDate=false
AutoStartAsAdmin=True
TrayIconVisible=True
ConvertSelectionLayoutSwitching=False
ReSelect=True
RePress=False
AddOneSpaceToLastWord=True
AddOneEnterToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=True
SilentUpdate=True
Logging=False
CapsLockTimer=False
TrayFlags=True
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=true
MCDServerSupport=True
OneLayoutWholeWord=True
GuessKeyCodeFix=False
AppDataConfigs=False
RemapCapslockAsF18=True
UseJKL=True
ReadOnlyNA=False
WriteInputHistory=True
WriteInputHistoryBackSpaceType=1
TrayText=False
[Layouts]
SwitchBetweenLayouts=True
OneLayout=True
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=Русская(68748313)
MainLayout2=США(67699721)
SpecificKey1=1
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Переключать между раскладками
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
SpecificKeysType=0
SpecificKeySets=set_0
QWERTZfix=False
[PersistentLayout]
OnlyOnWindowChange=True
ChangeOnlyOnce=True
ActivateForLayout1=False
ActivateForLayout2=False
Layout1CheckInterval=50
Layout2CheckInterval=50
Layout1Processes=devenv.exe wdexpress.exe
Layout2Processes=VaporumGame.exe
[Appearence]
DisplayLangTooltipForMouse=True
DisplayLangTooltipForMouseOnChange=True
DisplayLangTooltipForCaret=True
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
MouseLTAlways=False
Language=Русский
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Georgia; 8pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Georgia; 8pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTFont=Georgia; 8pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=16
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
CaretLTTransparentBackColor=True
CaretLTFont=Georgia; 8pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=16
CaretLTPositionY=24
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
MouseLTUseFlags=True
CaretLTUseFlags=True
Layout1LTText=
Layout2LTText=
MouseLTUpperArrow=True
CaretLTUpperArrow=True
WindowsMessages=True
[Timings]
UsePasteInCS=False
ExcludeCaretLD=false
ConvertSWLinExcl=False
DelayAfterBackspaces=100
UseDelayAfterBackspaces=False
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=50
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe Hitman.Exe VaporumGame.exe
ChangeLayoutInExcluded=True
LangTooltipForMouseSkipMessages=10
[Snippets]
SnippetsEnabled=True
SpaceAfter=True
SwitchToGuessLayout=False
SnippetExpandKey=Space
[AutoSwitch]
Enabled=False
SpaceAfter=True
SwitchToGuessLayout=True
DownloadInZip=True
[Hotkeys]
SelectedTextToCustomConv_Mods=
SelectedTextToCustomConv_Enabled=False
SelectedTextToCustomConv_Double=False
SelectedTextToCustomConv_Modifiers=
SelectedTextToCustomConv_Key=0
CycleCase_Enabled=False
CycleCase_Double=False
CycleCase_Modifiers=Shift
CycleCase_Key=114
ToggleMainWindow_Enabled=False
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=True
ConvertLastWord_Double=True
ConvertLastWord_Modifiers=Shift
ConvertLastWord_Key=0
ConvertSelectedText_Enabled=True
ConvertSelectedText_Double=True
ConvertSelectedText_Modifiers=Shift
ConvertSelectedText_Key=0
ConvertLastLine_Enabled=True
ConvertLastLine_Double=True
ConvertLastLine_Modifiers=Win + Shift
ConvertLastLine_Key=0
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=True
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Win + Control
ToggleSymbolIgnoreMode_Key=0
SelectedTextToTitleCase_Enabled=True
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Control
SelectedTextToTitleCase_Key=0
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Alt
SelectedTextToRandomCase_Key=0
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win + 
SelectedTextToSwapCase_Key=190
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win + 
SelectedTextTransliteration_Key=191
SelectedToUpper_Enabled=False
SelectedToUpper_Double=False
SelectedToUpper_Modifiers=Win + 
SelectedToUpper_Key=90
SelectedToLower_Enabled=False
SelectedToLower_Double=False
SelectedToLower_Modifiers=Win + 
SelectedToLower_Key=88
ExitMahou_Enabled=False
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=False
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
ToggleLangPanel_Enabled=False
ToggleLangPanel_Double=False
ToggleLangPanel_Modifiers=Shift
ToggleLangPanel_Key=120
ShowSelectionTranslate_Enabled=True
ShowSelectionTranslate_Double=True
ShowSelectionTranslate_Modifiers=Alt
ShowSelectionTranslate_Key=0
ToggleMahou_Enabled=True
ToggleMahou_Double=False
ToggleMahou_Modifiers=Win Shift
ToggleMahou_Key=112
[LangPanel]
Display=False
Transparency=90
RefreshRate=25
Position=X0 Y1050
ForeColor=#000000
BackColor=#FFFFFF
Font=Microsoft Sans Serif; 8.25pt
BorderColor=#8B5FFF
BorderAeroColor=True
UpperArrow=True
[Updates]
Delay=5
Channel=LatestCommit(Beta)
LatestCommit=8cc617e
[Sounds]
CustomSound2=
UseCustomSound2=False
OnLayoutSwitch2=True
OnConvertLast2=False
OnSnippets2=True
OnAutoSwitch2=False
CustomSound=
UseCustomSound=False
OnLayoutSwitch=False
OnConvertLast=True
OnSnippets=False
OnAutoSwitch=True
Enabled=True
[TranslatePanel]
UseNA=True
UseGS=False
LanguageSets=set_1/auto/ru|set_2/auto/en
BG=#FFFFFF
BorderC=#F1F100
FG=#8B5FFF
Transparency=90
BorderAero=True
OnDoubleClick=False
Enabled=True
TitleFont=Segoe UI; 12pt
TextFont=Microsoft Sans Serif; 8.25pt
[Sync]
BLast=https://hastebin.com/ibifojedid
RLast=https://hastebin.com/akurovogob
RBools=1|1|1|1|0
BBools=1|1|0|0|0


</details>
<details><summary>Snippets</summary>

```
-><***ANY***>====><***ANY***>__cursorhere()</***ANY***><====
->a_time====>__date(HH:mm:ss)<====
->a_date====>__date(dd/MM/yyyy)<====
->a_date====>__date(dd, ddd MMM)<====
->a_system====>__system()<====
->фдштф====>@AlinaRinRin<====
->alina====>@AlinaRinRin<====
```
</details>
</details>

**Comment by Dra9o** [comment]
It turns out that here you can drag files directly into the message box. Sorry for putting them in a third-party cloud before :)

**Comment by BladeMight** [comment]
> Tray icon still disappears, without any exception, just like ThrottleStop. But Mahou.exe stays in memory. As it was before — relaunched Mahou works fine.

This is quite strange... If you say that error occurred only once, then... btw, did you tried starting .Net apps(ThrottleStop and Mahou separately) with delay using Task Scheduler, see 7. in [delay top](https://www.raymond.cc/blog/delay-startup-programs-to-boot-windows-faster/)

Also try disabling "Startup updates check" and "Silent update", and see if it helps.

**Comment by Dra9o** [comment]
This crash was caused by WMI store corruption and wrong security ACLs in registry. After WMI store recreation and some other corrections Mahou and ThrottleStop both start with big delay (task in queue). Mahou does not react at any network changes, ThrottleStop crashes as it was before.
But ThrottleStop developer wrote in description that Windows 7 support is limited. Also this problem is not related to Mahou. So issue is closed now...
