### ISSUE TITLE
Двойной shift для переключения раскладки

### ISSUE THREAD

**Issue by avently** [BladeMight/Mahou#28]
Будет очень удобно, если появится возможность установить двойное нажатие shift (или любой другой клавиши - кому как удобно) для переключения последнего слова и выделенного текста. Шифт всегда под рукой, никаких дополнительных клавиш искать не надо. Пару раз нажал и готово. Как вам такая идея? Можете реализовать?

И еще, не задумывались ли вы о такой фиче, как автозамена? К примеру, установил какое-то слово, которое должно заменится на другое слово: eml = moyemail@email.com и т.д. Списочек коротких слов и их полных версий по-началу можно тупо вписывать в конфигурационный файл, чтобы не возиться с изменением интерфейса. Ввел слово, нажал пробел и появилась его замена - красота.

P.S. До вашей программы использовал Everylang, но опенсорс вне конкуренции

**Comment by avently** [comment]
а, и кстати, попробуйте настроить быстрыми клавишами shift+a. После этого ввожу ghbdtn и после нажатия горячих клавиш получаюприветФ. То есть перед словом убирается пробел и в конец добавляется та буква, что значится последней в комбинации горячих клавиш.
Windows 10.

**Comment by BladeMight** [comment]
> Шифт всегда под рукой, никаких дополнительных клавиш искать не надо. Пару раз нажал и готово. Как вам такая идея? Можете реализовать?

Думаю да, вполне реально.

> И еще, не задумывались ли вы о такой фиче, как автозамена?

До сего момента - нет, но думаю можно будет реализировать.

> Ввел слово, нажал пробел

Пробел? А может лучше тоже гор. клавишу? А то вдруг вам нужно будет просто написать то самое слово?

> но опенсорс вне конкуренции

Рад что вы тоже так считаете...

> а, и кстати, попробуйте настроить быстрыми клавишами shift+a.

Ну так это поведение шифта, то есть нужно убрать возможность писать Shift+A при назначении его горячей клавишей? И вообще мне кажется горячая клавиша Shift + любая письменная клавиша - не правильно, из-за невозможности напечатать ее с Shift.

**Comment by avently** [comment]
Про шифт + А согласен. 
По поводу пробела и автозамены - думаю, стоит для автозамены выбирать именно такие короткие слова, которых не существует в языке. То есть нелогично использовать слово "email", так как его используешь в тексте. А вот какие-нибудь другие сокращения, типа eml, ml, mml вполне можно сделать. Я сторонник того, чтобы было все настолько просто, насколько возможно. Запоминать ещё одну комбинацию клавиш, в дополнение к тем, что используются виндой, фотошопом, браузером и т.д. - это не есть просто. Только если использовать пробел, то нужно его подчищать после замены на  заготовленное слово. А то

**Comment by BladeMight** [comment]
Весьма проблематично получается, придется переделывать весь метод использования горячих клавиш, и это займет много времени, так что пока могу сказать: "Ждите!"

**Comment by BladeMight** [comment]
Уже есть успехи, по поводу нового метода горячих клавиш.

**Comment by avently** [comment]
Первый раз встречаю разработчика,который так оперативно действует. Спасибо!

**Comment by BladeMight** [comment]
Вот можете пока проверить бетку:
[Mahou_BETA.gz](https://github.com/BladeMight/Mahou/files/491691/Mahou_BETA.gz)

**Comment by avently** [comment]
иногда текст ghbdtn становится ПРИВЕТ. То есть делает с капсом, хотя его не было изначально. Если же включить перенажатие и активировать горячую клавишу, иногда система виснет на несколько секунд и видно как текст меняет раскладку туда сюда с десяток раз и меняется в трее русский на английский и наоборот. И почему-то иногда бывает текст сам меняет раскладку даже тогда, когда я не нажимал горячую клавишу. Может, это следствие глюка при активированном перенажатии.

Если скопировать вышенаписанный текст, нажать горячую клавишу, затем нажать снова - получится абракадабра, с использованием английской раскладки, а не эталонный русский текст.

**Comment by BladeMight** [comment]
> Если же включить перенажатие и активировать горячую клавишу, иногда система виснет на несколько секунд

Да я уже заметил.

Сейчас вот что получается у меня(КВ-Ключ вкл., конверт линии назначеной на Shift) в блокноте :

>byjulf ntrcn ghbdtn cnfyjdbncz GHBDTN/ Nj tcnm ltkftn c rfgcjv? [jnz tuj yt ,skj bpyfxfkmyj/ Tckb ;t drk.xbnm gthtyf;fnbt b frnbdbhjdfnm ujhzxe. rkfdbie? byjulf cbcntvf dbcytn yf ytcrjkmrj ctreyl b dblyj rfr ntrcn vtyztn hfcrkflre nelf c.lf c ltcznjr hfp b vtyztncz d nhtt heccrbq yf fyukbqcrbq b yfj,jhjn/ B gjxtve-nj byjulf ,sdftn ntrcn cfv vtyztn hfcrkflre lf;t njulf? rjulf z yt yf;bvfk ujhzxe. rkfdbie/ Vj;tn? 'nj cktlcndbt uk.rf ghb frnbdbhjdfyyjv gthtyf;fnbb/

И назад:

>иногда текст привет становится ПРИВЕТ. То есть делает с капсом, хотя его не было изначально. Если же включить перенажатие и активировать горячую клавишу, иногда система виснет на несколько секунд и видно как текст меняет раскладку туда сюда с десяток раз и меняется в трее русский на английский и наоборот. И почему-то иногда бывает текст сам меняет раскладку даже тогда, когда я не нажимал горячую клавишу. Может, это следствие глюка при активированном перенажатии.

**Comment by avently** [comment]
если копирую ВЕСЬ текст из вашего сообщения byjulf ntrcn ghbdtn......и так далее,  то он остается таким же после двойного шифта (вообще не изменяется). Если копирую это:
byjulf ntrcn ghbdtn cnfyjdbncz GHBDTN/ Nj tcnm ltkftn c rfgcjv?

то получается это:

иногда текст привет становится ПРИВЕТ/ То есть делает с капсом?

Если копирую это:
byjulf ntrcn ghbdtn

то получатся норм:

иногда текст привет

То есть происходит что-то непонятное. При этом я ВЫДЕЛЯЮ весь текст и активирую двойной шифт, а не использую конверт линии. При конверте линии все ок работает. Так что, видимо, дело в выделении текста.

**Comment by BladeMight** [comment]
А если не на двойной шифт?

**Comment by avently** [comment]
копирую тот текст из вашего сообщения с английскими буквами, выделяю, зажимаю горячие клавиши (не шифт), получаю тот же текст без изменений. Нажимаю еще раз:

иногда текст привет становится ПРИВЕТ/ То есть делает с капсом? хотя его не ,ыло изначально/ Если ;е вкл.чить перена;атие и активировать горячу. клавишу? иногда система виснет на несколько секунд и видно как текст меняет раскладку туда с.да с десяток раз и меняется в тре руский на английский и нао,орот/ И почему-то иногда ,ывает текст сам меняет раскладку да;е тогда? когда я не на;имал горячу. клавишу/ Мо;ет? это следствие гл.ка при активированом перена;ати/

А это если выключить КБ-ключ:

иногда текст привет становится ПРИВЕТ| То есть делает с капсом& хотя его не ?ыло изначально| Если $е вкл/чить перена$атие и активировать горячу/ клавишу& иногда система виснет на несколько секунд и видно как текст меняет раскладку туда с/да с десяток раз и меняется в трее русский на английский и нао?орот| И почему-то иногда ?ывает текст сам меняет раскладку да$е тогда& когда я не на$имал горячу/ клавишу| Мо$ет& это следствие гл/ка при активированном перена$атии|

**Comment by BladeMight** [comment]
> получаю тот же текст без изменений

ВОТ, это потому что КВ-Ключ включен, то есть текст будет распознаваться по текущему языку ввода, благодаря чему не будет проблем с символами.
Поэтому перед конвертацией установите язык в тот на котором написан текст.

P.S. Из-за того что сейчас все пишется в консоль, скорость конвертации снижена и могут быть непредвиденные баги. Вот без записи в консоль:
[Mahou-Beta2.gz](https://github.com/BladeMight/Mahou/files/491735/Mahou-Beta2.gz)

**Comment by BladeMight** [comment]
> Поэтому перед конвертацией установите язык в тот на котором написан текст.

Кстати текст можно вернуть обратным путём.

**Comment by avently** [comment]
а, ну да, если текст был eng и раскладка eng, то нормально меняет на русский при включенном кв-ключ. Даже с двойным шифтом. 
Конечно, это не сильно юзер-френдли решение. Это мы с вами знаем про этот "фокус", а другие-то пользователи - нет. Если бы можно было без указания языка оригинала текста менять раскладку текста, то было бы гораздо понятнее всем, в том числе программе:)

А как быть с капсом: привет = GHBDTN?

Попробуйте установить двойной шифт горячей клавишей. Затем зажать один шифт, выделить любое написанное слово стрелками, не отпуская шифт, отпустить шифт. Подсказываю - сменится раскладка. Такого, по идее, быть не должно

**Comment by avently** [comment]
К примеру, если есть у пользователя две раскладки. Текст такой - ghbdtn. Фиксируется выделенный текст, соотносится с какой-то раскладкой из раскладок юзера, берется вторая раскладка и в нее конвертируется. Проще простого, разве нет7

**Comment by BladeMight** [comment]
> соотносится с какой-то раскладкой из раскладок юзера

Именно это и делает Конверт выделения без КВ-Ключ, но символы есть в обеих раскладках, так что есть проблемы с ними.

>  Затем зажать один шифт, выделить любое написанное слово стрелками, не отпуская шифт, отпустить шифт.

Вроде все нормально.
[Mahou-Beta3.gz](https://github.com/BladeMight/Mahou/files/491781/Mahou-Beta3.gz)

**Comment by avently** [comment]
Все также на длительное нажатие шифт меняет раскладку, а должен на двойное нажатие шифт (только конвертация выделения, конвертация слова - ок).

Сейчас получается так, что, насколько я понял, определяется принадлежность каждой отдельной буквы (или слова) к языку и затем она меняется на букву противоположного языка. Уверены, что это лучше, чем определять один раз и весь текст переиначить в нужный язык?

Возьмем текст:
Rjvgfybz Мщдмо - kblth yf hsyrt fdnj/

Попробуйте "перекодировать" его. Ваш метод у каждого слова будет определять язык, что не есть подходяще. Ведь я писал текст неверной раскладкой на протяжении всего участка текста, который я в последствии выделю для перекодировки, значит и перекодировать нужно весь текст одинаково, а не каждое слово в отдельности. 

Результат сейчас:
Компания Мщдмо - лидер на рынке авто.

Ожидаемый результат:
Компания Volvo - лидер на рынке авто.

Не знаю, понятно ли я описал или нет, если что - спросите.

> Именно это и делает Конверт выделения без КВ-Ключ, но символы есть в обеих раскладках, так что есть проблемы с ними.

Не совсем понял, о чем вы. Я копирую тот текст для проверки (byjulf ntrcn ghbdtn cnfyjdbncz GHBDTN/ Nj t     и так далее), устанавливаю русский язык и текст остается прежним после перекодировки и меняется раскладка на eng. После следующей итерации текст перекодируется. Вывод - используется не тот механизм определения принадлежности текста, о котором я писал выше, а именно текущая раскладка.

**Comment by BladeMight** [comment]
> Ожидаемый результат:
Компания Volvo - лидер на рынке авто.

Для такого результата нужно выключить КВ-Ключ. [Подробнее](https://github.com/BladeMight/Mahou/issues/18)

> текст остается прежним

Это говорит о том что КВ-Ключ включен.

> Вывод - используется не тот механизм определения принадлежности текста, о котором я писал выше, а именно текущая раскладка.

__без КВ-Ключ__

**Comment by avently** [comment]
Сорри, видимо, забыл нажать "Применить". 
Такой результат:
Компания Volvo - лидер на рынке авто|

Значит, с символами пока что беда осталось и с шифтом при выделенном тексте.

**Comment by BladeMight** [comment]
> шифтом при выделенном тексте

Вот этого я не могу понять... У меня  работает нормально.
Давай я лучше объясню как работает:
При отпускании первый раз Shift стартует таймер с временем указанном в настройках, и ожидает отпускания второго раза Shift, если время таймера истекло то все начинается заново.
Ну так вот что я подумал, вы каким-то дивным образом отпускаете Shift 2 раза?

**Comment by avently** [comment]
Просто выделите текст, нажмите шифт один раз и отпустите. 

Нашел баг:)
Он проявляется только тогда, когда для конвертации слова тоже указан двойной шифт.

**Comment by BladeMight** [comment]
> Он проявляется только тогда, когда для конвертации слова тоже указан двойной шифт.

Вот так уже понятно.

**Comment by avently** [comment]
Не заметил багов в buggy, как не заметил их в пререлизе. Вроде все круто, за исключением символов.
Что подумал, раз у вас получилось каким-то неизвестным образом с включенной КВ-ключ правильно менять символы, то может объединить эти способы и сделать один - универсальный? Надо бы посмотреть исходники и найти всю магию

**Comment by BladeMight** [comment]
> Не заметил багов в buggy

Для создания бага нужно:
КВ-Ключ вкл., Shift на Конверт выделения и слова.
После этого попробуйте конвертировать выделение 2+ раза.

> то может объединить эти способы и сделать один - универсальный?

Может быть.

>  Надо бы посмотреть исходники

Буду только рад.

**Comment by avently** [comment]
А у вас есть какие-то идеи, как с символами быть? Мне сишарповский синтаксис и методы непонятны...

**Comment by BladeMight** [comment]
> А у вас есть какие-то идеи, как с символами быть?

Да есть, но нужно ее до-думать. И это уже другая проблема... 
Так что эта решена?(закрываем и делаем релиз?)

> Мне сишарповский синтаксис и методы непонятны...

Жаль...

**Comment by avently** [comment]
Мне понятны Objective-C, PHP (на уровне - а, понимаю, как правильно скопипастить и изменить, чтобы работало), Java (как и PHP).

Можно и закрыть и сделать релиз, если вас устраивает эта проблемка с символами. Просто я, когда проги делал, спать не мог, если выкачу недопиленный релиз:) Прям все мысли о том, что надо бы доработать. А то некомильфо получается:)

А так, да, текущий вопрос решен благодаря вам. Спасибо.

**Comment by BladeMight** [comment]
>  если вас устраивает эта проблемка с символами.

Не она меня не устраивает, но я же говорил надо до-думать способ, поэтому я решил пока что опубликовать достигнутое, и создать новую issue по проблеме с символами.

И еще по поводу:
>И еще, не задумывались ли вы о такой фиче, как автозамена?

Тоже лучше создать отдельную issue.

**Comment by avently** [comment]
ok, создам обе тогда. А эту закрываю

**Comment by avently** [comment]
По сути, эта issue об этом же:
https://github.com/BladeMight/Mahou/issues/18

Так что можно новую не открывать, а доработать старую

**Comment by BladeMight** [comment]
>По сути, эта issue об этом же

Ну да, создай там коммент и ОК.
Сейчас сделаю релиз, и думаю на сегодня хватит.

**Comment by avently** [comment]
в последней версии поломан конверт слова на двойной шифт, но конверт выделения работает. Поставил версию 0.1 - работает как надо.

**Comment by BladeMight** [comment]
> конверт слова на двойной шифт

Не конверт слова на двойной шифт, а конверт слова при конверт выделения и конверт слова установленных на двойной шифт.
Сейчас посмотрю почему...

**Comment by BladeMight** [comment]
Нашел, все потому что слово очищалось последним добавленным правилом, Ctrl+Any Key в Конверт выделения при копировании текста, сейчас уже исправил, добавив исключение для правила Ctrl+Any Key, что только когда пользователь нажмет  Ctrl+Any Key слово будет очищаться.
Скоро будет релиз.
