### ISSUE TITLE
Semicolon key in Greek produces unwanted output

### ISSUE THREAD

**Issue by acicovic** [BladeMight/Mahou#292]
Hi,

In Greek, the semicolon key (the key next to L in a QWERTY keyboard) is used to put accents. Pressing the semicolon key and then a letter will produce an accented letter (for example έ instead of ε).

### Expected behavior
Pressing semicolon key in Greek keyboard layout should produce no output and put an accent on the next vowel that will be pressed.

### Actual behavior
Pressing semicolon key results sometimes in ΄΄ output, accents do not work correctly.

### Operating system
Windows 10 64 bit

### Steps to reproduce the behavior
- Install Greek keyboard layout in OS
- Run Mahou
- Switch to Greek
- Start typing words with accents and see semicolon results

Note: as this might not be an easy process, I can test it out.

### Useful info
Utilities such as Espanso and BeefText had similar issues, which they solved in https://github.com/federico-terzi/espanso/commit/5f71d0ad2483dfb366aff4a069246fd95b1a7793 and https://github.com/xmichelo/Beeftext/commit/d12e192bb1aaf49c83ba7543e0aa3e12c18fa675 respectively. I had reported the issue for BeefText in https://github.com/xmichelo/Beeftext/issues/107.

I hope this will facilitates the task if you decide to tackle the issue. Let me know how I can be of help if needed.

Thanks!

**Comment by BladeMight** [comment]
Thanks for `Useful info`, it made everything real quick, check out latest-commit: 3c40e90

**Comment by acicovic** [comment]
From quick tests this seems to work wel. Let me test it thoroughly for a few days because I will have limited time on the computer. If everything goes well I will mark this as resolved.

Thanks!

**Comment by BladeMight** [comment]
Okay. But I think everything will be fine.

**Comment by acicovic** [comment]
Yes, me too 😃

**Comment by acicovic** [comment]
Since the last update I'm getting exceptions. The flag icon becomes a red X and I get the following message:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Object is currently in use elsewhere.
   at System.Drawing.Image.get_Flags()
   at System.Windows.Forms.ControlPaint.IsImageTransparent(Image backgroundImage)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle)
   at System.Windows.Forms.Control.OnPaintBackground(PaintEventArgs pevent)
   at System.Windows.Forms.ScrollableControl.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmEraseBkgnd(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Mahou
    Assembly Version: 2.9.0.1
    Win32 Version: 2.9.0.1
    CodeBase: file:///C:/Portable%20Program%20Files/Mahou/Mahou.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by BladeMight** [comment]
Seems like native exception, according to [1](https://stackoverflow.com/a/1852451/5420570), seems like I can't have only one static "Flag" bitmap, I have to create bitmap for each thread that uses it. Sadly...

**Comment by acicovic** [comment]
OK, at least it was easy to find the source of the problem and a possible approach to fixing this. I'm not in a hurry, take your time to fix this.

Thank you so much for your responsiveness.

**Comment by BladeMight** [comment]
> Bitmap, I have to create bitmap for each thread that uses it

Or I can make only one thread to use it(as it was before latest-release), fixed in 06066dd.

**Comment by acicovic** [comment]
OK, will check it out and report.

**Comment by acicovic** [comment]
No other issues so far, so closing this. I will reopen if needed.

Thank you!
