### ISSUE TITLE
транслитерация последней линии

### ISSUE THREAD

**Issue by Shedevri** [BladeMight/Mahou#296]
Очень не xватает в горячиx клавишаx транслитерация последней линии.
можно ли как то сделат другим способом чтобы при нажати клавиши транслировалась вся линия?
сейчас надо выделят слово а потом нажат

**Comment by BladeMight** [comment]
Чем <kbd>Shift</kbd>+<kbd>Home</kbd> и  `твоя гор. клавиша транслитерации выделения` не вариант?

**Comment by Shedevri** [comment]
чтобы нажат шифт + хоме я еше должен нажат FN без него home ето стрелка влево, то ест надо нажимат 4 клавиши :)

**Comment by BladeMight** [comment]
Если пользуешься AutoHotkey можно сделать так:

```ahk
!^t::
Send {LShift down}{Home}{LShift up}
Send {F24}
return
```
А потом в Mahou назначить гор. клавишу "транслитерации на F24", используя `^!t` = `Control+Alt+T`, т.е. нажать в "поле гор. клавиши" `Ctrl+Alt+T`. а потом можно пробовать, пример:
```
pishem liniyu i nazhimaet Kontrol Aljt i T
```

**Comment by Shedevri** [comment]
> Если пользуешься AutoHotkey можно сделать так:
> 
> ```ahk
> !^t::
> Send {LShift down}{Home}{LShift up}
> Send {F24}
> return
> ```
> 
> А потом в Mahou назначить гор. клавишу "транслитерации на F24", используя `^!t` = `Control+Alt+T`, т.е. нажать в "поле гор. клавиши" `Ctrl+Alt+T`(после того как запустил Скрипт AHK), а потом можно пробовать, пример:
> 
> ```
> pishem liniyu i nazhimaet Kontrol Aljt i T
> ```

ну ето еше одна лишняя программа висячая на панели задач , мой путь минимализм :)

**Comment by BladeMight** [comment]
> висячая на панели задач

можно `#NoTrayIcon` использовать

**Comment by Shedevri** [comment]
а функциями Mahou никак не сделать?

**Comment by BladeMight** [comment]
На данный момент горячие клавиши в Mahou - не *гибкие*, т.е. какие действия стоят такие и выполняются. Я думаю сделать *гибкие* горячие клавиши чтобы можно было добавлять к горячим клавишам различные действия вроде симуляции Shift+Home и т.д. Но на данный момент этого нет, и делать "отдельную гор. клавишу" для этого - много кода и мне кажется не очень правильным.

**Comment by Shedevri** [comment]
> На данный момент горячие клавиши в Mahou - не _гибкие_, т.е. какие действия стоят такие и выполняются. Я думаю сделать _гибкие_ горячие клавиши чтобы можно было добавлять к горячим клавишам различные действия вроде симуляции Shift+Home и т.д. Но на данный момент этого нет, и делать "отдельную гор. клавишу" для этого - много кода и мне кажется не очень правильным.

ясно буду ждат гибкийе горячийе клавиши

**Comment by BladeMight** [comment]
@Shedevri В 2d66c5a обновил немного скрытое пользовательское меню в трее: [Mahou.mm](https://github.com/BladeMight/Mahou/wiki/Mahou.mm_RU) теперь добавил возможность "симуляции клавиатуры" и вызова действий стандартных гор. клавиши и также "несколько действий" для одного элемента меню(и гор. клавиши если указана для этого элемента меню), в общем теперь можно сделать "Транслитерацию линии", вот так:


Сохрани это в файл `Mahou.mm` рядом с `Mahou.ini`.
```
||||##Mahou-Пользовательское-меню##
Транслитерация линии|^^LAlt+LCtrl+T|multi|kbd|lshift+home|hk|s0
```

Объясняю:

`mutli` = выполняются следующие действия после неё(сколько угодно), в данном примере их 2:
`kbd`  = одно из действий multi, посылает LShift+Home
`hk`    = еще одно из действий multi, вызывает гор клавишу s0 = Транслитерация

Описание и синтаксис Mahou.mm смотри тут: [MahouMM_RU](https://github.com/BladeMight/Mahou/wiki/Mahou.mm_RU)

**Comment by BladeMight** [comment]
Проверить можно в latest-commit, 

Для обновления до latest-commit:
1. Во вкладке "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление)
2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - Release_x86_x64.zip)

**Comment by Shedevri** [comment]
все сделал работает урааааа.
Спасибо огромное
