### ISSUE TITLE
Клавиатурные индикаторы

### ISSUE THREAD

**Issue by HYBRID-BEING** [BladeMight/Mahou#297]
## Описание запроса

Хотелось бы иметь возможность отображать иконку, указывающую состояние Caps Lock, Num Lock, Scroll Lock в трее (или несколько). Было бы полезно для клавиатур не имеющих индикаторов Caps Lock, Num Lock, Scroll Lock (или имеющих, но неисправные).

Функционал уже реализован нексколькими приложениями (http://roidayan.com/keyboard-indicator/, https://keyboard-leds.com/, https://www.traystatus.com/), но хотелось бы иметь всё в одной корзине.

**Comment by BladeMight** [comment]
@HYBRID-BEING Что-то вроде такого?
[Mahou_NCS.zip](https://github.com/BladeMight/Mahou/files/5506977/Mahou_NCS.zip)

(Запусти эту версию и в трее появятся(автоматически) N C S иконки, которые меняются с "черных" на "желтые", при изменении состояния Num/Caps/Scroll)

**Comment by HYBRID-BEING** [comment]
Вроде этого, ага.
К этому, минимум хотя бы добавить возможность выбрать нужные индикаторы - например, у меня Caps Lock имеет LED, а Scroll Lock вобще отсутствует. Ну а когда-нибудь потом можно и больше настроек - внешний вид, действия по ЛКМ, использования одну иконку для

**Comment by BladeMight** [comment]
@HYBRID-BEING Сделал как скрытую функцию в latest-commit, и добавил настраиваемости в Mahou.ini ищи `NCS_tray` и `NCS`:

```ini
[Hidden]
NCS_tray=false
NCS=NCS
```

- `NCS_tray` - может быть `true` или `false`, если `true` означает что иконки будут показываться, после изменения и сохранения Mahou.ini можно нажать применить в Mahou.
- `NCS` - какие иконки показывать, "строка" которая может содержать `N`(NumLock), `C`(CapsLock) и `S`(ScrollLock), по-умолчанию стоит `NCS` т.е. все три.

**Comment by HYBRID-BEING** [comment]
Полёт нормальный.
