### ISSUE TITLE
Замена раскладки в строках

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#3]
Здравствуйте, могли бы Вы сделать, так, чтобы при нажатии хоткея раскладка заменялась бы в строке, а не последнем написанном слове?

![Саша Священная](http://i.imgur.com/xlZJXZM.gif)

Из всех программ, альтернативных Вашей, я нашёл, что эта необходима мне функция присутствует  лишь в LangOver, но LangOver некорректно работает в Sublime Text, подробности [тут](https://forum.sublimetext.com/t/tune-up-langover-in-sublime-text/21819).

Спасибо.

**Comment by BladeMight** [comment]
Эта функция была еще с основания, но была ошибка в последних версиях, так что вот исправленная версия -> [Mahou v1.0.3.9](https://github.com/BladeMight/Mahou/releases/tag/v1.0.3.9)

**Comment by BladeMight** [comment]
Только что проверил в Sublime Text 3, работает отлично.

**Comment by Kristinita** [comment]
> вот исправленная версия -> Mahou v1.0.3.9

Извиняюсь, а где там исполняемый файл? Спасибо.

**Comment by BladeMight** [comment]
Хм, а я вроде загрузил... видимо ошибка была, перезалил, проверь [теперь](https://github.com/BladeMight/Mahou/releases/tag/v1.0.3.9)

**Comment by Kristinita** [comment]
@BladeMight , по-прежнему меняется раскладка только у последнего слова либо выделенных слов, смены раскладки строки в один клик как у LangOver не происходит.

Отдельную горячую клавишу неплохо бы выделить для переключения раскладки в строке, т. е. какие хоткеи мне бы пригодились:

+ Смена раскладки в последнем слове,
+ Смена раскладки в выделенном тексте,
+ Смена раскладки в строке (новая).

Спасибо.

**Comment by BladeMight** [comment]
Точно? Я же говорил что если отключить галочку **Space begins new word** то тогда будет конвертировать всю строку.
Насчет новой горячей клавиши, думаю можно.

**Comment by Kristinita** [comment]
@BladeMight, прошу прощения, невнимательность проявил. Спасибо, ждём горячей клавиши!

**Comment by BladeMight** [comment]
Готово в [версии 1.0.4.0](https://github.com/BladeMight/Mahou/releases/tag/v1.0.4.0) добавлена функция конвертирования линии по умолчанию назначена на `Shift+Pause/Break`.
P.S. Удалите свой файл конфигурации `Mahou.settings` с прошлых версии, т.к. произошли некоторые изменения и старая конфигурация может вызвать проблемы.
