### ISSUE TITLE
[Bug] Swedish keyboard layout displayed as English 

### ISSUE THREAD

**Issue by OleksandrKucherenko** [BladeMight/Mahou#30]
![image](https://cloud.githubusercontent.com/assets/6419758/18825037/9fa2674c-83c6-11e6-8fe4-199321953163.png)

**Comment by BladeMight** [comment]
No you're wrong, it just not displayed, tell me the code displayed in Mahou locales:
![a](https://cloud.githubusercontent.com/assets/11931888/18828398/662a8ec6-83e0-11e6-8d60-385356e1894a.png)

**Comment by BladeMight** [comment]
Check out [this](https://github.com/BladeMight/Mahou/releases/tag/v1.3.0.1) version.
P.S. Close issue if it solved.
