### ISSUE TITLE
Регулярки в сниппетах не работают

### ISSUE THREAD

**Issue by ux01** [BladeMight/Mahou#303]
Регулярки в сниппетах не работают или работают не так. Проверял и на простейших своих регулярках, вроде:

```
->regex/\d\d/
====>xxx<==== (нулевой результат)
````
И на некоторых сниппетах из раздела полезных:

СЕгодня => Сегодня

```
->regex/^([А-ЯA-Z])([А-ЯA-Z][а-яa-z])([a-zA-ZА-Яа-я]*)(?!.*? )/
====>$1\L$2$3<==== 
```

Слушал музыку. за окном шел дождь. => Слушал музыку. За окном шел дождь.
```
->regex/([\.!?])[ ](.)(.*)/
====>$1 \U$2\E$3<====
```

Подмена старого обозначения российского рубля официальным знаком:
```
->regex/^(.*)(\d+)[ ](р.|руб.|рубл.|RUB)(?!.*? )$/i
====>$1$2 ₽<====
```

Из них работает только последняя, но частично. Превращения такие:
"2 р." - не меняется.
"2 руб." - 2 $1$2 ₽ (именно в таком виде)
"2 рубл." - 2 $1$2 ₽
"2 RUB" - не меняется.
И точка, похоже, работает не как "любой символ", а как реальная точка. То же касается и $1$2.

Версия Mahou последняя стабильная. Win10.

**Comment by BladeMight** [comment]
Используй latest-commit:

Для обновления до latest-commit:
1. Во вкладке "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление)
2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - Release_x86_x64.zip)

> последняя стабильная

самая стабильная сейчас - latest-commit.

**Comment by ux01** [comment]
Спасибо, помогло. Я, как обычно, прочитал только половину слов и подумал, что beta-версия здесь обыкновенная, а не наоборот - самая стабильная. Но, может, стоит сделать самый очевидный вариант - в Latest release отправлять стабильные версии, а в Pre-release - нестабильные бета-вверсии?

**Comment by BladeMight** [comment]
> что beta-версия здесь обыкновенная, а не наоборот - самая стабильная

Ну обычно оно так, но в Mahou я делаю исправления сразу как найду проблему поэтому версия "с последними изменениями" - самая стабильная т.к. содержит больше исправлений чем "замороженная" стабильная.

>нестабильные бета-вверсии

Таких нет… Ну если latest-commit не стабильная - значит нужно это исправить, вот так вот.
