### ISSUE TITLE
Баг с конвертацией при выделенной подсказке от браузера

### ISSUE THREAD

**Issue by nikitasA1NT** [BladeMight/Mahou#306]
На последнем Beta обновлении вот такой баг появился:
![image](https://user-images.githubusercontent.com/57367746/103546016-d12a6700-4ebb-11eb-93d3-28a2aaee1bce.png)
Конвертируем и...:
![image](https://user-images.githubusercontent.com/57367746/103546048-dab3cf00-4ebb-11eb-8049-58921058e7a4.png)
После обновления в настройках ничего не менял, кроме того, что задал вот здесь другие символы:
![image](https://user-images.githubusercontent.com/57367746/103546152-fc14bb00-4ebb-11eb-9495-ca72aa37fc9f.png)

**Comment by BladeMight** [comment]
@nikitasA1NT Точно ничего другого не менял? У меня работает как и раньше:
![yap](https://user-images.githubusercontent.com/11931888/103571436-e9aa7980-4edb-11eb-9de6-27d9c6d304eb.gif)

**Comment by nikitasA1NT** [comment]
Дк вроде же должен конвертироваться не выделенный текст, а тот, что был введен. На гифке противоположное показывается

**Comment by BladeMight** [comment]
> Баг с конвертацией при выделенной подсказке

Я думал что ты имеешь в виду что при её выделении конвертацией выделения. А конвертация последнего работает так же как и раньше:
![raduj](https://user-images.githubusercontent.com/11931888/103579768-f6ce6500-4ee9-11eb-9b4c-f16a473ea44e.gif)

**Comment by nikitasA1NT** [comment]
Можно как-то сбросить настройки программы на изначальные по-умолчанию? У меня просто та же проблема

**Comment by BladeMight** [comment]
> как-то сбросить настройки программы на изначальные по-умолчанию

закрой Mahou, удали/перемести/переименуй **Mahou.ini**, и запусти Mahou опять.

**Comment by BladeMight** [comment]
P.S. А может у тебя назначены на одну горячую клавиши "конвертация выделения" и "последнего слова"?

**Comment by nikitasA1NT** [comment]
Нет, при конвертации выделения "выкл" та же фигня. Щас попробую удалить .ini файл...

Да, дело было в том, что у меня одна и та же клавиша была на "конвертация выделения" и "последнего слова". Но что странно, так это то что у меня на предыдущем коммите клавиши были одни и те же, но проблемы этой не было. Хотя я также мог конвертировать выделенный текст. Видимо вы на последнем коммите сделали отслеживается всегда как-то выделения текста. Даже если никакие клавиши не прожимались системные для его выделения, последняя клавиша была нажата просто за ввод символа отвечающая.

Также еще баг. Даже если конвертация выделения у меня выключена она всё равно работает если она на Control забиндена. Если забиндить допустим на Shift, то такой проблемы нет при выключенном "конвертация выделения"

**Comment by nikitasA1NT** [comment]
Попробуйте забиндить одну и ту же клавишу на "конвертация выделения" и "последнего слова" на последнем коммите и предыдущем. На предыдущем проблемы точно не было той, про которую текущий issue

**Comment by BladeMight** [comment]
> Но что странно, так это то что у меня на предыдущем коммите клавиши были одни и те же, но проблемы этой не было

В самом деле странно, если они стоят на одну гор. клавишу, значит сначала будет выполнятся "конвертация выделения", а так как выделение есть, она выполнится 100% а "конвертации последнего" не выполнится...

>  Даже если конвертация выделения у меня выключена она всё равно работает если она на Control забиндена. Если забиндить допустим на Shift, то такой проблемы нет при выключенном "конвертация выделения"

Странно, может в Mahou.mm есть дубликат? Вот у меня при выкл. ничего не происходит:
![ctrlsel](https://user-images.githubusercontent.com/11931888/103585662-84af4d80-4ef4-11eb-9825-a68795dffac4.gif)

**Comment by BladeMight** [comment]
>В самом деле странно, если они стоят на одну гор. клавишу, значит сначала будет выполнятся "конвертация выделения", а так как выделение есть, она выполнится 100% а "конвертации последнего" не выполнится...

Хотя нет, они просто оба "выполнялись", а если выключить "выделять заново текст после конвертации", тогда и начинает *неправильно работать*, объясняю:

1. Сначала происходит конвертация выделения на "выделенном"(т.е. подсказка chrome), если "выделять заново текст после конвертации", то позже Mahou не будет удалять это "выделенное".
2. Если есть выделение Mahou его удаляет, но его может и не быть если не включена "выделять заново текст после конвертации".
3. Обычная конвертация последнего слова.

Кстати на "выделять заново текст после конвертации" влияет настройка в [Hidden]: 
![2021 01 05 - 00'34'09_rect](https://user-images.githubusercontent.com/11931888/103586427-1e2b2f00-4ef6-11eb-8a00-ccc5a1085835.jpg)

Где:

- t - Транслитереация выделения
- T Выделение в заглавный регистр
- R Выделение в случайный регистр
- S Выделение в обратный регистр
- U Выделение в верхний регистр
- L  Выделение в нижний регистр
- C Особое изменение текста
- N обычная "Конвертация выделенного текста"

**Comment by BladeMight** [comment]
Кстати еще при всём этом, на результат влияет "Смена раскладки в Конверт выделения", т.к. она явно меняет раскладку перед "конвертацией последнего слова" и если у тебя только 2 раскладки результат будет такой же как и до конвертации, см: с момента где пишу "рецепт".
![ctrlsel](https://user-images.githubusercontent.com/11931888/103587237-dc02ed00-4ef7-11eb-980e-8ce042a11101.gif)

**Comment by nikitasA1NT** [comment]
Короче сделал вот так:
![image](https://user-images.githubusercontent.com/57367746/103587201-28eac180-4f00-11eb-8c74-4de26da05e22.png)
и всё стало хорошо, как на предыдущем коммите при одной и той же забинденной клавише.

**Comment by BladeMight** [comment]
На всякий случай напишу, для твоих настроек:
1. Одна и та же горячая клавиша на "Конвертация выделения" и "Конвертация последнего слова".
2. Включить ☑️ "Выделять заново текст после конвертации"
3. Проверить в [Hidden] "Reselect customs", tTRSULCN = это стандартное значение, т.е. для всех горячих клавиш. Поставить хотя бы N.
4. ☐ "Смена раскладки в Конверт выделения" - выключить если включена.

вроде бы всё. С такими настройками будет работать как ты хочешь.

**Comment by BladeMight** [comment]
@nikitasA1NT Кстати только что вот закончил документацию [[Hidden] на wiki](https://github.com/BladeMight/Mahou/wiki/%5BHidden%5D-RU)… фух...
