### ISSUE TITLE
Mahou "не читает" установки

### ISSUE THREAD

**Issue by yuklov** [BladeMight/Mahou#309]
Mahou с настройками и другие файлами копировал на новый компьютер. Но программа как новая. Не видит ничего. 
Сниппеты копировал с snippets.txt и поставил на программу заново. Работал.

Но программа не видит TSDict.txt и CustomConversion.txt. Что делать?

Файл Mahou.ini (размер, дата) не изменяется.

**Comment by BladeMight** [comment]
хм..

> Но программа не видит TSDict.txt и CustomConversion.txt.

Возможно ты просто забыл использовать latest-commit версию Mahou?
Или в настройках стоит "Конфигурация в Appdata"? Тогда все файлы настроек должны быть в %appdata%\Mahou\

**Comment by yuklov** [comment]
Кажется это связано с доступом к файлу.

Выбрал легкий путь – переустановил Виндовс 😄. Теперь все норм.
