### ISSUE TITLE
OS shows language form on ALT-TAB

### ISSUE THREAD

**Issue by OleksandrKucherenko** [BladeMight/Mahou#31]
![hide-window-on-alt-tab](https://cloud.githubusercontent.com/assets/6419758/18915131/4d964a6a-8590-11e6-8a38-7fefd1b0c95e.gif)

**Comment by OleksandrKucherenko** [comment]
http://stackoverflow.com/questions/2791947/how-to-make-a-program-not-show-up-in-alt-tab-or-on-the-taskbar

http://stackoverflow.com/questions/357076/best-way-to-hide-a-window-from-the-alt-tab-program-switcher

**Comment by BladeMight** [comment]
Hahaha, ok i will fix it now.

**Comment by BladeMight** [comment]
Ok fixed it, [here](https://github.com/BladeMight/Mahou/releases/tag/v1.3.0.5).
