### ISSUE TITLE
Исключения или индивидуальная настройка "добавлять пробел" для сниппетов

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#310]
Сейчас настрйока "Добавлять 1 пробел после сниппетов" работает для всех сниппетов.
В целом это удобно, но в ряде случаев проблем нежелателен.

Может быть как-то расширить сам шаблон, чтобы он показывал, что не следует добавлять пробел? Например, вторым минусом `-->!tn`

**Comment by BladeMight** [comment]
@Makishima Также можно её выключить и явно ставить в каждый сниппет где нужен пробел:


```js
->тутда
====>ставим-в-конце-пробел: <====
->тутнет
====>не-ставим<====
```

**Comment by Makishima** [comment]
Тоже верно :)
