### ISSUE TITLE
Обновление словаря со сниппетами

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#311]
Взял десять случайных слов из сниппетов - все они есть в обычном словаре.
Может стоит сниппеты поставлять в пустом виде, чтобы избежать дублирования?

**Comment by BladeMight** [comment]
"словаря со сниппетами"?

в Mahou по умолчанию стандартные сниппеты такие:

```
-><***ANY***>====><***ANY***>__cursorhere()</***ANY***><====
->mahou
====>Mahou (魔法) - Magical layout switcher.<====
->eml
====>BladeMight@gmail.com<====
->nowtime====>__date(HH:mm:ss)<====
->nowdate====>__date(dd/MM/yyyy)<====
->datepretty====>__date(dd, ddd MMM)<====
->mahouver====>__version()<====
->mahoutitle====>__title()<====
->env_system====>__system()<====
->date_esc====>\__date(HH:mm:ss)<====
```

кому какие не надо, может удалить, я просто оставил чтобы можно было понять формат/возможности.

Может ты имел в виду словарь автозамен?
А словарь автозамен по умолчанию - пуст.

**Comment by Makishima** [comment]
У меня такой
![изображение](https://user-images.githubusercontent.com/5548003/104559172-10dc1600-5655-11eb-8d7d-ce9d05245483.png)
И в [latest](https://github.com/BladeMight/Mahou/blob/latest-commit/snippets.txt) он же лежит

**Comment by BladeMight** [comment]
Это старый **тэг** latest-commit в репозиторие содержит очень старый код(этот тег нужен просто чтобы перезаписывать _релиз_ **lastest-commit** который собирается на [ci.appveyor](https://ci.appveyor.com/project/BladeMight/mahou/history)):
![2021 01 14 - 09'45'30_rect](https://user-images.githubusercontent.com/11931888/104559611-ae374a00-5655-11eb-9dd4-2ff88719005d.jpg)
это ещё когда не было "автозамены". А сейчас эти словари стали автозаменой, и храняться тут: [Mahou/Dictionaries-origin](https://github.com/BladeMight/Mahou/tree/master/Dictionaries-origin), а "общий"/"совместный"/"стандартный" словарь автозамен хранится тут: [Mahou/AS_dict.txt](https://github.com/BladeMight/Mahou/blob/master/AS_dict.txt)

**Comment by Makishima** [comment]
Похоже, у меня очень старая версия сниппетов :)
Получается, я могу из своей версии снести все, кроме того, что добавлял сам, так как оно уже в основном словаре есть?

**Comment by BladeMight** [comment]
> что добавлял сам, так как оно уже в основном словаре есть?

Возможно, в стандартном словаре 151429 слов наверняка они там есть, и лучше ставь его в AS_dict.txt, а **свои** сниппеты пиши в snippets.txt

![2021 01 14 - 09'54'29_rect](https://user-images.githubusercontent.com/11931888/104560614-2d794d80-5657-11eb-9b4c-1215ac99a9d6.jpg)

**Comment by BladeMight** [comment]
А вот сколько слов в [супер тяжелом русском словаре](https://files.gitter.im/BladeMight/TRfj/mux-dict.7z)+[большой английский](https://github.com/BladeMight/Mahou/blob/master/Dictionaries-origin/!English-big.txt):
![2021 01 14 - 09'58'22_rect](https://user-images.githubusercontent.com/11931888/104560893-9b257980-5657-11eb-8145-642b44f5fd65.jpg)
Mahou с ним берёт 500+мб оперативки:
![2021 01 14 - 10'00'11_rect](https://user-images.githubusercontent.com/11931888/104561000-c27c4680-5657-11eb-92ad-50bdf7b42c34.jpg)

**Comment by Makishima** [comment]
> лучше ставь его в AS_dict.txt, а свои сниппеты пиши в snippets.txt

Да, так и сделал. 
С одной стороны хорошо, что обновление не затерло старый словарь сниппетов, с другой стороны осталась неактуальная информация

**Comment by Makishima** [comment]
> Mahou с ним берёт 500+мб оперативки:

Если именно Mahou не будет тормозить при автозамене, то лично мне не жалко такой объем выделять :)

**Comment by BladeMight** [comment]
Вот:
[AS_Dict_Superbig_ru+big_en.zip](https://github.com/BladeMight/Mahou/files/5813103/AS_Dict_Superbig_ru%2Bbig_en.zip)

Не тормозит вообще:

![auto](https://user-images.githubusercontent.com/11931888/104561500-8eedec00-5658-11eb-905b-840390bbb0b8.gif)

\* - промоутерах - последнее слово в словаре, поэтому я его вводил, т.к. до него дольше "проверять".

**Comment by BladeMight** [comment]
> что обновление не затерло старый словарь сниппетов, с другой стороны осталась неактуальная информация

Ну так snippets.txt - теперь не словарь автозамен, а "пользовательские замены", т.е. пользовательские сниппеты. А автозамена только для знакомых слов.

**Comment by Makishima** [comment]
Обновился на большой словарь - полет нормальный.
