### ISSUE TITLE
Ошибки обратной конвертации

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#315]
Для списка 
```
totermw.exe
ubuntu1804.exe
powershell.exe
wsl.exe
conhost.exe
wslhost.exe
ConEmuC64.exe
ConEmu64.exe
notepad.exe
Code.exe
WindowsTerminal.exe
javaw.exe
wsl.exe
wslhost.exe
conhost.exe
winbox.exe
```
делаю два раза конвертацию - при обратной почему-то неверно восстанавливаются все символы
![E6146AE4-735E-406E-86A5-532D9B63994E](https://user-images.githubusercontent.com/5548003/104588771-ef415580-5679-11eb-96e0-a5ac102c2a93.GIF)

**Comment by BladeMight** [comment]
Хм, интересно, "распознавание раскладки слова" неправильно срабатывает если в слове есть "цифры", нужно проверить в коде...

**Comment by BladeMight** [comment]
Исправил в a90abf2, это было из-за "правила для IP адресов"(уже не помню кто его предложил), поменял его.
