### ISSUE TITLE
Должна ли выгружаться jkl.dll при закрытии программы?

### ISSUE THREAD

**Issue by Makishima** [BladeMight/Mahou#318]
Столкнулся с тем, что jkl.dll, не выгружается при закрытии программы. 
Хотел удалить одну из используемых версий и не смог полностью до перезагрузки.
![изображение](https://user-images.githubusercontent.com/5548003/104806351-db1b6680-57e7-11eb-9983-d62bbd86b8ad.png)

**Comment by BladeMight** [comment]
> Должна ли выгружаться jkl.dll при закрытии программы?

TLDR;  Нет

JKL создают "**суперглобальный хук**" `WH_CALLWNDPROC` для мониторинга сообщения смены раскладки: `WM_INPUTLANGCHANGE`, и таким образом этот хук подключается ко всем приложениям, и не может быть "выгружен" из них, пока они не завершаться. Как вариант, можно переименовать и поместить в папку `trash` рядом с Mahou.exe, а Mahou удалит их если сможет при следующем запуске, сейчас именно так и работает обновление с JKL.
