### ISSUE TITLE
Автоматическое переключение на заранее выбранный метод ввода IME

### ISSUE THREAD

**Issue by HYBRID-BEING** [BladeMight/Mahou#322]
## Проблема/описание запроса

Не знаю какое отношение к фичревестам касающимся конкретных языков (костылём попахивает), но было бы здорово, если бы была возможность выбрать метод ввода, который бы автоматически выбирался при переключении на определённый язык (ввод хираганы при выборе японского языка, к примеру).

**Comment by BladeMight** [comment]
> ввод хираганы при выборе японского языка,

Такое можно сделать если использовать "посылание клавиш клавиатуры", т.е. если установилась конкретная раскладка "послать конкретные клавиши", т.е. если сменилась раскладка на "японскую" послать <kbd>Alt</kbd>+<kbd>`</kbd>(т.е. установить ввод "romaji=>kana")

Есть горячие клавиши для быстрого переключения: см. [1](https://superuser.com/a/267694/579751),[2](https://www.reddit.com/r/LearnJapanese/comments/2w5bux/japanese_ime_input_annoyance/coo6zhs?utm_source=share&utm_medium=web2x&context=3)

**Comment by HYBRID-BEING** [comment]
Хорошая идея. Я пользуюсь Alt+`, но время от времени забываюсь и переключаю обратно на romaji.

Вообще, думал предложить индикатор раскладки (не языка, а именно раскладки)/метода ввода, но я кроме хироганы не пользуюсь другими методами, так что оставлю другим.

**Comment by BladeMight** [comment]
> думал ещё предложить индикатор раскладки

А это уже наверно зависит больше от "IME", навряд ли в WinAPI есть функции получения текущего `IME ввода` для разных IME: Microsoft IME, Google Japanese IME, Baidu IME, и т.д. к примеру могут все иметь разные "способы получения текущего ввода"... или не иметь вообще, т.к. вне IME доступ к этим данным мало каким(вообще каким??) программам надо... По моему мнению максимум что есть в WinAPI наверно только `"статус" IME` - активный или нет, а какой конкретно (мне кажется) такого нет...

**Comment by BladeMight** [comment]
В 8446db8 сделал "дополнение" к [Mahou.mm](https://github.com/BladeMight/Mahou/wiki/Mahou.mm_RU), теперь можно привязывать действия к "событиям": (пока только 2 события):

```mm
"послать" Alt+` при смене на японскую раскладку|evt|layoutchange1041_kbd_alt+oemtilde
"послать" Alt+` при смене с японской на другую раскладку|evt|layoutchangedfrom1041_kbd_alt+oemtilde
```

**примечание**: Работать будет только для функции "Переключать раскладки по клавишам", .т.е. для ручной смены раскладки через трей или по стандартным гор. клавишам Windows - **_пока_** не реализовано, _возможно и не будет_..., также при включенной "эмуляции переключения раскладки" и отключенном "JKL" - не будет работать.

**Comment by HYBRID-BEING** [comment]
Скопировал строки в Mahou.mm (необычный формат). По поведению (и по тому, что я понял из лога), подозреваю, что не срабатывает событие переключения НА раскладку.
[Лог](https://github.com/BladeMight/Mahou/files/5938461/2021.02.07.txt)

**Comment by BladeMight** [comment]
Судя по логу ты ни разу не переключил на японский(используя Mahou)...

вот как должно быть:

![mahoux](https://user-images.githubusercontent.com/11931888/107141150-ffc2b400-6937-11eb-8ed6-22f46b3d3082.gif)

**Comment by HYBRID-BEING** [comment]
Ну как, с японского на русский же переключаюсь, стало быть и на японский переключаюсь тоже. Три раза в логе:
```[EVT] Starting event #1 on layoutchangedfrom1041 | (1041 == 1041) => <menuhandle>b__9f```
Системные хоткеи отключены, на японский переключаюсь исключительно по <kbd>Alt</kbd>+<kbd>Shift</kbd>.

**Comment by BladeMight** [comment]
> [EVT] Starting event #1 on layoutchangedfrom1041 | (1041 == 1041) => <menuhandle>b__9f

Это "с", а не "на".

**Comment by HYBRID-BEING** [comment]
Так я о чём и говорю, раз есть событие "с", значит и переключение "на" было.
Вот как происходит:
![jap](https://user-images.githubusercontent.com/1691231/107143914-8045dc80-6959-11eb-906c-7db01fdb5023.gif)
Может дело в конфликте <kbd>Alt</kbd>+<kbd>Shift</kbd> и <kbd>Alt</kbd>+<kbd>`</kbd>?

Настройки (если я правильно понял, что речь про эти):
![изображение](https://user-images.githubusercontent.com/1691231/107143541-7f13b000-6957-11eb-9796-7bbf8d3603b4.png)
![изображение](https://user-images.githubusercontent.com/1691231/107143568-98b4f780-6957-11eb-9d59-eb21f786bee2.png)

**Comment by BladeMight** [comment]
>Может дело в конфликте <kbd>Alt</kbd>+<kbd>Shift</kbd> и <kbd>Alt</kbd>+<kbd>`</kbd>

Может быть... Попробуй с <kbd>CapsLock</kbd>?


> "на" было.

было, судя по логу "на" было только не в "японскую":

> 12:39:55.783 [I]: [EVT] Starting event #0 on layoutchange1041 | (1033 == 1041) => <menuhandle>b__9f

1033 - английская.


> Настройки (если я правильно понял, что речь про эти)

Да, эти.

**Comment by HYBRID-BEING** [comment]
Возможно где-то переключился на английский язык. Вот новая попытка, без переключения на английский и с переключением на японский по <kbd>Capslock</kbd>:
![jap](https://user-images.githubusercontent.com/1691231/107144487-3d860380-695d-11eb-9d58-b4b9601f7be2.gif)
[Лог](https://github.com/BladeMight/Mahou/files/5938771/2021.02.07.txt)

**Comment by BladeMight** [comment]
Тут в логе пишет что у тебя только 1 событие стоит:

> [EVT] Check event bindings1

Ты уверен что у тебя есть в Mahou.mm две строчки, одна с "layoutchange" и другая "layoutchangedfrom"? И после редактирования Mahou.mm нажми в Mahou "применить".

**Comment by HYBRID-BEING** [comment]
Ууупс, небольшой косяк с моей стороны - в качестве экспериментра выставил _layoutchangeto_, вместо _layoutchange_. Выставил:
```
Послать Alt+` при смене на японскую раскладку|evt|layoutchange1041_kbd_alt+oemtilde
Послать Alt+` при смене с японской на другую раскладку|evt|layoutchangedfrom1041_kbd_alt+oemtilde
```
, но не помогло:
![jap](https://user-images.githubusercontent.com/1691231/107147356-64e5cc00-696f-11eb-96d0-d1a2bc0870df.gif)
[Лог](https://github.com/BladeMight/Mahou/files/5939055/2021.02.07.txt)

**Comment by BladeMight** [comment]
Хм... в логе есть только переключения на 1049 "русская"

```
[EVT] Starting event #0 on layoutchange1041 | (1049 == 1041)
```

на 1041 нет, а должно быть... У меня пишет для обоих:

```
03:35:52.640 [I]: [EVT] Starting event #1 on layoutchangedfrom1041 | (1041 == 1041) => <menuhandle>b__9f
....
03:35:53.516 [I]: [EVT] Starting event #0 on layoutchange1041 | (1041 == 1041) => <menuhandle>b__9f
```

<s>Попробуй с "включенной эмуляцией" **и** "JKL"</s>, а нет стой у тебя ведь "стандартные отключены"? Или подожди есть же Win+Space(по идее не отключаемая), включи обе:
![изображение](https://user-images.githubusercontent.com/1691231/107143541-7f13b000-6957-11eb-9796-7bbf8d3603b4.png)
![изображение](https://user-images.githubusercontent.com/1691231/107143568-98b4f780-6957-11eb-9d59-eb21f786bee2.png)

и поставь тип эмуляции на Win+Space.

**Comment by BladeMight** [comment]
Мне кажется или ты помимо смены раскладки в Mahou используешь еще какую-то? Как-то много клавиш показывает в gif'ке.

**Comment by HYBRID-BEING** [comment]
> поставь тип эмуляции на Win+Space
Хмм, так?
![изображение](https://user-images.githubusercontent.com/1691231/107149284-9499d180-6979-11eb-8a0f-4c28f63c6de8.png)

> Мне кажется или ты помимо смены раскладки в Mahou используешь еще какую-то? Как-то много клавиш показывает в gif'ке.
Откуда-то берётся непонятный _Scroll_, остальное всё что жму.

**Comment by BladeMight** [comment]
Да, так. И также сделал небольшое исправление в 0e9e6fc, попробуй там по разному, но вот так должно работать:

![2021 02 07 - 16'24'28_rect](https://user-images.githubusercontent.com/11931888/107149405-76c47080-6969-11eb-9dc8-5424c18374e6.jpg)

**Comment by HYBRID-BEING** [comment]
これでいいんだよ。
С этой обновой работает корректно.

**Comment by HYBRID-BEING** [comment]
Не запомнил когда точно, но с какого-то момента перестало работать. Mahou.mm не трогал (записи на месте).
[log.txt](https://github.com/BladeMight/Mahou/files/11303229/log.txt)

**Comment by BladeMight** [comment]
@HYBRID-BEING Странно что тогда работало, поменял способ сравнения раскладок в f47d28d.

**Comment by HYBRID-BEING** [comment]
Снова работает, спасибо!
