### ISSUE TITLE
Запоминать последний язык ввода (из двух основных)

### ISSUE THREAD

**Issue by HYBRID-BEING** [BladeMight/Mahou#323]
## Проблема/описание запроса

Если выбран не один из двух основных языков ввода, то команда "Переключать между раскладками" всегда выбирает 1ый язык. Было бы неплохо, если бы Mahou запоминала, какой из двух основных языков был выбран последним.

Например, в моём случае, между русским и английским я переключаюсь с помощью <kbd>Ctrl</kbd>+<kbd>Shift</kbd>, и переключаюсь на японский с помощью <kbd>Alt</kbd>+<kbd>Shift</kbd>. Однако, даже если я переключился с английского на японский, то <kbd>Ctrl</kbd>+<kbd>Shift</kbd> всё равно переключает на русский язык.

**Comment by BladeMight** [comment]
Интересно...

P.S. А тебе точно нужна раскладка "США(67699721"? Можно же таким же способом писать и в японской, только меняя режимы?

**Comment by HYBRID-BEING** [comment]
У нас уже был этот [разговор](https://github.com/BladeMight/Mahou/issues/284#issuecomment-723671263)) Там кстати упоминал про сегодняшние фичи, сейчас вот дозрел зарепортить)

**Comment by BladeMight** [comment]
@HYBRID-BEING В f743f02 добавил, для проверки я использовал:
1. 3 раскладки
2. 1 и 2 раскладки назначил в \#1 и \#2.
3. Поставил две "менять раскладку 1 клавишей":
  3.1. первая(`мр1к1`) - "Между раскладками"
  3.2. вторая(`мр1к2`) - "На третью раскладку".
4. Нажимая `мр1к1` Mahou теперь запоминает на какую изменилась раскладка, если потом нажать `мр1к2` и опять `мр1к1` то раскладка будет опять такой же как перед `мр1к2`

**Comment by HYBRID-BEING** [comment]
С виду, запоминает исправно, хотя, судя по всему, я наткнулся на #241.
