### ISSUE TITLE
[Feature request] Новая конвертация при смене фокуса

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#33]
### Summary

Неплохо было бы, если при смене фокуса не конвертировались символы, которые я вводил при предыдущем фокусе.
### Expected behavior

Отсутствие конвертации текста в прежнем текстовом поле.
### Actual behavior

Конвертация текста из прежнего текстового поля в новом текстовом поле.
### Steps to reproduce

Допустим, я работаю в Sublime Text → я открываю command palette или любую другую панель → пишу в этой панели текст в неправильной раскладке → запускаю команду `Конверт линии` → у меня в command palette конвертируются слова, которые я писал в текстовом поле.

![Конвертация при смене фокуса](http://i.imgur.com/hwM91dN.gif)

Спасибо.

**Comment by BladeMight** [comment]
Наверно нужно сделать очистку слова при срабатывании гор. клавиш, то есть `Ctrl+Shift/Alt+Любая клавиша`.
Ок, принято, будет добавлено.

**Comment by BladeMight** [comment]
Сделал еще проще, при нажатии `Ctrl+Любая клавиша`.
Вот проверь:
[Mahou-Ctrl+any = Clear.gz](https://github.com/BladeMight/Mahou/files/525519/Mahou-Ctrl.any.Clear.gz)

**Comment by BladeMight** [comment]
@Kristinita Вот [релиз](https://github.com/BladeMight/Mahou/releases/tag/v1.4.0.5).

**Comment by Kristinita** [comment]
Спасибо, работает!

**Comment by Kristinita** [comment]
@BladeMight , эта же проблема опять воспроизводится для меня в Mahou 1.5.0.6.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Да в #44 уже было об этом сказано.

**Comment by BladeMight** [comment]
@Kristinita Сейчас алгоритм срабатывает **при отпускании** клавиши, в следующем релизе будет **при нажатии**.

**Comment by BladeMight** [comment]
[Релиз](https://github.com/BladeMight/Mahou/releases/tag/v1.5.1.0), [Chocolatey](https://chocolatey.org/packages/Mahou/1.5.1.0).

**Comment by Kristinita** [comment]
@BladeMight , проблема воспроизводится в Mahou 1.5.1.0

```
### MAHOU DEBUG INFO
- Mahou-v1.5.1.0
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
SashaCoolMakEn(4039181321)
SashaCoolMakRU(4039115801)
US(67699721)
#### Mahou.ini:
```ini
!Unicode(✔), Mahou settings file
[Hotkeys]
HKCLKey=121
HKCLMods=Shift
HKCSKey=121
HKCSMods=Control
HKCLineKey=121
HKCLineMods=None
OnlyKeyLayoutSwicth=CapsLock
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=121
HKConvertMoreMods=Shift + Control
[Locales]
locale1uId=4039181321
locale1Lang=SashaCoolMakEn
locale2uId=4039115801
locale2Lang=SashaCoolMakRU
LANGUAGE=EN
[Functions]
IconVisibility=True
CycleMode=False
EmulateLayoutSwitch=False
ELSType=0
CSSwitch=True
BlockCTRL=False
RePress=True
EatOneSpace=False
ReSelect=True
SymIgnModeEnabled=false
MoreTries=True
TriesCount=5
DisplayLang=False
DLRefreshRate=50
DLForeColor=#FFFFFF
DLBackColor=#000000
ExperimentalCSSwitch=False
Snippets=False
DTTOnChange=False
ScrollTip=False
UpdatesEnabled=False
Logging=True
DiffLayoutColors=True
CrtDisplayLang=True
CrtDLRefreshRate=50
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=True
[ExtCtrls]
UseExtCtrls=False
LCLocale=4039181321
LCLocaleName=SashaCoolMakEn
RCLocale=4039115801
RCLocaleName=SashaCoolMakRU
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=14
Width=24
Font=Microsoft Sans Serif, 8.25pt
xpos=8
ypos=0
TransparentBack=True
DLForeColor=#FFFFFF
DLBackColor=#000000
CrtDLForeColor=#FFFFFF
CrtDLBackColor=#000000
L1DiffFGColor=#8B5FFF
L1DiffBGColor=#FFFFFF
L1DiffFont=Carlito, 8.25pt, style=Bold
L2DiffFGColor=Red
L2DiffBGColor=White
L2DiffFont=Candara, 8.25pt, style=Bold
CrtHeight=14
CrtWidth=24
CrtFont=Microsoft Sans Serif, 8.25pt
Crtxpos=8
Crtypos=0
[DoubleKey]
Use=False
Delay=350
```
#### Snippets:
```
->mahou
====>
Mahou (魔法) - Magical layout switcher.
<====
->eml
====>BladeMight@gmail.com<====
```

Спасибо.

**Comment by BladeMight** [comment]
[Вот](https://github.com/BladeMight/Mahou/commit/c2fd888c3d8de49b03a710dd009728fab10a66be) исправил, релиз пока делать не буду, скачать можете [здесь](https://ci.appveyor.com/project/BladeMight/mahou/build/job/aobxh2gqiblvdw9d/artifacts).

**Comment by Kristinita** [comment]
@BladeMight , это скачивать вручную(( . В Chocolatey, кстати, можно делать пререлизы. [**Пример**](https://chocolatey.org/packages/putty/0.64-prerelease).

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Тогда мне и в GitHub придется их делать...

**Comment by Kristinita** [comment]
@BladeMight , не конвертировать текст, который ввёл до нажатия клавиши <kbd>Browser_Search</kbd> тоже не помешало бы. 

Спасибо.

**Comment by BladeMight** [comment]
> который ввёл до нажатия клавиши <kbd>Browser_Search</kbd>

То есть очищать слова после нажантия <kbd>Browser_Search</kbd>?

**Comment by Kristinita** [comment]
Желаемое поведение: пишу текст A → нажимаю Browser_Search → пишу текст B 
в неправильной раскладке → нажимаю хоткей для «Convert line:» → в другую 
раскладку конвертируется только текст B, но не текст A.

Спасибо.

**Comment by BladeMight** [comment]
Ну да как Я и думал.

**Comment by BladeMight** [comment]
Добавил в [v1.5.2.3](https://github.com/BladeMight/Mahou/releases/tag/v1.5.2.3), сейчас на chocolatey залью.

**Comment by Kristinita** [comment]
*Оффтоп*

[**Статью**](http://kristinita.ru/IT-articles/Fastest-way-to-add-new-version-of-Sublime-Text-3-package) тут написал, как сделать релиз и журнализацию изменений проекта сразу во много мест. В статье это рассматривается применительно к особенностям Sublime Text, но, может, тоже пригодится.

Можно дописать скрипт, о котором рассказывается в статье, и автоматически отправлять новые релизы в Chocolatey.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Спасибо, но у меня уже есть свой скрипт который пишет изменения версию, и т.д. и грузит на Chocolatey. Сначала [build-github-release+chocolatey-update.vbs а потом](https://github.com/BladeMight/Mahou/blob/master/Mahou/build-github-release%2Bchocolatey-update.vbs):
```
choco push Mahou.nupkg --source https://push.chocolatey.org/
```
