### ISSUE TITLE
[Suggestion] Срабатывание снипплетов в любой раскладке

### ISSUE THREAD

**Issue by Korb** [BladeMight/Mahou#333]
Предлагаю добавить возможность включения выполнения снипплетов вне зависимости от текущей раскладки. Потому что сейчас для этого сперва приходится сначала переключиться в нужную раскладку, и только затем - набрать сочетание символов, забитое в "->". Либо, дублировать все снипплеты для всех вариантов раскладки.

**Comment by BladeMight** [comment]
Ой. Забыл добавить это на wiki, обновил: [Не-зависимые-от-раскладки-сниппеты](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BD%D0%B8%D0%BF%D0%BF%D0%B5%D1%82%D1%8B%3F-%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%3F#%D0%9D%D0%B5-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D1%8B%D0%B5-%D0%BE%D1%82-%D1%80%D0%B0%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B8-%D1%81%D0%BD%D0%B8%D0%BF%D0%BF%D0%B5%D1%82%D1%8B)

Вот с использованием `?~?` модификатора игнорирования раскладки:

```Сейчас 27.03.2021 23:22:59 
->?~?ddd
====>Сейчас __date(dd.MM.yyyy HH:mm:ss) __delay(1200)__keyboard(lctrl+lshift+left*7 back|10)<====
```

Ввод любой комбинации из `d` и `в`, т.е. `ddd`, `ввв`,  `вdd` и т.д. развернёт в:

```
Сейчас 27.03.2021 23:24:50
```

Подождёт 1.2 сек и удалит.

Но лично я считаю что лучше всё же использовать `regex//`.
