### ISSUE TITLE
Мультистрочные сниппеты в телеграме

### ISSUE THREAD

**Issue by YaMaZZZim** [BladeMight/Mahou#339]
Доброго времени суток

Суть проблемы - мультистрочный снипет при вставке в телеграм каждую строку отправляет отдельным сообщением. 
Можно ли как-то сделать чтобы весь мультистрочный снипет вставлялся целиком?
Через __paste() тоже не работает. Символа переноса строки я на вики не нашёл, если он есть.

Информация окружения/Отладочная информация
Версия Windows: 10х64
Версия .Net: 4.8.04084
Версия Mahou: 2.9.0.1

**Comment by AlexTransit** [comment]
а если в телеграмме, сделать отправку сообщения по **Ctrl+Enter**?

**Comment by YaMaZZZim** [comment]
> а если в телеграмме, сделать отправку сообщения по **Ctrl+Enter**?

Да так работает в десткопе.
Но у меня люде в вебе работают и в рабочем мессенджере похожем, который тоже в браузере =\

**Comment by BladeMight** [comment]
@YaMaZZZim 
> Через __paste()

Должно работать, т.к. Mahou копирует текст в буфер обмена потом *нажимает* `Ctrl+V`, например так:

```
->mus
====>__paste(Много
строк
и вставка
игнор скобки: \)
!)<====
```

Проверял в web gitter, вариант без __paste() создаёт новые строки, а с __paste - нет:
![2021 04 21 - 13'59'15_rect](https://user-images.githubusercontent.com/11931888/115543321-ea5bf580-a2a9-11eb-86d5-adab59f9310a.jpg)

- \* Вариант без __paste:
```->nmus
====>Много
строк
и вставка
игнор скобки: )
!<====
```

P.S. Если не используешь уже - лучше используй latest-commit версию, для обновления к latest-commit:
1. Во вкладке "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление)
2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - Release_x86_x64.zip)

**Comment by YaMaZZZim** [comment]
@BladeMight 

Версия последняя.
Снипет из примера работает нормально...

Вот снипет с работы который отправляется по строке в сообщении:

Без комиссии вы можете пополнить карту в терминалах:
- iBOX
- Алло (находятся в магазинах Алло)
- банкоматах Универсал Банка (находятся в отделениях банка)
- в кассах Универсал банка, А-банка
Карта точек пополнения с адресами находится в приложении в меню "Пополнить свою карту" на  главном экране.
В кассах других украинских банков - комиссия согласно условиям банка, через который вы пополняете карту. Через ТСО других банков - комиссия согласно условиям банка, владельца терминалов

[Отправляется он вот так](https://i.imgur.com/iEDCDyl.png)
В чем проблема, я не понимаю. Выглядит как какое-то ограничение по длине строки или как попытка переноса, но я вроде в документации такого не встречал.

**Comment by BladeMight** [comment]
@YaMaZZZim 

А так:

```
->komb
====>__paste(Без комиссии вы можете пополнить карту в терминалах:
- iBOX
- Алло (находятся в магазинах Алло\)
- банкоматах Универсал Банка (находятся в отделениях банка\)
- в кассах Универсал банка, А-банка
Карта точек пополнения с адресами находится в приложении в меню "Пополнить свою карту" на  главном экране.
В кассах других украинских банков - комиссия согласно условиям банка, через который вы пополняете карту. Через ТСО других банков - комиссия согласно условиям банка, владельца терминалов)<====
```
?

**Comment by YaMaZZZim** [comment]
@BladeMight 
Так работает. Проблема была в скобках...
Огромное спасибо!
