### ISSUE TITLE
При конвертации также срабатывают соответствующие клавиши (Scroll Lock, Caps Lock)

### ISSUE THREAD

**Issue by GreatMaestro** [BladeMight/Mahou#34]
Установил конвертацию на Shift + Caps Lock, и вот что происходит:
![2016-11-22_15-42-41](https://cloud.githubusercontent.com/assets/17749274/20518774/88c0245c-b0ca-11e6-86a5-9ce25fed5d05.gif)
Также и при конвертации слова по Caps Lock. Scroll Lock тоже срабатывает при конвертации выделенного слова, это не критично, но хотелось бы иметь возможность отключить.

**Comment by BladeMight** [comment]
Ок, посмотрю что можно сделать.

**Comment by BladeMight** [comment]
Вот, проверьте [v1.4.1.1](https://github.com/BladeMight/Mahou/releases/tag/v1.4.1.1).

**Comment by GreatMaestro** [comment]
Всё работает, спасибо! А по какому принципу работает фикс?

**Comment by BladeMight** [comment]
Принцип:
Если любой хоткей имеет CapsLock как клавишу, и текущий нажатый хоткей имеет имеет CapsLock как клавишу то выключить(нажать программно) CapsLock его если он светится, и продолжать действия по конвертации.
P.S. Нажмите на *Close issue* или *Close and comment* если ваша проблема решена.
