### ISSUE TITLE
Переключение раскладки не работает в некоторых программах

### ISSUE THREAD

**Issue by cheack** [BladeMight/Mahou#343]
Привет, использую последнюю версию, настроил CapsLock для переключения раскладки. 
Работает хорошо, но не во всех программах, например, не работает в PhpStorm и ConEmu (https://conemu.github.io/), в них CapsLock переключает регистр.
Попробовал все способы, описанные в https://github.com/BladeMight/Mahou/issues/342 - не помогло.
Windows 10 20H2

**Comment by BladeMight** [comment]
@cheack У меня работает, даже на стандартных настройках в ConEmu:
![ct](https://user-images.githubusercontent.com/11931888/126250657-c5beaba9-9a2b-4384-8710-42c668bf0fc8.gif)

Попробуй включить "Эмуляцию переключения раскладки" и попробовать разные варианты "Alt+Shift"/"Win+Space" (выбрать=> применить => проверить)

**Comment by cheack** [comment]
Разобрался, https://github.com/BladeMight/Mahou/issues/277 мне подсказал, в чем дело, PhpStorm и консоль приходится запускать от админа, потому что докер в винде нормально работает только под админом 🦽
