### ISSUE TITLE
"Переключать раскладки по клавишам" отпускает LCtrl

### ISSUE THREAD

**Issue by fixator10** [BladeMight/Mahou#344]
## Проблема/описание запроса

При настройке "Переключать раскладки по клавишам" на любую кнопку - после использования так же "отпускается" и LCtrl
![настройки](https://moeka.is-a-good-waifu.com/AZt8mC2.png)

Три нажатия на LCtrl при выключенном переключении:
```
Key.ctrl_l pressed
Key.ctrl_l release
Key.ctrl_l pressed
Key.ctrl_l release
Key.ctrl_l pressed
Key.ctrl_l release
Key.esc pressed
Key.esc release
```

Три нажатия на LCtrl при переключении на LCtrl:
```
Key.ctrl_l pressed
Key.ctrl_l release
Key.ctrl_l release
Key.ctrl_l pressed
Key.ctrl_l release
Key.ctrl_l release
Key.ctrl_l pressed
Key.ctrl_l release
Key.ctrl_l release
Key.esc pressed
Key.esc release
```

При установке переключения на ALT или TAB:
```
Key.alt_l pressed
Key.alt_l release
Key.ctrl_l release
Key.tab pressed
Key.tab release
Key.ctrl_l release
```
*проверялось скриптом на питоне, выполняющемся через [Windows Terminal](https://moeka.is-a-good-waifu.com/4LYCrFK.png):*
<https://stackoverflow.com/a/53210441/8148543>

## Ожидаемое поведение (только при сообщении об ошибках)

LCtrl отпускается один раз

## Информация окружения/Отладочная информация

- Версия Windows: Windows-10-10.0.19041-SP0
- Архитектура Windows: x64
- Версия .Net: 4.0.30319.42000
- Версия Mahou: Mahou 2.9.0.1-dev <94034ce>

**Comment by BladeMight** [comment]
@fixator10 Это поведение вызывается не самим Mahou а сообщением WinAPI `WM_INPUTLANGCHANGEREQUEST` - оно используется для смены раскладки, хотя Windows сама использует какой-то другой метод смены раскладки который я так и [не узнал](https://stackoverflow.com/questions/61310903/how-does-windows-changes-keyboard-layout), происходит при вызове WM_INPUTLANGCHANGEREQUEST, вот простой скрипт на AutoHotkey, который только это и делает:

```ahk
WM_INPUTLANGCHANGEREQUEST := 0x0050
F1::
WinGet, winid, ID, A
PostMessage, %WM_LANGCHANGEREQUEST%, 0, 1,, ahk_id %winid%
return
```

При запуске и нажатии на F1 - происходит то же самое:
![](https://user-images.githubusercontent.com/11931888/126364725-fc54b024-9283-48ff-851e-268e968eb73e.jpg)

вот для проверки в формате exe и ahk:
[test.zip](https://github.com/BladeMight/Mahou/files/6850031/test.zip)

------------------

Я когда-то спрашивал на stackoverflow почему так происходит, но ответа не пришло и вопрос видимо удалили - сейчас смотрел не смог найти его в своих вопросах.

-----------------

Как вариант можно использовать "эмуляцию переключения раскладки", тогда Mahou будет нажимать сочетание клавиш для 
 смены раскладки как это делал бы сам пользователь вместо сообщения WinAPI `WM_INPUTLANGCHANGEREQUEST`.

**Comment by fixator10** [comment]
Посмотрел я на это дело... Действительно, даже стандартные Win+Space и *Shift+LCtrl* вызывает "отжим" LCtrl.

**Comment by BladeMight** [comment]
> Действительно, даже стандартные Win+Space и Shift+LCtrl вызывает "отжим" LCtrl.

Ох, даже так? Тогда любая смена раскладки в принципе в Windows вызывает событие отпуска LCtrl...
