### ISSUE TITLE
Предложение для Caps 

### ISSUE THREAD

**Issue by MishGa** [BladeMight/Mahou#35]
Здравствуйте. Во-первых спасибо, то что надо.
Во вторых, для переключения языка долгое время пользовался утилиткой capslang, там кроме переключения языка есть вот какая штука. 
"Эта маленькая программка без видимых частей предназначена для переключения раскладки клавиатуры кнопкой CapsLock, когда используется нестандартная раскладка -- горит индикатор Scroll Lock. Включать Caps Lock можно сочетанием Shift + CapsLock."
Было бы здорово реализовать это у вас.

**Comment by BladeMight** [comment]
Ок, как будет время попробую добавить.

**Comment by BladeMight** [comment]
@MishGa 
> нестандартная раскладка

Он считает стандартную раскладку, языком системы. А у меня стандартная **раскладка** - English(US), так что он не по стандартной раскладке а по стандартному языку(у меня Русский) работает.
Я тут подумал может сделать так чтобы раскладка №1 в Mahou считалась главной, и при ее активации чтоб горел Scroll Lock, как думаешь?
P.S. Но если нравится вариант с стандартным **языком**, я могу и его сделать.

**Comment by MishGa** [comment]
Я настолько глубоко не задумывался. У меня стандартная тоже Английская, так что на Русской горит Scroll Lock, на Английской - нет. Думаю тут не принципиально, как проще так пусть и будет. Удобно для тех кто не умеет писать в слепую ориентироваться по Scroll Lock.

**Comment by BladeMight** [comment]
ОК, сделаю как там.

**Comment by BladeMight** [comment]
Чего-то я передумал, думаю лучше будет давать пользователю выбирать при каком что горел Scroll.

**Comment by MishGa** [comment]
Как будет угодно.

**Comment by BladeMight** [comment]
Вот добавил в [v1.4.1.7](https://github.com/BladeMight/Mahou/releases/tag/v1.4.1.7), проверьте.

**Comment by MishGa** [comment]
Спасибо, Scroll Lock работает. А Shift+Caps для включение-выключения Caps сделаете?

**Comment by BladeMight** [comment]
Хорошо, только уже завтра.

**Comment by MishGa** [comment]
Как вам будет угодно, уже и так больше чем я хотел от функционала при ничтожном размере.

**Comment by BladeMight** [comment]
Не, не я уже сделал :p
[Mahou-v1.4.1.8.zip](https://github.com/BladeMight/Mahou/files/616881/Mahou-v1.4.1.8.zip)

**Comment by MishGa** [comment]
Спасибо. Всё работает на ура.

**Comment by BladeMight** [comment]
Ну вот и отлично!
