### ISSUE TITLE
А существует ли функциональность "слов-исключений"?

### ISSUE THREAD

**Issue by ammosov** [BladeMight/Mahou#357]
## Problem/Request description

Возможно, это не issue per se - но существует ли user defined перечень строк, по которым автоконвертацию не следует производить?

## Expected behavior (Only if reporting bug)

Пример: 
печатается англ VS (сокр. от англ-лат versus - против) - частый юридический термин "дело такого-то против такого-то" или обиходное "сравнить А и Б"  
ожидается: VS
результат: автоконвертация в МЫ 

## System information

- Windows version: [Windows version (XP/7/8/8.1/10)]
- Windows architecture: [x86/x64]
- .Net version: [Your .Net version (4.0/4.5/4.6)]
- Mahou version: [Mahou version (you can see it in Mahou main window title)]

**Comment by BladeMight** [comment]
Нет, но можно удалить/закомментировать их в словаре.

**Comment by ammosov** [comment]
То есть ручным способом в текстовом редакторе?
