### ISSUE TITLE
[Feature request] Chocolatey support

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#36]
Предложение сделать возможной установку Mahou через [**Chocolatey**](https://chocolatey.org/) — пакетный менеджер для Windows.

Преимущества использования Chocolatey:

+ Лёгкая установка. Пользователю достаточно будет только ввести в терминал команду `cinst mahou -y`.
+ Можно настроить периодическое автоматическое обновление сразу для всех установленных программ (у меня их уже почти сотня). В таком случае не лишней будет опция отключения встроенного в Mahou средства автоматического обновления.
+ Если потребуется переустановка Windows или же пользование другим компьютером, пользователь может скопировать список программ Chocolatey → вставить его в терминал на другом компьютере в формате `cinst program1 program2 -y`. Не нужно переустанавливать каждую программу отдельно.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Попробую добавить.

**Comment by BladeMight** [comment]
@Kristinita добавил, теперь нужно одобрение администрации... Когда одобрят появится в поиске, а пока [здесь](https://chocolatey.org/packages/Mahou).

**Comment by BladeMight** [comment]
@Kristinita Все, готово!

**Comment by Kristinita** [comment]
@BladeMight , спасибо, не забывайте обновлять Chocolatey пакет!

**Comment by Kristinita** [comment]
@BladeMight , опция отказа от автоматического обновления была бы не лишней. Если пользователи обновляют Mahou через Chocolatey, то окно, предлагающее обновиться при старте Windows, только мешает.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita  добавлю.

**Comment by Kristinita** [comment]
Такой вопрос: у Вас достаточно быстро получается добавлять новые версии Mahou в Chocolatey, тогда как другим приходится несколько недель ждать модерации.

Как Вы это делаете? Возможно, подтвердили каким-либо образом владение программой?

Спасибо.

**Comment by BladeMight** [comment]
> Как Вы это делаете? Возможно, подтвердили каким-либо образом владение программой?

После 6-7 отправленной версии моя программа стала [trusted package](https://chocolatey.org/faq#what-is-a-trusted-package), поэтому все заканчивается через пол часа как я залил nupkg  и написал комментарий к выпуску в chocolatey чтобы статус программы стал `maintainer responded waiting for review or`... что то там.
