### ISSUE TITLE
Исправления в полезных сниппетах

### ISSUE THREAD

**Issue by yuklov** [BladeMight/Mahou#362]
Здравствуйте.

В полезных сниппетах есть такая функция:

1. Для исправления двух заглавных букв:

    СЕгодня => Сегодня

```
->regex/^([А-ЯA-Z])([А-ЯA-Z][а-яa-z])([a-zA-ZА-Яа-я]*)(?!.*? )/
====>$1\L$2$3<====
```

Но это не работает **с двухсимвольными словами**. Например:

СЕ годня => СЕ годня.
ОБ этом => ОБ этом.

Как это исправить?

**Comment by BladeMight** [comment]
Это правило срабатывает при 3 символах, для двух можешь использовать еще 1 правило:

```
->regex/^([А-ЯA-Z])([А-ЯA-Z])(?!.*? )$/
====>$1\L$2<====
```

В виду того что пользователь может захочет написать сам 2 заглавные и оставить их таковыми после пробела, например: КТ, ЗП, УД и т.д., а в правиле на wiki смотрится на 3-й символ - если он нижнего регистра тогда заменить и второй на нижний тоже.

**Comment by yuklov** [comment]
Спасибо.

Но почему-то не сработал.
```

->regex/^([А-ЯA-Z])([А-ЯA-Z])(?!.*? )$/
====>$1\L$2<====

```

Что-то изменить не надо?

**Comment by yuklov** [comment]
Убрал $, не сработал:

```
->regex/^([А-ЯA-Z])([А-ЯA-Z])(?!.*? )/
====>$1\L$2<====
```

**Comment by yuklov** [comment]
**После добавления этого кода:**

1. Отключилась автоматическая коррекция на ворде. То есть заглавная буква абзаца и предложения (после ! ? и .  обратно становиться строчными.

2. Если добавлю пробел в уже набранное слово, исчезается буква перед пробелом.

**Comment by BladeMight** [comment]
Вот с этими двумя правилами:

```
->regex/^([А-ЯA-Z])([А-ЯA-Z][а-яa-z])([a-zA-ZА-Яа-я]*)(?!.*? )$/
====>$1\L$2$3<====
->regex/^([А-ЯA-Z])([А-ЯA-Z])(?!.*? )$/
====>$1\L$2<====
```

1-е для 3+ букв и второе для 2-х заглавных, работает:

ЧТ => Чт
ЗАчем => Зачем
ОК => Ок
ЧТО => ЧТО (по правилу 1 не учитывается если 3-й символ не нижнего регистра, поэтому без изменений)

**Comment by yuklov** [comment]
![изображение](https://user-images.githubusercontent.com/59954194/151984783-678e384b-20db-42c5-9d88-6a2898118e98.png)
Знак $ нужен или нет? На вики этого символа нет.

У меня первое работает отлично. Проблема с новым кодом.

A-Z поменял на А-ЯЎҚҒҲA-Z.

**Comment by yuklov** [comment]
> (применить не забывай нажимать)

Сохранил, и перезапустил Mahou.

Сниппеты редактирую в ноутпаде. Если редактирую в программе, почему-то программа падает. Или появится китайские иероглифы.

**Comment by yuklov** [comment]
> P.S. Для символов с других раскладок может не хватать просто A-Z или a-z, так что это тоже следует учитывать.

Вот мой код:
```
->regex/^([А-ЯЎҚҒҲA-Z])[А-ЯЎҚҒҲA-Z])(?!.*? )$/
====>$1\L$2<====
```

**Comment by BladeMight** [comment]
> Знак $ нужен или нет

Нужен, изменил wiki. Там обычно хватает и `(?!.*? )` но лучше всё же использовать `$` всегда.


> Вот мой код

Пропустил скобку:

->regex/^([А-ЯЎҚҒҲA-Z])**(**[А-ЯЎҚҒҲA-Z])(?!.*? )$/
====>$1\L$2<====

**Comment by yuklov** [comment]
> Пропустил скобку:

🤦🏻‍♂️

**Comment by yuklov** [comment]
> А можно так делать, чтобы код **только в начале абзаца и только после знаки !?.** срабатывал?

Поставил код `(?<=[\.!?]\s)`. Не сработал.

**Comment by BladeMight** [comment]
> только в начале абзаца 

Mahou этого никак не узнать, он не редактор он следит только за словами.

> только после знаки !?.

Т.к. Mahou может следить за 2 словами, то можно вот так:

```
->regex/([\.!?])[ ](.)(.*)/
====>$1 \U$2\L$3<====
```

Кому! ЗАчем => Кому! Зачем

**Comment by BladeMight** [comment]
> Чтобы US, UK не изменился

Убрать A-Z?

**Comment by yuklov** [comment]
> Mahou этого никак не узнать, он не редактор он следит только за словами.

Понел ))



> Убрать A-Z?

Это надо в других языках.

Ладно, вручную буду делать.

**Comment by yuklov** [comment]
> ->regex/([\.!?])[ ](.)(.*)/
> ====>$1 \U$2\L$3<====

Этот код не работает в начале абзаца.

ОБ этом => ОБ этом 
_Слово какое-то._ ОБ этом => Об этом.

Можно добавить и начало абзаца?

**Comment by yuklov** [comment]
Добавил $ в конце кода:

->regex/([.!?]) (.*)**$**/

Правильно?

**Comment by BladeMight** [comment]
Это правило срабатывает только после слова заканчивающегося на .?! пробела и еще какого-то слова.

> Добавил $ в конце кода:

Тут не обязательно но можно ставить, т.к. это правило явно может сработать только при 2 словах - тут явно указан пробел.

**Comment by BladeMight** [comment]
>Чтобы слова в начале абзаца

Это для Mahou неизвестно, так что единственный вариант для 2-буквенных слов: https://github.com/BladeMight/Mahou/issues/362#issuecomment-1026899218

**Comment by yuklov** [comment]
Понял, тогда использую #362 (comment).

Спасибо огромное!
