### ISSUE TITLE
Не считывается из настроек "Другая" клавиша развёртывания сниппета

### ISSUE THREAD

**Issue by Dentorol** [BladeMight/Mahou#367]
## Problem/Request description

При установке "Другой" клавиши развёртывания сниппета (я использую сочетание RSHIFT+TAB), она работает и даже записывается в ini-файл. Но после перезапуска Mahou, данной клавиши снова нет в выпадающем списке.

## Expected behavior (Only if reporting bug)

Корректная загрузка из настроек сочетания клавиш для развёртывания сниппета.

## System information

- Windows version: 7 SP1 (Microsoft Windows NT 6.1.7601 Service Pack 1)
- Windows architecture: x64
- .Net version: .NET Framework 4.8 (4.0.30319.42000)
- Mahou version: 2.9.0.1-dev <226f5cc>

**Comment by BladeMight** [comment]
Хм. Такое у меня не воспроизводится:
![not-confirmed](https://user-images.githubusercontent.com/11931888/171998559-2281cb05-5a2c-41de-b2be-5951fddcec76.gif)

Как видно в конце просто по Tab/Space ничего не происходит, развёртывание происходит только при RShift+Tab как настроено.

**Comment by Dentorol** [comment]
Вот, записал экран: [YouTube](https://youtu.be/QUmEWi3hR-o)

**Comment by Dentorol** [comment]
Кажется, разобрался. Дело было в двух ini-файлах. Первый в AppData\Roaming\Mahou, а второй в Program Files (x86)\Mahou. Если я правильно понял, в моём случае, Mahou записывал настройки в первый ini, а читал из второго. Я скопировал первый на мето второго, и теперь он всегда сохраняет настройки в папке с программой. Хотя, это немного странно, ведь настройки желательно должны храниться в папке профиля.

**Comment by Dentorol** [comment]
Да, кажется, нашёл ошибку. Если стоит галочка "Конфигурация в AppData", то клавиша сниппетов не считывается.

**Comment by BladeMight** [comment]
@Dentorol У меня и так и так работает. 

При включении "Конфигурация в AppData" !!Mahou записывать AppDataConfigs=True в ini который рядом с Mahou.exe!!, и переключается на %appdata%\Mahou.ini, при запуске первым делом считывается AppDataConfigs из ini что рядом с exe, если True - тогда сразу идёт переключение на %appdata% и загрузка других настроек. Проверь "SnippetExpandKey" в %appdata%\Mahou.ini после закрытия Mahou. 

Также есть способ "принудительного переключения на %appdata%" создать файл `.force` в %appdata%, можно так: Win+R и
```cmd
cmd /c echo "" > "%appdata\Mahou\.force"
```

Наличие этого файла является приоритетом перед проверкой AppDataConfigs из ini что рядом с exe

> Program Files (x86)\Mahou

Скорее всего Mahou не смог !!записать файл Mahou.ini!!, права папки Mahou стоят такие что полный доступ пользователю который его запускает?

**Comment by Dentorol** [comment]
Нет, запись в Program Files осуществляется. Видимо, у меня какие-то кривые конфиги. Возможно, от старых версий остались какие-то неправильные записи. На всякий случай прикладываю мои конфиги: https://disk.yandex.ru/d/sX09HljWyxYWSw

**Comment by BladeMight** [comment]
@Dentorol Нашел. Исправил в [08572c6](https://github.com/BladeMight/Mahou/commit/08572c6ed62c3b34608ff482d86198ddcb519751)

**Comment by Dentorol** [comment]
Теперь работает! Спасибо!
