### ISSUE TITLE
Ошибка.

### ISSUE THREAD

**Issue by MishGa** [BladeMight/Mahou#37]
При запуске командной строки, или PowerShell Вылетает ошибка Net, в сведениях вот что.
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.Globalization.CultureNotFoundException: Неподдерживаемая культура.
Имя параметра: culture
0 (0x0000) - недопустимый идентификатор культуры.
   в System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride)
   в System.Globalization.CultureInfo..ctor(Int32 culture, Boolean useUserOverride)
   в Mahou.LangDisplay.RefreshLang()
   в Mahou.MahouForm.<.ctor>b__3(Object _, EventArgs __)
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Mahou
    Версия сборки: 1.4.2.1
    Версия Win32: 1.4.2.1
    CodeBase: file:///D:/Images/dotdwitch/Mahou.exe
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by BladeMight** [comment]
Ошибка вылетает из-за недавно упрощенного способа получения букв языка через `System.Globalization`, и вылетает потому что в командной строке(или PowerShell) код языка почему-то `0x0000`.
Как работает здесь:
[Mahou-Beta.zip](https://github.com/BladeMight/Mahou/files/628889/Mahou-Beta.zip)

**Comment by BladeMight** [comment]
@MishGa Как в новых версиях(1.4.2.2+)?

**Comment by BladeMight** [comment]
@MishGa Как работает в v1.4.3.2 со включенным логированием, и что показывает в логе?

**Comment by MishGa** [comment]
Версия 1.4.2.2 работает прекрасно. Версия 1.4.3.2 вызывает зависание мыши и клавиатуры. (К примеру запущенное видео работает, но клавиатура и мышь не отзываются, но горит индикатор на мыши и NumLock на клавиатуре). С логированием проверю сегодня, но позже.

**Comment by BladeMight** [comment]
>Сначала программа вылетела, я запустил повторно и после применения снипета "хх" опять зависание, компьютер перегрузил кнопкой reset.

Не стоило перезагружать, это просто ошибка .Net она больше 15-30 секунд не держит зависание.
Лог оказался очень полезным, проверьте эту версию:
[MahouBeta.zip](https://github.com/BladeMight/Mahou/files/633666/MahouBeta.zip)

**Comment by MishGa** [comment]
ОК.

**Comment by BladeMight** [comment]
А можешь мне прислать архив с Mahou.exe, Mahou.ini, snippets.txt и с папкой Logs? (Для для более детального анализа.)

>ОК.

То есть все ок, можно делать релиз?(Думаю после детального анализа, будет в самый раз.)

**Comment by MishGa** [comment]
http://take.ms/nyyjH - на всякий случай файлы которые вы просили.
За последние час-полтора не подвисало. Считаю что всё исправили. Спасибо.

**Comment by BladeMight** [comment]
>http://take.ms/nyyjH - на всякий случай файлы которые вы просили.
За последние час-полтора не подвисало. Считаю что всё исправили. Спасибо.

ОК, проверю и сделаю релиз.

**Comment by BladeMight** [comment]
Релиз [v1.4.3.5](https://github.com/BladeMight/Mahou/releases/tag/v1.4.3.5).

**Comment by BladeMight** [comment]
@MishGa По поводу дополнительных файлов:
В логе многократно показывается только 1 предупреждение о том что текущая раскладка не может быть получена, вероятно некая программа блокирует доступ к текущей раскладке, но это не так страшно, ведь Mahou будет пробовать пока не получится, так что все ОК.

**Comment by MishGa** [comment]
Стоило обновится на новый релиз, как сразу ошибка вернулась. Программа с которой возникнет ошибка скорее всего Miranda NG, по крайней мере  пару раз точно при обращение к ней подвисало.
Но сейчас не работает только клавиатура, завершил мышкой в диспетчере Mahou и клавиатура ожила.
Лог был отключен но в системных пишет следующее:

> Имя журнала:   Application
> Источник:      .NET Runtime
> Дата:          06.12.2016 21:40:31
> Код события:   1026
> Категория задачи:Отсутствует
> Уровень:       Ошибка
> Ключевые слова:Классический
> Пользователь:  Н/Д
> Компьютер:     DESKTOP-HV1JEI8
> Описание:
> Приложение: Mahou.exe
> Версия платформы: v4.0.30319
> Описание. Процесс был завершен из-за необработанного исключения.
> Сведения об исключении: System.ArgumentOutOfRangeException
>    в System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
>    в System.Collections.Generic.List`1[[Mahou.KMHook+YuKey, Mahou, Version=1.4.3.5, Culture=neutral, PublicKeyToken=null]].get_Item(Int32)
>    в Mahou.KMHook.HookCallback(Int32, IntPtr, IntPtr)
> 
> 
> Xml события:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name=".NET Runtime" />
>     <EventID Qualifiers="0">1026</EventID>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2016-12-06T14:40:31.170469000Z" />
>     <EventRecordID>173434</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer>DESKTOP-HV1JEI8</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Приложение: Mahou.exe
> Версия платформы: v4.0.30319
> Описание. Процесс был завершен из-за необработанного исключения.
> Сведения об исключении: System.ArgumentOutOfRangeException
>    в System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
>    в System.Collections.Generic.List`1[[Mahou.KMHook+YuKey, Mahou, Version=1.4.3.5, Culture=neutral, PublicKeyToken=null]].get_Item(Int32)
>    в Mahou.KMHook.HookCallback(Int32, IntPtr, IntPtr)
И следом вторая ошибка.
Имя журнала:   Application
Источник:      Application Error
Дата:          06.12.2016 21:40:31
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     DESKTOP-HV1JEI8
Описание:
Имя сбойного приложения: Mahou.exe, версия: 1.4.3.5, метка времени: 0x5846c2e6
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.14393.321, метка времени: 0x57f4c291
Код исключения: 0xe0434352
Смещение ошибки: 0x000da6f2
Идентификатор сбойного процесса: 0x1010
Время запуска сбойного приложения: 0x01d24fce6acc3aab
Путь сбойного приложения: D:\Images\dotdwitch\Mahou.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 8100a9f7-4e2c-4232-8543-8417cf7f5b83
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-12-06T14:40:31.486372000Z" />
    <EventRecordID>173435</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-HV1JEI8</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Mahou.exe</Data>
    <Data>1.4.3.5</Data>
    <Data>5846c2e6</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.14393.321</Data>
    <Data>57f4c291</Data>
    <Data>e0434352</Data>
    <Data>000da6f2</Data>
    <Data>1010</Data>
    <Data>01d24fce6acc3aab</Data>
    <Data>D:\Images\dotdwitch\Mahou.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>8100a9f7-4e2c-4232-8543-8417cf7f5b83</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by MishGa** [comment]
Стоило обновится на новый релиз, как сразу ошибка вернулась. Программа с которой возникнет ошибка скорее всего Miranda NG, по крайней мере  пару раз точно при обращение к ней подвисало.
Но сейчас не работает только клавиатура, завершил мышкой в диспетчере Mahou и клавиатура ожила.
Лог был отключен но в системных пишет следующее:

> Имя журнала:   Application
> Источник:      .NET Runtime
> Дата:          06.12.2016 21:40:31
> Код события:   1026
> Категория задачи:Отсутствует
> Уровень:       Ошибка
> Ключевые слова:Классический
> Пользователь:  Н/Д
> Компьютер:     DESKTOP-HV1JEI8
> Описание:
> Приложение: Mahou.exe
> Версия платформы: v4.0.30319
> Описание. Процесс был завершен из-за необработанного исключения.
> Сведения об исключении: System.ArgumentOutOfRangeException
>    в System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
>    в System.Collections.Generic.List`1[[Mahou.KMHook+YuKey, Mahou, Version=1.4.3.5, Culture=neutral, PublicKeyToken=null]].get_Item(Int32)
>    в Mahou.KMHook.HookCallback(Int32, IntPtr, IntPtr)
> 
> 
> Xml события:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name=".NET Runtime" />
>     <EventID Qualifiers="0">1026</EventID>
>     <Level>2</Level>
>     <Task>0</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2016-12-06T14:40:31.170469000Z" />
>     <EventRecordID>173434</EventRecordID>
>     <Channel>Application</Channel>
>     <Computer>DESKTOP-HV1JEI8</Computer>
>     <Security />
>   </System>
>   <EventData>
>     <Data>Приложение: Mahou.exe
> Версия платформы: v4.0.30319
> Описание. Процесс был завершен из-за необработанного исключения.
> Сведения об исключении: System.ArgumentOutOfRangeException
>    в System.ThrowHelper.ThrowArgumentOutOfRangeException(System.ExceptionArgument, System.ExceptionResource)
>    в System.Collections.Generic.List`1[[Mahou.KMHook+YuKey, Mahou, Version=1.4.3.5, Culture=neutral, PublicKeyToken=null]].get_Item(Int32)
>    в Mahou.KMHook.HookCallback(Int32, IntPtr, IntPtr)
И следом вторая ошибка.
Имя журнала:   Application
Источник:      Application Error
Дата:          06.12.2016 21:40:31
Код события:   1000
Категория задачи:(100)
Уровень:       Ошибка
Ключевые слова:Классический
Пользователь:  Н/Д
Компьютер:     DESKTOP-HV1JEI8
Описание:
Имя сбойного приложения: Mahou.exe, версия: 1.4.3.5, метка времени: 0x5846c2e6
Имя сбойного модуля: KERNELBASE.dll, версия: 10.0.14393.321, метка времени: 0x57f4c291
Код исключения: 0xe0434352
Смещение ошибки: 0x000da6f2
Идентификатор сбойного процесса: 0x1010
Время запуска сбойного приложения: 0x01d24fce6acc3aab
Путь сбойного приложения: D:\Images\dotdwitch\Mahou.exe
Путь сбойного модуля: C:\WINDOWS\System32\KERNELBASE.dll
Идентификатор отчета: 8100a9f7-4e2c-4232-8543-8417cf7f5b83
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 
Xml события:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-12-06T14:40:31.486372000Z" />
    <EventRecordID>173435</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-HV1JEI8</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Mahou.exe</Data>
    <Data>1.4.3.5</Data>
    <Data>5846c2e6</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.14393.321</Data>
    <Data>57f4c291</Data>
    <Data>e0434352</Data>
    <Data>000da6f2</Data>
    <Data>1010</Data>
    <Data>01d24fce6acc3aab</Data>
    <Data>D:\Images\dotdwitch\Mahou.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>8100a9f7-4e2c-4232-8543-8417cf7f5b83</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by MishGa** [comment]
http://take.ms/DE6oE - это лог с зависанием новой версии. Но сейчас Mahou просто закрылась.
Есть вот какая мысль. В Миранде установлен штатный плагин по смене раскладки. Попробую отключить и потестировать.

**Comment by BladeMight** [comment]
>Программа с которой возникнет ошибка скорее всего Miranda NG

Где конкретно зависает? Я вот сейчас скачал и сам проверяю, но пока не вылетало...

**Comment by BladeMight** [comment]
> Программа с которой возникнет ошибка скорее всего Miranda NG

@MishGa Где конкретно зависает(при каких действиях)? Я вот сейчас скачал и сам проверяю, но пока не вылетало...

**Comment by BladeMight** [comment]
Ну не знаю. у меня все нормально работает и в окне отправления сообщения и везде где только можно писать...
Даже с твоими настройками(кроме Win+Space т.к. у меня Win7):
[Mahou-MishGA.zip](https://github.com/BladeMight/Mahou/files/634389/Mahou-MishGA.zip)

**Comment by MishGa** [comment]
Да никаких действия. Обычно начинаешь печатать, а уже зависло. В журнале пишет что ошибку вызвала Mahou. Может с чем-то стороннем конфликт, но последняя бета которую вы присылали - работает хорошо. Релизы - вылетает. Останусь на этой бете. Будет время попытаюсь разобоаться детальней.

**Comment by BladeMight** [comment]
Давай я тогда сделаю несколько сборок, с разными типами, эмм..., того что я изменял в бетке, а ты скажешь какая работает, ОК?

**Comment by MishGa** [comment]
Проверил, оба проработали примерно 2 минуты. И если Mahou[GotoCatch] - подвесил клавиатуру и мышь, то Mahou[SpaceBack]+[GotoCatch] - подвесил клавиатуру, мышь и появилось окно ошибки win. 
Есть у меня новое подозрение, может конфликт с утилиткой CLCL. Но проверять я буду завтра.

**Comment by BladeMight** [comment]
Я рекомендую [обновить .Net](https://www.microsoft.com/ru-ru/download/details.aspx?id=53344), потому что настолько разное поведение почти идентичных сборок не нормально.
И насчет CLCL с ней конфликтов нет...

**Comment by MishGa** [comment]
CLCL - точно не виновато, проверил. NET стоит самый последний. Завтра попробую запускать от админа и варианты у меня закончились.

**Comment by BladeMight** [comment]
Еще судя по последнему логу, ошибка произошла после того как ты написал "CThsq?" и начал удалять по одному, и нажал один лишний раз BackSpace, из-за чего вышла ошибка, но у меня при нажатии лишний раз BackSpace не происходит ничего, как было задумано. Так что пока Я не знаю в чем причина, быть может в .Net'е, может в Win 10...
И еще вопрос а ты не можешь протестировать с использованием SharpDevelop? Если да, я могу дать все нужное.
Все это очень странно, ведь у меня все работает отлично... Думаю стоит установить себе 10-ку на вирт машину и проверить там. А какая версия Win10 у тебя?

**Comment by MishGa** [comment]
Ошибка возникает когда я использую любую горячую клавишу. Сейчас обновил до последней версии, поставил всё по умолчанию, отключил всё что по моему мнению могло помешать. И словил вылет, а потом и зависание по "конверт выделения". Лог тот же, виндовая ошибка - та-же. 
Система - win 10 x64. Без всяких твиков, лицензия. 
Потестировать  SharpDevelop я наверное смогу, но если честно не знаю что и как. Для меня что программирование, это даже не наука, это какая-то магия.

**Comment by BladeMight** [comment]
> Потестировать SharpDevelop я наверное смогу

ОК, тогда это очень хорошо! Вот что нужно сделать:

1. Скачай этот архив [Testing.zip](https://github.com/BladeMight/Mahou/files/636854/Testing.zip) и распакуй в любую папку.
2. Запусти в распакованной папке файл `opensolution` и подожди пока запустится SharpDevelop.
3. В панели инструментов нажми на кнопку:
![sharpdev](https://cloud.githubusercontent.com/assets/11931888/20971951/fdeaa022-bc9b-11e6-8ec0-eef25710305d.PNG)
4. И соберется Mahou, и запустится, после этого если зависнет, сделай мне скриншот вывода SharpDevelop'а или скопируй весь текстовый вывод и отправь мне.

Лучше попробуй 2-3 раза собрать и запустить, и словленные ошибки SharpDevelop'ом присылай мне.
После этого Я уверен что смогу понять в чем именно ошибка.

**Comment by MishGa** [comment]
http://take.ms/P53Y6 качество плохое, но та же ошибка что и в логе. Зависает буквально через 5 секунд после запуска, последний раз даже не успел нажать на pause. Так-что скопировать ничего не получается, пришлось фотографировать на то что было под рукой.
Вот ещё что. Пишет что у меня .NET Framework 4.0, ставлю NET Framework 4.6.2., говорит что версия не требует обновления. Пробовал сейчас удалить NET и поставить новый, всё равно. Может есть какая-то свзяь.

**Comment by BladeMight** [comment]
Вот самое интересное в последней строчке, после слов В d:\testing\ то то мне и нужно было узнать.

**Comment by MishGa** [comment]
Зависает напрочь, я посмотреть не смогу. Попробую ещё, но не обещаю.

**Comment by BladeMight** [comment]
Ну оно и правда зависает, но не надолго секунд ~15-30.

**Comment by MishGa** [comment]
Я жду минут по 10 пока не отвиснет. Потом перегружаю кнопкой reset. Вся проблема в том, что клавиатура и мышь не работают.

**Comment by BladeMight** [comment]
> Я жду минут по 10 пока не отвиснет.

Да ладно, не ожидал такого... Совсем странно... Пробуй много нажимать кнопки на клавиатуре и мышке, и двигать мышкой, слышен ли звук какой-то?(должен быть)

Вот я тут еще пару сборок создал, исходя из того что есть, я предположил что проблема в новой функции "конверт нескольких последних слов", проверь какая как работает.
[Mahou-Tests.zip](https://github.com/BladeMight/Mahou/files/637092/Mahou-Tests.zip)

**Comment by MishGa** [comment]
Зависает конкретно. Даже не зависает, а скорее отключает мышь и клавиатуру. Потому-что звук, или видео при этом работает, в диспетчере задач тоже всё в порядке. Но Mahou в диспетчере вылетает с системной ошибкой. Я даже пробовал клавиатуру+мышь отключать и подключать, не подхватывает.
Так-что я сам в шоке от такого поведения. А теперь о тестах. Тестил пять 5 минут, обычно для ошибки хватает и две.
Mahou-NoCwords-Absolute _ не работает конверт строки 
Mahou-NoCwords-More _ зависла сразу
Mahou-NoCwordsAddins _ не работает конверт строки, при нажатии "конверт строку" пропадает последняя буква в последнем слове.
Mahou-NoCwordsClea _ поработала 5 минут и не зависла.
Mahou-NoLogging _ поработала 5 минут и не зависла.

**Comment by BladeMight** [comment]
Mahou-NoLogging - не зависла??? А можешь еще ее потестить?

**Comment by MishGa** [comment]
> Mahou-NoLogging - не зависла??? А можешь еще ее потестить?
Да, я уже с полчаса с ней сижу и ничего.

**Comment by BladeMight** [comment]
Хм, тогда проблема в логгинге? Что это я там упусти...?

**Comment by BladeMight** [comment]
Оказывается у меня на 7 был, какой-то не рабочий .Net который просто пропускал ошибки... на 10 я уже разобрался в чем проблема, и выпустил релиз: [v1.4.3.6](https://github.com/BladeMight/Mahou/releases/tag/v1.4.3.6).

**Comment by MishGa** [comment]
Спасибо. Уже обновился и всё работает.

**Comment by BladeMight** [comment]
Отлично, еще одна проблема решена.
