### ISSUE TITLE
Не конвертирует или конвертирует неправильно ' ("), если менять методом selected text

### ISSUE THREAD

**Issue by FedirVolkov** [BladeMight/Mahou#370]
## Problem/Request description
Не конвертирует с английской на украинскую раскладку и обратно ' ("), если менять методом selected text
## Expected behavior (Only if reporting bug)
' - є - '
" - Є - "
Конвертирование на русский тоже корявое: ' - ё - `
должно быть: ' - э - '
## System information
- Windows version: Windows 8.1 x64 со всеми обновлениями
- Mahou version: 2.9.0.1
- Раскладка: Ukrainian Enhanced (4037542946)

**Comment by BladeMight** [comment]
Mahou latest-commit:

![worksok](https://user-images.githubusercontent.com/11931888/175925356-61dce3eb-2f9b-4ab1-b402-d38d4b7cf8f0.gif)

Для обновления до latest-commit:
1. Во вкладке "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление)
2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - Release_x86_x64.zip)

**Comment by FedirVolkov** [comment]
> Mahou latest-commit:
> 
> ![worksok](https://user-images.githubusercontent.com/11931888/175925356-61dce3eb-2f9b-4ab1-b402-d38d4b7cf8f0.gif) [ ](https://user-images.githubusercontent.com/11931888/175925356-61dce3eb-2f9b-4ab1-b402-d38d4b7cf8f0.gif) ![worksok](https://user-images.githubusercontent.com/11931888/175925356-61dce3eb-2f9b-4ab1-b402-d38d4b7cf8f0.gif) [ ](https://user-images.githubusercontent.com/11931888/175925356-61dce3eb-2f9b-4ab1-b402-d38d4b7cf8f0.gif)
> 
> Для обновления до latest-commit:
> 
> 1. Во вкладке "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление)
> 2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - Release_x86_x64.zip)

**Comment by FedirVolkov** [comment]
Обновился, теперь конвертирует нормально, но не работает опция "выделять заново текст после конвертации"

**Comment by BladeMight** [comment]
> выделять заново текст после конвертации

Возможно у тебя сбросилось? Во вкладке [Hidden] нужно поставить значение для которых гор. клавиш использовать пере-выделение:

![](https://camo.githubusercontent.com/0ee73c385352438cc85ce1955c07aa3ca22e6b146e030edbb0f1bec98a760d8f/68747470733a2f2f692e696d6775722e636f6d2f694f74485a55312e6a7067)

По-умолчанию стоит - для всех: `tTRSULCNB`

**Comment by FedirVolkov** [comment]
Да, там почему-то было пусто , теперь всё ок

**Comment by BladeMight** [comment]
В a24efe2 исправил, там в настройках при загрузке/сохранении использовалось значение: `ReselectCustoms`, а стандартное значение стояло длс `ReSelectCustoms` (S - верхнего регистра), теперь загружает и сохраняет также в `ReSelectCustoms`.
