### ISSUE TITLE
Иконка в трее исчезает

### ISSUE THREAD

**Issue by fixator10** [BladeMight/Mahou#371]
## Проблема/описание запроса

При перезапуске `explorer.exe` любая "динамическая" (флаги/текст) иконка Mahou в трее становится прозрачной.

До перезапуска:
![Трей Windows 10: Mahou имеет иконку английского языка (флаг США)](https://moeka.is-a-good-waifu.com/5Ste9td.png)
После:
![Трей Windows 10: У Mahou отсутствует иконка](https://moeka.is-a-good-waifu.com/2x9hQEb.png)

При смене языка иконка возвращается

## Ожидаемое поведение (только при сообщении об ошибках)

Иконка остаётся на месте с перезапуском `explorer.exe`

## Информация окружения/Отладочная информация

- Версия Windows: Windows-10-10.0.19041-SP0
- Архитектура Windows: x64
- Версия .Net: 4.0.30319.42000
- Версия Mahou: 2.9.0.1-dev <584b67e>

**Comment by BladeMight** [comment]
Mahou меняет иконку только когда язык меняется во избежания лишней нагрузки. При перезапуске проводника происходит очистка(?) иконок из-за этого Mahou не знает что иконка очистилась, сделал проверку что id проводника всё еще тот же что и был раньше, если отличается то обновить иконку.
