### ISSUE TITLE
English -> Russian conversion in "symbol ignored mode" acts strange

### ISSUE THREAD

**Issue by cherjr** [BladeMight/Mahou#380]
Very strange behavior: "ignored" symbol goes to first position of string when perform "Convert last line" from ENG to RU (works if RU to ENG): https://user-images.githubusercontent.com/49041653/212378634-bcc64ec6-a890-470e-ad61-0be5b84e735a.mp4

Toggle symbol ignore mode: enabled and on
![image](https://user-images.githubusercontent.com/49041653/212376427-14d85505-4835-444b-b61d-61213304c3dd.png)

Convert last line: enabled
![image](https://user-images.githubusercontent.com/49041653/212376531-97bc9855-ea37-4ecb-a39d-21620f71b444.png)

Functions: 
![image](https://user-images.githubusercontent.com/49041653/212377793-b9c3b6d0-a120-479b-b858-e7dd1e3f7e7d.png)

**Comment by BladeMight** [comment]
Try different doing same thing in a different program, like regular notepad and see if there is any difference?

Weird things from configuration in functions:

1. You really need both "L" and "T" startup types? Pretty sure you need only T. If you want to disable one, select it from dropdown and uncheck "Start with Windows." then press Apply.
2. `Retrieve layout from JKL ` is colored red - meaning there is some kind of issue with JKL, do you have jkl* files near Mahou.exe?

**Comment by cherjr** [comment]
> Try different doing same thing in a different program, like regular notepad and see if there is any difference?

No, it's the same...

> Weird things from configuration in functions:
> 
> 1. You really need both "L" and "T" startup types? Pretty sure you need only T. If you want to disable one, select it from dropdown and uncheck "Start with Windows." then press Apply.

done, thanks!

> 2. `Retrieve layout from JKL ` is colored red - meaning there is some kind of issue with JKL, do you have jkl* files near Mahou.exe?

no, I don't (and, I guess, I'm not using it).

Any ideas?... Want to get rid of conversion for smiles ( :) ;) etc)....

**Comment by BladeMight** [comment]
> it's the same...

Hm... I couldn't reproduce same behavior, could you upload your configs/Mahou.ini, so I can try to figure it out?

**Comment by BladeMight** [comment]
Oh, I just noticed that you are using **regular** 2.9.0.1 version, which doesn't have many new functions and bugfixes, consider updating to latest-commit:

To update to latest-commit:
1. In "Updates" tab switch update channel to LatestCommit(Beta), and update as usual (check=>download)
2. On this page: https://github.com/BladeMight/Mahou/releases/tag/latest-commit there are auto-updated latest-commit build. (if unsure which to download - choose Release_x86_x64.zip)

**Comment by cherjr** [comment]
Yes, on dev-version everything works fine! Great, and thanks one more time for your excellent product!
