### ISSUE TITLE
Функция новой линии без enter???

### ISSUE THREAD

**Issue by znthtclee** [BladeMight/Mahou#384]
Использую сниппеты чтобы отправлять быстрые сообщения.

Когда пишу сниппет следующим образом:

->snippet1
====>this is a snippet text:
-one example
-two examples
-three examples
And a final text, for example<====

Сообщение в whatsapp выводится как 5 отдельных сообщений:

this is a snippet text:

-one example

-two examples

-three examples

And a final text, for example

Вопрос:

Можно ли сделать так, чтобы всё это послалось одним сообщением, с соблюдением положения строк?

**Comment by BladeMight** [comment]
В зависимости от того как Whatsapp реагирует на <kbd>Enter</kbd> - можно, если `Ctrl+Enter` в Whatsapp вводит новую линию то вместо новых линий поставь `__keyboard(ctrl+enter)`:

```
->snippet1
====>this is a snippet text:__keyboard(ctrl+enter)-one example__keyboard(ctrl+enter)-two examples__keyboard(ctrl+enter)-three examples__keyboard(ctrl+enter)And a final text, for example<====
```

Не самый "визуально" лучший способ, однако рабочий. Можно также использовать `__paste()` чтобы вставить текст как из буфера обмена:

```
->snippet1
====>__paste(this is a snippet text:
-one example
-two examples
-three examples
And a final text, for example)<====
```

"визуально" получше, однако есть ограничения и использование `)` внутри функции нужно записывать как `\)`.

Подробнее о возможностях в сниппетах см. [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BD%D0%B8%D0%BF%D0%BF%D0%B5%D1%82%D1%8B%3F-%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%3F#список-функций)

**Comment by znthtclee** [comment]
> В зависимости от того как Whatsapp реагирует на Enter - можно, если `Ctrl+Enter` в Whatsapp вводит новую линию то вместо новых линий поставь `__keyboard(ctrl+enter)`:
> 
> ```
> ->snippet1
> ====>this is a snippet text:__keyboard(ctrl+enter)-one example__keyboard(ctrl+enter)-two examples__keyboard(ctrl+enter)-three examples__keyboard(ctrl+enter)And a final text, for example<====
> ```
> 
> Не самый "визуально" лучший способ, однако рабочий. Можно также использовать `__paste()` чтобы вставить текст как из буфера обмена:
> 
> ```
> ->snippet1
> ====>__paste(this is a snippet text:
> -one example
> -two examples
> -three examples
> And a final text, for example)<====
> ```
> 
> "визуально" получше, однако есть ограничения и использование `)` внутри функции нужно записывать как `\)`.
> 
> Подробнее о возможностях в сниппетах см. [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BD%D0%B8%D0%BF%D0%BF%D0%B5%D1%82%D1%8B%3F-%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%3F#%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9)



Огромное спасибо, попробую обязательно.

**Comment by BladeMight** [comment]
И да не забудь использовать latest-commit версию.

Для обновления до latest-commit:
1. Во вкладке "Обновления" поставить канал обновлений на LatestCommit(Beta), и обновиться как обычно(проверить, скачать обновление)
2. На странице: https://github.com/BladeMight/Mahou/releases/tag/latest-commit есть постоянно авто-обновляемые сборки. (если не знаешь какую брать - Release_x86_x64.zip)

**Comment by znthtclee** [comment]
Большое спасибо!
