### ISSUE TITLE
Некоторие замечание

### ISSUE THREAD

**Issue by irasved197** [BladeMight/Mahou#385]
Отличное приложение! Единственное, что мне не нравится, что иконка самого ярлыка программы не совпадает с иконкой, используемой в самой программе. То есть, насколько я вижу, как эмблему для приложения Вы используете волшебную палочку, а вот в самой программе используется значок бабочки. Это немного запутано получается. Мне лично больше нравится именно бабочка. Но когда я создаю ярлык, или в проводнике вместо отображения списком переключаю на плитку, то вместо бабочки уже появляется волшебная палочка. Это не очень хорошо. Если можно, то поправьте это пожалуйста. А если не планируете исправлять, то сбросьте мне тогда пожалуйста иконку бабочки, которую Вы используете, потому что я не смогла найти. Вижу на гитхабе там какая-то другая бабочка в папочке Mahou/Mahou.ico. Я прикрепила скрин, который именно используется сейчас в приложении.

А, и  ещё. Раньше Вы все упаковывали в один ехе, а сейчас много всяких-различных файлов дополнительно. Не могли бы вы вернуть как раньше. Спасибо.
![2141030420230](https://user-images.githubusercontent.com/126984690/222925857-a3bf8a7c-8693-4d51-885b-618341a52c04.png)

**Comment by BladeMight** [comment]
> волшебную палочку

и 

> значок бабочки

Это старые иконки, уже не используются в exe, текущая версия - [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit), использует именно ту иконку что в [Mahou/Mahou.ico](https://github.com/BladeMight/Mahou/blob/master/Mahou/Mahou.ico)

Старую конечно можно посмотреть перед коммитом обновления: [42876acd/Mahou/Mahou.ico](https://github.com/BladeMight/Mahou/blob/42876acdd30f1e2c7b3d11aaf2fc5932ea7b96cf/Mahou/Mahou.ico)
Как можно увидеть в волшебной палочке также присутствовала бабочка.

В заголовке Mahou используются иконка отсюда [Mahou/Properties/Resourses.resx](https://github.com/BladeMight/Mahou/blob/master/Mahou/Properties/Resources.resx#L123), это base64 самого изображения, можно посмотреть если вставить сюда например: https://base64.guru/converter/decode/file

> много всяких-различных файлов дополнительно

Они не обязательны, без них тоже работает, однако с JKL распознавание раскладки работает гораздо лучше.

> Не могли бы вы вернуть как раньше.

Нет.

**Comment by irasved1997** [comment]
> > волшебную палочку
> 
> и
> 
> > значок бабочки
> 
> Это старые иконки, уже не используются в exe, текущая версия - [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit), использует именно ту иконку что в [Mahou/Mahou.ico](https://github.com/BladeMight/Mahou/blob/master/Mahou/Mahou.ico)
> 
> Старую конечно можно посмотреть перед коммитом обновления: [42876acd/Mahou/Mahou.ico](https://github.com/BladeMight/Mahou/blob/42876acdd30f1e2c7b3d11aaf2fc5932ea7b96cf/Mahou/Mahou.ico) Как можно увидеть в волшебной палочке также присутствовала бабочка.
> 
> В заголовке Mahou используются иконка отсюда [Mahou/Properties/Resourses.resx](https://github.com/BladeMight/Mahou/blob/master/Mahou/Properties/Resources.resx#L123-L194), это base64 самого изображения, можно посмотреть если вставить сюда например: https://base64.guru/converter/decode/file
> 
> > много всяких-различных файлов дополнительно
> 
> Они не обязательны, без них тоже работает, однако с JKL распознавание раскладки работает гораздо лучше.
> 
> > Не могли бы вы вернуть как раньше.
> 
> Нет.

Понятно.

То изображение что в проекте слишком мелкое, вроде 16х16, или 32х32, для ярлыка это набор пикселей получается. Нужно, чтобы хотя 128х128, как у волшебной палочки. Я думала, может у Вас на компе где-то сохранилось исходное изображение, Вы же вряд ли сначала использовали такое мелкое, наверняка сжимали. Может, где-то завалялось и исходное изображение. Посмотрите, пожалуйста. Буду очень благодарна 🥺

**Comment by BladeMight** [comment]
[m.zip](https://github.com/BladeMight/Mahou/files/10891939/m.zip)

**Comment by irasved1997** [comment]
> [m.zip](https://github.com/BladeMight/Mahou/files/10891939/m.zip)

Огромное спасибо ☺️
