### ISSUE TITLE
перестали работать горячие клавиши

### ISSUE THREAD

**Issue by Satenex** [BladeMight/Mahou#398]
2.9.0.1 dev a5c26d4
перестали работать горячие клавиши через Control. может быть немного раньше по версиям... ориентировочно максимум месяц

**Comment by Satenex** [comment]
![2023-08-05_200935](https://github.com/BladeMight/Mahou/assets/112253104/d9ceee94-7c1a-4451-92d2-8ba755c145b1)

**Comment by BladeMight** [comment]
см. https://github.com/BladeMight/Mahou/issues/390

**Comment by Satenex** [comment]
вот теперь работает, спасибо

**Comment by BladeMight** [comment]
ОК.
