### ISSUE TITLE
make it x64 compatible

### ISSUE THREAD

**Issue by OleksandrKucherenko** [BladeMight/Mahou#40]
Right now app is executing in 32-bits mode, Its .net - so it should be quite easy to resolve the APIs binding and make it fully compatible with 64-bits.

Thanks for nice software!

References that may help:
- http://www.hanselman.com/blog/BackToBasics32bitAnd64bitConfusionAroundX86AndX64AndTheNETFrameworkAndCLR.aspx

**Comment by BladeMight** [comment]
Actually, I was been doing some benchmarks and didn't get too much performance(maybe just on my dual-core cpu?) so I just leave it to be x86, but if there really performance then I should it AnyCPU, so it can run on any platform with max performance, right?

**Comment by BladeMight** [comment]
I think, now doing some other tests, I noticed that there IS some performance boost, so soon I'll release the AnyCPU version, which will be the default from now on.

**Comment by BladeMight** [comment]
OK, I done a [AnyCPU release](https://github.com/BladeMight/Mahou/releases/tag/v1.4.3.8).

**Comment by OleksandrKucherenko** [comment]
👍
