### ISSUE TITLE
Замена флагов на свои

### ISSUE THREAD

**Issue by bratskij** [BladeMight/Mahou#400]
Можно как то заменить флаги на свои? Они маленько побольше и по ярче.
https://dropmefiles.com/HlZVy

**Comment by BladeMight** [comment]
[wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#отображать-флаги-стран-в-трее)

**Comment by bratskij** [comment]
Да, я понял. Но Вы может посмотрите эти флаги и добавите если они понравятся. Они не плохо смотрятся. 
https://dropmefiles.com/cOmMJ

**Comment by BladeMight** [comment]
Кому как. Если "добавлять" то придётся заменять текущие, а мне они больше нравятся.

**Comment by bratskij** [comment]
Хорошо, спасибо за подсказку как самому можно было добавить. Да и вообще за программу..
