### ISSUE TITLE
дублирует текст в Notion

### ISSUE THREAD

**Issue by Coin-ai** [BladeMight/Mahou#402]
## Проблема/описание запроса

в https://www.notion.so/ (web и desktop версии)
при попытке конвертации - удаляет только 1 предшествующий символ и вставляет  копию введенного текста (без конвертации)
при повторном нажатии  -  удаляет один последний символ новой строки и копирует повторно всю строку конвертируя первую ее часть

До этого пользовался everylang, там были косяки связанные с спецсимволами Notion, а с обычным текстом не было проблем.

![Notion_YalSKbTwrW](https://github.com/BladeMight/Mahou/assets/58988648/47fab16d-e420-47ca-bf46-3dee511da911)

## Информация окружения/Отладочная информация

- Версия Windows: 10
- Архитектура Windows: x64
- Версия .Net : 4.8.09037 (relese 533325) [4.0.30319.42000]
- Версия Mahou: Mahou 2.9.0.1-dev <9d88cc9>

## журналы (logs)

<details>
<summary>Log</summary>
https://pastebin.com/YFjRkB4a
</details>

**Comment by BladeMight** [comment]
web notion, работает без проблем:
![notion-web](https://github.com/BladeMight/Mahou/assets/11931888/45417755-e069-464a-921f-84261e807f08)
То же 10x64.
Возможно используемая гор. клавиша как-то влияет? Я пробовал с <kbd>Pause</kbd> и <kbd>Alt</kbd>+<kbd>F1</kbd>, работает без проблем... Или что-то еще извне?

**Comment by Coin-ai** [comment]
понял в чем проблема
стоит конвертация последнего слова на  Pause 
стоит конвертация выделенного на Pause

проблем в других приложениях с такими настройками не было, поэтому сразу и не понял, что причина в этом

в Notion видимо происходит двойное срабатывание
возможно сделать проверку на то, что после события что-то выделено или нет и соответственно не давать отрабатывать одной из функций, они по сути заменяют друг друга.

удобно на одной клавиши держать эти две опции.

**Comment by BladeMight** [comment]
> проблем в других приложениях с такими настройками не было

У notion, также как и в [других](https://github.com/BladeMight/Mahou/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B2-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%3F#sublime-text-atom-и-visual-studio-code) редакторах, которые _**при пустом выделении**_ при нажатии Ctrl+Insert или Ctrl+C копируют текущую линию, что и вызывает такой эффект, поэтому:

> проверку на то, что после события что-то выделено или нет

не работает как нужно...

**Comment by Coin-ai** [comment]
>  _**при пустом выделении**_ при нажатии Ctrl+Insert или Ctrl+C копируют текущую линию, что и вызывает такой эффект

правильно я понимаю, что при попытке изменить выделенный текст идет копирование, а потом проверка.
1.Нет ли возможности до копирования проверять на то есть ли выделенная область selection и ее длинна? 
2.Пойти от обратного, если есть "последнее слово" и т.д. (как понимаю идет некая буферизация нажатий, до сигнала сброса). Тут вопрос есть ли ситуации когда текст сразу выделен и это поведение некорректно отработает в этой ситуации.

Интересно как это решено в everylang.  Провел в ней тест, если произвести конвертацию сразу после ввода, то все ок, а если сместить курсор, то поведение почти идентично (т.е. возможно там используется вариант 2).

**Comment by BladeMight** [comment]
Когда используются одна и та же гор. клавиша для конвертации посл. слова и выделения Mahou запускает проверки:

1. Получить выделенный текст используя Ctrl+Insert, если не получается то попробовать Ctrl+C. 
2. На основе того что получили в буфере обмена делать конвертацию выделения, если пусто пропускается.
3. Выполняется конвертация посл. слова если перед этим конвертация выделения не сработала.

Т.е. приоритет для выделения, потом посл. слова, т.к. логически на мой взгляд более корректно. Если посл. слово не пустое - значит был ввод текста, а значит выделенного текста не может быть - т.к. любой способ выделения сбрасывает посл. слово. Поэтому проверка выделение идёт первее.

> что при попытке изменить выделенный текст

Конвертация выделения не "меняет" выделенный текст, сначала идёт копирование в буфер обмена, обработка - далее ввод нового текста. Т.е. новый текст полностью посимвольно вводиться, и в конце если указано в настройках "пере-выделяет" его используя Shift+Left * ДЛИНА_ТЕКСТА

> 1.Нет ли возможности до копирования проверять на то есть ли выделенная область selection и ее длинна?

Доступ к тому что внутри браузера у Mahou как программы извне - сейчас уже нет.

В Chrome/Electron/etc. убрали поддержку старых WinAPI которые можно было бы использовать чтобы получать эту информацию. Я раньше делал plugin как для SublimeText 3 только для VSCode, кое-как работало, но слишком много пришлось вручную доделывать и я забросил.

**Comment by Coin-ai** [comment]
> Т.е. приоритет для выделения, потом посл. слова, т.к. логически на мой взгляд более корректно. Если посл. слово не пустое - значит был ввод текста, а значит выделенного текста не может быть - т.к. любой способ выделения сбрасывает посл. слово. Поэтому проверка выделения идёт первее.

может поменять приоритет? первым проверять последнее слово. если оно есть, "значит был ввод текста, а значит выделенного текста не может быть - т.к. любой способ выделения сбрасывает посл. слово.". далее проверяем выделение, если есть то отрабатываем по выделенному.

я как понял текст должен был указать на то, что в приоритете должно быть выделение, а потом слово. Но из пояснения я вижу что - Есть слово- значит нет выделения, вывод: проверяем слово, потом выделение, т.к. первая проверка нам сразу скажет нужно ли идти дальше, конечно тут и обратное верно, есть выделение- нет слова (но т.к. мы можем получить выделение и при наличии слова из за особенностей некоторого софта, то мб идти обратным путем?). Возможно что-то упускаю?

**Comment by BladeMight** [comment]
> может поменять приоритет?

Даже если поменять, проблема останется - когда нет посл. слова - будет всегда вызывается конвертация выделения т.к. Ctrl+Insert/C всегда что-то выдаёт даже без выделения.

> может поменять приоритет? первым проверять последнее слово. если оно есть

Посл. слово не может быть когда есть выделение, за исключением случаев как этот когда "выделение" есть всегда из-за функционала Ctrl+C/Insert на пустом выделении. Единственна проблема в том что Ctrl+C/Insert копирует что-то "без" выделения, создавая неправильную обработку того, для Mahou кажется что выделение есть всегда т.к. триггером того что оно есть - является наличие чего-то в буфере обмена после копирования через Ctrl+C/Insert

**Comment by Coin-ai** [comment]
> Даже если поменять, проблема останется - когда нет посл. слова - будет всегда вызывается конвертация выделения т.к. Ctrl+Insert/C всегда что-то выдаёт даже без выделения.

действительно, но часть случаев ошибочного срабатывания уйдет. Останется случай когда пользователь ничего не выделил и сбросил "последнее слово". В этих случаях ожидаемый результат - ничего не происходит (ошибочный ввод пользователем), но т.к. мы не можем понять было ли выделение или нет, то копируется вся строка.

вот как это выглядит в EveryLang
![Notion_x5HYfYMg3R](https://github.com/BladeMight/Mahou/assets/58988648/7af59858-a6ee-4098-888c-80d342a782a6)

1. вводим слово, меняем - все ок
2. вводим еще слово меняем, меняется последнее - все ок
3. меняем последнюю строку - все ок
4. вводим еще слово меняем последнее - все ок
5. Enter на новой строке вводим слово, меняем последнее - все ок
6. возвращаемся на предыдущую строку с помощью мыши (сброс), меняем - провал теста (копирует всю строку без выделения)
7. выделяем часть текста, меняем - все ок
8. возвращаемся на вторую строку с помощью мыши (сброс), вводим новое слово, меняем - все ок
9. добавляем еще слово, меняем строку  - частичное прохождение теста , убран пробел в начале словосочетания (предположение: видимо где-то отрабатывает trim, а количество символов под удаление рассчитано с пробелом)

**Comment by BladeMight** [comment]
Через [Mahou.mm](https://github.com/BladeMight/Mahou/wiki/Mahou.mm_RU) можно сделать другой приоритет:

```perl
Посл. слово, потом выделение|^^Pause|multi|hk|c0|ifhk|n|hk|s7
```

**Comment by Coin-ai** [comment]
интересный функционал, спасибо, буду экспериментировать
