### ISSUE TITLE
Troobleshooting information

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#42]
### 1. Request

К сожалению, пока что багрепорты о Mahou приходится отсылать нередко. Полагаю, как для Вас так и для Ваших пользователей было бы удобнее сделать кнопку типа `Debug Info`.

### 2. Desirable behavior

В интерфейсе Mahou пользователь нажимает кнопку `Debug Info` → в клипбоард копируется следующая информация:

+ Версия и любая другая информация о Mahou, которую сочтёте нужной добавить в отчёт;
+ Содержимое файла `Mahou.ini`;
+ Информация об операционной системе.

В данном репозитории можно сделать [**Issue Template**](https://github.com/blog/2111-issue-and-pull-request-templates), где пользователям настоятельно рекомендовалось бы прикрепить данную информацию к своему багрепорту.

### 3. Examples on other apps

См. [**пакет Troubleshooting**](https://github.com/guillermooo/sublime-troubleshooting) для Sublime Text.

Спасибо.

**Comment by BladeMight** [comment]
> Issue Template

Про него Я думал, но все как-то забывал, спасибо теперь добавлю.

> сделать кнопку типа Debug Info

Неплохо, принято.

**Comment by BladeMight** [comment]
> кнопку Debug Info

Добавлено в [Mahou-v1.4.4.1](https://github.com/BladeMight/Mahou/releases/tag/v1.4.4.1).

> можно сделать Issue Template

[Issue template](https://github.com/BladeMight/Mahou/blob/v1.4.4.1/.github/ISSUE_TEMPLATE.md)/[Issue template RU](https://github.com/BladeMight/Mahou/blob/v1.4.4.1/.github/ISSUE_TEMPLATE_RU.md).

**Comment by Kristinita** [comment]
@BladeMight , что-то не могу найти эту кнопку( .

**Comment by BladeMight** [comment]
@Kristinita Дополнительные настройки страница 3

**Comment by BladeMight** [comment]
Добавил, [здесь](https://github.com/BladeMight/Mahou/wiki/Functions-list#debug-info) и [здесь](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9E%D1%82%D0%BB%D0%B0%D0%B4%D0%BE%D1%87%D0%BD%D0%B0%D1%8F-%D0%B8%D0%BD%D1%84).

**Comment by Kristinita** [comment]
@BladeMight , а можно ли как-то извлечь в Debug info, что у пользователей настроено в `Control Panel\Clock, Language, and Region\Language`?

Спасибо.

**Comment by BladeMight** [comment]
> что у пользователей настроено в Control Panel\Clock, Language, and Region\Language?

То есть какие раскладки установлены? Можно их посмотреть в списке [Switch between layouts](https://github.com/BladeMight/Mahou/wiki/Functions-List#switch-between-layouts) после отключения [Cycle Mode](https://github.com/BladeMight/Mahou/wiki/Functions-List#cycle-mode).

**Comment by Kristinita** [comment]
Прошу прощения, зачем Вы заголовок изменили? Не принципиально, интересно только. мне вот немного удобнее ориентироваться в своих issues и отличать их от issues других пользователей благодаря содержимому квадратных скобок.

Спасибо.

**Comment by BladeMight** [comment]
> Прошу прощения, зачем Вы заголовок изменили? 

Переместил в label:
![2017-02-06 07-25-57-selection](https://cloud.githubusercontent.com/assets/11931888/22661158/01d95a8e-ecad-11e6-8fa3-1da939f48151.jpg)

> issues и отличать их от issues других пользователей благодаря содержимому квадратных скобок.

Не у всех [ваших issues](https://github.com/BladeMight/Mahou/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3AKristinita%20)  есть квадратные скобки.
