### ISSUE TITLE
[Bug] Третья клавиатурная раскладка при конвертации линии

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#43]
### 1. Summary

При запуске команды `Convert line` в taskbar появляется третья клавиатурная раскладка — `ENG/US`.

### 2. Expected behavior

Конвертация только между двумя клавиатурными раскладками — `ENG` и `RU`.

### 3. Actual behavior

Производится конвертация между тремя раскладками — `ENG`, `RU` и `ENG/US`.

### 4. Settings

Писал о них [**на Super User**](http://chat.stackexchange.com/transcript/52176/2017/1/21). Также. Вроде бы везде, где можно, убрал `ENG/US`.

![Язык 1](http://i.imgur.com/0VOzUtL.png)
![Язык 2](http://i.imgur.com/aZj2da9.png)
![Язык 3](http://i.imgur.com/l8dBg66.png)

### 5. Steps to reproduce

Набираю слово в ошибочной клавиатурной раскладке → запускаю хоткеем (<kbd>F10</kbd>, менял на явно неиспользуемый <kbd>Ctrl+Shift+Alt+F10</kbd> — получил аналогичное поведение) команду `Convert line` → получаю актуальное поведение, не желаемое.

#### MAHOU DEBUG INFO
- Mahou-v1.4.4.1
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### Mahou.ini:
```ini
!Unicode(✔), Mahou settings file
[Hotkeys]
HKCLKey=121
HKCLMods=Shift
HKCSKey=121
HKCSMods=Control
HKCLineKey=121
HKCLineMods=None
OnlyKeyLayoutSwicth=None
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=122
HKConvertMoreMods=Shift + Control
[Locales]
locale1uId=1033
locale1Lang=English
locale2uId=1049
locale2Lang=Русский
LANGUAGE=EN
[Functions]
IconVisibility=True
CycleMode=True
EmulateLayoutSwitch=False
ELSType=0
CSSwitch=True
BlockCTRL=False
RePress=True
EatOneSpace=False
ReSelect=True
SymIgnModeEnabled=false
MoreTries=true
TriesCount=5
DisplayLang=false
DLRefreshRate=50
DLForeColor=#FFFFFF
DLBackColor=#000000
ExperimentalCSSwitch=false
Snippets=false
DTTOnChange=false
ScrollTip=false
UpdatesEnabled=true
Logging=true
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=true
[ExtCtrls]
UseExtCtrls=false
LCLocale=
LCLocaleName=
RCLocale=
RCLocaleName=
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=14
Width=24
Font=Georgia; 8pt
xpos=8
ypos=0
TransparentBack=false
[DoubleKey]
Use=false
Delay=350
```

Спасибо.

**Comment by BladeMight** [comment]
> Вроде бы везде, где можно, убрал ENG/US

А еще есть:

- Раскладка в `Apply language settings to welcome screen, system accounts, new user accounts` поменяйте ее на вашу кастомную раскладку.
- Включите `Let me set different input language for each app window` 

И перезагрузитесь/выйдете из системы, и проверьте как работает.

Отключив [CycleMode](https://github.com/BladeMight/Mahou/wiki/Functions-List#cycle-mode)([Циклич. режим](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%A6%D0%B8%D0%BA%D0%BB%D1%87-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC)) можно достигнуть переключения **только** по [выбранным в настройках раскладках](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9A%D0%BE%D0%BD%D0%B2%D0%B5%D1%80%D1%82-%D0%BC%D0%B5%D0%B6%D0%B4%D1%83-%D1%8F%D0%B7%D1%8B%D0%BA%D0%B0%D0%BC%D0%B8).

P.S. Баг появляется только в `Convert line`? И при ручной смене раскладки появляется 3-я?

**Comment by Kristinita** [comment]
> И перезагрузитесь/выйдете из системы, и проверьте как работает.

Сделано:

![1](http://i.imgur.com/Eu2dBWE.png)
![2](http://i.imgur.com/SFHgZBP.png)

> Отключив CycleMode(Циклич. режим) можно достигнуть переключения только по выбранным в настройках раскладках.

Снял галочку с CycleMode → выбирал как верхний, так и нижний English (1033) → всё равно раскладка переключается на ENG/US.

![ENG/US](http://i.imgur.com/Efq7Asm.png)

> P.S. Баг появляется только в Convert line? И при ручной смене раскладки появляется 3-я?

При выключенном Mahou ENG/US у меня не появляется. При включённом появляется и при ручной смене раскладок.

**Comment by BladeMight** [comment]
Странно, у них одиннаковый UID? Именно поэтому при запросе смены появляется оригинальная раскладка ENG/US, интересно есть ли способ их различать?

**Comment by BladeMight** [comment]
А можете сделать свою кастомную раскладку не из English US а из другого?

**Comment by Kristinita** [comment]
Взял за основу дефолтный [Colemak](https://chocolatey.org/packages/colemak) и убрал оттуда все хоткеи с Ctrl+Alt, потому что я использую их для других целей. Вот мои раскладки:

+ [Раскладка 1](http://jmp.sh/MrgeKLj)
+ [Раскладка 2](http://jmp.sh/PHEJunj)

Редактировал через Microsoft Keyboard Layout Creator → не нашёл и не нагуглил, где там изменять ID.

![MCLC](http://i.imgur.com/2EoYO9d.png)

Спасибо.

**Comment by BladeMight** [comment]
Странно, у меня прекрасно все работает, и 3-я не появляется.
![2017-01-22 02-49-35-window](https://cloud.githubusercontent.com/assets/11931888/22182611/1f6bcbc4-e0b2-11e6-87aa-ac2a38b2ef52.Png)
![2017-01-22 02-49-44-window](https://cloud.githubusercontent.com/assets/11931888/22182610/1f67698a-e0b2-11e6-855c-bc75e0e2b113.Png)

Быть может все-таки что-то с раскладками?

**Comment by BladeMight** [comment]
У меня таки получилось воспроизвести ошибку, для ее исправления пойдите в настройки раскладок в параметрах, а дальше:

![2017-02-02 11-15-56-window](https://cloud.githubusercontent.com/assets/11931888/22569079/e24bfeda-e99e-11e6-81fb-8320891c19ad.jpg)

И здесь удалите другие раскладки, чтобы осталась только желаемая:

![2017-02-02 11-16-00-window](https://cloud.githubusercontent.com/assets/11931888/22569165/1f786686-e99f-11e6-9392-7af4349cac09.jpg)

До выше описанного в Mahou:

![2017-02-02 11-26-46-window](https://cloud.githubusercontent.com/assets/11931888/22569185/37799e26-e99f-11e6-89ec-c4b6d839de32.Jpeg)

После:

![2017-02-02 11-15-01-window](https://cloud.githubusercontent.com/assets/11931888/22569187/3b9b3d48-e99f-11e6-928c-8ce33c2f2770.Png)

**Comment by BladeMight** [comment]
@Kristinita Нашел способ различать раскладки!! Нужно не сокращать ID, а использовать оригинальный(HWND) и тогда все будет ОК. В новом релизе будет вот так:
![2017-02-03 12-48-01-window](https://cloud.githubusercontent.com/assets/11931888/22571893/71098eb6-e9aa-11e6-8560-a181a46dde5a.Jpeg)

**Comment by BladeMight** [comment]
Готово: [Mahou-v1.4.4.4](https://github.com/BladeMight/Mahou/releases/tag/v1.4.4.4).

**Comment by BladeMight** [comment]
>Готово: [Mahou-v1.4.4.4](https://github.com/BladeMight/Mahou/releases/tag/v1.4.4.4).

@Kristinita Ну а лучше [последнюю версию](https://github.com/BladeMight/Mahou/releases/latest)(v1.4.4.9 на момент сообщения)

**Comment by Kristinita** [comment]
@BladeMight, спасибо! С этой проблемой вроде бы всё. Но привыкаю сейчас переключать раскладки левым <kbd>Ctrl</kbd>, и нередко получается, что хоткеи <kbd>Ctrl+key</kbd> непроизвольно нажимаются.

![Хоткеи](http://i.imgur.com/gVOv1FH.gif)

Можно и как-нибудь уменьшить время переключения раскладки?

Наверное, лучшее решение — переключать посредством <kbd>CapsLock</kbd>, поскольку это не служебная клавиша, однако так удобно её вместо <kbd>BackSpace</kbd> использовать — `CapsLock::BackSpace` в AutoHotkey.

Спасибо.

**Comment by BladeMight** [comment]
> Можно и как-нибудь уменьшить время переключения раскладки?

При переключении <kbd>Ctrl</kbd> _не удерживается_, **удерживаете его Вы**, так что уменьшите время отпуска клавиши. Я пробовал очень быстро двумя руками, указательными пальцами - все нормально работает.

**Comment by Kristinita** [comment]
@BladeMight , переключаю сейчас раскладки клавишей <kbd>Caps_Lock</kbd>. Т.к. она не служебная, проблемы вроде бы исчезли. Единственная проблема — раньше я применял скрипт `CapsLock::BackSpace`, теперь придётся опять тянуться мизинцем до клавиши <kbd>Backspace</kbd>. На какую клавишу функция Backspace настроена лично у Вас?

И опубликуйте ответ [**здесь**](http://superuser.com/q/1169680/572069), чтобы как минимум 25 баллов от меня получить.

Спасибо.

**Comment by BladeMight** [comment]
> На какую клавишу функция Backspace настроена лично у Вас?

У меня она не на что не настроена, Я пользуюсь самим <kbd>Backspace</kdb> и нажимаю на него безымянным пальцем, т.к. он почти всегда на нем или на <kbd>Ented</kbd> или тех что вокруг них.

**Comment by Kristinita** [comment]
**Тип: Дополнительная информация** 📓

### 1. История

Использую Mahou неделю после длительного перерыва.

В первые дни появлялся этот баг. Решался просто — что-нибудь ввожу и вызываю `Convert last line`. Однако баг возникал столь часто, что намного легче было не использовать Mahou.

Далее попробовал [**это решение**](https://superuser.com/a/1172554/572069) → как ни странно, помогло. 4 дня проблема вообще не появлялась.

Вчера перезагрузил Windows → сегодня проблема возникла снова. Снова проделал то, что рекомендовали на Super User → пока баг не проявляется; посмотрим, что будет дальше.

### 2. Программное обеспечение

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. Mahou 2.9.0.1
1. Пользовательские клавиатурные раскладки на основе [**Colemak**](https://colemak.com/)

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita 

> Далее попробовал это решение

Можно побыстрее сделать на AHK гор. клавишу:

```ahk

engLayout := 0x409 ; https://www.autoitscript.com/autoit3/docs/appendix/OSLangCodes.htm
#f7::
DllCall("User32.dll\UnloadKeyboardLayout", "UInt", engLayout)
return
```

ДеРегистрирует эту раскладку из системы, т.е. появилась английская раскладка, нажал Win+F7 - всё исчезла :)
