### ISSUE TITLE
[Feature request] Keyboard layout indication

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#44]
### 1. Request

Неплохо было бы добавить возможность как-нибудь отображать рядом с кареткой, какая раскладка используется на данный момент. Например, показывать флаг страны или же аббревиатуру, состоящую из начальных букв языка, например, `EN` или `RU`.

### 2. Justification

Чтобы посмотреть, какая на данный момент раскладка, нужно направить взгляд в правый нижний угол экрана, а затем возвращаться к месту, где редактировал текст. Когда делаешь это постоянно, отнимается время. Можно сэкономить временные затраты, если видеть, какая раскладка используется, там, где редактируешь текст.

я много перепробовал, [**спрашивал на Software Recommendations**](http://softwarerecs.stackexchange.com/q/38403/23324), но найти gratis программу с таким функционалом не удалось.

### 3. Desirable behavior

![Aml Maple](http://www.amlpages.com/images/AmlMaple_Demo.gif)

### 4. Examples on other apps

Пример из раздела выше программы [**Aml Maple**](http://www.amlpages.com/Rus/amlmaple.htm), но она коммерческая.

Спасибо.

**Comment by BladeMight** [comment]
> Неплохо было бы добавить возможность как-нибудь отображать рядом с кареткой, какая раскладка используется на данный момент.

Будет не легко, нужно будет искать как узнать позицию каретки через **WinAPI**. Это может занять много времени...

**Comment by BladeMight** [comment]
Вы знаете, у меня уже получилось найти способ как это сделать... В ближайшее время будет тестовая версия.

**Comment by Kristinita** [comment]
>  а вот Sublime Text, Firefox и т.д. - нет,

А это что-то не очень хорошо. В эти двух программах я провожу 90% времени...

В Sublime Text, кстати, есть [**поддержка Pywin32**](https://forum.sublimetext.com/t/st3-pywin32-plugin-beta-pywin32-support-in-sublime/12296?u=sasha_chernykh).

> Ну в принципе так и сделано в AmI MapIe... 

Aml Maple у меня вроде бы везде работало.

Спасибо.

**Comment by BladeMight** [comment]
Теперь в [Mahou-v1.5.0.0](https://github.com/BladeMight/Mahou/releases/tag/v1.5.0.0) есть такая возможность:
![mahou caret lang display feature](https://cloud.githubusercontent.com/assets/11931888/22780876/edfcf692-eec8-11e6-976c-11bef5a76758.gif)

**Comment by Kristinita** [comment]
Шрифт можно сделать пожирнее для языка? Нынешний тонким, ПМСМ, выглядит.

Спасибо.

**Comment by BladeMight** [comment]
В настройках:
![2017-02-09 12-14-27-window](https://cloud.githubusercontent.com/assets/11931888/22781102/c92a8f2c-eec9-11e6-85a1-916d399d1e47.jpg)

**Comment by Kristinita** [comment]
@BladeMight, работает везде, включая Firefox и блокнот, но только не в той программе, где данная функция как раз и нужна — Sublime Text 3.

Может, можно что-нибудь придумать? Спросить [**на форуме Sublime Text**](https://forum.sublimetext.com/), например, можно; там обычно конструктивно отвечают.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Если вы уже знакомы с форумом, то тогда можете задать: **Как получить позицию каретки через WinAPI?** 
Хотя может и есть другой способ например Sublime Text записывает позицию в файл а потом Mahou читает и рисует LangDisplay на позици, но для этого надо сначала вызвать как-то эту функцию записи в файл отдаленно из Mahou в Sublime Text и еще этот способ не очень хорош т.к. использует диск, быть может есть другой способ содержать информацию при удаленном вызове, хотя если бы было возможно вызвать что-то удаленно из Sublime Text то можно было бы сразу и получить позицию каретки, так вот еще вопрос - **Можно ли удаленно вызывать команды в Sublime Text и получать их значения?**

> включая Firefox 

Быть может у меня на Nightly просто не работает, вы точно уверены что именно функция отображения **рядом с кареткой работает** в Firefox?

> блокнот

Само сабо разумеется, там ведь чистый WinAPI.

Я тут вас еще просил(насчет Aml Maple):

>Ну ка покажите как язык рядом с кареткой(не рядом с мышкой!!) отображается в Sublime Text или Firefox(у меня не показывает)

Не покажите ли? А заодно и как работает Mahou в Firefox?

Пожалуйста.

**Comment by Kristinita** [comment]
@BladeMight,

> Можно ли удаленно вызывать команды в Sublime Text и получать их значения?

Можно из терминала запускать команды для Sublime Text. Синтаксис: `subl --command examplecommand`. Подробнее [**здесь**](http://nbviewer.jupyter.org/github/Kristinita/SashaBooks/blob/master/IT/Sublime%20Text/Sublime%20Text%20Power%20User.pdf#page=51).

> Быть может у меня на Nightly просто не работает, вы точно уверены что именно функция отображения рядом с кареткой работает в Firefox(и где в Firefox она у Вас работает?)?

![Mahou + Firefox](http://i.imgur.com/dfi35KN.gif)

Firefox 51.0.1 64-bit, стабильная версия. Работает в любых textarea формах, URL bar и search bar.

> Ну ка покажите как язык рядом с кареткой(не рядом с мышкой!!) отображается в Sublime Text или Firefox(у меня не показывает)

Да, Вы правы, у AmlMaple для в Sublime Text только около курсора, но не каретки может отображаться язык. Прошу прощения. В Firefox у меня и AmlMaple работает.

> Как получить позицию каретки

Вообще получить [**можно**](http://stackoverflow.com/a/12815138/5951529), а как через WinAPI...

> Если вы уже знакомы с форумом, то тогда можете задать:

я бы правда, уже бы спросил сам, однако если б ещё понимал, как в Mahou там всё устроено :crying_cat_face:. Могу, конечно, но Вы гораздо понятнее сможете изложить, что необходимо для реализации данной функции.

Спасибо.

**Comment by Kristinita** [comment]
@BladeMight, возможно, для Вас что-то прояснит плагин [**CursorRuler**](https://github.com/icylace/CursorRuler) (название некорректное, точнее было б CarriageRuler), действие которого напрямую зависит от положения каретки. Ruler (столбик) появляется в том же столбце, что и каретка.

![Ruler 1](http://i.imgur.com/9ox4ggi.png)
![Ruler 2](http://i.imgur.com/G9z4YTe.png)

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita У вас и впрямь в Firefox возле каретки отображается подсказка языка? У меня никак не хочет отображаться,  даже установил чистую Windows 10 в VirtualBox в ней все равно не хочет... Устанавливал последнюю стабильную, различные старые версии Firefox все x32 & x64 пробовал, но в се равно не отображает...
Быть может у вас есть **что-то особенное**?

**Comment by BladeMight** [comment]
> У меня никак не хочет отображаться

Ура [исправил](https://github.com/BladeMight/Mahou/commit/179219f5ef3d0273cec8793c0d4329817310c14d), теперь будет отображаться.

> Можно из терминала запускать команды для Sublime Text

По поводу этого, если это так то наверно будет создана новая сессия(экземпляр) sublime text в который не вернет нужные значения текущей линии и длины символов в строке. 
Есть ли вариант работать с уже запущенным sublime text?

**Comment by Kristinita** [comment]
> По поводу этого, если это так то наверно будет создана новая сессия(экземпляр) sublime text в который не вернет нужные значения текущей линии и длины символов в строке.
Есть ли вариант работать с уже запущенным sublime text?

Боюсь, неправильно Вас понял( . Могли бы пошагово объяснить ограничения? Процесс Sublime Text должен запускаться раньше процесса Mahou?

Спасибо.

**Comment by BladeMight** [comment]
> Могли бы пошагово объяснить ограничения? Процесс sublime_text.exe должен запускаться раньше процесса mahou.exe?

Как Вы и говорили раннее:

> Можно из терминала запускать команды для Sublime Text. Синтаксис: `subl --command examplecommand`

А это значит что при запуске из терминала если будет создан новый Sublime Text, то получая позицию каретки было бы не правильным, хотя сейчас проверил вроде не открывает другой экземпляр...

Кто первый запущен не имеет значение, главное получать значения:

> текущей линии и длины символов в строке


Команда к которой я пришел, для получения текущей позиции каретки в Sublime Text:
```
print(view.rowcol(view.sel()[0].begin()))
```
хорошо работает, а теперь все что нужно получить это значение из запущенного Sublime Text, удаленно, у меня есть пара вариантов на этот счет:

1. Послать команду Sublime Text чтобы он записал в файл на диске позицию каретки. (Может быть медленным и с большой нагрузкой на диск...)
2. или использовать ответ запуска той самой команды из cmd, позже можно будет используя скрывать cmd. (Быстрее чем предыдущий без нагрузки на диск, но нужно подтвердить возможность(существование) этого способа)
3. Создать дополнение к Sublime Text которое будет работать как сервер который будет иметь свой адрес, в котором будет постоянно обновляться позиция каретки. И создать дополнение к Mahou которое будет \*слушать\* этот сервер, если Sublime Text запущен/активен. (Похоже что это самый способ будет  работать быстрее, но нужно будет вникать в структуру дополнений(учиться создавать) Sublime Text, возможно на это потребуется много времени...)

Все я спать 😴

**Comment by Kristinita** [comment]
> (Похоже что это самый способ будет работать быстрее, но нужно будет вникать в структуру дополнений(учиться создавать) Sublime Text, возможно на это потребуется много времени...)

Возможно, [**эта книга**](http://jmp.sh/zkEKLl4) не будет лишней.

Спасибо.

**Comment by BladeMight** [comment]
У меня получилось создать 3 вариант, вот тестовый плагин ST3:
[MahouCaretDisplayServer.zip](https://github.com/BladeMight/Mahou/files/828012/MahouCaretDisplayServer.zip)

Как проверить:
1. Распаковать плагин в папку "Data\Packages".
2. Внутри папки плагина есть папка TestListeners в которой есть тесты(на разных языках) для сервера, если не знаете что выбрать, в C# есть `exe` файл.
3. Запускаете один из listener'ов, запускаете ST3(или наоборот) и пробуйте что-то ввести, кликать мышкой, скрывать/показывать боковую панель.
4. В listener'е будет отображаться информация используя которую **можно будет** получить позицию каретки.
5. В консоли Sublime Text будет отображаться более читабельная информация.

P.S. Пока что это **только сервер и слушатель** который **нужно будет внедрять** в Mahou, для работы функции показа языка рядом с кареткой.

**Comment by BladeMight** [comment]
🌟 А вот тестовая программа которая по нажатию на F8 переносит окно к позиции каретки, с поддержкой *слушателя сервера*:
[CaretAttachWithListener.zip](https://github.com/BladeMight/Mahou/files/828323/CaretAttachWithListener.zip)
Получает правильную позицию каретки даже если:
1. Масштабировать текст.
2. Скрыта/показана боковая панель.
3. Чтобы правильно работала в Консоли ST3 тоже, нужно нажать мышкой на ней или клавишу при фокусе.

Проверьте и скажите(а лучше gif) как работает лично у Вас.

**Comment by BladeMight** [comment]
@Kristinita 🎉 В [Mahou v2.1.0.4](https://github.com/BladeMight/Mahou/releases/tag/v2.1.0.4) теперь есть поддержка [MCDS](https://github.com/BladeMight/MahouCaretDisplayServer)(скоро(?) [появится в Package Control](https://github.com/wbond/package_control_channel/pull/6180)), установите MCDS в ST3 и включите поддержку MCDS в Mahou, после: 
Вот:
![mahou mcds - works](https://cloud.githubusercontent.com/assets/11931888/23801636/85954e4e-05b9-11e7-8be3-2991bc0980d0.gif)

:cake: 🍵
