### ISSUE TITLE
Убрать сообщение об автообновлении

### ISSUE THREAD

**Issue by dmiko** [BladeMight/Mahou#45]
Доброго времени суток!
Спасибо за отличную программу.

А можно как-нибудь убрать сообщение о новой версии? 
Лучше оставить кнопочку "Обновить", это ж просто переключалка раскладок, нет экстренной необходимости при загрузке диалогом уведомлять о выходе минорной версии. У кого наблюдаются баги, тот сам в первую очередь нажмет эту кнопку.

**Comment by BladeMight** [comment]
Есть на [Wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F), почитайте.

**Comment by dmiko** [comment]
@BladeMight в таком случае хорошо бы сделать это поведением по умолчанию.
