### ISSUE TITLE
[Bug] Удаляются символы, если при наборе слова переключалась раскладка

### ISSUE THREAD

**Issue by plazmer** [BladeMight/Mahou#46]
## Problem/Request description
Проблема возникает, если в процессе набора строки производилось переключение раскладки.
Пример:
r['ид']<PAUSE>
Результат:
r['ид

В итоге - потеря двух последних символов. При повторных нажатиях этой же кнопки строка укорачивается еще больше.

Пример того, где это иногда требуется - парсинг XML от 1С на любом языке за пределами 1С

## Expected behavior(Only if reporting bug)
Ожидалась строка "кхэидэъ", или "r['bl']" но никак не укорачивание.

### MAHOU DEBUG INFO
- Mahou-v1.5.0.3
- OS = [Microsoft Windows NT 6.1.7601 Service Pack 1]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
США(67699721)
Русская(68748313)
#### Mahou.ini:
```ini
!Unicode(✔), Mahou settings file
[Hotkeys]
HKCLKey=19
HKCLMods=None
HKCSKey=145
HKCSMods=None
HKCLineKey=19
HKCLineMods=Shift
OnlyKeyLayoutSwicth=CapsLock
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=122
HKConvertMoreMods=Shift + Control
[Locales]
locale1uId=67699721
locale1Lang=США
locale2uId=68748313
locale2Lang=Русская
LANGUAGE=EN
[Functions]
IconVisibility=True
CycleMode=False
EmulateLayoutSwitch=False
ELSType=0
CSSwitch=True
BlockCTRL=False
RePress=True
EatOneSpace=False
ReSelect=False
SymIgnModeEnabled=false
MoreTries=False
TriesCount=5
DisplayLang=False
DLRefreshRate=50
ExperimentalCSSwitch=True
Snippets=False
DTTOnChange=False
ScrollTip=False
UpdatesEnabled=True
Logging=False
DiffLayoutColors=False
CrtDisplayLang=False
CrtDLRefreshRate=50
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=True
[ExtCtrls]
UseExtCtrls=False
LCLocale=67699721
LCLocaleName=США
RCLocale=68748313
RCLocaleName=Русская
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=14
Width=24
Font=Georgia; 8pt
xpos=8
ypos=0
TransparentBack=False
DLForeColor=#FFFFFF
DLBackColor=#000000
CrtDLForeColor=#FFFFFF
CrtDLBackColor=#000000
L1DiffFGColor=#8B5FFF
L1DiffBGColor=#FFFFFF
L1DiffFont=Georgia; 8pt
L2DiffFGColor=#E1E100
L2DiffBGColor=#000000
L2DiffFont=Palatino Linotype; 9pt
CrtHeight=14
CrtWidth=24
CrtFont=Georgia; 8pt
Crtxpos=8
Crtypos=0
[DoubleKey]
Use=False
Delay=350
```
#### Snippets:
```
->mahou
====>
Mahou (魔法) - Magical layout switcher.
<====
->eml
====>BladeMight@gmail.com<====
```

**Comment by BladeMight** [comment]
Этот баг уже исправлен [здесь](https://github.com/BladeMight/Mahou/commit/82e66049e40a45a31a1a90d42ff089a6b0ec023b) релиза пока что нет, но авто-сборка есть на [AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou/build/job/agl2ag9nyl69nnpt/artifacts).

**Comment by plazmer** [comment]
Да, в актуальной версии повторить не удалось. Спасибо :)

**Comment by BladeMight** [comment]
Ну вот и хорошо, сейчас скоро будет релиз 1.5.0.6.
