### ISSUE TITLE
[Question] Disable native Caps_Lock function

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#47]
### 1. Summary

Переключаю раскладки при помощи Mahou клавишей <kbd>Caps_Lock</kbd>. Если чуть придержать <kbd>Caps_Lock</kbd>, то текст будет печататься заглавными буквами. мне это не нужно.

### 2. Expected behavior

Полное отключение функции <kbd>Caps_Lock</kbd> по умолчанию, чтобы клавиша использовалась только для переключения раскладок в Mahou.

### 3. Actual behavior

![Caps_Lock](http://i.imgur.com/9oCqu54.gif)

### 4. Not helped

1. Пробовал некоторые способы, но <kbd>Caps_Lock</kbd> отключается насовсем; клавишу нельзя использовать для переключения раскладок в Mahou.
2. Использование [**Вашего метода**](http://superuser.com/a/1169778/572069) редиректом при помощи AutoHotkey, не нравится, поскольку я могу сделать редирект только на <kbd>Ctrl</kbd> (левое или правое), а это [**ещё хуже**](https://github.com/BladeMight/Mahou/issues/43#issuecomment-277651356).

### 5. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit EN
**Mahou:**
1.5.0.6

Спасибо.

**Comment by BladeMight** [comment]
> Если чуть придержать CapsLock

~1 сек нужно для включения CapsLoсk, я думал этого достаточно, ведь на одно нажатие нужно всего лишь <0.3 сек.

> Полное отключение функции CapsLock по умолчанию

Отключить функцию Windows я пожалуй не смогу, зато могу создать таймер который сам будет выключать CapsLock если он включен.

**Comment by BladeMight** [comment]
@Kristinita в [Mahou-v1.5.08](https://github.com/BladeMight/Mahou/releases/tag/v1.5.0.8) добавлен таймер отключения CapsLock.

**Comment by Kristinita** [comment]
@BladeMight , у Вас в Chocolatey [**возникли ошибки**](https://chocolatey.org/packages/Mahou/1.5.0.8) при добавлении 1.5.0.8.

Спасибо.

**Comment by BladeMight** [comment]
>Chocolatey возникли ошибки

Странно, мне на email ничего не пришло... Сейчас исправлю.

**Comment by Kristinita** [comment]
Спасибо, работает!

**Comment by Kristinita** [comment]
Загрузил <https://chocolatey.org/packages/permain/0.7> сейчас пакет для 
Сhocolatey — пришли все уведомления. Может, в спам письмо попало?

Спасибо.

**Comment by BladeMight** [comment]
> спам письма попали

таки да, хотя раньше такого небыло...
