### ISSUE TITLE
Переключение раскладки RightControl

### ISSUE THREAD

**Issue by KSerg0** [BladeMight/Mahou#48]
## Problem/Request description

Настройка переключения раскладки в Mahou - RightControl.
Настройка переключения раскладки в ОС - RightControl + Shift

Комбинации RightControl + End; RightControl + Backspace; RightControl + (стрелки) и т.п. переключают раскладку.

Только установил, на других компьютерах не эксперементировал.
Так и задумано или это единичный (мой) случай?
В wiki ответа не нашел

### MAHOU DEBUG INFO
- Mahou-v1.5.0.6
- OS = [Microsoft Windows NT 6.1.7601 Service Pack 1]
- x64 = [True]
- .Net = [4.0.30319.36373]
#### All installed layouts:
US(67699721)
Russian(68748313)
#### Mahou.ini:
```ini
!Unicode(✔), Mahou settings file
[Hotkeys]
HKCLKey=19
HKCLMods=None
HKCSKey=145
HKCSMods=None
HKCLineKey=19
HKCLineMods=Shift
OnlyKeyLayoutSwicth=Right Control
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=122
HKConvertMoreMods=Shift + Control
[Locales]
locale1uId=67699721
locale1Lang=US
locale2uId=68748313
locale2Lang=Russian
LANGUAGE=RU
[Functions]
IconVisibility=True
CycleMode=False
EmulateLayoutSwitch=False
ELSType=0
CSSwitch=True
BlockCTRL=False
RePress=True
EatOneSpace=False
ReSelect=True
SymIgnModeEnabled=false
MoreTries=False
TriesCount=5
DisplayLang=False
DLRefreshRate=50
ExperimentalCSSwitch=False
Snippets=False
DTTOnChange=False
ScrollTip=False
UpdatesEnabled=True
Logging=False
DiffLayoutColors=False
CrtDisplayLang=False
CrtDLRefreshRate=50
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=True
[ExtCtrls]
UseExtCtrls=False
LCLocale=67699721
LCLocaleName=US
RCLocale=68748313
RCLocaleName=Russian
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=14
Width=24
Font=Georgia; 8pt
xpos=8
ypos=0
TransparentBack=False
DLForeColor=#FFFFFF
DLBackColor=#000000
CrtDLForeColor=#FFFFFF
CrtDLBackColor=#000000
L1DiffFGColor=#8B5FFF
L1DiffBGColor=#FFFFFF
L1DiffFont=Georgia; 8pt
L2DiffFGColor=#E1E100
L2DiffBGColor=#000000
L2DiffFont=Palatino Linotype; 9pt
CrtHeight=14
CrtWidth=24
CrtFont=Georgia; 8pt
Crtxpos=8
Crtypos=0
[DoubleKey]
Use=False
Delay=350
```
#### Snippets:
```
->mahou
====>
Mahou (魔法) - Magical layout switcher.
<====
->eml
====>BladeMight@gmail.com<====
```

**Comment by BladeMight** [comment]
Да, пока что так, я думаю можно сделать чтобы если нажата другая клавиша пока эта нажата чтобы не менялась раскладка.

**Comment by KSerg0** [comment]
Спасибо за быстрый отклик.
В отличие от RusLat проблем со стабильностью не замечено.
Все остальное устраивает, правда тестов по конвертированию было мало, т.к. в таком виде пока не ставил на постоянное использование.

**Comment by BladeMight** [comment]
@KSerg0 в [Mahou-v1.5.08](https://github.com/BladeMight/Mahou/releases/tag/v1.5.0.8) исправлено.

**Comment by KSerg0** [comment]
В релизах старше 1.5.2.4 ошибка вернулась.

**Comment by BladeMight** [comment]
@KSerg0 В [2.0.0.5](https://github.com/BladeMight/Mahou/releases/tag/v2.0.0.5) исправлено.

**Comment by KSerg0** [comment]
Ксожалению,  для Right Control ошибка осталась

**Comment by BladeMight** [comment]
@KSerg0 Я думал вы имели в виду переключение на конкректную раскладку по R/L Ctrl, а по поводу переключения раскладки по R Ctrl  терепь тоже есть правило блокирующее переключение если была нажата другая клавиша до отпуска R Ctrl(или любой другой, в зависимости от настройки!)
[Mahou-v2.0.0.8](https://github.com/BladeMight/Mahou/releases/tag/v2.0.0.8).
