### ISSUE TITLE
Автообновление Mahou

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#5]
Неплохо бы приделать, на мой взгляд. Спасибо.

**Comment by BladeMight** [comment]
Весьма интересненько, надо подумать...

**Comment by BladeMight** [comment]
В версии [1.0.4.2](https://github.com/BladeMight/Mahou/releases/tag/v1.0.4.2) добавлена функция обновления.

**Comment by Kristinita** [comment]
@BladeMight , а можно сделать так, чтобы не нужно было тратить лишние движения на распакову архива? Обновился → перезагрузился → пользуешься новой версией. Спасибо.

**Comment by BladeMight** [comment]
Если бы все было так просто... НО пока запущен Mahou он не может перезаписать себя... И в добавок надо будет добавлять на скачку архиватор для распаковки, пока что это самый оптимальный вариант, возможно в будущем будет автоматическое обновление.

**Comment by BladeMight** [comment]
Начиная с версии [Mahou v1.0.4.7](https://github.com/BladeMight/Mahou/releases/tag/v1.0.4.7) теперь есть функция АВТО-ОБНОВЛЕНИЯ, было не легко но оно того стоило. Попробуй, и скажи как.

**Comment by Kristinita** [comment]
@BladeMight, спасибо! Zip-архив в папке с Mahou остаётся разве что, можно и убрать его.

**Comment by BladeMight** [comment]
Не с последней(1.0.4.9) уже сам будет убираться.
Подробнее в [релизах](https://github.com/BladeMight/Mahou/releases).

**Comment by Kristinita** [comment]
@BladeMight, а можно ли сделать автоматическую проверку на обновления, например, при запуске Mahou? Т. е., когда запускается Mahou, будет идти проверка на наличие новой версии. Если выпущена новая версия, то появится надпись вроде «Выпущена новая версия».

Спасибо.

**Comment by BladeMight** [comment]
> при запуске Mahou

Да, я уже тоже думал об этом, добавлю в следующей версии.

**Comment by BladeMight** [comment]
Вот, в [версии 1.1.2.5](https://github.com/BladeMight/Mahou/releases/tag/v1.1.2.5), добавлено.(хоть и проверить пока что не получиться...)

**Comment by Kristinita** [comment]
@BladeMight, после обновлений приходится запускать Mahou вручную. 2 раза при старте системы появлялось окно, что можно обновиться. После обновления Mahou не запускается автоматически.
В автозагрузке Mahou у меня [от имени администратора](http://superuser.com/a/1039156/572069).

Но когда я кликнул по значку Mahou на рабочем столе и обновился, обновление прошло успешно, без нареканий.

Спасибо.

**Comment by BladeMight** [comment]
> после обновлений приходится запускать Mahou вручную. 

Да, это из-за того что я использовал относительный путь к Mahou, который работал если запускал пользователь, а так как Mahou запускает система при старте то стартовая директоря - `C:\Windows\System32` в которой НЕТ Mahou! Использование полного путя исправляет проблему. [Mahou-v1.1.3.1](https://github.com/BladeMight/Mahou/releases/tag/v1.1.3.1)

> 2 раза при старте системы появлялось окно

с чего бы это? 2 раза? А включена ли галочка авто-запуска в Mahou?

**Comment by Kristinita** [comment]
> с чего бы это? 2 раза?

Хотел сказать, что уже однажды обновлялся и появилось окно. Сегодня тоже появилось. Итого — 2 раза.

> А включена ли галочка авто-запуска в Mahou?

Нет, поскольку Mahou добавлена в автозагрузку другим путём.

**Comment by BladeMight** [comment]
> Хотел сказать, что уже однажды обновлялся и появилось окно. Сегодня тоже появилось. Итого — 2 раза.

А я подумал что 2 окна обновления...

> Нет, поскольку Mahou добавлена в автозагрузку другим путём.

Все ОК тогда.
