### ISSUE TITLE
Переключение последнего слова и выделенного текста по двойному нажатию "SHIFT"

### ISSUE THREAD

**Issue by vicodin77** [BladeMight/Mahou#50]
Доброго дня!

Очень хотелось бы увидеть в программе возможность переключения последнего слова и выделенного текста по двойному нажатию "SHIFT", если возможно конечно!
Заранее спасибо!

**Comment by BladeMight** [comment]
Увидеть?(хм) Ну тогда смотрите:
Она уже есть, просто включите функцию [Двойные гор. клавиши](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%94%D0%B2%D0%BE%D0%B9%D0%BD%D1%8B%D0%B5-%D0%B3%D0%BE%D1%80-%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D1%88%D0%B8) а после настроить обе гор. клавиши на Shift:
![2017-02-13 09-30-25-window](https://cloud.githubusercontent.com/assets/11931888/22877830/e8f02704-f1df-11e6-9668-148cbb926945.jpg)

**Comment by vicodin77** [comment]
Супер! Спасибо!
