### ISSUE TITLE
Возможность задать надпись, которая появляется возле каретки для каждого языка

### ISSUE THREAD

**Issue by vicodin77** [BladeMight/Mahou#51]
Вот еще придумал одну фичу!)
Если не затруднит!
Заранее спасибо!

**Comment by BladeMight** [comment]
Это может быть проблемно, т.к. сейчас используется *уникальный* метод для получения букв который работает с любой раскладкой, в принципе можно сделать так чтобы была замена этих уникальных пользовательскими, но прям для **каждой раскладки** будет еще труднее и будет добавлено очень много настроек. 
Но если это **так нужно** то можно добавить.

**Comment by vicodin77** [comment]
Просто на мой взгляд, три буквы для индикатора это многовато, а две настроить нормально обрезкой не получается...

**Comment by BladeMight** [comment]
> а две настроить нормально обрезкой не получается...

H: 15 W: 23
![clipboard01](https://cloud.githubusercontent.com/assets/11931888/22881414/02f23642-f1ef-11e6-8529-141fbcd496b8.jpg)

**Comment by vicodin77** [comment]
А какой шрифт и его размер?

**Comment by BladeMight** [comment]
Georgia 8 полужирный

**Comment by vicodin77** [comment]
И кстати, не планируется ли сделать свой индикатор раскладки в трее вместо бабочки?

**Comment by BladeMight** [comment]
Да есть в планах.

**Comment by BladeMight** [comment]
Планы:

1. Флаги стран в трее.
2. Новый интерфейс.
3. Новый способ локализации.
4. Улучшить многопоточность.

**Comment by vicodin77** [comment]
Да, с этим шрифтом и размером получилось? только у меня почему то H:15 W:19... А вот с другими шрифтами и размерами уже сложнее...

**Comment by vicodin77** [comment]
Планы- супер! Будем ждать!!!

**Comment by BladeMight** [comment]
> Флаги стран в трее.

@vicodin77 Готово в [Mahou-v1.5.2.0](https://github.com/BladeMight/Mahou/releases/tag/v1.5.2.0) есть такая возможность.

**Comment by vicodin77** [comment]
v1.5.0.2: 
1. при нажатии в доп. настройках первый раз на кнопку "Еще" ни чего не происходит, второй раз - поподаем на окно со сниппетами, третий раз - на первое оно доп. настроек и т.д. Во второе окно доп настроек не попадаем.
2. Только что вылетела прога!
[err.txt](https://github.com/BladeMight/Mahou/files/774098/err.txt)

**Comment by BladeMight** [comment]
1. Да я уже заметил, исправляю...
2. Видимо из-за функции флагов стран, но я полностью не понял из-за чего, опишите что Вы делали.

**Comment by vicodin77** [comment]
В момент конвертации последнего слова.

**Comment by BladeMight** [comment]
Странно у меня все работает нормально, а какие раскладки установлены?

**Comment by vicodin77** [comment]
locale1uId=4039115785
locale1Lang=US (Apple)
locale2uId=4039181337
locale2Lang=Russian (Apple)

**Comment by vicodin77** [comment]
пока работает тоже... )))
включил логирование, жду вылета!))

**Comment by vicodin77** [comment]
О! Вылет!!! Правда с прогой ни чего не делал и не конвертировал... Лог прилагаю. 
[2017.02.14.log.txt](https://github.com/BladeMight/Mahou/files/774128/2017.02.14.log.txt)

**Comment by BladeMight** [comment]
> О! Вылет!!! 

Да у меня тоже встречается, думаю это из-за того что Mahou слишком быстро менять иконку трея на флаги (50мс), сейчас буду дебажить.

**Comment by BladeMight** [comment]
Придумал исправление, сейчас сделаю бетку.

**Comment by BladeMight** [comment]
[Mahou.zip](https://github.com/BladeMight/Mahou/files/774156/Mahou.zip)

**Comment by vicodin77** [comment]
На одно окно в доп. настройках так и не попасть!

**Comment by BladeMight** [comment]
Ну так Я еще решаю ту проблему...

**Comment by BladeMight** [comment]
> Ну так Я еще решаю ту проблему...

Все нашел... Проблема в использовании switch который раньше работал, а теперь не хочет, вместо него можно использовать несколько if, сейчас сделаю бетку.

**Comment by BladeMight** [comment]
[MahouPrerelease.zip](https://github.com/BladeMight/Mahou/files/774269/Mahou.zip)

**Comment by vicodin77** [comment]
Работает! Будем дальше посмотреть!

**Comment by BladeMight** [comment]
Значит делаю релиз.

**Comment by BladeMight** [comment]
Принцип исправления такой(вдруг интересно):
Если последнее изменение(50мс назад) иконки было допустим en, и сейчас en то не менять иконку, а если сейчас отличается от en то тогда менять.

**Comment by vicodin77** [comment]
Опять упал при конвертации выделенного слова. Падение повторяющееся.
[2017.02.16err.txt](https://github.com/BladeMight/Mahou/files/780328/2017.02.16err.txt)

**Comment by BladeMight** [comment]
> Опять упал при конвертации выделенного слова. Падение повторяющееся.
> 2017.02.16err.txt

Ну здесь в логе видно что из-за обновления при старте, не думаю что это связано с Конвертацией выделенного.

**Comment by BladeMight** [comment]
> Возможность задать надпись, которая появляется возле каретки для каждого языка

Для 2 главных раскладок — добавил([коммит](https://github.com/BladeMight/Mahou/commit/2ba4c289832d490a8eadbb7b98669cc4dae34e35), забрать можно [здесь](https://ci.appveyor.com/project/BladeMight/mahou/build/job/28qg4py0cna30vix/artifacts)). Релиз будет позже.

**Comment by BladeMight** [comment]
Релиз [Mahou-v2.1.1.1](https://github.com/BladeMight/Mahou/releases/tag/v2.1.1.1), закрываю.
