### ISSUE TITLE
Добавьте преобразование регистра и транслит

### ISSUE THREAD

**Issue by de1eted** [BladeMight/Mahou#52]
Уж очень хочется пунто выкинуть. Этих двух возможностей не хватает.

**Comment by BladeMight** [comment]
Добавлю, позже.

**Comment by de1eted** [comment]
Спасибо

**Comment by Kristinita** [comment]
@BladeMight ,

Полагаю, эти возможности должны присутствовать в любом продвинутом текстовом редакторе. Для Sublime Text:

1. Транслит — [**SublimeTranslit**](https://github.com/malexer/SublimeTranslit), вроде работает, как заявлено; [**пофиксил**](https://github.com/malexer/SublimeTranslit/pull/4), что увидел.
2. Преобразование регистра — Title Case, lower case, sWAP cASE и UPPER KEYS [**доступны по умолчанию**](https://github.com/bradrobertson/sublime-packages/blob/master/Default/Default.sublime-commands#L7-L22). Есть также [**пакет**](https://github.com/jdc0589/CaseConversion) для конвертации ещё в 10 форматов, правда, [**он не работает с кириллическими символами**](https://github.com/jdc0589/CaseConversion/issues/31). Не знаю, где там в пакете кодировку правильно указывать.

Да, функционал может понадобиться не только для работы в редакторе; однако если что-то понадобилось писать непосредственно в браузере, есть [**GhostText**](http://ru.stackoverflow.com/a/595371/199934).

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita ,

1. Не сложно нужно просто создать словарь по которому будет конвертировать.
2. Ну если для каждого типа, то сложнее всего будет добавить гор. клавиш в текущий интерфейс, но с новым интерфейсом это уже будет легче(намного).

Ждите новый интерфейс.

**Comment by vublack** [comment]
Добрый день. Спасибо за ваш труд, это лучший софт по переключению раскладки. что я видел.
Есть небольшая хотелка по поводу смены регитра. Было бы очень круто, если бы смена регистра во всех приложениях происходила как в Word (shift+F3) - по кругу (ааа Ааа ААА ааа), и работала как с выделенным текстом, так и с последним набранным словом(включая пробел).
У вас получается что перевод в оБРАТНЫЙ регистр вряд ли кто то использует. Не могу представить себе кому нужно слово начинающееся  со строчной буквы, с остальными заглавными.
Спасибо.

**Comment by BladeMight** [comment]
@vublack 
> "У вас получается что перевод в оБРАТНЫЙ регистр вряд ли кто то использует. Не могу представить себе кому нужно слово начинающееся со строчной буквы, с остальными заглавными."

Обратный регистр значит что регистр каждой буквы будет изменен на противоположный, примеры:

- ааа             => ААА
- пРИВЕТ      => Привет
- СлУЧаЙно => сЛучАйНО

т.е. полностью наоборот, что было маленьким стало большим и что было большим стало маленьким.

Для самого

> по кругу (ааа Ааа ААА ааа)

Можно использовать горячие клавиши:
1. В Заглавный регистр
2. В ВЕРХНИЙ регистр
3. В нижний регистр.
Перед этим выделив слово(-а), 
например для последнего слова можно использовать <kbd>Shift</kbd>+<kbd>Ctrl</kbd>+<kbd>←</kbd> и потом эти горячие клавиши, но можно и не по кругу, так ведь? Можно сразу в нужную форму одной горячей клавишей переключить.

**Comment by vublack** [comment]
Лично мне удобнее по кругу одним сочетанием либо одной горячей клавишей(не надо много хоткеев запоминать, да и просто в ворде так привык)))

> Можно использовать горячие клавиши:
> 
> В Заглавный регистр
> В ВЕРХНИЙ регистр
> В нижний регистр.
Это я так понимаю предлагаемый вами вариант реализации? Т.к > В ВЕРХНИЙ регистр и > В нижний регистр. сейчас в программе не вижу. В принципе очень интересно, но если логика будет повторять переключение раскладки(переключение последнего слова, выделенного текста, галочка для пробела, возможность переключать по кругу) то будет интуитивно понятнее

**Comment by BladeMight** [comment]
@vublack 
> В ВЕРХНИЙ регистр и > В нижний регистр. сейчас в программе не вижу

Видно же во вкладке "Горячие клавиши":
![2019 03 20 - 16'59'59_rect](https://user-images.githubusercontent.com/11931888/54694914-b265af80-4b31-11e9-8b39-c21278fecce2.jpg)

P.S. Обновись до [Mahou-latest-commit](https://github.com/BladeMight/Mahou/releases/tag/latest-commit).

**Comment by vublack** [comment]
Да, с дев версией есть указанные горячие клавиши. Спасибо.
Если вдруг будет желание сделать переключение по кругу одним хоткеем, буду признателен. Хотя я и без этого переживу))
Еще раз спасибо за ваш труд
