### ISSUE TITLE
Подсвечивать ScrollLock когда язык 1 активен

### ISSUE THREAD

**Issue by MishGa** [BladeMight/Mahou#53]
### MAHOU DEBUG INFO
- Mahou-v1.5.1.0
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
США(67699721)
Русская(68748313)
#### Mahou.ini:
```ini
!Unicode(?), Mahou settings file
[Hotkeys]
HKCLKey=19
HKCLMods=None
HKCSKey=3
HKCSMods=Control
HKCLineKey=19
HKCLineMods=Shift
OnlyKeyLayoutSwicth=CapsLock
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=122
HKConvertMoreMods=Shift + Control
[Locales]
locale1uId=1033
locale1Lang=English
locale2uId=1049
locale2Lang=Русский
LANGUAGE=RU
[Functions]
IconVisibility=False
CycleMode=True
EmulateLayoutSwitch=True
ELSType=2
CSSwitch=True
BlockCTRL=False
RePress=True
EatOneSpace=False
ReSelect=True
SymIgnModeEnabled=false
MoreTries=True
TriesCount=5
DisplayLang=True
DLRefreshRate=50
DLForeColor=#FF8040
DLBackColor=White
ExperimentalCSSwitch=False
Snippets=True
DTTOnChange=False
ScrollTip=True
UpdatesEnabled=False
Logging=False
DiffLayoutColors=False
CrtDisplayLang=False
CrtDLRefreshRate=50
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=True
[ExtCtrls]
UseExtCtrls=False
LCLocale=67699721
LCLocaleName=США
RCLocale=68748313
RCLocaleName=Русская
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=18
Width=20
Font=Georgia; 9pt; style=Bold
xpos=8
ypos=0
TransparentBack=True
DLForeColor=#FF8000
DLBackColor=#000000
CrtDLForeColor=#FFFFFF
CrtDLBackColor=#000000
L1DiffFGColor=#FF8080
L1DiffBGColor=#FFFFFF
L1DiffFont=Georgia; 8pt
L2DiffFGColor=#E1E100
L2DiffBGColor=#000000
L2DiffFont=Palatino Linotype; 9pt
CrtHeight=14
CrtWidth=24
CrtFont=Georgia; 8pt
Crtxpos=8
Crtypos=0
[DoubleKey]
Use=False
Delay=350
```
#### Problem description:

Перестал работать вкл\выкл CAPS по нажатию shift+Caps и "Подсвечивать ScrollLock когда язык 1 активен". 
Проверка обновлений отключена, обновил сегодня руками до последней версии. Какая версия стояла до этого - не помню.

**Comment by BladeMight** [comment]
> Перестал работать вкл\выкл CAPS по нажатию shift+Caps 

Это да, потому что в #47 Я добавил таймер отключающий его, нужно будет добавить возможность его отключать.

> Подсвечивать ScrollLock когда язык 1 активен

Выключите **Циклич. режим** поставьте желаемую раскладку в **Раскладка 1:** и тогда опять будет работать, а потом можете включить **Циклич. режим** .

**Comment by MishGa** [comment]
Спасибо за быстрый ответ. Какая стояла не помню, но теперь всё работает. Установил 1.5.0.6 вроде всё работает как надо. Теперь буду ждать исправление ДВух больших букв в начале слова и пожалуй для меня это будет последняя версия.

**Comment by BladeMight** [comment]
> Теперь буду ждать исправление ДВух больших букв в начале слова 

Это вы о чем?

> и пожалуй для меня это будет последняя версия.

??

**Comment by BladeMight** [comment]
@MishGa [вот](https://github.com/BladeMight/Mahou/releases/tag/v1.5.2.0) добавил возможность отключить таймер CapsLock.

**Comment by MishGa** [comment]
> 

    Теперь буду ждать исправление ДВух больших букв в начале слова

Это вы о чем?

    и пожалуй для меня это будет последняя версия.

??
ИНогда ВОтак-ВОт ПОлучается КОгда с ЗАглавной БУквы НАчинаешь ПЕчатать. Это я для примера. А последней, в том смысле что больше никаких хотелок от программы у меня нет.

**Comment by BladeMight** [comment]
Ну так понятно, а может лучше сделать возможность делать первую букву заглавной а остальные нет, и еще эта функция наверно будет как Конверт выделения, т.е. нужно выделить текст и нажать гор. клавишу для преобразования.
