### ISSUE TITLE
Invalid culture exception

### ISSUE THREAD

**Issue by TrueXakeP** [BladeMight/Mahou#54]
## Problem/Request description

![exception](https://cloud.githubusercontent.com/assets/5345528/22966314/4e640034-f36a-11e6-8ccd-44571562ee97.png)

Exception: invalid culture [exception.txt](https://github.com/BladeMight/Mahou/files/776373/exception.txt)
*Mahou 1.5.1.0 and earlier does not thown it.*

How to reproduce:
Install [ConEmu](https://conemu.github.io/) and import these settings [ConEmu.xml.txt](https://github.com/BladeMight/Mahou/files/776387/ConEmu.xml.txt)
Search for cmd in the Windows Start Menu and select "Run as administrator" from the context menu of it.

![def-term](https://cloud.githubusercontent.com/assets/5345528/22966005/fa60c2de-f368-11e6-84ae-bd0ca7d69db7.png)

P.S. Jesus Christ! Your GUI should definitely be redone. These buttons leading to the Debug Info and to the advanced settings are almost impossible to find.

## Expected behavior (Only if reporting bug)

No exceptions

## System information

- Windows version: [Windows 8.1]
- Windows architecture: [x64]
- .Net version: [4.6]
- Mahou version: [Only Mahou **1.5.2.0** and Mahou **1.5.2.3**]

Or you can Paste here debug info from Mahou (version >1.4.4.1):

### MAHOU DEBUG INFO
- Mahou-v1.5.2.3
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
США(67699721)
Русская(68748313)
Украинская (расширенная)(4037542937)
#### Mahou.ini:

[Mahou.ini.txt](https://github.com/BladeMight/Mahou/files/776337/Mahou.ini.txt)

## Attach logs (if logging were enabled)

[2017.02.15.log.txt](https://github.com/BladeMight/Mahou/files/776338/2017.02.15.log.txt)

**Comment by BladeMight** [comment]
> Exception: invalid culture

It is thrown because of country flags in tray feature. When window only showing it has 0x0000 culture and when Mahou gets it, it can't change tray icon to that culture, so we should skip the points where keyboard layout id is 0x0000 (if layoutID > 0), because we can't get culture ID from 0 and  it only appears when some windows like cmd **showing**.

Fixed in [v1.5.2.4](https://github.com/BladeMight/Mahou/releases/tag/v1.5.2.4). Now if layout id was  smaller than 1 it will be displayed in log like this:

```
02:52:32.750 [Warning]
                      Layout id was [0].
```

**Comment by TrueXakeP** [comment]
Yes it's fixed now. Thanks.

**Comment by BladeMight** [comment]
> Jesus Christ! Your GUI should definitely be redone.

Yeah I know that, I'm working on this. In it is in [my planes](https://github.com/BladeMight/Mahou/issues/51#issuecomment-279360661).
