### ISSUE TITLE
Caps-lock stopped working until Mahou is restarted

### ISSUE THREAD

**Issue by TrueXakeP** [BladeMight/Mahou#56]
## Problem/Request description

Maybe after Mahou update Caps-Lock started switching languages.
After disabling switching a layout by key a Caps-Lock function does not return to it's key until Mahou is restarted.

Steps to reproduce:
Enable switch layout by Caps-Lock.
Restart Mahou.
See a Caps Lock switches the languages.
Disable switch layout by key (set key to "none", do not restart Mahou).
See a Caps Lock doesn't work as a Caps Lock and not switches the languages. A led just blinks. (expected: it works as a Caps Lock)

If Mahou started with "none" key to switch layouts at the beginning then key change is working properly.

## Expected behavior (Only if reporting bug)

see "Problem" section

### MAHOU DEBUG INFO
- Mahou-v1.5.2.4
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
США(67699721)
Русская(68748313)
Украинская (расширенная)(4037542937)
#### Mahou.ini:

[Mahou.ini.txt](https://github.com/BladeMight/Mahou/files/780483/Mahou.ini.txt)

#### Snippets:
```
->mahou
====>
Mahou (魔法) - Magical layout switcher.
<====
->eml
====>BladeMight@gmail.com<====
```

## Attach logs (if logging were enabled)

[2017.02.16.log.txt](https://github.com/BladeMight/Mahou/files/780482/2017.02.16.log.txt)

**Comment by BladeMight** [comment]
Disable the **CapsLock timer** function in **More configs page 1**. I'we been thinking I fixed that if you not selected CapsLock from "Switch layout by key", I'll fix that soon.

**Comment by Kristinita** [comment]
@BladeMight , у Вас воспроизводится эта проблема? Работаете над устранением бага? У меня повторяется несколько раз в час, из-за чего пришлось временно прекратить использование Mahou. В версиях 1 её не было.

Временами `Caps_Lock` начинает функционировать по умолчанию — переключает символы в верхний регистр, а не переключает раскладки. Не работают и остальные функции конвертации Mahou. Перезагрузка Mahou разрешает проблему.

Напротив `Activate Caps Lock disabler timer` галочка не стоит, раскладки переключаю при помощи `Caps_Lock`.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Как я и говорил ранее:

> Disable the CapsLock timer function in More configs page 1. I'we been thinking I fixed that if you not selected CapsLock from "Switch layout by key", I'll fix that soon.

Но это было про версию 1.5.3.4, а в 2.0-beta все это уже исправлено. Для отключения **отключения Caps Lock** таймером([которая кстати появилась благодаря Вам](https://github.com/BladeMight/Mahou/issues/47)), отключите Включить таймер отключатель Caps Lockе во вкладке Функции. (это я про 2.0)
Версия 1+ **обновляется не будет**, т.к. в 2.0 уже очень много изменений, нужно всего лишь исправить и доделать несколько вещей для релиза стабильной версии 2.0. А пока что я рекомендую использовать [самую последнюю бету](https://ci.appveyor.com/project/BladeMight/mahou/build/job/r53i1a07hffglr8n/artifacts).
