### ISSUE TITLE
Undo doesn't work after a spacebar

### ISSUE THREAD

**Issue by TrueXakeP** [BladeMight/Mahou#57]
## Problem/Request description

A
```
еуые<spacebar><Break>
```
not going to become a
```
test 
```

## Expected behavior (Only if reporting bug)

Undo works in this case.

## System information
Same as in the #56 
## Attach logs (if logging were enabled)

[2017.02.16.log.txt](https://github.com/BladeMight/Mahou/files/780549/2017.02.16.log.txt)

**Comment by BladeMight** [comment]
Enable [**Eat one Space**](https://github.com/BladeMight/Mahou/wiki/Functions-List#--) feature.

**Comment by TrueXakeP** [comment]
Oh... Then I think it should be renamed.

**Comment by BladeMight** [comment]
@TrueXakeP Yeah I know, I'm working now on new user interface, which will be more user-friendly ^^)

**Comment by TrueXakeP** [comment]
I look forward to. Thanks.
