### ISSUE TITLE
[Bug] Crash Mahou 1.5.2.3

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#58]
### 1. Summary

Mahou постоянно крашится у меня. Если раньше редко, то сейчас иногда по несколько раз в час.

### 2. Expected behavior

Стабильная работа Mahou.

### 3. Actual behavior

Процесс `Mahou.exe` самостоятельно убивается, мне приходится заново запускать Mahou.

### 4. Steps to reproduce

я занимаюсь какими-то делами на компьютере → нажимаю <kbd>Caps_Lock</kbd> → Mahou крашится.

### 5. Дополнительная информация

Если посмотреть в [**Process Hacker**](http://processhacker.sourceforge.net/), то Mahou у меня лидирует среди всех других программ по показателям `CPU` и `I/O total rate`.

![Process Hacker](http://i.imgur.com/63qCu6X.png)

Не уверен, что это хорошо для столь маленькой программы.

### 5. Trobleshooting

- Mahou-v1.5.2.3
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
SashaCoolMakEn(4039181321)
SashaCoolMakRU(4039115801)
US(67699721)
#### Mahou.ini:
```ini
!Unicode(✔), Mahou settings file
[Hotkeys]
HKCLKey=119
HKCLMods=Control
HKCSKey=119
HKCSMods=Shift
HKCLineKey=119
HKCLineMods=None
OnlyKeyLayoutSwicth=CapsLock
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=121
HKConvertMoreMods=Shift + Control
[Locales]
locale1uId=4039181321
locale1Lang=SashaCoolMakEn
locale2uId=4039115801
locale2Lang=SashaCoolMakRU
LANGUAGE=EN
[Functions]
IconVisibility=True
CycleMode=False
EmulateLayoutSwitch=False
ELSType=0
CSSwitch=True
BlockCTRL=False
RePress=True
EatOneSpace=False
ReSelect=True
SymIgnModeEnabled=false
MoreTries=True
TriesCount=5
DisplayLang=False
DLRefreshRate=50
DLForeColor=#FFFFFF
DLBackColor=#000000
ExperimentalCSSwitch=False
Snippets=False
DTTOnChange=False
ScrollTip=False
UpdatesEnabled=False
Logging=True
DiffLayoutColors=True
CrtDisplayLang=True
CrtDLRefreshRate=50
TrayFlags=true
CapsLockTimer=true
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=True
[ExtCtrls]
UseExtCtrls=False
LCLocale=4039181321
LCLocaleName=SashaCoolMakEn
RCLocale=4039115801
RCLocaleName=SashaCoolMakRU
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=14
Width=24
Font=Microsoft Sans Serif, 8.25pt
xpos=8
ypos=0
TransparentBack=True
DLForeColor=#FFFFFF
DLBackColor=#000000
CrtDLForeColor=#FFFFFF
CrtDLBackColor=#000000
L1DiffFGColor=#8B5FFF
L1DiffBGColor=#FFFFFF
L1DiffFont=Carlito, 8.25pt, style=Bold
L2DiffFGColor=Red
L2DiffBGColor=White
L2DiffFont=Candara, 8.25pt, style=Bold
CrtHeight=14
CrtWidth=24
CrtFont=Microsoft Sans Serif, 8.25pt
Crtxpos=8
Crtypos=0
[DoubleKey]
Use=False
Delay=350
```
#### Snippets:
```
->mahou
====>
Mahou (魔法) - Magical layout switcher.
<====
->eml
====>BladeMight@gmail.com<====
```

Спасибо.

**Comment by BladeMight** [comment]
> Если посмотреть в Process Hacker, то Mahou у меня лидирует среди всех других программ по показателям CPU и I/O total rate.

Спасибо за сообщение, обязательно исправлю.

**Comment by BladeMight** [comment]
> Если посмотреть в Process Hacker, то Mahou у меня лидирует среди всех других программ по показателям CPU и I/O total rate.

В текущем релизе Mahou 1.5.2.4 есть проблемы с таймерами, и они очень сильно нагружают диск и процессор, [но в последнем предрелизе](https://github.com/BladeMight/Mahou/releases/download/v2.0.0.0beta/Mahou-v2.0.0.0-Beta.zip) при всех таймерах включенных даже со значениями обновления таймеров в 1мс CPU <0.1%. Mahou v2.0-beta имеет очень действия таймеров.

P.S. Закрывать любые Issue не буду до того как не выйдет стабильная версия Mahou-v2.0.

**Comment by BladeMight** [comment]
@Kristinita В [самой последней beta](https://ci.appveyor.com/project/BladeMight/mahou/build/job/m8jel09vtkubdb09/artifacts) очень сильно оптимизированы таймеры.

**Comment by Kristinita** [comment]
@BladeMight , ждём новую beta в Chocolatey) .

2.0.0.0 за день использования ни разу не крашилась, поэтому issue закрываю.

Спасибо!

**Comment by BladeMight** [comment]
> ждём новую beta в Chocolatey) .

Я пока буду просто обновлять эту же 2.0.0.0-beta.

**Comment by Kristinita** [comment]
@BladeMight , в Chocolatey вроде если какая-либо версия программы имеет статус «Approved», то изменить эту версию уже нельзя. Чтобы пользователи получили изменения, необходим push новой версии.

Спасибо.

**Comment by BladeMight** [comment]
> изменить эту версию уже нельзя

А? ну тогда будет beta-1.
