### ISSUE TITLE
[Bug] System.Globalization.CultureNotFoundException: Culture is not supported.

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#59]
### 1. Summary

Когда открываю некоторые программы, в частности, [**PViewer**](https://chocolatey.org/packages/pViewer) или [**ScreenToGIF**](https://chocolatey.org/packages/screentogif), а также некоторые другие, то появляется окно с ошибкой.

![Culture](http://i.imgur.com/zAmuVZ1.png)

Причём здесь Mahou — у этого окна в Taskbar Windows значок-бабочка Mahou.

![Butterfly](http://i.imgur.com/bAiCPT4.png)

### 2. Expected behavior

Никаких окон с ошибками от Mahou.

### 3. Actual behavior

```
Culture is not supported.
Parameter name: culture
0 (0x0000) is an invalid culture identifier.
```

![Mahou Window](http://i.imgur.com/zAmuVZ1.png)

Текст, появляющийся, если нажать на `Details`:

```c++
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: culture
0 (0x0000) is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride)
   at Mahou.MahouForm.RefreshIconAll()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Mahou
    Assembly Version: 1.5.2.3
    Win32 Version: 1.5.2.3
    CodeBase: file:///D:/Chocolatey/lib/Mahou/tools/Mahou.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

Иногда Mahou крашится, как расписано [**здесь**](https://github.com/BladeMight/Mahou/issues/58).

### 4. Settings

Т.к, возможно, дело в моём .NET Framework, привожу данные, полученные программой [**DotNET Version Detector**](https://chocolatey.org/packages/dotnetversiondetector):

```
<32Bit>
2.0.50727.8745
  ->C:\Windows\Microsoft.NET\Framework\v2.0.50727
4.6.1586.0
  ->C:\Windows\Microsoft.NET\Framework\v4.0.30319

<64Bit>
2.0.50727.8745
  ->C:\Windows\Microsoft.NET\Framework64\v2.0.50727
4.6.1586.0
  ->C:\Windows\Microsoft.NET\Framework64\v4.0.30319

< Installed .NET Frameworks >
.NET FW 2.0 SP 2  (CLR:2.0)
.NET FW 3.0 SP 2  (CLR:2.0)
.NET FW 3.5 SP 1  (CLR:2.0)
.NET FW 4.6.2  (CLR:4.0)

< Installed Updates >
Microsoft .NET Framework 4 Client Profile 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
Microsoft .NET Framework 4 Extended 
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217
 KB2468871
 KB2468871v2
 KB2478063
 KB2533523
 KB2544514
 KB2600211
 KB2600217

< Installed Languages 3.0>
English - United States
< Installed Languages 3.5.x>
English - United States
< Installed Languages 4.x>
English - United States
```

Когда пробую установить .NET 4.6.2 как через Chocolatey, так и вручную, система показывает, что .NET 4.6.2 уже установлен.

![.NET Framework](http://i.imgur.com/mJqlSic.png)

### 5. Steps to reproduce

В проводнике Windows открываю любое изображение программой PViewer → вместе с изображением открывается попап с ошибкой.

Или запускаю программу ScreenToGIF → появляется окно с ошибкой.

### 6. Environment

**Operating system and version:**
Windows 10 Enterprise LTSB 64-bit En
**PViewer:**
1.3.1
**ScreenToGIF:**
2.4.0.170115

### 7. Troubleshooting

- Mahou-v1.5.2.3
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
SashaCoolMakEn(4039181321)
SashaCoolMakRU(4039115801)
US(67699721)
#### Mahou.ini:
```ini
!Unicode(✔), Mahou settings file
[Hotkeys]
HKCLKey=119
HKCLMods=Control
HKCSKey=119
HKCSMods=Shift
HKCLineKey=119
HKCLineMods=None
OnlyKeyLayoutSwicth=CapsLock
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=121
HKConvertMoreMods=Shift + Control
[Locales]
locale1uId=4039181321
locale1Lang=SashaCoolMakEn
locale2uId=4039115801
locale2Lang=SashaCoolMakRU
LANGUAGE=EN
[Functions]
IconVisibility=True
CycleMode=False
EmulateLayoutSwitch=False
ELSType=0
CSSwitch=True
BlockCTRL=False
RePress=True
EatOneSpace=False
ReSelect=True
SymIgnModeEnabled=false
MoreTries=True
TriesCount=5
DisplayLang=False
DLRefreshRate=50
DLForeColor=#FFFFFF
DLBackColor=#000000
ExperimentalCSSwitch=False
Snippets=False
DTTOnChange=False
ScrollTip=False
UpdatesEnabled=False
Logging=True
DiffLayoutColors=True
CrtDisplayLang=True
CrtDLRefreshRate=50
TrayFlags=true
CapsLockTimer=true
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=True
[ExtCtrls]
UseExtCtrls=False
LCLocale=4039181321
LCLocaleName=SashaCoolMakEn
RCLocale=4039115801
RCLocaleName=SashaCoolMakRU
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=14
Width=24
Font=Microsoft Sans Serif, 8.25pt
xpos=8
ypos=0
TransparentBack=True
DLForeColor=#FFFFFF
DLBackColor=#000000
CrtDLForeColor=#FFFFFF
CrtDLBackColor=#000000
L1DiffFGColor=#8B5FFF
L1DiffBGColor=#FFFFFF
L1DiffFont=Carlito, 8.25pt, style=Bold
L2DiffFGColor=Red
L2DiffBGColor=White
L2DiffFont=Candara, 8.25pt, style=Bold
CrtHeight=14
CrtWidth=24
CrtFont=Microsoft Sans Serif, 8.25pt
Crtxpos=8
Crtypos=0
[DoubleKey]
Use=False
Delay=350
```
#### Snippets:
```
->mahou
====>
Mahou (魔法) - Magical layout switcher.
<====
->eml
====>BladeMight@gmail.com<====
```

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Спасибо за сообщение об ошибках, я сейчас работаю над **Mahou 2.0** в которой будет новый интерфейс и будут исправлены все баги которые есть в текущих. Скоро(через ~4 часа) будет предрелизная версия в [релизах на GitHub](https://github.com/BladeMight/Mahou/releases).

**Comment by Kristinita** [comment]
@BladeMight , в Chocolatey её не забудьте добавить.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Хорошо.

**Comment by BladeMight** [comment]
@Kristinita [Вот](https://github.com/BladeMight/Mahou/releases/tag/v2.0.0.0beta).

**Comment by BladeMight** [comment]
> Когда открываю некоторые программы, в частности, PViewer или ScreenToGIF, а также некоторые другие, то появляется окно с ошибкой.

В версии [1.5.2.4](https://github.com/BladeMight/Mahou/releases/tag/v1.5.2.4) это уже исправлено.

**Comment by Kristinita** [comment]
@BladeMight , добавьте, пожалуйста, пре-релиз в Chocolatey, как сделано [**здесь**](https://chocolatey.org/packages/TeraCopy/3.0.3.20150603-alpha). 

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Спасибо, Я как раз искал как.

**Comment by Kristinita** [comment]
@BladeMight , не за что. я сам не понимаю, как это сделать, хотел у Вас посмотреть 😺 . 

Поиск в Google не привёл к положительным результатам. Где из [**репозитория**](https://github.com/ddieppa/Chocolatey-Packages/tree/master/TeraCopy%203.0.a3) следует, что это пре-релиз, тоже не пойму.

Спасибо.

**Comment by BladeMight** [comment]
@Kristinita Нужно просто к версии добавить **-** и она будет предрелизной.

**Comment by BladeMight** [comment]
Кстати вот [Mahou-v2.0-beta](https://chocolatey.org/packages/Mahou/2.0.0.0-beta) на Chocolatey.

**Comment by Kristinita** [comment]
@BladeMight, 

1. Где находятся исходники Вашего пакета? Их [**желательно указывать в параметре**](https://github.com/Kristinita/SashaChocolatey/blob/76d115a0cdf56c609856f49717504756a7d9ac50/packages/Performance%20Maintainer/permain.nuspec#L12) `packageSourceUrl`, дабы другие пользователи могли посмотреть Ваш пакет или пофиксить в нём баги.
2. Так как для Mahou необходима определённая версия .NET Framework, желательно в `nuspec`-файле указывать зависимости, [**пример**](https://github.com/Kristinita/SashaChocolatey/blob/master/packages/Performance Maintainer/permain.nuspec#L36).

Спасибо.

**Comment by BladeMight** [comment]
1. Не думал что и их нужно ставить, исходники все у меня. [Добавил их сюда](https://github.com/BladeMight/Mahou/tree/master/Chocolatey).
2. Это тоже нужно добавить.

**Comment by Kristinita** [comment]
@BladeMight , сделайте, пожалуйста, push 1.5.2.4 — последней версии без серьёзных багов — на Chocolatey.

Спасибо.

**Comment by BladeMight** [comment]
> push 1.5.2.4 

? Не push а release или хотя-бы tag/label.

Сделал, [вот](https://chocolatey.org/packages/Mahou/1.5.3.4).
