### ISSUE TITLE
Convert selection and layout switch hotkeys

### ISSUE THREAD

**Issue by Mikanoshi** [BladeMight/Mahou#6]
Shift+Pause (and any hotkey with Shift modifier) doesn't convert selected text.
Also, why only Caps Lock to switch between layouts?
I got used to left Ctrl with Punto Switcher... Tried all the swicthers and they all lack something compared to Punto :(
I just want last word conversion with Pause, selected text with Shift+Pause and language with left Ctrl.

Win 10 1607

**Comment by BladeMight** [comment]
> Shift+Pause (and any hotkey with Shift modifier) doesn't convert selected text.

You need to re-press shift every time.
Just tested in [Mahou v1.0.4.9](https://github.com/BladeMight/Mahou/releases/tag/v1.0.4.9) works.

>Also, why only Caps Lock to switch between layouts?

Okay, will do it, to make assign own hotkey...

**Comment by Mikanoshi** [comment]
Re-press? How is that?) I think it works only if you press combination very fast.

**Comment by BladeMight** [comment]
NO, i meant:
HOLD Shift -> Pause -> RELEASE Shift

**Comment by Mikanoshi** [comment]
Shouldn't it be the other way around?) Hold Shift and press Pause to cycle between languages. I release shift only if I force myself to do it, that's why this combination rarely works.
P.S. Yes, just left Ctrl.

**Comment by BladeMight** [comment]
> Shouldn't it be the other way around?) Hold Shift and press Pause to cycle between languages.

I'm working on this...
Maybe *today* or **tomorrow** everything will be ready.

**Comment by Mikanoshi** [comment]
Also note that LCtrl+Key shouldn't switch layout if LCtrl is set as a hotkey (Simple Switcher has this problem)

**Comment by BladeMight** [comment]
> LCtrl+Key shouldn't switch layout if LCtrl is set as a hotkey

Okay, i'll note that, thanks for reporting)

**Comment by BladeMight** [comment]
Check out the [Mahou v1.0.5.6](https://github.com/BladeMight/Mahou/releases/tag/v1.0.5.6) or Auto-update from older.

**Comment by Mikanoshi** [comment]
There is some problem with a dot and sometimes Alt (and Shift) modifiers stuck in a pressed state and I have to press Ctrl again to unstuck it.
Also cycle mode... well, see yourself :D

![bugs](https://cloud.githubusercontent.com/assets/5113439/17551585/745a33fc-5f14-11e6-8628-7026565fce22.gif)

**Comment by Mikanoshi** [comment]
I found how to avoid the problem with LCtrl language switching and hotkeys in Simple Switcher, it has an option to do an action on KEYUP, so when LCtrl is long pressed language doesn't switch like crazy and it also resolves the conflict with other LCtrl+Key combinations.

**Comment by BladeMight** [comment]
Well, about "/" after conversion, some symbols can't be recognized in **Convert Selection** because they exist it both languages, so switch 2-nd language to 1-st and try again, or use **Convert Last** or **Convert Line**.
And about cycle mode, does that happen in earlier(1.0.4.9 and lower) Mahou?

**Comment by Mikanoshi** [comment]
Convert Last Word is not working in both 1.0.4.9 and 1.0.5.6 when cycle mode is enabled, it rewrites the word, but the word always stays the same. Other than that there were no bugs similar to the ones in latest version, where Alt is consistently stucking (by the flashing underlined shortcuts in programs menu it looks like cycle mode uses some combination with the Alt, it will definitely conflict with a lot programs, e.g. in Firefox I have main menu hidden and pressing Alt opens it effectively blocking all the subsequent input).

How does Mahou detects current layout? I guess it's not just using the current one. That allows switching selected text from EN to RU even if current layout is already RU, but the downside is that some characters won't be the same in both directions no matter what language is selected as 1st and 2nd.

I'm used to "ю" becoming "." and back (or "/" becoming "." and back depending on the initial layout).

1st - EN, 2nd - RU:
Mahou switches "." to "/" and "/" to "\" in a selected text which can be confusing.
Also "ntcn/ntcn" is switched to "ntcn\ntcn" and then to "тест\тест", this is not correct.
Depending on the 1st and 2nd languages switching in one of the directions will always be incorrect.

P.S. You forgot to change version in form's caption :)

**Comment by BladeMight** [comment]
> Convert Last Word is not working in both 1.0.4.9 and 1.0.5.6 when cycle mode is enabled, it rewrites the word, but the word always stays the same. Other than that there were no bugs similar to the ones in latest version, where Alt is consistently stucking (by the flashing underlined shortcuts in programs menu it looks like cycle mode uses some combination with the Alt, it will definitely conflict with a lot programs, e.g. in Firefox I have main menu hidden and pressing Alt opens it effectively blocking all the subsequent input).

There was bug with extended keys, so now try latest version.

> How does Mahou detect current layout? 

For "Convert selection" it doesn't detect it, it just Unicode-Converts them by specified layout in settings.

> 1st - EN, 2nd - RU:

Try otherwise, and write how it goes.(Mine works so `"ю" to "." & "/" to "." and then "ю"`)

> Depending on the 1st and 2nd languages switching in one of the directions will always be incorrect.

But that symbols, they cant be recognized by my `UltimateUnicodeConverter`, maybe i will do an other implementation, so Mahou be able to switch between _UUC_ and _Direct Input_(as __ConvertLast/Line__), and with this language will be changed.
Keep reporting, and Mahou will become best layout switcher :gem:

**Comment by Mikanoshi** [comment]
Now LCtrl doesn't work at all )))

I like the other selection switch method better - get current layout and switch selected text based on it, then change layout too. Next switch will use new layout and all chars will be reverted back as they were.

**Comment by BladeMight** [comment]
> Now LCtrl doesn't work at all )))

WHAT? Are you sure? Try RCtrl is it work? What happening to your layout, does it flickering?
P.S. Mahou window must be not focused or hidden, so all hotkey will work.

> and all chars will be reverted back as they were.

Thats right!

**Comment by Mikanoshi** [comment]
It's not flickering. Will test more tomorrow, need to sleep now))

**Comment by BladeMight** [comment]
> need to sleep now))
Just like me)) "Good Morning." (My time is 8:11)

**Comment by Mikanoshi** [comment]
10 :)
Latest version. Only LCtrl is not working in normal mode. None of the keys work in cycle mode.
What does the hint about LCtrl means and why is it using a combination with Alt? I can see access shortcuts blinking in menus.

**Comment by BladeMight** [comment]
> None of the keys work in cycle mode.
Maybe that is because it simulates Alt+Shift to switch layout, i must add an Ctrl+Shift too.
> What does the hint about LCtrl means
It means that normal mode not works for LCtrl, i don't know why if i leave it it will stuck and will switch layout infinite.
>  and why is it using a combination with Alt?
That is because Alt+Shift switches layout in Russian Windows, In English Ctrl+Shift.

**Comment by Mikanoshi** [comment]
> Maybe that is because it simulates Alt+Shift to switch layout, i must add an Ctrl+Shift too.
I have all the default hotkeys in OS disabled :) Those that could be disabled, Win+Space is still there.
You should add a direct switching, it will be less buggy and more compatible with various programs.

Actually, I'm using Simple Switcher now. it has all I need (not without some bugs though) - all hotkey actions can be set on KEYUP, LCtrl's working with disabled OS layout switching, uses other method of selected text switching (together with current language). This method won't switch EN text to RU if current lang is already RU, but it's rarely a case, so not a big deal.
It doesn't show current lang code in its tray icon though, that would be helpful, I could hide default indicator then.

**Comment by BladeMight** [comment]
> I have all the default hotkeys in OS disabled :)

> LCtrl's working with disabled OS layout switching

I looked at Simple Switcher's code and found that it simulates the Alt+Shift, but not just that, it also uses PostMessage(my Direct Input) to switch layout which is not works with LCtrl in Mahou yet.

I'll keep updating Mahou, and notice you when all will be done, happy waiting.

P.S. So i don't need to add Ctrl+Shift...

**Comment by Mikanoshi** [comment]
But I don't see a blinking access shortcuts when switching with SS at all, even if LAlt+Shift is enabled in the system, so it must be doing something differently.

**Comment by BladeMight** [comment]
> access shortcuts

what is this?(screenshot)

**Comment by Mikanoshi** [comment]
Underlined keys in program's menu you have to press in an Alt+Key combination.
Windows LAlt+Shift vs Simple Switcher LCtrl:
![layout](https://cloud.githubusercontent.com/assets/5113439/17595429/7b4bb49a-6006-11e6-9649-efb4839e5f0a.gif)

**Comment by BladeMight** [comment]
Ah this...

Maybe SS presses Alt + Shift lightingly falst? Mahou have little delay so they are blinking.

**Comment by Mikanoshi** [comment]
Don't think so, tested with PassMark KeyboardTest and the only pressed key was LCtrl.
For Mahou it shows LCtrl+RAlt+LShift

**Comment by BladeMight** [comment]
Then that is just PostMessage...

Could you try SS in Edge/Mail/Settings/Store or any other Metro apps, does it works in them?

P.S. Mahou gets not right layout in them, is SS get the right one?

**Comment by Mikanoshi** [comment]
PostMessage can just hang the program))
https://github.com/alexazz19/SimpleSwitcher/issues/10
Works perfectly in Settings. Layout and last word switching are working in Edge, switching selected text works too, but if it's in an address box it hangs the browser for like 30 seconds.
Punto has this problem too, but it conflicts with a lot of games, they either hang completely or have all the controls stuck until you Alt+Tab. I was always disabling it before playing.

**Comment by BladeMight** [comment]
> Maybe SS presses Alt + Shift lightingly fast?
IT IS! Now Mahou can do it too(using reworked `KInputs`), WITHOUT any delay, you won't able to see the blink.

**Comment by Mikanoshi** [comment]
And how does it work if I have Alt + Shift disabled?))

**Comment by BladeMight** [comment]
> And how does it work if I have Alt + Shift disabled?))

I'll add **option** to select between `PostMessage` changing and `Alt+Shift Emulation`.

**Comment by Mikanoshi** [comment]
1.0.7.4
_Normal mode_
Last word and LCtrl - layout switches in an endless loop and everything lags until focus is removed from the current window.
Selection - works with layout switch, but frequently stops working because of the stuck modifier, had to press LCtrl once to unstuck.
_Cycle mode_
Nothing works :)
Last word switches from EN to RU and then always switches from RU to RU, LCtrl doesn't change language, selection is like in normal mode.

**Comment by BladeMight** [comment]
Why Mahou on your system works different? On my system everything works __perfect__, how could i release a release if it not work?

**Comment by Mikanoshi** [comment]
No idea) Are you on Win 10 x64 Build 1607?

**Comment by BladeMight** [comment]
Win 10 x64 Build 1511.

**Comment by Mikanoshi** [comment]
Looks like a problem with elevated processes. All switching works fine in programs that are not executed under admin, but modifier still stuck there too sometimes (input comes in UPPERCASE even when Shift is not pressed).

**Comment by BladeMight** [comment]
> All switching works fine 

Fuh, I'm so happy.

> Looks like a problem with elevated processes.

if you wan't Mahou to work with them start it elevated.([Autstart Mahou with Windows Elevated](https://github.com/BladeMight/Mahou/wiki/Mahou-not-work-in-Administrative-programs.))

> but modifier still stucks there too sometimes

It will stuck if you released modifier before it end conversion.(working on fixing it)

**Comment by Mikanoshi** [comment]
Now running as admin, switching is working until I select LCtrl, after that it's always an endless loop for LCtrl and Pause (last word).
P.S. SS creates high priv task automatically :)

**Comment by BladeMight** [comment]
Bye, i'm go to sleep.

**Comment by BladeMight** [comment]
The main issue was:

> Shift+Pause (and any hotkey with Shift modifier) doesn't convert selected text.
Also, why only Caps Lock to switch between layouts?
I got used to left Ctrl with Punto Switcher... Tried all the swicthers and they all lack something compared to Punto :(
I just want last word conversion with Pause, selected text with Shift+Pause and language with left Ctrl.<br/>
Win 10 1607

So, it is fixed.
