### ISSUE TITLE
[Bug] Don't open files in Windows Explorer

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#60]
### 1. Summary

Несколько раз в день получаю поведение, когда не могу открыть папки в Windows Explorer и ссылки в Firefox. После перезапуска Mahou поведение нормальное. Проблема началась где-то с версий 1.5.

### 2. Expected behavior

Открытие папок в Windows Explorer двойным кликом.

### 3. Actual behavior

При двойном клике по любой папке в Windows Explorer появляется окно свойств папки.

![Properties](http://i.imgur.com/iGKFN70.png)

Я не могу открывать папки.

При кликам по любым ссылкам в браузере ничего не происходит.

### 4. Steps to reproduce

Иногда с запущенным Mahou я получаю актуальное поведение. Убиваю процесс Mahou в ProcessHacker или командой `taskkill` → вновь запускаю `Mahou.exe` → получаю нормальное поведение.

### 5. MAHOU DEBUG INFO
- Mahou-v2.0.0.0
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
#### All installed layouts:
SashaCoolMakEn(4039181321)
SashaCoolMakRU(4039115801)
US(67699721)
#### Mahou.ini:
```ini
!Unicode(✔), Mahou settings file
[Hotkeys]
HKCLKey=119
HKCLMods=Control
HKCSKey=119
HKCSMods=Shift
HKCLineKey=119
HKCLineMods=None
OnlyKeyLayoutSwicth=CapsLock
HKSymIgnKey=122
HKSymIgnMods=Shift + Control + Alt
HKConvertMore=121
HKConvertMoreMods=Shift + Control
ToggleMainWindow_Enabled=False
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=True
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=Win + None
ConvertLastWord_Key=119
ConvertSelectedText_Enabled=True
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=Win + Shift
ConvertSelectedText_Key=119
ConvertLastLine_Enabled=True
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=None
ConvertLastLine_Key=119
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=False
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=0
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Shift
SelectedTextToRandomCase_Key=0
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win + Control + Shift + Alt
SelectedTextToSwapCase_Key=19
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win + 
SelectedTextTransliteration_Key=45
ExitMahou_Enabled=True
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
[Locales]
locale1uId=4039181321
locale1Lang=SashaCoolMakEn
locale2uId=4039115801
locale2Lang=SashaCoolMakRU
LANGUAGE=EN
[Functions]
IconVisibility=True
CycleMode=False
EmulateLayoutSwitch=False
ELSType=0
CSSwitch=True
BlockCTRL=False
RePress=False
EatOneSpace=False
ReSelect=True
SymIgnModeEnabled=false
MoreTries=True
TriesCount=5
DisplayLang=False
DLRefreshRate=50
DLForeColor=#FFFFFF
DLBackColor=#000000
ExperimentalCSSwitch=False
Snippets=False
DTTOnChange=False
ScrollTip=False
UpdatesEnabled=False
Logging=True
DiffLayoutColors=True
CrtDisplayLang=True
CrtDLRefreshRate=50
TrayFlags=True
CapsLockTimer=True
TrayIconVisible=True
ConvertSelectionLayoutSwitching=True
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
StartupUpdatesCheck=False
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
[EnabledHotkeys]
HKCLEnabled=True
HKCSEnabled=True
HKCLineEnabled=True
HKSymIgnEnabled=True
[ExtCtrls]
UseExtCtrls=False
LCLocale=4039181321
LCLocaleName=SashaCoolMakEn
RCLocale=4039115801
RCLocaleName=SashaCoolMakRU
[Proxy]
ServerPort=
UserName=
Password=
[TTipUI]
Height=14
Width=24
Font=Microsoft Sans Serif, 8.25pt
xpos=8
ypos=0
TransparentBack=True
DLForeColor=#FFFFFF
DLBackColor=#000000
CrtDLForeColor=#FFFFFF
CrtDLBackColor=#000000
L1DiffFGColor=#8B5FFF
L1DiffBGColor=#FFFFFF
L1DiffFont=Carlito, 8.25pt, style=Bold
L2DiffFGColor=Red
L2DiffBGColor=White
L2DiffFont=Candara, 8.25pt, style=Bold
CrtHeight=14
CrtWidth=24
CrtFont=Microsoft Sans Serif, 8.25pt
Crtxpos=8
Crtypos=0
[DoubleKey]
Use=False
Delay=350
[Layouts]
SwitchBetweenLayouts=True
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=-1
ChangeToSpecificLayoutByKey=True
MainLayout1=SashaCoolMakEn(4039181321)
MainLayout2=SashaCoolMakRU(4039115801)
SpecificKey1=1
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Switch between layouts
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
[Appearence]
DisplayLangTooltipForMouse=False
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
Language=English
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Microsoft Sans Serif, 8.25pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Microsoft Sans Serif, 8.25pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Microsoft Sans Serif, 8.25pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Microsoft Sans Serif, 8.25pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
[Timings]
LangTooltipForMouseRefreshRate=5
LangTooltipForCaretRefreshRate=5
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=10
ScrollLockStateRefreshRate=5
CapsLockDisableRefreshRate=5
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
[Snippets]
SnippetsEnabled=False
```
#### Snippets:
```
->mahou
====>
Mahou (魔法) - Magical layout switcher.
<====
->eml
====>BladeMight@gmail.com<====
```

Спасибо.

**Comment by Kristinita** [comment]
*(Не показывает Debug info, что Beta-1 версию использую).*

Спасибо.

**Comment by BladeMight** [comment]
> При двойном клике по любой папке в Windows Explorer появляется окно свойств папки.

Это значит что какой-то из Alt'ов зажат. Можно решить проблему нажав на каждый из них по 1 разу.
Для того чтобы понять почему появляется "залипание" попробуйте включить логирование( и выключить все подсказки языка т.к. они создают слишком много лога) и подождать пока не случится "залипание", затем отправьте мне лог.

**Comment by Kristinita** [comment]
> и выключить все подсказки языка

Можно поподробнее, что необходимо отключить?

Спасибо.

**Comment by BladeMight** [comment]
> Можно поподробнее, что необходимо отключить?

Это не обязательно, а только для того чтобы уменьшить количество лога, вот:
![2017-03-02 11-05-05-selection](https://cloud.githubusercontent.com/assets/11931888/23500310/3c9eecea-ff38-11e6-96d0-cef2f14800aa.jpg)

**Comment by Kristinita** [comment]
@BladeMight , с утра эта проблема воспроизвелась 1 раз, [**эта**](https://github.com/BladeMight/Mahou/issues/56#issuecomment-282473881) примерно 10—15 раз.

[**Лог**](https://gist.github.com/baa8d5fa1b200a0ff6303b865b969600)

Спасибо.

**Comment by Kristinita** [comment]
> ( и выключить все подсказки языка т.к. они создают слишком много лога) и подождать
>  только для того чтобы уменьшить количество лога,

У меня логи размером в пол-гигабайта за сутки выходили (доказательства привести не могу, поскольку сделал их автоматическую очистку каждый день). Вероятно, стоит что-то сделать, чтобы уменьшить размер лога, если подсказки отображаются.

Спасибо.

**Comment by BladeMight** [comment]
> поскольку сделал их автоматическую очистку каждый день

Постойте у вас логи стоят в постоянном использовании? Там же написано что надо использовать ТОЛЬКО ДЛЯ ПОИСКА ошибок, а ошибок в 

> [**Лог**](https://gist.github.com/baa8d5fa1b200a0ff6303b865b969600)

Я не увидел, так что может быть логгинг - это и есть ошибка(или в нём)

> Вероятно, стоит что-то сделать, чтобы уменьшить размер лога, если подсказки отображаются.

Да но тогда данные могут бы **чуть** менее детальными, думаю можно сделать что-то с повторяющимися логами каждую секунду или две.

**Comment by BladeMight** [comment]
А и еще кое-что по поводу того что я [сказал](https://github.com/BladeMight/Mahou/issues/60#issuecomment-281753708) насчет:
> При двойном клике по любой папке в Windows Explorer появляется окно свойств папки.

Теперь увидев это:

> При кликам по любым ссылкам в браузере ничего не происходит.

И вспомнив [это](https://github.com/BladeMight/Mahou/issues/44#issuecomment-278632542)(то что Вы используете Firefox), это означало что то что я сказал:

> Это значит что какой-то из Alt'ов зажат. Можно решить проблему нажав на каждый из них по 1 разу.

100% правда, у Вас просто залипает один из Alt'ов... Но судя по [логу](https://gist.github.com/baa8d5fa1b200a0ff6303b865b969600) у Вас они не залипли, только три раза Alt был нажат для действий:

- <kbd>Alt</kbd>+<kbd>Space</kbd>
- <kbd>Alt</kbd>+<kbd>+</kbd>
- <kbd>Alt</kbd>+<kbd>Win</kbd>+<kbd>F</kbd>

Это ведь Ваши горячие клавиши, я прав? Если да то тогда в этом логе нет ошибки о которой [Вы сообщили](https://github.com/BladeMight/Mahou/issues/60#issue-209423938).

**Comment by Kristinita** [comment]
Сегодня вечером в версии 2.0.0.5 [**эти проблемы**](https://github.com/BladeMight/Mahou/issues/60#issuecomment-283865325) не воспроизвелись. Мне ни разу не приходилось перезагружать Mahou или нажимать на <kbd>Alt</kbd>.

Спасибо.
