### ISSUE TITLE
Падает с ошибкой при попытке обновления, если нет подключения.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#63]
Закрываю фаерволом подключения для Mahou.
В версии 2.0 нажимаю "проверить обновления"
[Скриншот ошибки](http://prntscr.com/edzbkr)

**Comment by BladeMight** [comment]
ОК, исправил в [Mahou-v2.0.0.2](https://github.com/BladeMight/Mahou/releases/tag/v2.0.0.2).
