### ISSUE TITLE
[Feature request] Restart Mahou by hotkey

### ISSUE THREAD

**Issue by Kristinita** [BladeMight/Mahou#64]
### 1. Request

Было бы неплохо добавить возможность рестарта Mahou хоткеем.

### 2. Justification

К сожалению, начиная с версий 1.5, несколько раз в час получаю [**баги**](https://github.com/BladeMight/Mahou/issues/56#issuecomment-282473881). Помогает перезагрузка Mahou.

### 3. Actual behavior

Кликаю правой кнопкой мыши по иконке Mahou в трее → Exit → ввожу «Mahou» [**в ланчере**](http://www.getwox.com/) → <kbd>Enter</kbd> → Mahou перезапускается для меня.

### 4. Desirable behavior

Нажимаю какой-нибудь шорткат → Mahou перезапускается.

### 5. Examples on other apps

Например, в [**Clipjump**](http://softwarerecs.stackexchange.com/a/39662/23324) есть команда для `Restart`:

![Restart](http://i.imgur.com/t14Wu6c.png)

Спасибо.

**Comment by BladeMight** [comment]
> Было бы неплохо добавить возможность рестарта Mahou хоткеем.

Может быть и так но проблемы только у Вас, и Вы же пользуютесь AutoHotkey'ем? Думаю не составит труда написать что-то вроде этого:
```
#A::
Process,Close,Mahou.exe
Run,D:\Путь_к_Mahou\Mahou.exe
return
```

> несколько раз в час получаю баги

Something может? Быть wrong?
Я don't думаю so...
Даже if это so, как do мне do чтобы meet эту error?
Как this не funny... 
To слушать about неподтвержденный bug от ones кто uses Махоу...
Actually Я can't повторить this ошибку, even если I стараюсь hard...
I тестил with всеми functions, и timers значения set на 1 мс, and даже so Я can't meet ошибку...
Но error не showing и I не can исправить it без knowing почему it появляется, if появляется for настоящему.
Just подумать about это seems невозножным, but Я try усерднее to поймать it наконец(if это possible).
Everything работает just хорошо and никаких bugs после hours использования.
Как can это be? Только some логика need для understand это writing, но I уверен you понимаешь!
If бы you мог provide журнал(log) после crash, то maybe Я can понять why это happened.
Ошибки must быть solved, чтобы was весело to использовать program, и to быть happy самому.
So единственный who может provide детали this является YOU! Так please если can предоставьте...

Thanks за attention, веселого conversion и layout переключения.

**Comment by Kristinita** [comment]
> Может быть и так но проблемы только у Вас, и Вы же пользуютесь AutoHotkey'ем?

Да, прошу прощения. я написал похожий скрипт.

```
; close Mahou
Process, Close, Mahou.exe
; re-open Mahou
run D:\Chocolatey\bin\Mahou.exe
```

Добавил его запуск шорткатом в кронтаб:

```
#( Mahou_restart
WatchHotKey: "@${NUMPAD6}"
Action:
StartIn: "D:\AutoHotkey" 
ShowNormal   NormalPriority
START-APP: D:\AutoHotkey\Restart Mahou.exe
)#
```

Но это не заработало. я думал, что по причине ошибочности моего скрипта, оказалось — шорткаты, которые пробовал, были заняты другой программой. Плохо, что для Windows 10, по-видимому, [**нет программы**](http://softwarerecs.stackexchange.com/q/33669/23324), которая показывала бы, какие глобальные хоткеи заняты запущенными процессами.

Спасибо.

**Comment by BladeMight** [comment]
> Но это не заработало. я думал, что по причине ошибочности моего скрипта

Если бы это был Я то я бы сначала проверил скрипт(сразу после создания) запустив его и пришел бы к выводу

> оказалось — шорткаты

И первым делом попробовал другой hotkey, после чего бы понял что он занят.

> Плохо, что для Windows 10, по-видимому, нет программы, которая показывала бы, какие глобальные хоткеи заняты запущенными процессами.

Это да, но если сделать программу которая будет регистрировать **все возможные хоткеи** то тогда те которые не получилось зарегистрировать и будут занятыми(т.е те которые используются другими процессами), но это не относится к программам которые используют свои [HOOK](https://msdn.microsoft.com/en-us/library/windows/desktop/ms632589(v=vs.85).aspx)'и для хоткеев([кстати в Mahou так же](https://github.com/BladeMight/Mahou/blob/master/Mahou/Classes/KMHook.cs#L115)), так что идентифицировать что у них там внутри - не получиться **никак**, хотя насчет конфликтов с этими программами - их не будет, действия обоих(а то и больше) программ  использующие свои HOOK'и для хоткеев будут работать вместе с той которая была [зарегистрирована](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309(v=vs.85).aspx).

**Comment by BladeMight** [comment]
> Ладно добавлю. :smiley_cat:

@Kristinita Добавил в [Mahou v2.1.0.7](https://github.com/BladeMight/Mahou/releases/tag/v2.1.0.7).
