### ISSUE TITLE
В skype перестаёт работать "конвертация последней линии".

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#65]
Skype.
В [поле ввода сообщения](http://prntscr.com/eegken) перестаёт работать "конверт последней введенной строки". Причину пока не выявил (если получится отследить - добавлю). Иногда жму кнопку - ничего не конвертит. Иногда - каретка на чверть секунды прыгает влево, но текст остаётся тем же. После этого иногда меняется раскладка, а иногда - нет.

При этом "конверт выделения" работает.
Также в [поле поиска](http://prntscr.com/eegjai) той же программы конверт последней линии работает.

Еще, если написать 1 символ - "конверт строки" работает в поле сообщения. 😖

**Comment by Trost123** [comment]
Суда по ощущением происходит двойной конверт - каретка прыгает, NumLock мигает на долю секунды, а текст - тот же.

**Comment by BladeMight** [comment]
У меня все работает, вот гифка:
![mahou skype - ok](https://cloud.githubusercontent.com/assets/11931888/23440670/14950fc6-fe26-11e6-85e6-99d2f6a04114.gif)

**Comment by Trost123** [comment]
Это не то поле.
Попробуйте в поле, где вы обычно отравляете кому-то сообщения.
Скачал софт для записи гифок, удалось поймать в анимации новых багов:
![skype bug](https://cloud.githubusercontent.com/assets/21346282/23454130/f3ef923e-fe73-11e6-8c75-b62168605cc2.gif)
Во время записи я не использовал копирование\вставку. Просто писал текст и пытался конвертировать его (конверт линии, один раз конверт выделения).
По перемещению каретки можно понять когда я жму конверт линии.

Детальнее могу продемонстрировать баг через демонстрацию экрана в Skype.
Мой skype: trost123

**Comment by BladeMight** [comment]
> Попробуйте в поле, где вы обычно отравляете кому-то сообщения.

И здесь все ОК:
![mahou skype - ok](https://cloud.githubusercontent.com/assets/11931888/23454713/cc86afe6-fe75-11e6-9fda-7e851d71be2f.gif)

> Mahou скопировал мне текст из этого поля на гитхабе 😄

Видимо по если переключать окна по Alt-Tab'у то слова не очищаются, надо будет добавить правило для очистки.

P.S. Можете отладочную информацию из Mahou сюда вставить?

**Comment by Trost123** [comment]
Вот еще странную вещь нашел:
![skype bug 2](https://cloud.githubusercontent.com/assets/21346282/23455169/599af224-fe77-11e6-8b28-eb594d8e42fb.gif)
Т.е. изначально стоит английский, пишу "ssssss", жму капс-лок (меняю на рус), пишу "ыыыыы", держу бексейс - после удаления всех символов, язык сам меняется на англ (wtf??).
Во вторых - когда я жму капс - почему-то запись экрана выдала "capital capital scroll". Что?
Если выключить Mahou и перезагрузиться - такое не повторяется. 
Прикрепил лог в пред. посте.

**Comment by BladeMight** [comment]
> capital capital scroll

В первый раз - нажимаете Вы, во второй раз Mahou отключает лампочку CapsLock а в третий включает или выключает лампочку ScrollLock зависимую от текущего языка.

> после удаления всех символов, язык сам меняется на англ (wtf??).
Не удалось повторить такое... Может вы нажали мышкой на другое окно(или панель задач) после удаления?

**Comment by Trost123** [comment]
Если есть 15 минут - могу через Skype (демонстрация экрана) продемонстрировать всё вживую, так понятней и быйстрей будет.
Мышкой во время этой гифки не кликал.

**Comment by BladeMight** [comment]
> В поле ввода сообщения перестаёт работать "конверт последней введенной строки"

У меня получилось воспроизвести ошибку, пока для ее решения пока что включите "Переключение между раскладками" и перезагрузите Mahou и Skype, а Я сейчас поищу способ решения...

**Comment by Trost123** [comment]
Вот еще одна вариация - тут я не пользуюсь конвертом линии, просто переключаю раскладку - сначала по alt+shift, потом по caps lock.
При удалении первого текста - раскладка не меняется.
При удалении второго текста - раскладка меняется много раз.
![skype bug 3](https://cloud.githubusercontent.com/assets/21346282/23456201/1e5b1618-fe7b-11e6-97c7-76af44c31283.gif)

**Comment by Trost123** [comment]
Да, "Переключение между раскладками" исправляет баг "конверт строки в Skype" и баг cо сменой раскладки из предыдущего поста.
Я и так использую только 2 языка, так что мне с этой галочкой ничем не хуже. (Но для других пользователей баг убрать не помешало бы)

**Comment by BladeMight** [comment]
Пришел к выводу что ЭТО ПОЛЕ(как и в WordPad) САМО ВОССТАНАВЛИВАЕТ БЫВШУЮ РАСКЛАДКУ из-за не соответствия чарсетов раскладок... НО как очень странно что только при использовании сообщения HKL_NEXT... Видимо оно не совершенно... Так что нужно будет придумать другой способ циклинга по раскладкам.

**Comment by BladeMight** [comment]
Все придумал новый способ, должно хорошо работать. [Mahou-v2.0.0.3](https://github.com/BladeMight/Mahou/releases/tag/v2.0.0.3)
Проблема заключалась в 

> В поле ввода сообщения перестаёт работать "конверт последней введенной строки"

Так что если она решена, нажмите **close issue**.

**Comment by Trost123** [comment]
Сейчас проверим. Пока что:
[Баг в диалоге обновления](http://prntscr.com/eemqur)

**Comment by BladeMight** [comment]
Ну надо же прям в момент как я залил тег 2.0.0.3, у вас хорошая удача.

**Comment by Trost123** [comment]
А вообще, чтобы максимально стабильно\правильно работало везде (если 2 раскладки всего в системе) - "переключать между расскладками" и "эмулировать переключение раскладки" лучше off или on ставить?
В старом интерфейсе помню при наведении обьяснения были.
(после ответа закрою топик)

**Comment by BladeMight** [comment]
> "переключать между расскладками" и "эмулировать переключение раскладки" лучше off или on ставить?

**переключать между расскладками** - уже не имеет значения после этого фикса... Но если вы используете функцию **смена раскладки в конверт выделения**(или даже плюс) то без нее не обойтись(что она делает можно узнать на [Wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9A%D0%92-%D0%9A%D0%BB%D1%8E%D1%87)) т.к. она зависима от нее.
**эмулировать переключение раскладки** - может быть полезно в Windows 8/10 там где есть метро приложения, т.к. там не всегда срабатывают Windows Messages, хотя в сборке 1607 вроде все нормально работало... Так что лучше **off**.

> В старом интерфейсе помню при наведении обьяснения были.

Я думаю их тоже добавить позже.

**Comment by Trost123** [comment]
Спасибо за оперативную поддержку!
Надеюсь ваш энтузиазм еще долго продержится. (А баги будут лезть реше 😉 )

**Comment by BladeMight** [comment]
> В старом интерфейсе помню при наведении обьяснения были.

В версии [2.0.0.5](https://github.com/BladeMight/Mahou/releases/tag/v2.0.0.5) добавлены подсказки для самых сложных для понимания функций.
