### ISSUE TITLE
Дефолтные сниппеты вставляются с новой строки.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#66]
Дефолтные сниппеты выглядят примерно так
```
->snip
====>
Snippet test
<====
```
Лично меня это заставило почесать затылок лишних 5-10 минут т.к. подставив в такую конструкцию свои тексты я получал 2 лишних сбросов строки (до и после текста).
К тому же, если ввести такой сниппет в адресной строке браузера - при замене сниппета автоматом нажимается enter и после замены браузер автоматически переходит по новой ссылке, что весьма неожиданно.

Предлагаю поменять примеры сниппетов (или хотя-бы один) в такой формат:

```
->snip
====>Snippet test<====
```

Имхо в 90% случаев пользователю нужна замена в пределах одной строки, без энтеров до\после.

**Comment by BladeMight** [comment]
@Trost123 Ок, поменял в [коммите](https://github.com/BladeMight/Mahou/commit/30442fc795d2b8f69b42e7d2eb8782e24c944399) будет в следующих релизах по умолчанию.
