### ISSUE TITLE
В окне уведомления о новой версии не отображаются иконки.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#68]
http://prntscr.com/eg77cd
Скорее всего в кодировке проблема. Если легкого фикса нет - можно забить.

**Comment by BladeMight** [comment]
@Trost123 Это потому что в Windows 7 нет поддержки emoji в окне уведомления... И поменять шрифт окна не можно, в Windows 8+ такого нет.

**Comment by BladeMight** [comment]
@Trost123 В [Winaero Tweaker](http://winaero.com/comment.php?comment.news.1836) есть [возможность изменить шрифт окон сообщений](http://winaero.com/blog/the-list-of-winaero-tweaker-features)(секция Message Font), хотя это изменит шрифт в Firefox...

**Comment by Trost123** [comment]
Спасибо за совет, но этот баг не насколько значим, чтобы так заморачиваться.
Тем более в главном окне программы changelog показывает с иконками - я просто захожу и там читаю.

**Comment by BladeMight** [comment]
Ну я просто хотел сказать что это возможно.
