### ISSUE TITLE
После перезагрузки неправильно работает первая конвертация.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#69]
Загружаю ПК. > Жду некоторое время, чтобы всё прогрузилось. > В любой программе набираю "привет" в английской расскладке - "ghbdtn" > Жму "конвертация последней линии" > Получаю:

> ghbdет

Количество букв, которые не захватывает - варьируется. Иногда 1 букву забывает, иногда больше.
После этого, Mahou начинает нормально работать до след. перезагрузки.

**Comment by BladeMight** [comment]
@Trost123 Может быть Mahou у Вас запускается последним? Потому что это поведение может быть только если Mahou не запустился еще.

**Comment by Trost123** [comment]
Дело в том, что у меня всё на SSD - загружается быстро.
Только что подождал пару минут после перезагрузки - "ghивет".
Да и припоминаю случай, когда включал пк, листал в интернете страницы пол часа (не касаясь клавиатуры), потом решал что-то написать и конверт вот так вот тупил.

**Comment by Trost123** [comment]
Нашел причину - 360 Total Security видимо блокирует считывание первых пары нажатий.
Обычно когда начинаешь печатать и включен Mahou\EveryLang - кейлоггинг блокируется появляется окно с предупреждением. Пока не разрешишь кейлоггинг - в программу кнопки не передаются.
Но похоже даже добавив программу в "разрешенные", 360 не сразу "соображает" и блокирует первые пару нажатий.
В общем это не баг Mahou. Попробывал с EveryLang - та же история.

**Comment by BladeMight** [comment]
@Trost123 Я считаю что Антивирусы - нужны только для супер не опытных пользователей (зло которое следит за всем что ты делаешь и проверяет его), у меня их нет но хорошо что ты нашел причину, будет полезно другим пользователям.
