### ISSUE TITLE
Вылет Mahou при запуске с созданным Mahou.settings

### ISSUE THREAD

**Issue by vicodin77** [BladeMight/Mahou#7]
Доброго дня!
При попытке запустить Mahou с уже имеющимся Mahou.settings происходит вылет программы. Скрин прилагаю. 
![image](https://cloud.githubusercontent.com/assets/16464189/17582142/ac36a3ca-5fb2-11e6-8247-fe472fb7c87d.png)
При запуске без файла настроек, программа запускается корректно.
Операционка Win 7 Corp SP1

**Comment by BladeMight** [comment]
В [Mahou v1.0](https://github.com/BladeMight/Mahou/releases/tag/v1.0) так же?

**Comment by vicodin77** [comment]
Только что проверил - да, версия 1.0 так же вылетает с той же ошибкой.

**Comment by BladeMight** [comment]
А какой версии .Net установлен?(Нужен 4.5)

**Comment by vicodin77** [comment]
Стоит 4.0. Сейчас поставлю 4.5!

**Comment by vicodin77** [comment]
Поставил. Тоже самое!

**Comment by BladeMight** [comment]
А как насчет разрешений папки? При запуске от Администратора? И Откройте блокнотом Mahou.settings и напишите здесь.

**Comment by BladeMight** [comment]
Попробуйте [dotSwitcher](https://github.com/kurumpa/dotswitcher), там так же?(т.к. он тоже на C#)
P.S. Я уже работаю над новым способом сохранения/загрузки настроек.

**Comment by vicodin77** [comment]
Права на папку проверил - все норм. При запуске от админа так же вылетает. dotSwitcher запускается нормально всегда.
Прикладываю Mahou.settings:
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <0000WS054385>
    <locale2Lang>English</locale2Lang>
  </0000WS054385>
  <0000WS054385>
    <OnlyKeyLayoutSwicth>CapsLock</OnlyKeyLayoutSwicth>
  </0000WS054385>
  <0000WS054385>
    <HKCLineMods>Shift</HKCLineMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLKey>19</HKCLKey>
  </0000WS054385>
  <0000WS054385>
    <IconVisibility>true</IconVisibility>
  </0000WS054385>
  <0000WS054385>
    <HKCSKey>145</HKCSKey>
  </0000WS054385>
  <0000WS054385>
    <HKCSMods>None</HKCSMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLMods>None</HKCLMods>
  </0000WS054385>
  <0000WS054385>
    <locale1uId>1033</locale1uId>
  </0000WS054385>
  <0000WS054385>
    <HKCSEnabled>true</HKCSEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale1Lang>English</locale1Lang>
  </0000WS054385>
  <0000WS054385>
    <HKCLineKey>19</HKCLineKey>
  </0000WS054385>
  <0000WS054385>
    <HKCLEnabled>true</HKCLEnabled>
  </0000WS054385>
  <0000WS054385>
    <CycleMode>false</CycleMode>
  </0000WS054385>
  <0000WS054385>
    <BlockCTRL>false</BlockCTRL>
  </0000WS054385>
  <0000WS054385>
    <HKCLineEnabled>true</HKCLineEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale2uId>1033</locale2uId>
  </0000WS054385>
  <0000WS054385>
    <locale2Lang>Русский</locale2Lang>
  </0000WS054385>
  <0000WS054385>
    <OnlyKeyLayoutSwicth>CapsLock</OnlyKeyLayoutSwicth>
  </0000WS054385>
  <0000WS054385>
    <HKCLineMods>Shift</HKCLineMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLKey>19</HKCLKey>
  </0000WS054385>
  <0000WS054385>
    <IconVisibility>True</IconVisibility>
  </0000WS054385>
  <0000WS054385>
    <HKCSKey>145</HKCSKey>
  </0000WS054385>
  <0000WS054385>
    <HKCSMods>None</HKCSMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLMods>None</HKCLMods>
  </0000WS054385>
  <0000WS054385>
    <locale1uId>1033</locale1uId>
  </0000WS054385>
  <0000WS054385>
    <HKCSEnabled>True</HKCSEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale1Lang>English</locale1Lang>
  </0000WS054385>
  <0000WS054385>
    <HKCLineKey>19</HKCLineKey>
  </0000WS054385>
  <0000WS054385>
    <HKCLEnabled>True</HKCLEnabled>
  </0000WS054385>
  <0000WS054385>
    <CycleMode>False</CycleMode>
  </0000WS054385>
  <0000WS054385>
    <BlockCTRL>False</BlockCTRL>
  </0000WS054385>
  <0000WS054385>
    <HKCLineEnabled>True</HKCLineEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale2uId>1049</locale2uId>
  </0000WS054385>
  <0000WS054385>
    <locale2Lang>Русский</locale2Lang>
  </0000WS054385>
  <0000WS054385>
    <OnlyKeyLayoutSwicth>CapsLock</OnlyKeyLayoutSwicth>
  </0000WS054385>
  <0000WS054385>
    <HKCLineMods>Shift</HKCLineMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLKey>19</HKCLKey>
  </0000WS054385>
  <0000WS054385>
    <IconVisibility>True</IconVisibility>
  </0000WS054385>
  <0000WS054385>
    <HKCSKey>145</HKCSKey>
  </0000WS054385>
  <0000WS054385>
    <HKCSMods>None</HKCSMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLMods>None</HKCLMods>
  </0000WS054385>
  <0000WS054385>
    <locale1uId>1033</locale1uId>
  </0000WS054385>
  <0000WS054385>
    <HKCSEnabled>True</HKCSEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale1Lang>English</locale1Lang>
  </0000WS054385>
  <0000WS054385>
    <HKCLineKey>19</HKCLineKey>
  </0000WS054385>
  <0000WS054385>
    <HKCLEnabled>True</HKCLEnabled>
  </0000WS054385>
  <0000WS054385>
    <CycleMode>False</CycleMode>
  </0000WS054385>
  <0000WS054385>
    <BlockCTRL>False</BlockCTRL>
  </0000WS054385>
  <0000WS054385>
    <HKCLineEnabled>True</HKCLineEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale2uId>1049</locale2uId>
  </0000WS054385>
  <0000WS054385>
    <locale2Lang>Русский</locale2Lang>
  </0000WS054385>
  <0000WS054385>
    <OnlyKeyLayoutSwicth>CapsLock</OnlyKeyLayoutSwicth>
  </0000WS054385>
  <0000WS054385>
    <HKCLineMods>Shift</HKCLineMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLKey>19</HKCLKey>
  </0000WS054385>
  <0000WS054385>
    <IconVisibility>True</IconVisibility>
  </0000WS054385>
  <0000WS054385>
    <HKCSKey>145</HKCSKey>
  </0000WS054385>
  <0000WS054385>
    <HKCSMods>None</HKCSMods>
  </0000WS054385>
  <0000WS054385>
    <HKCLMods>None</HKCLMods>
  </0000WS054385>
  <0000WS054385>
    <locale1uId>1033</locale1uId>
  </0000WS054385>
  <0000WS054385>
    <HKCSEnabled>True</HKCSEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale1Lang>English</locale1Lang>
  </0000WS054385>
  <0000WS054385>
    <HKCLineKey>19</HKCLineKey>
  </0000WS054385>
  <0000WS054385>
    <HKCLEnabled>True</HKCLEnabled>
  </0000WS054385>
  <0000WS054385>
    <CycleMode>False</CycleMode>
  </0000WS054385>
  <0000WS054385>
    <BlockCTRL>False</BlockCTRL>
  </0000WS054385>
  <0000WS054385>
    <HKCLineEnabled>True</HKCLineEnabled>
  </0000WS054385>
  <0000WS054385>
    <locale2uId>1049</locale2uId>
  </0000WS054385>
</Settings>

**Comment by BladeMight** [comment]
ЭТО ЧТО ФАЙЛ НАСТРОЕК? Это весь файл? Не вижу `</xml>`, мдаа, он полон ошибок, и вообще не XML... и к тому же все параметры почему-то стали `<0000WS054385>`, а можно загрузить мне файл?
Точно надо делать новый способ сохранения/загрузки настроек.

**Comment by vicodin77** [comment]
Да, именно так и выглядит файл настроек. <0000WS054385> - это имя моего компа.
Куда отправить файл?

**Comment by vicodin77** [comment]
Файл отправил!

**Comment by BladeMight** [comment]
Здесь в форме нажми `Attach files by dragging & dropping or selecting them` и выбери файл и Comment.

**Comment by vicodin77** [comment]
Файл отправил по почте! Мой ZIP-файл почему-то не понравился githab`у...))

**Comment by BladeMight** [comment]
Вижу, Mahou создает для каждого элемента конфигурации  `<0000WS054385>` и `</0000WS054385>` когда должен один раз и для всех...
вот мой файл:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <YUI>
    <locale1Lang>Русский</locale1Lang>
    <locale2uId>1041</locale2uId>
    <CycleMode>False</CycleMode>
    <HKCLineMods>Shift</HKCLineMods>
    <HKCLKey>19</HKCLKey>
    <IconVisibility>False</IconVisibility>
    <HKCSKey>145</HKCSKey>
    <locale2Lang>日本語</locale2Lang>
    <HKCSMods>None</HKCSMods>
    <SwitchLayoutByCaps>True</SwitchLayoutByCaps>
    <HKCLineKey>19</HKCLineKey>
    <HKCLMods>None</HKCLMods>
    <locale1uId>1049</locale1uId>
    <OnlyKeyLayoutSwicth>CapsLock</OnlyKeyLayoutSwicth>
    <HKCSEnabled>True</HKCSEnabled>
    <HKCLEnabled>True</HKCLEnabled>
    <BlockCTRL>False</BlockCTRL>
    <HKCLineEnabled>True</HKCLineEnabled>
    <SwitchLayoutInCS>False</SwitchLayoutInCS>
    <EmulateLayoutSwitch>False</EmulateLayoutSwitch>
  </YUI>
</Settings>
```
YUI - имя компьютера. 
Ждите релиза новой способа сохранения/загрузки настроек.

**Comment by vicodin77** [comment]
С твоим файлом тоже не запускается... Запускается только без файла конфигурации.

**Comment by vicodin77** [comment]
Ок! Будем ждать!

**Comment by BladeMight** [comment]
> С твоим файлом тоже не запускается... Запускается только без файла конфигурации.

И не должен, т.к. у тебя не YUI.

вот с этим должно запуститься(используя последнюю версию):
```xml
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <0000WS054385>
    <locale1Lang>Русский</locale1Lang>
    <locale2uId>1033</locale2uId>
    <CycleMode>False</CycleMode>
    <HKCLineMods>Shift</HKCLineMods>
    <HKCLKey>19</HKCLKey>
    <IconVisibility>False</IconVisibility>
    <HKCSKey>145</HKCSKey>
    <locale2Lang>English</locale2Lang>
    <HKCSMods>None</HKCSMods>
    <SwitchLayoutByCaps>True</SwitchLayoutByCaps>
    <HKCLineKey>19</HKCLineKey>
    <HKCLMods>None</HKCLMods>
    <locale1uId>1049</locale1uId>
    <OnlyKeyLayoutSwicth>CapsLock</OnlyKeyLayoutSwicth>
    <HKCSEnabled>True</HKCSEnabled>
    <HKCLEnabled>True</HKCLEnabled>
    <BlockCTRL>False</BlockCTRL>
    <HKCLineEnabled>True</HKCLineEnabled>
    <SwitchLayoutInCS>False</SwitchLayoutInCS>
    <EmulateLayoutSwitch>False</EmulateLayoutSwitch>
  </0000WS054385>
</Settings>
```

**Comment by vicodin77** [comment]
К сожалению, тоже не запустился...((

**Comment by BladeMight** [comment]
> Ок! Будем ждать!

Уже готово. В [Mahou v1.0.7.9](https://github.com/BladeMight/Mahou/releases/tag/v1.0.7.9) уже новый метод ссохранения/загрузки настроек.

**Comment by Mikanoshi** [comment]
Convert Line не отключить с новым конфигом, после рестарта включается.

**Comment by BladeMight** [comment]
Исправлено [Mahou v1.0.8.0](https://github.com/BladeMight/Mahou/releases/tag/v1.0.8.0).

**Comment by vicodin77** [comment]
Проверил! Заработало! Спасибо!!!

**Comment by BladeMight** [comment]
Еще одна проблема решена.
