### ISSUE TITLE
Light alloy + Mahou при двойном нажатии пробела.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#70]
Вот еще прикольный баг словил - смотришь такой фильм в Light Alloy, хочешь остановить на каком-то определенном кадре - нажимаешь пробел (пауза) два раза в быстрой последовательности и твой плеер сходит с ума 🤕 
![light_alloy_mahou_bug](https://cloud.githubusercontent.com/assets/21346282/23699460/e03a809e-03f7-11e7-974e-547308e2a0a9.gif)
Нюансы:
Shift во время гифки я не нажимал, но система почему-то фиксирует нажатие шифта. (Даже без Mahou)
Выключаю Mahou - проблема исчезает. Включаю EveryLang (аналог Mahou) - всё норм (хотя у меня там на двойной шифт тоже назначено переключение).
Если включить индикацию NumLock - диод будет моргать постоянно во время бага.

В общем не помешал бы список программ-исключений.

**Comment by BladeMight** [comment]
Вероятно проблема со сниппетами, т.к. у меня все норм:
![just](https://cloud.githubusercontent.com/assets/11931888/23700055/512cb0cc-03fa-11e7-82f9-a60a00b0d16a.gif)
хоть и Shift откуда-то берется, но это даже если Mahou выключен!

**Comment by Trost123** [comment]
Ага, короче Light Alloy симулирует левый шифт при паузе - не важно пробелом или кликом.
При разворачивании на весь экран симулирует ctrl+insert и так далее.

**Comment by Trost123** [comment]
А чтобы проблема была - нужно конверт последней линии повесить на двойной шифт, тогда при двойном пробеле случается какое-то зацикливание, и плеер уже без моего участия будет очеьн быстро включать\выключать паузу 🗡

**Comment by BladeMight** [comment]
> По-этому просто неплохо было бы иметь программы-исключения.

Может быть добавлю такую функцию.

**Comment by BladeMight** [comment]
@Trost123 [Добавил](https://github.com/BladeMight/Mahou/commit/920019bb45dc717bd34bf6eaed4c39ccb07856d8), тестовую версию можно собрать самому или взять с [AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou/build/job/c565y9js2n2wpani/artifacts)(ссылка на сборку последнего коммита на момент сообщения).

**Comment by Trost123** [comment]
Да, всё рабоает.

**Comment by BladeMight** [comment]
Закрываю с релизом [Mahou v2.1.0.4](https://github.com/BladeMight/Mahou/releases/tag/v2.1.0.4).

**Comment by Trost123** [comment]
Хм. А как поступать, если процесс называется "LA.exe x32"?
Я так понимаю пробел сейчас парсит как разделитель названий процессов. Итого получается невозможно исключить х32 процессы?
