### ISSUE TITLE
"Подсвечивать ScrollLock" ломает alt-tab.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#72]
Вот еще поймал баг - когда пытаешься переключаться между окнами через alt-tab, Mahou соответственно нажимает скролл-лок и тем самым закрывает диалог альт-таба. (окна не переключаются)
Баг повторяется через раз. Но обычно, если открыть 2 окна и в них разный язык (в одном светится диод, в другом - нет), то после пары хаотичных альттабов баг появляется.
Заснял гифку с нажатиями - нажимаю я только alt+tab, а в логе получилось множество нажатий.
![alt_tab_mahou_bug](https://cloud.githubusercontent.com/assets/21346282/23990189/eab468fe-0a3d-11e7-94c5-45de0d127472.gif)

**Comment by BladeMight** [comment]
@Trost123 Подумаю над этим, спасибо за находку.

**Comment by BladeMight** [comment]
@Trost123 Все придумал исправление → Не подсвечивать Scroll Lock при Alt нажатом.
[MahouTest.zip](https://github.com/BladeMight/Mahou/files/848642/MahouTest.zip)

**Comment by Trost123** [comment]
Работает.

**Comment by BladeMight** [comment]
@Trost123 Релиз [Mahou v2.1.0.7](https://github.com/BladeMight/Mahou/releases/tag/v2.1.0.7).
