### ISSUE TITLE
падает при конвертации выделенного в outlook 2016

### ISSUE THREAD

**Issue by f242** [BladeMight/Mahou#74]
при написании нового письма, в поле "тема" работает исправно, а падает в поле где писать непосредственно текст сообщения
![2017-03-18 16_44_29- microsoft outlook 2016](https://cloud.githubusercontent.com/assets/10371194/24072569/3536ac80-0bfa-11e7-9f63-1e008226aa52.png)

[debug.txt](https://github.com/BladeMight/Mahou/files/852467/debug.txt)

[2017.03.18.log.txt](https://github.com/BladeMight/Mahou/files/852468/2017.03.18.log.txt)

**Comment by BladeMight** [comment]
@f242 Это точно лог когда Mahou *падает*? В логе никаких ошибок нет, можете сделать другой?

**Comment by BladeMight** [comment]
@f242 Офисные приложения Microsoft 2016 — не любят сообщение **WM_INPUTLANGCHANGEREQUEST** которое меняет раскладку, так что пользуйтесь функцией **Эмулировать переключение раскладки** с типом установленным на `Alt+Shift` или `Win+Space`, а я посмотрю что можно сделать...

**Comment by BladeMight** [comment]
> падает при конвертации выделенного в outlook 2016

Хах, а знаешь это Outlook его *убивает*! из-за **WM_INPUTLANGCHANGEREQUEST**. Потому что при дебаггинге Outlook висит → пытается *убить* Mahou.

**Comment by BladeMight** [comment]
О нашел причину, это все из-за восстановления предыдущего текста в буфере обмена.

**Comment by BladeMight** [comment]
@f242 Все исправил, [Mahou-v2.1.1.1](https://github.com/BladeMight/Mahou/releases/tag/v2.1.1.1).
