### ISSUE TITLE
Numpad символы

### ISSUE THREAD

**Issue by Shavcat** [BladeMight/Mahou#75]
## Проблема

Если после текста ввести любой символ из Numpad, то программа конвертирует некорректно (если символ идет до текста ошибка не проявляется).

Пример: **_кг-_** конвертируется на **_кru_** (вместо **_ru-_**). И так с любыми символами, если они набраны из Numpad: 1234567890./*-+

## Информация окружения

- Версия Windows: 10
- Архитектура Windows: x64
- Версия .Net: 4.6
- Версия Mahou: 2.1.1.1

![mahou-error](https://cloud.githubusercontent.com/assets/10747109/24076780/62692c3a-0c5b-11e7-88a8-b3f708b7b222.gif)

**Comment by BladeMight** [comment]
@Shavcat ОК, [исправлено](https://github.com/BladeMight/Mahou/commit/be1cbb16521f498142c5d47218628ce3fca895ce), релиз делать пока не буду(т.к. только недавно [сделал](https://github.com/BladeMight/Mahou/releases/tag/v2.1.1.1)), сборку можете взять [отсюда](https://ci.appveyor.com/project/BladeMight/mahou/build/job/3y8e8o1ul9f08dda/artifacts).
Ловит цифры Numpad только при NumLock включенном, а символы +/-* Numpad — всегда.

**Comment by Shavcat** [comment]
Супер оперативно, спасибо. Очень крутая программа.

**Comment by BladeMight** [comment]
[Star Mahou](https://github.com/BladeMight/Mahou/stargazers).
