### ISSUE TITLE
Не переключает язык в программе FAR

### ISSUE THREAD

**Issue by Alexeyvg** [BladeMight/Mahou#76]
## Problem/Request description

Не переключает язык в программе FAR
Если для переключения использовать Windows-комбинацию клавиш, то язык переключается.

<details><summary>MAHOU DEBUG INFO</summary>
<details><summary>Environment info</summary>

- Mahou 2.1.1.1
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

US(67699721)
Russian(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=true
[Functions]
TrayIconVisible=True
ConvertSelectionLayoutSwitching=True
ReSelect=True
RePress=True
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=False
Logging=False
CapsLockTimer=True
TrayFlags=False
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
[Layouts]
SwitchBetweenLayouts=True
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=US(67699721)
MainLayout2=Russian(68748313)
SpecificKey1=5
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Switch between layouts
SpecificLayout2=Switch between layouts
SpecificLayout3=
SpecificLayout4=
[Appearence]
DisplayLangTooltipForMouse=False
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
Language=English
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Georgia; 8pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Georgia; 8pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Georgia; 8pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Georgia; 8pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
Layout1LTText=
Layout2LTText=
[Timings]
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
[Snippets]
SnippetsEnabled=False
[Hotkeys]
ToggleMainWindow_Enabled=True
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=True
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=True
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=
ConvertSelectedText_Key=145
ConvertLastLine_Enabled=True
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=True
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=True
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=16
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Alt
SelectedTextToRandomCase_Key=17
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win
SelectedTextToSwapCase_Key=19
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win
SelectedTextTransliteration_Key=191
ExitMahou_Enabled=True
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=True
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
```
</details>
</details>
</details>

**Comment by BladeMight** [comment]
@Alexeyvg Где запущен Far? (в ConEmu или просто cmd.exe?)

**Comment by BladeMight** [comment]
@Alexeyvg Итого нашел 2 решения проблемы:
1. В Far в [ConEmu](https://conemu.github.io/ru/index.html) работает нормально, в любом случае.
2. Вижу у Вас всего 2 раскладки так что можете смело включить функцию **Эмулировать переключение раскладки**, с ней у меня все работает в Far в cmd.exe и в ConEmu.

**Comment by Alexeyvg** [comment]
@BladeMight, здравствуйте! Спасибо за столь быструю реакцию, видно, приложение вам как родное, это радует :-)

1. FAR в Windows запускаю просто запуском EXE-фала. Это же родное Win 32/64 приложение, для него всякие эмуляции излишни. 
Версия FAR 3.0.4774 x64
В нескольких компаниях, в которых я работал, FAR устанавливался по умолчанию на рабочие станции и серверы, в первый раз слышу про необходимость использовать ConEmu...

2. Разумеется, я в первую очередь попробовал нажать галочку "Эмулировать переключение раскладки", но ничего не изменилось :-(

**Дополнение**:
2. Ещё раз попробовал включить галочку "**Эмулировать переключение раскладки**", при этом выключил "**Переключать между раскладками**" (само в версии 2.1.1.1 оно не отключалось) - всё заработало! 
Большое спасибо за помощь, успехов в работе над Mahou, и вообще в удачи в создании новой софтовой империи! :-)

**Comment by BladeMight** [comment]
> Это же родное Win 32/64 приложение,

А вот и нет, даже так оно эмулируется в cmd.exe.

>  для него всякие эмуляции излишни.

Для поддержки большего количества цветов, функции вкладок, тем и т.д.

[Star Mahou](https://github.com/BladeMight/Mahou/issues/75#issuecomment-287582365)

**Comment by Alexeyvg** [comment]
@BladeMight 
> А вот и нет, даже так оно эмулируется в cmd.exe.

Может быть, в слово "эмулируется" вы вкладываете скрытый от меня смысл, и я просто чего то не понимаю, но я подтверждения работы "под cmd.exe" не нашёл...

Я смотрю в Process Explorer от Руссиновича
Вижу 64 битный процесс, parent у него "Explorer", он создал 3 потока.
Даже более того, в ресурсах у образа процесса есть строка "!This program cannot be run in DOS mode.", что в общем понятно для многопоточного 64 битного приложения.

PS Извините за оффтоп :-)

**Comment by BladeMight** [comment]
@Alexeyvg Видимо вы не знаете про **conhost.exe** который предназначен именно для этого.

**Comment by BladeMight** [comment]
@Alexeyvg Если еще нужно, то недавно восстановил поддержку getconkbl, подробнее в #105. Скачать Mahou с getconkbl можно [здесь](https://github.com/BladeMight/Mahou/releases/tag/v2.3.5.2).
