### ISSUE TITLE
Отключается Mahou

### ISSUE THREAD

**Issue by MishGa** [BladeMight/Mahou#77]
## [Русский](https://github.com/BladeMight/Mahou/blob/master/.github/ISSUE_TEMPLATE_RU.md)

Не обновлял программу уже давно, решил обновить дня три назад и начались проблемы. По ощущениям просто перестают работать горячие клавиши, хотя программа висит в процессах. Приходится снимать задачу и запускать по новой. Сегодня включил логирование, надеюсь вы поможете разобраться.
Сейчас пришла мысль, не уверен, но вполне возможно в тоже самое время начал использовать программу для управлением буфером обмена Clibor, попробую завтра поработать без неё.

## System information

- Mahou 2.1.1.6
- OS = [Microsoft Windows NT 6.2.9200.0]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Русская(68748313)
США(67699721)
Русская(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=False
[Functions]
TrayIconVisible=False
ConvertSelectionLayoutSwitching=True
ReSelect=False
RePress=True
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=True
StartupUpdatesCheck=False
Logging=True
CapsLockTimer=False
TrayFlags=False
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=True
[Layouts]
SwitchBetweenLayouts=False
EmulateLayoutSwitch=True
EmulateLayoutSwitchType=Win+Space
ChangeToSpecificLayoutByKey=True
MainLayout1=США(67699721)
MainLayout2=Русская(68748313)
SpecificKey1=1
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Switch between layouts
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
[Appearence]
DisplayLangTooltipForMouse=True
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
Language=Русский
Layout1ForeColor=#FF8040
Layout1BackColor=White
Layout1TransparentBackColor=True
Layout1Font=Georgia; 8pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Georgia; 8pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#FF8040
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=True
MouseLTFont=Georgia; 9pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Georgia; 8pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
Layout1LTText=
Layout2LTText=
[Timings]
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=350
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
[Snippets]
SnippetsEnabled=True
[Hotkeys]
ToggleMainWindow_Enabled=True
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=True
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=None
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=True
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=Control
ConvertSelectedText_Key=3
ConvertLastLine_Enabled=True
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=19
ToggleSymbolIgnoreMode_Enabled=False
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=True
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=None
SelectedTextToTitleCase_Key=16
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=False
SelectedTextToRandomCase_Modifiers=None
SelectedTextToRandomCase_Key=16
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win + Control + Shift + Alt
SelectedTextToSwapCase_Key=19
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win +                 
SelectedTextTransliteration_Key=45
ExitMahou_Enabled=True
ExitMahou_Double=False
ExitMahou_Modifiers=Win + None
ExitMahou_Key=220
RestartMahou_Enabled=True
RestartMahou_Modifiers=Win + None
RestartMahou_Key=122

Or you can Paste here debug info from Mahou (version >1.4.4.1):

1. Go to Mahou main window (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd> or in *tray icon's* menu select settings).
2. Press on [...] button to go to *More configs* window.
3. Click twice on [More] button to go to page 3 in *More configs* window.
4. Click on **Debug Info** button this will copy debug info to your clipboard.
5. Paste it here.

## Attach logs (if logging were enabled)

https://drop.me/omE7Eo - Лог.
PS. Ещё одна просьба к вам. Можно маленько переделать функцию "Выделение слов в Заглавный регистр"? Я не мастер печатать и смотрю уже на напечатанный текст и чтобы исправить ДВе заглавных в начале предложения мне приходится выделять первое слово, потом жать горячие клавиши. Проще передвинуть каретку, стереть большую букву и напечатать маленькую.
Если я выделяю весь текст и жму заданную комбинацию, то все слова становятся написанными с заглавной. Возможно сделать чтоб при выделении нескольких слов менялся регистр только первого? Ну или хотя бы чтоб менять слово перед кареткой не выделяя его?

**Comment by BladeMight** [comment]
@MishGa Попробуй еще в момент когда такое случается нажать и отпустит левые и правые Alt, Shift, Ctrl, Win клавиши, если после этого заработает то тогда отключи [эту](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9D%D0%B0%D0%B6%D0%B8%D0%BC%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D0%B3%D0%BE%D1%80%D1%8F%D1%87%D0%B8%D1%85-%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D1%88) функцию

**Comment by MishGa** [comment]
Хорошо. А моя просьба про конвертирование слов в Заглавный регистр и лог по криворукости добавились в системную информацию. Я продублирую тут.
```
https://drop.me/omE7Eo - Лог.
PS. Ещё одна просьба к вам. Можно маленько переделать функцию "Выделение слов в Заглавный регистр"? Я не мастер печатать и смотрю уже на напечатанный текст и чтобы исправить ДВе заглавных в начале предложения мне приходится выделять первое слово, потом жать горячие клавиши. Проще передвинуть каретку, стереть большую букву и напечатать маленькую.
Если я выделяю весь текст и жму заданную комбинацию, то все слова становятся написанными с заглавной. Возможно сделать чтоб при выделении нескольких слов менялся регистр только первого? Ну или хотя бы чтоб менять слово перед кареткой не выделяя его
```

**Comment by BladeMight** [comment]
Как видите:

![2017-03-30 09-45-34-window](https://cloud.githubusercontent.com/assets/11931888/24520761/450906a2-1592-11e7-8ce0-cfd8a73d95ac.jpg)

Уже есть.

В логе нашел ошибку:

> Сбой при выполнении запрошенной операции с буфером обмена.

Вероятно таки конфликт с *Clibor*, попробуйте добавить количество попыток взять выделенный текст во вкладке *Тайминги*.

**Comment by MishGa** [comment]
Есть, но я же и описываю что это очень не удобно. 

> Если я выделяю весь текст и жму заданную комбинацию, то все слова становятся написанными с заглавной. Возможно сделать чтоб при выделении нескольких слов менялся регистр только первого? Ну или хотя бы чтоб менять слово перед кареткой не выделяя его.
Акцент на слово **все**, а нужно чтоб менялось только **первое**. Очень не удобно выделять **одно** слово. Лишние движения мышки, проще не выделять слово, а удалить большую букву и напечатать маленькую. 
А с ошибкой попробую, наверно придётся искать другую программу для буфера.

**Comment by BladeMight** [comment]
> слово перед кареткой не выделяя его

Не выделяя - не получится, но если хотите то могу сказать как я делаю только с клавиатуры:
1. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>←</kbd>(выделяете последнее слово), а потом нажимаете гор. клавишу конвертацию регистра.
2. Если слово в начале линии, то тогда нажимаете <kbd>Home</kbd> потом <kbd>Ctrl</kbd>+<kbd>→</kbd> если есть символы перед словом, как только будете перед словом которое нужно исправить нажмите <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>→</kbd>(выделяете последнее слово), а потом нажимаете гор. клавишу конвертацию регистра или если курсор прямо перед буквой которую нужно в высший регистр - нажимаете <kbd>Del</kbd> А потом <kbd>Shift</kbd>+Буква которая была но в таком случае вам придется самому менять раскладку, если она не стояла правильно.
3. ...

**Comment by MishGa** [comment]
Можно сделать всё быстрей, ткнуть мышью перед буквой, нажать backspace, написать нужную букву. Получается в два раза меньше телодвижений. 
 Я до вашей программой пользовался утилитой Arum, она не работает с х64 программами, глючит, но там эта функция была реализована очень удобно.

**Comment by BladeMight** [comment]
> ткнуть мышью перед буквой

Да но вы же писали:

> Лишние движения мышки

Поэтому только клавиатурный вариант предлагал.

> Кстати ваш совет увеличить тайминги помог, весь вечер проработал без проблем. Спасибо.

В таком случае можно закрывать.
