### ISSUE TITLE
Отключается Mahou

### ISSUE THREAD

**Issue by MishGa** [BladeMight/Mahou#79]
По мотивам https://github.com/BladeMight/Mahou/issues/77
Увеличение попыток помогло на вечер. Отключал Clibor, менял версии Mahou. Заметил что отключается чаще всего при работе в Firefox ESR 52. Может и не 100%, но как правило замечаю когда пишу там. Вырубает не часто, и специально повторить не удаётся.

**Comment by Makishima** [comment]
Да, есть похожая проблема. То ли в ФФ отключается, то ли после использования teamviewer-а, а по работе приходится много раз им пользоваться.
Поможет ли в этом случае отладочная информация?

**Comment by BladeMight** [comment]
@Makishima @MishGa Попробуйте отключить [эту функцию](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9D%D0%B0%D0%B6%D0%B8%D0%BC%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D1%8F-%D0%B3%D0%BE%D1%80%D1%8F%D1%87%D0%B8%D1%85-%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D1%88) и проверьте как будет работать.

**Comment by MishGa** [comment]
Вроде отписывался, но мог забыть. Нажимать заново модификаторы после действия горячих клавиш - включал, отключал, всё одинаково плохо . Вчера обновил WIN10 до версии 1703, кажется стало ещё хуже. Теперь почти перед каждым использованием приходится перезагружать Mahou через диспетчер задач (Process Hacker).

**Comment by BladeMight** [comment]
@MishGa Хотя бы лог пришли что-ли чтобы хоть что-то понять.

**Comment by MishGa** [comment]
Вообще никакие комбинации клавиш из Mahou не работают. Не открыть окно, не перегрузить. Программа висит в процессах и не открывается даже при запуске ехе. Поэтому и перегружаю из PH. Если раз в день, то не напрягает, а вот каждые полчаса уже напряжно. Буду пробовать старые версии, но проблема в том, что специально не получается воспроизвести. Можно час сидеть за компьютером и всё в порядке, а можно подойти на пять минут и получить. 
https://drop.me/M78g7B - тут лог и отладочная. Лог сумбурный, пробовал поймать.

**Comment by BladeMight** [comment]
> не перегрузить

Вот это совершенно неожиданно, т.к. для этой гор. клавиши используется отдельный системный hook, видимо система блокирует и его, и мой hook. И еще: запускаешь от Админа?

P.S. В логе нашел ошибку, опять связанную с восстановлением текста буфера обмена, сейчас сделаю тестовую сборку с большим кол. попыток восстановления текста.

**Comment by MishGa** [comment]
Контроль отключён, запускаю из планировщика, с наивысшими правами.

**Comment by BladeMight** [comment]
Ок, готово добавил проверку какой процесс блокирует буф. обмена и блокирует ли, еще добавил поимку в лог ошибку без остановки основных hook'ов, проверь и пришли мне лог.
[Mahou.zip](https://github.com/BladeMight/Mahou/files/908288/Mahou.zip)

**Comment by MishGa** [comment]
Сейчас отключается только когда активно окно Firefox, не работает ни одна комбинация горячих клавиш. Если переключится в тектосвый редактор, то там всё работает. Помогает перезагрузка Mahou, но обе ошибки словил минут за пять.  
Пробовал только первую версию, вторую только завтра. Лог - https://drop.me/M5wKNo

**Comment by BladeMight** [comment]
@MishGa Странно в логе все чисто...

> Сейчас отключается только когда активно окно Firefox

Это говорит о том что у Firefox выше права чем у Mahou, и у Вас не отключен Контр. Уч. Запс. [как отключить](http://windowsten.ru/zachem-nuzhna-uac-w10-11848/#i-5)(В реестре).

**Comment by MishGa** [comment]
Я не уверен что для того чтоб заработало mahou надо отключать UAC ещё и в реестре, до обновления браузера и Mahou всё работало прекрасно. 
Вторая версия заглючила после первого нажатия и не работала уже везде. Опять пришлось перегружать через РН. 
https://drop.me/on6kvo

**Comment by BladeMight** [comment]
> Вторая версия заглючила после первого нажатия и не работала уже везде

Чудеса? В логе чисто, У меня нормально(Везде в том числе FF), а Вас глючит...

**Comment by Makishima** [comment]
Мне пока что помогло "Нажимать заново модификаторы после действия горячих клавиш." Наблюдаю дальше.

**Comment by Makishima** [comment]
Боюсь, что на день помогло, или проявилось не сразу. Перестало переключать везде. Вчера вечером все было ок, пришел на работу, опять не работает.                                   

https://pastebin.com/Sj1rtrZ0

**Comment by BladeMight** [comment]
@Makishima Это все из-за особенности прав доступа системы, т.к. в W10 система сама через некоторое время сбрасывает права доступа на  пользовательские, я проверял с Mahou, StrokesPlus, Autohokey - так же отключается через некоторое время, мне помогло [отключить Контроль Учетных Записей.](http://windowsten.ru/zachem-nuzhna-uac-w10-11848/#i-5)(В реестре.)(В Windows 10 ниже 1703 из-за его отключения не работали Метро приложения, но **в 1703 работают даже после его отключения**, так что терять нечего при его отключении) А в Windows 7 все работает без отключения(хотя здесь я тоже выключил контроль уч. зап.).

**Comment by Makishima** [comment]
@BladeMight Он был отключен и так, подтюнил через регистр, наблюдаю.

**Comment by BladeMight** [comment]
@Makishima Вот это:

![](http://fastvista.ru/pictures/screen/disable-uac-in-windows-8-menu.png)

поставить на самый низ **мало** для **полного отключения**.

**Comment by BladeMight** [comment]
Вероятно проблема была решена в Mahou-v2.3.0.0, подробнее здесь #82

**Comment by Makishima** [comment]
Обновлюсь, думаю, за неделю будет понятно, помогло или нет.

**Comment by Makishima** [comment]
Так вот :) Тогда - помогло, сейчас (неделю или полторы) сломалось опять. Помогает, зайти в программу, нажать Применить и Ок. Какой еще информацией можно помочь?

**Comment by BladeMight** [comment]
@Makishima Включите функцию перезапуск Hook'ов.

**Comment by BladeMight** [comment]
> Помогает, зайти в программу, нажать Применить и Ок.

Это говорит о том что hook'и умерли, а я в #102 добавил обязательный перезапуск hook'ов после сохранения настроек, так что решение - функция перезапуск hook'ов после действий любых горячих клавиш Mahou([подробнее на wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9F%D0%B5%D1%80%D0%B5%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D1%82%D1%8C-hook%D0%B8)).

**Comment by BladeMight** [comment]
Ну в основном Mahou отключался из-за того что hook'и умирали, а с релизом [Mahou-v2.4.0.0](https://github.com/BladeMight/Mahou/releases/tag/v2.4.0.0), их больше нет так что думаю можно закрывать.

P.S. **Если** у кого еще воспроизводится может опять открыть.
