### ISSUE TITLE
Пробел после слова

### ISSUE THREAD

**Issue by qfeuer** [BladeMight/Mahou#8]
Приветствую, спасибо большое за Ваш труд.
Можно ли добавить переключение последнего введённого слова, если после него был нажат пробел ?

Существует ли возможность объеденить переключение выделенного и переключение последнего слова под одну клавишу pause\break ?
edit: "brake" 0_0

**Comment by BladeMight** [comment]
>Можно ли добавить переключение последнего введённого слова, если после него был нажат пробел ?

Можно, пока что пользуйтесь `Ctrl+Shift+Стрелка влево` а потом клавишу переключения выделенного. 
Насколько сильно вам нужна такая функция? (1 до 10)

> Существует ли возможность объеденить переключение выделенного и переключение последнего слова под одну клавишу pause\brake ?

Просто устоновите желаемую клавишу на обе, и они будут работать :)

**Comment by qfeuer** [comment]
по переключению с введённым пробелом 6 из 10, это удобно, так как иногда я успеваю нажать пробел, и если его стереть - то затем функция не работает.

по назначению одной клавиши - это первое что я сделал, но в веб телеграмме на chrome это вызывает глюк и сохраняет страницу в избранные, позже я обнаружил глюк так же воспроизводим на обычных sticky notes в windows 10, нажание pause вызывает диалог закрытия вкладки.
![image](https://cloud.githubusercontent.com/assets/15046288/17733881/b8dd42c2-649a-11e6-8afe-5cf76515966e.png)

**Comment by BladeMight** [comment]
> по переключению с введённым пробелом 6 из 10, это удобно, так как иногда я успеваю нажать пробел, и если его стереть - то затем функция не работает.

После объяснений того как вы хотите чтобы она работала у меня появилась идея.

> по назначению одной клавиши - это первое что я сделал, но в веб телеграмме на chrome это вызывает глюк и сохраняет страницу в избранные, позже я обнаружил глюк так же воспроизводим на обычных sticky notes в windows 10, нажание pause вызывает диалог закрытия вкладки.

Проблема вызывается тем что они вызываются одновременно, а нужно по очереди
Как все сделаю напишу.

**Comment by BladeMight** [comment]
Проверьте [версию 1.0.8.8](https://github.com/BladeMight/Mahou/releases/tag/v1.0.8.8).

**Comment by qfeuer** [comment]
спасибо за оперативный ответ и добавление новой фичи 

новая опция  feature "" " ←"(eat one space for Convert Last word) работает в приложениях тесковых процессорах, но внутри sticky notes не отрабатывает, а курсор переходит на кнопку добавления нового notes и добавляет его. (приложение хорошо подходит для тестирования =))

сохранение опции "" " ←",  не пишется в ini файл и после перезагрузки опция отключается.

работа вызова convert last & convert selection теперь замечательно работают на одной кнопке.

**Comment by BladeMight** [comment]
Я посмотрел на код не нашел...
Ну это уже завтра...

**Comment by BladeMight** [comment]
Нашел таки, и приделал исправление для Sticky Notes. [Mahou-v1.0.8.9](https://github.com/BladeMight/Mahou/releases/tag/v1.0.8.9).

**Comment by qfeuer** [comment]
Невероятная работа, спасибо большое.
вопрос офф топик
А чем sticky отличается от других полей ввода, почему они потребовали отдельного вмешательства ?

**Comment by BladeMight** [comment]
> А чем sticky отличается от других полей ввода, 
Тем что при отпускании ALT в Sticky notes фокусом становиться [+],
> почему они потребовали отдельного вмешательства ?
Нет, последняя версия исправляет не Sticky, а все поля.

**Comment by BladeMight** [comment]
> А чем sticky отличается от других полей ввода, 

Тем что при отпускании ALT в Sticky notes фокусом становиться [+],

> почему они потребовали отдельного вмешательства ?

Нет, последняя версия исправляет не Sticky, а все поля.

P.S. Это в 1.0.8.9 был фикс только для Sticky который все портит.
