### ISSUE TITLE
Возможность уставновить Shift+Caps на определенную раскладку

### ISSUE THREAD

**Issue by Ygarr** [BladeMight/Mahou#83]
## Problem/Request description

Реализовать возможность для двойной клавиши.
Возможность уставновить Shift+Caps на определенную раскладку

## System information
Версия: Windows 8.1(и скорее всего остальные)

**Comment by BladeMight** [comment]
Добавлю.

**Comment by BladeMight** [comment]
Готово, вот [Mahou v2.1.2.3](https://github.com/BladeMight/Mahou/releases/tag/v2.1.2.3).
