### ISSUE TITLE
Mahou + Firefox + (Win + P) = баг.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#84]
Запускаем Firefox и Mahou. Делаем активным десктоп, держим кнопку Win, жмём P - режимы экрана переключаются циклично, как должны.
Фокусируем браузер - держим Win, жмём P - окошко режимов экрана появляется на долю секунды и исчезает, режим не меняется. 
Выключаем Mahou, фокусим Firefox - режимы меняются как нужно.
Что интересно - не включен ни один хоткей с кнопкой Win в Mahou, чего он с ней конфликтует?

![mahou_firefox_screen_switch](https://cloud.githubusercontent.com/assets/21346282/25865273/109756ac-34fb-11e7-9366-076035465c4b.gif)

**Comment by BladeMight** [comment]
Из-за функции индикатора Scroll Lock.

9 мая 2017 г., 21:07 пользователь Trost123 <notifications@github.com>
написал:

**Comment by Trost123** [comment]
Ага. Отключил, всё норм.
