### ISSUE TITLE
Switching after word+space

### ISSUE THREAD

**Issue by Track77** [BladeMight/Mahou#85]
## Problem/Request description

Hi.
Switching for last word doesn't work if i type the space after.

## Expected behavior (Only if reporting bug)

Write here what did you expected to happen?

## System information

- Windows version: 10
- Windows architecture: x64
- .Net version: 4.0
- Mahou version: 2.1.2.3

Or you can Paste here debug info from Mahou (version >1.4.4.1):

1. Go to Mahou main window (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>I</kbd> or in *tray icon's* menu select settings).
2. Press on [...] button to go to *More configs* window.
3. Click twice on [More] button to go to page 3 in *More configs* window.
4. Click on **Debug Info** button this will copy debug info to your clipboard.
5. Paste it here.

## Attach logs (if logging were enabled)

Attach log from the day when problem happened from **Logs** folder.

**Comment by BladeMight** [comment]
I answered that question already a dozen times(via email & here on GitHub), before asking you could go to [WIKI](https://github.com/BladeMight/Mahou/wiki/Functions-List#add-one-space-to-last-word)([ru](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%94%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D1%8F%D1%82%D1%8C-1-%D0%BF%D1%80%D0%BE%D0%B1%D0%B5%D0%BB-%D0%B2-%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B5%D0%B5-%D1%81%D0%BB%D0%BE%D0%B2%D0%BE)) and see the full list of functions.
Closed as duplicate.

Thanks for interest to Mahou.
Happy converting.
