### ISSUE TITLE
Hotkeys working in Foobar instdead Mahou

### ISSUE THREAD

**Issue by ToyvoGlumov** [BladeMight/Mahou#88]
## Problem/Request description

When Foobar2000 launched and i trying to change text by "pause" button, nothing changes with text but foobar toggle to next track. Also there is no such global hotckey in Foobar as "Pause"

## System information
Windows 10, Foobar2000 1.3.9

**Comment by BladeMight** [comment]
> Also there is no such global hotckey 

@ToyvoGlumov And which are set? 

Mahou version? Enable logging in Mahou and give log.

**Comment by ToyvoGlumov** [comment]
М. последняя версия. и для последнего слова и для выделенного текста назначена клавиша Pause
В фубаре назначены след. клавиши:
![2017-05-29_164710](https://cloud.githubusercontent.com/assets/29034681/26548737/131f1b14-448f-11e7-87c7-b2ebeed56e98.png)
Если фубар выключен то перключалка норм работает.
Как включить лог?

**Comment by BladeMight** [comment]
>  ![image](https://cloud.githubusercontent.com/assets/11931888/26548848/c9bbd45e-447e-11e7-89b2-a05bfd86f371.png)

Ага вот оно `Ctrl + Insert` эта клавиша используется Windows для взятия копии выделенного текста (альтернатива Ctrl+C) в этом и вся проблема.

**Comment by ToyvoGlumov** [comment]
Спасибо, действительно, переназначил next и prev клавиши, все норм теперь. А как кнопка паузы связавна с с инсертом? Пунто было пофиг, например.

**Comment by BladeMight** [comment]
@ToyvoGlumov 

> А как кнопка паузы связавна с с инсертом? Пунто было пофиг, например.

Видимо у вас кнопка паузы настроена на Конвертацию выделения, что вызывает Ctrl+Insert для взятия выделенного текста.

P.S. Насчет `Ctrl+Insert` [вот](https://ru.wikipedia.org/wiki/Insert_(%D0%BA%D0%BB%D0%B0%D0%B2%D0%B8%D1%88%D0%B0)) здесь пишут 
`Сочетание клавиш Ctrl+Insert аналогично команде «копировать», ⇧ Shift+Insert аналогично команде «вставить». Эти сочетания работают даже там, где не действует Ctrl+C`. 
Так что думаю использовать Ctrl+Insert не стоит для горячих клавиш.

**Comment by ToyvoGlumov** [comment]
Ок, буду перевыкать к другим, спасибо!

**Comment by BladeMight** [comment]
@ToyvoGlumov Всегда пожалуйста, если что обращайтесь.
