### ISSUE TITLE
После последнего обновления не срабатывает double shift.

### ISSUE THREAD

**Issue by Trost123** [BladeMight/Mahou#89]
![screenshot_1](https://cloud.githubusercontent.com/assets/21346282/26576848/0d0c6fb6-4533-11e7-99ef-4f8e1e593f9c.png)
Не работает. Предположительно последние пару обновлений сломали.

Двойной insert срабатывает адекватно.
Если переназначить на что-то в стиле "двойной shift+Q" срабатывает.
А вот просто shift-shift перестал работать....

**Comment by BladeMight** [comment]
[Почитайте](https://github.com/BladeMight/Mahou/issues/82#issuecomment-304783015).

**Comment by BladeMight** [comment]
Теперь, вижу, сейчас посмотрю почему...

**Comment by BladeMight** [comment]
@Trost123 Все, [исправил](https://github.com/BladeMight/Mahou/commit/dcb48835b55a8269cef4881710d504f1115f0943), сборка dev на [AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou), или вот:
[Mahou+DoubleHK-Fix.gz](https://github.com/BladeMight/Mahou/files/1037868/Mahou.DoubleHK-Fix.gz)

**Comment by Trost123** [comment]
thx.

**Comment by BladeMight** [comment]
@Trost123 [Релиз 2.3.0.7](https://github.com/BladeMight/Mahou/releases/tag/v2.3.0.7).
