### ISSUE TITLE
Skype Capsbug

### ISSUE THREAD

**Issue by qfeuer** [BladeMight/Mahou#9]
Приветствую,

при попытке переключения раскладки в skype 7.26 на windows 10 - skype софт зависает и его можно только терминировать, так же наблюдается полный фриз скайпа если сделать double конверт написанного слова.

UPD: иногда скайп впадает в фриз после первого нажания pause. 

опция CS-switch после нажания apply остаётся включенной.

**Comment by BladeMight** [comment]
В Microsoft Edge так же? 
Просто интернет у меня медленный(4Кб/с) чтобы скачать скайп понадобится много времени, и к тому же не по-используешь.
И в версиях [1.0](https://github.com/BladeMight/Mahou/releases/tag/v1.0), [1.0.3.6](https://github.com/BladeMight/Mahou/releases/tag/v1.0.3.6) и [1.0.4.0](https://github.com/BladeMight/Mahou/releases/tag/v1.0.4.0) так же?(напишите про каждую отдельно, если в Edge так же как и в Skype то напишите как в Edge)
Попробуйте горячии клавиши отдельно и тоже напишите.

>опция CS-switch после нажания apply остаётся включенной.

Разберемся )

P.S. Наверно уже завтра... 😷 💤

**Comment by qfeuer** [comment]
Приятных сновидений.

lets go:

v1.0 (change selection & change last word)
скайп фризится, edge работает

v1.0.3.6 (change selection)
скайп фризится, edge работает

v1.0.3.6(change last word)
скайп фризится, едже работает, но есть существенный лаг в работе и баг первого символа

v1.0.4.0 (change selection & change last word)
скайп фризится
egde работает, но при конвертации последнего слова переводит раскладку 1 раз, потом алгоритм отрабатывает что-то, но конвертации не происходит.

v1.0.9.0 (change selection & change last word)
edge - работает last word, Не работает convert selection

v1.0.9.0
word - не всегда срабатывает конверт, как last word так и convert selection,

v1.0.9.0
опция с добавленным пробела после слова срабатывает не всегда, не удалось установить алгоритм повторения бага, возможно имеет смысл пробелы добавить в алгоритм конвертирования, тогда он будет работать даже с двумя-тремя пробелами, и нет ошибок с использованием backspace.

**Comment by BladeMight** [comment]
> опция CS-switch после нажания apply остаётся включенной.

> опция с добавленным пробела после слова срабатывает не всегда,

В [Mahou v1.0.9.2](https://github.com/BladeMight/Mahou/releases/tag/v1.0.9.2) исправлено.

> edge - работает last word, Не работает convert selection

Думаю Edge зависает если использовать доступ к Буфферу обмена.

> скайп фризится
видимо из-за `WM_INPUTLANGCHANGEREQUEST` что из Win32API, попробуйте с "Use Alt+Shift in CM" и "Enable Cycle Mode" включенными.

> v1.0 (change selection & change last word)
скайп фризится, edge работает

В 1.0 и "Convert Selection" и "Convert Last Word" работают в Edge???( у меня Convert Selection не работает)

**Comment by qfeuer** [comment]
Доброго времени суток,
v1.0.9.2
[+] CS-Switch - теперь сохраняется 
[+] проблема с пробелом ушла, теперь переводит нормально
[-] скайп по прежнему зависает при любом виде опций, CS switch, Use Alt+Shift, если при них включить enable Cycle mode - то слово стирается, и перенабирается во введённой раскладке (судя по анимации скайпа), а конвертация выделенной части не происходит вовсе
[-] внутри процессора word перевод выделенного происходит только после нескольких нажатий конвертации, и только с включенной опцией "re-select", без неё конвертации не происходит.
[-]при следующих настройках (картинка)
![image](https://cloud.githubusercontent.com/assets/15046288/17797282/831e3b5a-65e9-11e6-9020-05b4bdcdd0a9.png)
конвертация не происходит, происходит перенабор в уже набранной раскладе. если cycle mode убрать - то работает.

**Comment by BladeMight** [comment]
> [-] скайп по прежнему зависает при любом виде опций, CS switch, Use Alt+Shift, если при них включить enable Cycle mode - то слово стирается, и перенабирается во введённой раскладке (судя по анимации скайпа), а конвертация выделенной части не происходит вовсе

Да уж.

[-] внутри процессора word перевод выделенного происходит только после нескольких нажатий конвертации, и только с включенной опцией "re-select", без неё конвертации не происходит.

В WordPad'е так же? (У меня нормально работает)

> [-]при следующих настройках (картинка)
[!](https://cloud.githubusercontent.com/assets/15046288/17797282/831e3b5a-65e9-11e6-9020-05b4bdcdd0a9.png)
конвертация не происходит, происходит перенабор в уже набранной раскладе. если cycle mode убрать - то работает.

Странно у меня работает нормально. А только с "Use Alt+Shift in CM" выключенной так же?

**Comment by qfeuer** [comment]
| Странно у меня работает нормально. А только с "Use Alt+Shift in CM" выключенной так же?
без неё всё работает.

| WordPad
при включенных cycle mode и Use Alt+Shift in CM - wordpad так же рисует анимацию перепечатывания, но слово не меняется после конвертации.

| Как именно
Выделение снимается, если стоит опция снимать выделение, но при это самой конвертации не происходит, наблюдается анимация перепечатывания, если опцию с выделением оставить, конвертации так же не происходит, но есть анимация перепечатывания.
Тем не менее если остаться упёртым перевод раскладки переходит после 3-4 быстрых нажатий кавиши конвертации. если нажимать медленно (1 сек) то конвертации не происходит.

Если включена Use Alt+Shift in CM - то конвертации не происходит нигде, при работающем cycle mode, соответственно если отключить любую из опций конвертация работает.

**Comment by BladeMight** [comment]
> перенабирается во введённой раскладке

А включена ли у вас переключение раскладки по `Alt + Shift` в "Панель управления\Часы, язык и регион\Язык\Дополнительные параметры" → "Переключение методов ввода" → "Изменить сочетания клавиш языковой панели"?

**Comment by BladeMight** [comment]
> Если включена Use Alt+Shift in CM - то конвертации не происходит нигде

Попробуй [новую версию](https://github.com/BladeMight/Mahou/releases/tag/v1.0.9.6).

**Comment by qfeuer** [comment]
Привет,
в новой версии работает функция как часы, скайп пока не могу проверить, но Emu работает отлично и в ворде глюка больше нет. есть один момент, в рамках заметки на полях - в emu type добавить shift+ctrl, так как вин+спейс работает только на вин10, а у более ранних версий винды может возникнуть проблема из-за того, что переключение стоит на shift+ctrl, как раз так было у меня и поэтому shift+alt не срабатывал

**Comment by BladeMight** [comment]
:sleepy: Только недавно проснулся...

>  в emu type добавить shift+ctrl

[Вот](https://github.com/BladeMight/Mahou/releases/tag/v1.0.9.7), добавил.
P.S. Если в скайпе работает, то нажимай "Close Issue" или "Close and comment"(здесь).
P.S.S. У меня сегодня вырубят интернет в 24:00 так что до того времени смогу ответить, а потом уже...

**Comment by qfeuer** [comment]
Доброго дня, отличная работа, скайп с emu работает. в начале он не конвертил, а просто отображал анимацию перепечатывания с emu win+space, но потом начал конвертить и глюк повторить не удалось. закрываю issue.
Огромное спасибо, что Вы с нами!
