### ISSUE TITLE
Flags next to the cursor

### ISSUE THREAD

**Issue by AndreWin** [BladeMight/Mahou#90]
Hello!

I'd like to see flags next to cursor as it's realized in [aml maple](http://www.amlpages.com/Rus/amlmaple.htm).
This app shows flags next to text cursor and color text for pointer cursor.
I like this and I'd like to see the same in Mahou.

Best regards, Andrey.

**Comment by BladeMight** [comment]
> This app shows flags next to text cursor 

No, it is replacing your mouse's cursor image with cursor image with a flag on side with it.

> I like this and I'd like to see the same in Mahou.

I'll see what I can do.

**Comment by BladeMight** [comment]
@AndreWin Done, check it out in [Mahou v2.3.0.9](https://github.com/BladeMight/Mahou/releases/tag/v2.3.0.9).

**Comment by AndreWin** [comment]
Nice! It took me some time to find this option but it works now!)
The only moment is that flag doesn't move a little slow. So sometime it farther to cursor, sometime closer to one. Why not just change cursor image like it was done in aml maple?

Best regards, Andrey.

**Comment by AndreWin** [comment]
I don't know if it's possible in mahou, but I think that there is should be option to always show flags, not only for text fields.
For example I type some text in brower, but my cursor isn't above text field because it will meddle to me. But at this case I will not see flag on cursor, so I willn't know in what lang I type text.

**Comment by BladeMight** [comment]
> Why not just change cursor image like it was done in aml maple?

Some may not like this behaviour because of custom cursor images.

> I don't know if it's possible in mahou, but I think that there is should be option to always show flags, not only for text fields.

Yes it is possible, I'll make it possible to select in next release.(after I done with  #91 and #92)

**Comment by BladeMight** [comment]
> Yes it is possible, I'll make it possible to select in next release.(after I done with #91 and #92)

Done, check it out in [Mahou v2.3.1.3](https://github.com/BladeMight/Mahou/releases/tag/v2.3.1.3).

**Comment by AndreWin** [comment]
O_o
Cool! Really nice! :)
Now I no longer need aml maple!
Thank you very much!

**Comment by BladeMight** [comment]
@AndreWin Glad you like it :), feel free to suggest any other features.
