### ISSUE TITLE
Единая раскладка для всех приложений

### ISSUE THREAD

**Issue by grengray** [BladeMight/Mahou#91]
Пожалуйста, добавьте единую раскладку для всех приложений. Я переключил на английский я знаю, что у меня язык английский... а не как по умолчанию в Windows для каждого окна своя раскладка.

С уважением.

**Comment by BladeMight** [comment]
> Пожалуйста, добавьте единую раскладку для всех приложений

@grengray Ну в принципе можно хранить раскладку в Mahou и переключать для каждого окна на нее, если она отличается, но это можно будет сделать либо с таймерами либо более сложный вариант с глобальным прослушиванием сообщений окон Windows, который будет следить за переключением окон.

> а не как по умолчанию в Windows для каждого окна своя раскладка

Кстати начиная с Windows 8, в Windows по умолчанию стоит единая раскладка для всех приложений. Настройка подробно описана [здесь](http://osmaster.org.ua/?p=5975).

**Comment by grengray** [comment]
@BladeMight спасибо за ответ!

> глобальным прослушиванием сообщений окон Windows, который будет следить за переключением окон.
Если Вам не очень сложно, допилите, пожалуйста, только ради этой функции держу Пунто, который уже далеко не торт...
>Кстати начиная с Windows 8, в Windows по умолчанию стоит единая раскладка для всех приложений. 
Да, но поддержка Win7 будет до 2022 года и пока нет возможности отказаться от неё, хотя это свойство сильно вымораживает нервы.

**Comment by BladeMight** [comment]
> Если Вам не очень сложно, допилите, пожалуйста

Да, сейчас как раз думаю над этим, после добавление функции #90 буду делать прототип, если хочешь могу потом дать потестить.

**Comment by BladeMight** [comment]
Готово, вот [Mahou v2.3.1.3](https://github.com/BladeMight/Mahou/releases/tag/v2.3.1.3).(галочка во вкладке Раскладки)

**Comment by BladeMight** [comment]
@grengray А еще лучше [Mahou v2.3.1.4](https://github.com/BladeMight/Mahou/releases/tag/v2.3.1.4).

**Comment by grengray** [comment]
@BladeMight спасибо огромное!!!!
Просто слёзы на глаза... это не реально удобно и быстро!
Прошу прощения за офтом, но где из #90 галочка, чтобы был флаг рядом с курсором?

**Comment by BladeMight** [comment]
> рошу прощения за офтом, но где из #90 галочка, чтобы был флаг рядом с курсором?

@grengray Да, у меня все спрятано! :) Вот скрин:
![2017-06-20 06-44-33-selection](https://user-images.githubusercontent.com/11931888/27342368-aa393a88-55e8-11e7-8b04-cce7980ae0e9.Jpeg)
Думаю стоит обновить [wiki](https://github.com/BladeMight/Mahou/wiki) чтобы все могли узнать где что находиться.

>  спасибо огромное!!!!

Всегда пожалуйста, обращайтесь если что.

**Comment by BladeMight** [comment]
А насчет 

> Win Word 2010 - пропадает подсказка рядом с курсором

Перезапустите Mahou и Word.

**Comment by BladeMight** [comment]
> Думаю стоит обновить wiki

Обновил, почитайте.

**Comment by grengray** [comment]
>Перезапустите Mahou и Word.
Сработало.
Воркараунд :) 
Если кто-то будет это читать, то программу желательно запускать из Program Files (x86), проверить разрешение на запись (ПКМ - Свойства), добавить в "Доверенные" Kaspersky.

**Comment by BladeMight** [comment]
@grengray Ну это все система безопасности Windows...

**Comment by grengray** [comment]
@BladeMight да, я тоже так думаю...
У меня почему-то остались и текстовые подсказки Ru En и флаги. Как можно текст убрать, он флаг закрывает сильно.

**Comment by BladeMight** [comment]
> У меня почему-то остались и текстовые подсказки Ru En и флаги.

Можно скрин?

**Comment by grengray** [comment]
Готово!
http://dropmefiles.com/Hldid

**Comment by grengray** [comment]
Если есть необходимость подружить Mahou с консолью, то необходимо использовать бесплатную надстройку ConEmu. Там всё нормально переключает.

**Comment by BladeMight** [comment]
> подружить Mahou с консолью

Да, я уже знаю, у меня на wiki есть [страничка](https://github.com/BladeMight/Mahou/wiki/%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D0%B2-%D0%BD%D0%B5%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D1%85-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0%D1%85%3F) про совместимость и настройки для определенных программ.

По поводу скрина - так быть не должно, если используете не последнюю попробуйте ее, если и там будет так же, то попробуйте установить ширину и высоту подсказки на 0 и включите флаги(если не включено).

**Comment by grengray** [comment]
Спасибо! А то я велосипед изобретаю :(
Флаги, как оказалось, алгоритм такой. Рестарт программы - Снимаем все галочки - Выбираем "возле мыши", показывать флаги - Ставим галочку "... рядом с мышью". Повторяем тоже для курсора.

**Comment by grengray** [comment]
Ещё проще - отключить настройку "прозрачный цвет", тогда всё работает сразу.

**Comment by BladeMight** [comment]
@grengray Ясно, спасибо за находку сейчас исправлю.

**Comment by grengray** [comment]
Ещё одна находка:
![2017-06-20_23-17-01](https://user-images.githubusercontent.com/26556246/27354009-c7698560-560e-11e7-8098-908c8225fa60.png)

**Comment by BladeMight** [comment]
Вот здесь уже нет текста, даже если выбран прозр. фон: [Mahou.exe.gz](https://github.com/BladeMight/Mahou/files/1089579/Mahou.exe.gz)

> Ещё одна находка:

Может добавить скрытие подсказки каретки при прокрутке колесиком мыши? Другой способ будет гораздо сложнее т.к. придется считать на сколько пикселей изменяет прокрут и т.д. короче сложный способ.

А еще по поводу смены раскладки в консоли cmd.exe, посмотрите #76, или воспользуйтесь `getconkbl.dll, который позволяет получить правильную раскладку в консольных приложениях. ТОЛЬКО x86 версии обоих(Mahou и getconkbl.dll) поддерживаются. (вы можете взять dll отсюда, поставьте ее в папку где находится Mahou.exe, возможно потребуется перезапуск Mahou)`

**Comment by grengray** [comment]
> Может добавить скрытие подсказки каретки при прокрутке колесиком мыши?
Фишка в том, что он только в Firefox так едет, а в Word'е норм. Тогда лучше пусть так будет или потом со временем добавите более изысканный способ.

**Comment by BladeMight** [comment]
@grengray Ну это из-за не очень хорошей совместимости firefox c функцией WinAPI которая получает позицию каретки, тут уж ничего не поделаешь...

**Comment by grengray** [comment]
Тогда, наверное, лучше всё оставить "как есть".

**Comment by grengray** [comment]
@BladeMight спасибо за наводку, про консоль!

**Comment by grengray** [comment]
Супер! То, что нужно!

**Comment by BladeMight** [comment]
Сейчас сделаю новый релиз.

**Comment by BladeMight** [comment]
> Сейчас сделаю новый релиз.

Готово, вот [Mahou v2.3.1.7](https://github.com/BladeMight/Mahou/releases/tag/v2.3.1.7)
