### ISSUE TITLE
Падает после включения флагов рядом с мышью

### ISSUE THREAD

**Issue by TaciturnShadow** [BladeMight/Mahou#92]
## Проблема/описание запроса

Mahou достаточно быстро падает после включения отображения флагов рядом с мышью.
В данном случае читал Хабр в Firefox'е, особо ничего не нажимал, в основном делал всё мышью.

## Информация окружения/Отладочная информация

<details><summary>MAHOU DEBUG INFO</summary>

<details><summary>Environment info</summary>

- Mahou 2.3.0.9
- OS = [Microsoft Windows NT 6.1.7601 Service Pack 1]
- x64 = [True]
- .Net = [4.0.30319.42000]
</details>
<details><summary>All installed layouts</summary>

США(67699721)
Русская(68748313)

</details><details><summary>Mahou.ini</summary>

```ini
!Unicode(✔), Mahou settings file
[FirstStart]
First=False
[Functions]
TrayIconVisible=True
ConvertSelectionLayoutSwitching=True
ReSelect=True
RePress=True
AddOneSpaceToLastWord=False
ConvertSelectionLayoutSwitchingPlus=False
ScrollTip=False
StartupUpdatesCheck=False
Logging=False
CapsLockTimer=False
TrayFlags=True
BlockMahouHotkeysWithCtrl=False
SymbolIgnoreModeEnabled=false
MCDServerSupport=False
OneLayoutWholeWord=True
RestartHooksOnHotkeyActionEnd=True
[Layouts]
SwitchBetweenLayouts=True
EmulateLayoutSwitch=False
EmulateLayoutSwitchType=Alt+Shift
ChangeToSpecificLayoutByKey=True
MainLayout1=США(67699721)
MainLayout2=Русская(68748313)
SpecificKey1=1
SpecificKey2=0
SpecificKey3=0
SpecificKey4=0
SpecificLayout1=Переключать между раскладками
SpecificLayout2=
SpecificLayout3=
SpecificLayout4=
[Appearence]
DisplayLangTooltipForMouse=False
DisplayLangTooltipForMouseOnChange=False
DisplayLangTooltipForCaret=False
DisplayLangTooltipForCaretOnChange=False
DifferentColorsForLayouts=False
Language=Русский
Layout1ForeColor=#000000
Layout1BackColor=#FFFFFF
Layout1TransparentBackColor=False
Layout1Font=Microsoft Sans Serif, 8.25pt
Layout1Height=14
Layout1Width=26
Layout1PositionX=8
Layout1PositionY=0
Layout2ForeColor=#000000
Layout2BackColor=#FFFFFF
Layout2TransparentBackColor=False
Layout2Font=Microsoft Sans Serif, 8.25pt
Layout2Height=14
Layout2Width=26
Layout2PositionX=8
Layout2PositionY=0
MouseLTForeColor=#000000
MouseLTBackColor=#FFFFFF
MouseLTTransparentBackColor=False
MouseLTFont=Microsoft Sans Serif, 8.25pt
MouseLTHeight=14
MouseLTWidth=26
MouseLTPositionX=8
MouseLTPositionY=0
CaretLTForeColor=#000000
CaretLTBackColor=#FFFFFF
CaretLTTransparentBackColor=False
CaretLTFont=Microsoft Sans Serif, 8.25pt
CaretLTHeight=14
CaretLTWidth=26
CaretLTPositionX=8
CaretLTPositionY=12
MCDS_Pos_X=58
MCDS_Pos_Y=13
MCDS_Top=60
MCDS_Bottom=45
Layout1LTText=
Layout2LTText=
MouseLTUseFlags=True
CaretLTUseFlags=False
[Timings]
LangTooltipForMouseRefreshRate=25
LangTooltipForCaretRefreshRate=25
DoubleHotkey2ndPressWait=50
FlagsInTrayRefreshRate=100
ScrollLockStateRefreshRate=100
CapsLockDisableRefreshRate=100
SelectedTextGetMoreTries=False
SelectedTextGetMoreTriesCount=5
ExcludedPrograms=LA.exe SomeProg.exe
[Snippets]
SnippetsEnabled=False
[Hotkeys]
ToggleMainWindow_Enabled=False
ToggleMainWindow_Double=False
ToggleMainWindow_Modifiers=Win + Control + Shift + Alt
ToggleMainWindow_Key=45
ConvertLastWord_Enabled=False
ConvertLastWord_Double=False
ConvertLastWord_Modifiers=
ConvertLastWord_Key=19
ConvertSelectedText_Enabled=False
ConvertSelectedText_Double=False
ConvertSelectedText_Modifiers=
ConvertSelectedText_Key=145
ConvertLastLine_Enabled=False
ConvertLastLine_Double=False
ConvertLastLine_Modifiers=Shift
ConvertLastLine_Key=19
ConvertLastWords_Enabled=False
ConvertLastWords_Double=False
ConvertLastWords_Modifiers=Shift
ConvertLastWords_Key=122
ToggleSymbolIgnoreMode_Enabled=False
ToggleSymbolIgnoreMode_Double=False
ToggleSymbolIgnoreMode_Modifiers=Shift + Control
ToggleSymbolIgnoreMode_Key=122
SelectedTextToTitleCase_Enabled=False
SelectedTextToTitleCase_Double=True
SelectedTextToTitleCase_Modifiers=Shift
SelectedTextToTitleCase_Key=16
SelectedTextToRandomCase_Enabled=False
SelectedTextToRandomCase_Double=True
SelectedTextToRandomCase_Modifiers=Shift
SelectedTextToRandomCase_Key=17
SelectedTextToSwapCase_Enabled=False
SelectedTextToSwapCase_Double=False
SelectedTextToSwapCase_Modifiers=Win + 
SelectedTextToSwapCase_Key=19
SelectedTextTransliteration_Enabled=False
SelectedTextTransliteration_Double=False
SelectedTextTransliteration_Modifiers=Win + 
SelectedTextTransliteration_Key=191
ExitMahou_Enabled=False
ExitMahou_Double=False
ExitMahou_Modifiers=Win + Control + Shift + Alt
ExitMahou_Key=123
RestartMahou_Enabled=False
RestartMahou_Modifiers=Win + Shift + Alt
RestartMahou_Key=33
```
</details>
</details>
</details>

## Приложите журналы (logs) (если логирование было включено)
[2017.06.19.log.txt](https://github.com/BladeMight/Mahou/files/1086255/2017.06.19.log.txt)

**Comment by BladeMight** [comment]
> Mahou достаточно быстро падает после включения отображения флагов рядом с мышью.

> 2017.06.19.log.txt

В логе видно, что меняется изображение флага слишком быстро, чего в принципе быть не должно т.к. используется метод смены изображения только если раскладка отличается от предыдущей(50 мс раннее по умолчанию, интервал можно изменять во вкладке тайминги). Сейчас посмотрю поподробнее, и попробую исправить.

**Comment by TaciturnShadow** [comment]
Может дело в том что я наводил мышь на текстовое поле и убирал из него. На том же Хабре текстовым полем считается весь текст статьи и комментарии.

**Comment by BladeMight** [comment]
@TaciturnShadow Не я уже нашел в чем причина(таки менялась слишком быстро но не в подсказке, а в трее), вот попробуй эту сборку: [Mahou.exe.gz](https://github.com/BladeMight/Mahou/files/1086329/Mahou.exe.gz)

**Comment by TaciturnShadow** [comment]
На первый взгляд нормально, но тут лучше хотя бы сутки попользоваться, для надёжности.

**Comment by BladeMight** [comment]
@TaciturnShadow Ну думаю все будет нормально, т.к. ошибка именно в скорости смены иконки в трее, теперь я добавил правило чтобы меняло только если раскладка изменилась(в ранней версии так и было, только пришлось метод получения иконки переписывать, поэтому и не заметил как поставил чтобы менялась в любом случае).

**Comment by TaciturnShadow** [comment]
Прочитал этот комментарий и через несколько секунд Mahou упала. Включил лог обратно, буду ждать.

**Comment by TaciturnShadow** [comment]
Лог готов.
[2017.06.20.log.txt](https://github.com/BladeMight/Mahou/files/1086370/2017.06.20.log.txt)

**Comment by BladeMight** [comment]
@TaciturnShadow Та же ошибка с изображениями, видимо где-то еще меняет, буду смотреть...

**Comment by BladeMight** [comment]
@TaciturnShadow Нашел причину, в том же месте... фикс который я сделал работал не полностью(а точнее только 1 раз) т.к. переменная отвечающая за то "сменилась ли раскладка" менялась на true, в первый раз и потом так и оставалась true, добавил смену на false из правила проверки изменения раскладки.(что-то сегодня я не очень внимательно кодю... :memo:), вот сборка: [Mahou.exe.gz](https://github.com/BladeMight/Mahou/files/1086387/Mahou.exe.gz)

**Comment by TaciturnShadow** [comment]
Скачал, тестирую.

**Comment by BladeMight** [comment]
@TaciturnShadow ОК, вот релиз [Mahou v2.3.1.3](https://github.com/BladeMight/Mahou/releases/tag/v2.3.1.3).

**Comment by TaciturnShadow** [comment]
Со стабильностью вроде всё Ok. Вот только флаги в трее перестали работать совсем - постоянно значок бабочки.

**Comment by BladeMight** [comment]
> Вот только флаги в трее перестали работать совсем - постоянно значок бабочки.

@TaciturnShadow Ну это из-за необычного правила совместимости функции флагов в подсказке и в трее, [здесь](https://github.com/BladeMight/Mahou/commit/a289268fbbcb164a50bc63268812433dfdd84c25) уже исправил, сборку можешь взять от [автосборщика AppVeyor](https://ci.appveyor.com/project/BladeMight/mahou/build/job/9hu9d22qshwci214/artifacts).

**Comment by BladeMight** [comment]
@TaciturnShadow Обновил релиз [Mahou v2.3.1.4](https://github.com/BladeMight/Mahou/releases/tag/v2.3.1.4), по последнему коммиту(с фиксом совместимости флагов поск. и трея)

**Comment by TaciturnShadow** [comment]
Спасибо.
