### ISSUE TITLE
Плавающая панель

### ISSUE THREAD

**Issue by grengray** [BladeMight/Mahou#93]
Можно ли добавить такую панельку, которая была бы по верх всех окон?
![panel](https://user-images.githubusercontent.com/26556246/27354430-36596156-5610-11e7-8d02-69a31316149b.png)

**Comment by BladeMight** [comment]
@grengray Можно, но это уже позже. Как я понял нужно:

1. Прозрачность
2. Флаг
3. Название раскладки
4. Круглые углы?(не думаю не стоит)
5. Цвет фона/текста
6. Рамка, и ее цвет
7. Шрифт

Так?

**Comment by grengray** [comment]
Просто я печатаю очень быстро и хочется одним взглядом понять - какой язык.
Прозрачность, мне кажется, не нужна, как и круглые углы. Остальное прямо идеальный вариант. Ещё наверное горячая клавиша, чтобы быстренько скрыть показать, если панель что-то важно заслонила вдруг.

**Comment by BladeMight** [comment]
@grengray Понятно, добавлю и гор. клавишу и прозрачность. Я тут подумал а может добавить возможность ее показа при удерживании какой-то клавиши(типа Shift или Ctrl)?

**Comment by grengray** [comment]
>может добавить возможность ее показа при удерживании какой-то клавиши(типа Shift или Ctrl)?
Да, замечательная идея, только просьба не делать это основным способом, а доп. фишкой.

**Comment by BladeMight** [comment]
@grengray ОК.

**Comment by grengray** [comment]
Кстати! А что если при нажатии определённой клавиши переключается язык или регистр пока клавиша нажата? То есть зажали Shift или Alt и набрали символ или парочку из другой раскладки.

P.S.
А как включить капс, если на него назначено переключение языков?

**Comment by grengray** [comment]
И если капс уже занят, то почему бы его не использовать как сигнал для языка? То есть - горит, русский, потух - английский. Как Вам идея?

**Comment by BladeMight** [comment]
> А как включить капс, если на него назначено переключение языков?
Shift+CAPS

> И если капс уже занят, то почему бы его не использовать как сигнал для языка? То есть - горит, русский, потух - английский. Как Вам идея?

Уже есть что-то подобное, но только для вида. [wiki](https://github.com/BladeMight/Mahou/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B9#%D0%9F%D0%BE%D0%B4%D1%81%D0%B2%D0%B5%D1%87%D0%B8%D0%B2%D0%B0%D1%82%D1%8C-scroll-lock-%D0%BA%D0%BE%D0%B3%D0%B4%D0%B0-%D1%80%D0%B0%D1%81%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0-1-%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%BD%D0%B0)

> почему бы его не использовать как сигнал для языка?

Потому что он меняет регистр...

>  что если при нажатии определённой клавиши переключается язык или регистр пока клавиша нажата? То есть зажали Shift или Alt и набрали символ или парочку из другой раскладки.

По поводу регистра Shift+Caps, а вот по поводу раскладки думаю неплохо.

**Comment by grengray** [comment]
У меня Shift+CAPS не работает - нажимаю, а печатаются обычные символы.
>Потому что он меняет регистр...

А лампочку отдельно зажечь нельзя?

> поводу раскладки думаю неплохо

Спасибо!

**Comment by BladeMight** [comment]
> А лампочку отдельно зажечь нельзя?

На Windows - к сожалению нет...

> У меня Shift+CAPS не работает 

**Выключите** таймер выключатель CapsLock.

**Comment by grengray** [comment]
> Выключите таймер выключатель CapsLock.

Вкладка "Функции" (справа; если кому-то будет нужно).

>На Windows - к сожалению нет...

пичалька :(

**Comment by grengray** [comment]
@BladeMight сделайте, пожалуйста, какую-нибудь панельку-форму со свойством поверх всех окон. Самую - самую простую, пожалуйста. Тогда можно будет полностью отказаться от 3 (!) программ.

**Comment by BladeMight** [comment]
@grengray Сделаю, только вот закончу с мелочами (#94 и #95).

**Comment by grengray** [comment]
@BladeMight Есть подозрение, что в #95 нужно просто дот_нет обновить. У меня 4.7 даже намёка не было. Только если товарищ пытается запускать всё это дело на x64 из Program Files, нужно из Program Files (x86).

**Comment by BladeMight** [comment]
@grengray Нет, я уже же там написал в чем причина. (к тому же на Win10 - 4.6+, когда для Mahou нужно хотя-бы 4.0)

**Comment by grengray** [comment]
То есть хотел подгрузить ресурс, а его не оказалось, правильно?

**Comment by BladeMight** [comment]
Да.

**Comment by grengray** [comment]
Спасибо!

**Comment by BladeMight** [comment]
@grengray Много времени потратил на дизайн(прилипание к краям экрана и т.д.) и пока что не меняет язык и флаг, но если хочется посмотреть как будет выглядеть то вот:
[Mahou.exe.gz](https://github.com/BladeMight/Mahou/files/1097294/Mahou.exe.gz)

P.S. Рамка сейчас имеет цвет Aero(или главный цвет на Windows 8 и выше), ну и возможности пока не реализированы, но их сделать уже будет по-легче.

**Comment by BladeMight** [comment]
Примерно 50% функционала сделал, но пока менять настройки(панели) не можно, вот если хочешь попробуй:
[Mahou+LP(~50%).gz](https://github.com/BladeMight/Mahou/files/1097706/Mahou.LP.50.gz)

**Comment by BladeMight** [comment]
@grengray Готово, полная рабочая версия со всеми настройками - [Mahou-v2.3.3.3](https://github.com/BladeMight/Mahou/releases/tag/v2.3.3.3).

**Comment by grengray** [comment]
@BladeMight спасибо Вам большое! Очень крутая функция, а можно центрировать надписи или добавить какие-то пояснения в скобочка, чтобы они одинаковую длину занимали или изменять размер панели динамически?
Теперь Mahou заменила мне ещё две программы о_0

**Comment by BladeMight** [comment]
@grengray Можно, вот так:
[Mahou.exe.gz](https://github.com/BladeMight/Mahou/files/1098781/Mahou.exe.gz)

**Comment by BladeMight** [comment]
И вот еще с динамическим размером:
[Mahou(dynamic size).gz](https://github.com/BladeMight/Mahou/files/1098807/Mahou.dynamic.size.gz)

**Comment by grengray** [comment]
@BladeMight 
Вы волшебник какой-то...
Сейчас протестирую...
