### ISSUE TITLE
При взаимодействии с TeamViewer раскладка меняется

### ISSUE THREAD

**Issue by grengray** [BladeMight/Mahou#94]
При включённой опции "единая раскладка для всех приложений" TeamViewer на неё не реагирует и меняет раскладку.

**Comment by BladeMight** [comment]
@grengray Сейчас делал тесты, в логе пишет `Layout in this window [TeamViewer] was different, changing layout to Mahou global layout.` это значит что Mahou *хотел* изменить раскладку в TV но не смог, надо искать причину.

**Comment by BladeMight** [comment]
@grengray Заметил очень странную вещь, меняться не хочет именно на русскую раскладку(если она была глобальной, а в TV стояла другая).

**Comment by BladeMight** [comment]
@grengray Вот попробуй как работает здесь: 
[Mahou.gz](https://github.com/BladeMight/Mahou/files/1094369/Mahou.gz)
У меня работает, но я не залогиневался, просто в окне которое открывается после запуска ярлыка. Исправление работает следующим образом:
Раньше когда Mahou слушал изменения текущего активного окна он вызывал смену раскладки зи **слушателя** что видимо не понравилось TV, я добавил один таймер который будет запускаться из **слушателя** и будет срабатывать через 100 мс. Сколько проверял с разными раскладками - работало.

**Comment by grengray** [comment]
Никогда не думал, что можно испытывать такое удовольствие работая с программой... Просто слёзы на глаза!
ВСЁ ИДЕАЛЬНО!!!!!!!

**Comment by BladeMight** [comment]
@grengray Круто, сейчас сделаю релиз, закрою #95 и эту, а потом займусь #93.

**Comment by grengray** [comment]
@BladeMight оперативно Вы, а что там было (в 95'ом)?

**Comment by BladeMight** [comment]
@grengray Написал в #93.

**Comment by BladeMight** [comment]
Релиз [Mahou-v2.3.1.9](https://github.com/BladeMight/Mahou/releases/tag/v2.3.1.9).
