### ISSUE TITLE
Подсказка для регистра вводимых символов

### ISSUE THREAD

**Issue by grengray** [BladeMight/Mahou#96]
Вот такую плюшечку можно ещё добавить, что весьма украсит программу, как мне кажется.
![2017-06-22_16-38-21](https://user-images.githubusercontent.com/26556246/27437226-44c3c870-576a-11e7-8d17-42453f17f34c.png)

**Comment by BladeMight** [comment]
@grengray То есть показывать ее при удерживании Shift или при включенном Caps Lock?

**Comment by grengray** [comment]
@BladeMight думаю, что при включённом Caps Lock, но у Вас, как обычно, идея глубже и интереснее.

**Comment by grengray** [comment]
@BladeMight можно обновляться?

**Comment by BladeMight** [comment]
@grengray ОК, готово, вот [Mahou-v2.3.4.0](https://github.com/BladeMight/Mahou/releases/tag/v2.3.4.0).

P.S. Также добавил эту же функцию и для языковой панели(#93).
