### ISSUE TITLE
ИСправление ДВух ЗАглавных БУкв в НАчале СЛова

### ISSUE THREAD

**Issue by grengray** [BladeMight/Mahou#97]
Возможно имеет смысл добавить такую фишку в Mahou, поскольку при быстрой печати имеет место быть такая накладка и, к сожалению, довольно часто.

**Comment by BladeMight** [comment]
@grengray Ну уже есть такая функция которую можно использовать для этого → вкладка горячие клавиши → Конверт выделенного слова в Заглавный регистр.

**Comment by grengray** [comment]
@BladeMight протестируем...

**Comment by BladeMight** [comment]
> жмем Ctrl + стрелка влево

Ой, не дописал, нужно: <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>←</kbd>.

**Comment by grengray** [comment]
@BladeMight самое удобное это нажимать все три клавиши правой рукой, то есть правый контрол, шифт и стрелка.
